In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv(r'/home/user/Documents/zepto_2026_07_14.csv',  low_memory=False)

In [3]:
df.shape

(881077, 31)

In [4]:
df.isnull().sum()

crawl_date_and_time             0
platform_name                   0
store_id                        0
store_name_location             0
city                            0
pin_code                        0
unique_id                       0
product_id_upc_ean              0
department                      0
category                        0
sub_category                    0
product_type               881077
brand_name                      0
product_name                    0
product_description        881077
product_grammage           136210
package_type               881077
net_quantity                    0
variants                   873787
item_mrp                        0
item_selling_price              0
out_of_stock_flag               0
discount_flag                   0
product_price                   0
unit_price                 881077
promo_offer_description         0
promo_offer_price               0
discount_in_percent             0
stock_count                     0
product_url                     0
product_image_urls         881077
dtype: int64

In [6]:
df.nunique()

crawl_date_and_time        15439
platform_name                  1
store_id                     310
store_name_location          292
city                           6
pin_code                     136
unique_id                   8824
product_id_upc_ean          8613
department                    10
category                      24
sub_category                 159
product_type                   0
brand_name                  1222
product_name                8151
product_description            0
product_grammage             749
package_type                   0
net_quantity                1337
variants                     145
item_mrp                     993
item_selling_price          1726
out_of_stock_flag              2
discount_flag                  2
product_price               1726
unit_price                     0
promo_offer_description     1197
promo_offer_price           1726
discount_in_percent           91
stock_count                   54
product_url                 8825
product_image_urls             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.unique_id.duplicated().sum()

np.int64(872253)

In [9]:
pin_check = (
    df.groupby("store_name_location")["pin_code"]
        .nunique()
        .sort_values(ascending=False)
)

pin_check[pin_check > 1]

Series([], Name: pin_code, dtype: int64)

In [10]:
missing_grammage = df[df["product_grammage"].isna()]

print("Rows with missing product_grammage:", len(missing_grammage))
missing_grammage.head()

Rows with missing product_grammage: 136210

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
55,2026-07-14 07:33:37,zepto,f70fa1be-1eea-45a4-a692-219b12d85b24,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,b01ce71b-cb04-4569-95f0-ebed29ad6de3,298c3523-b8b0-4d36-85f7-9836d4ad1f5f,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Rice & More,NaN,921,921 Mini Mogra Basmati Rice,NaN,NaN,NaN,5 kg,NaN,325.0,267.0,No,Yes,267.0,NaN,₹58 OFF,267.0,17,2,https://www.zepto.com/pn/921-mini-mogra-basmati-rice/pvid/b01ce71b-cb04-4569-95f0-ebed29ad6de3,NaN
81,2026-07-14 07:33:37,zepto,681003a8-bce8-4481-980d-8253746471e6,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,95b0ef74-7198-4f1c-9360-aa6e13c2321f,9f4801ae-24d2-4317-b0e8-5b69794a0f99,Baby Care,Packaged Food,Infant Food,NaN,Dexolac,Dexolac Follow Up Formula Powder For Babies - Stage 3 (12 To 18 Months),NaN,NaN,NaN,400 g,NaN,490.0,490.0,No,No,490.0,NaN,No offer,490.0,0,2,https://www.zepto.com/pn/dexolac-follow-up-formula-powder-for-babies-stage-3-12-to-18-months/pvid/95b0ef74-7198-4f1c-9360-aa6e13c2321f,NaN
94,2026-07-14 07:33:37,zepto,681003a8-bce8-4481-980d-8253746471e6,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,c7514415-5dcb-4550-a18a-35fda15a2bbb,413d9a78-5151-429d-81e4-2b07c0e1e452,Baby Care,Baby Care,Baby Gear,NaN,LuvLap,"LuvLap Royal Hip Seat Baby Carrier, 4 Carry Positions, Adjustable, for 6 to 24 Months, Upto 15 Kgs",NaN,NaN,NaN,1 pc,NaN,2099.0,1624.0,No,Yes,1624.0,NaN,₹475 OFF,1624.0,22,3,https://www.zepto.com/pn/luvlap-royal-hip-seat-baby-carrier-4-carry-positions-adjustable-for-6-to-24-months-upto-15-kgs/pvid/c7514415-5dcb-4550-a18a-35fda15a2bbb,NaN
96,2026-07-14 07:33:37,zepto,681003a8-bce8-4481-980d-8253746471e6,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,7d39af66-bb8f-4ba7-9cdf-459c97568477,7d3f23a7-4d06-43d4-805a-a779edc4d3d8,Baby Care,Baby Care,Baby Gear,NaN,R For Rabbit,R for Rabbit Little Feet Sportz Walker (Green Yellow),NaN,NaN,NaN,1 pc,NaN,3393.0,2768.0,No,Yes,2768.0,NaN,₹625 OFF,2768.0,18,1,https://www.zepto.com/pn/r-for-rabbit-little-feet-sportz-walker-green-yellow/pvid/7d39af66-bb8f-4ba7-9cdf-459c97568477,NaN
97,2026-07-14 07:33:37,zepto,681003a8-bce8-4481-980d-8253746471e6,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,55fa6dfc-4ab2-4111-b08c-a79431af55f9,9cdf88ab-da02-4bd1-8e65-98e161585069,Baby Care,Baby Care,Baby Gear,NaN,LuvLap,LuvLap Elegant Baby Carrier 4 Carry Positions Cushioned Leg Support Navy Blue,NaN,NaN,NaN,1 pc,NaN,1899.0,1407.0,No,Yes,1407.0,NaN,₹492 OFF,1407.0,25,1,https://www.zepto.com/pn/luvlap-elegant-baby-carrier-4-carry-positions-cushioned-leg-support-navy-blue/pvid/55fa6dfc-4ab2-4111-b08c-a79431af55f9,NaN

In [11]:
df.net_quantity.value_counts()

net_quantity
1 pc                                 52724
1 pack (200 g)                       36964
1 pack (500 g)                       31572
1 pack (1 kg)                        30631
1 pc (100 ml)                        20518
1 pc (100 g)                         19430
1 pack (100 g)                       18573
1 pc (200 ml)                        17941
1 pc (250 ml)                        17553
1 pc (1 L)                           17372
1 pack (5 kg)                        13710
1 set                                12410
1 pc (50 g)                          12229
1 pack (1 L)                         10456
1 pc (50 ml)                         10209
1 pack (250 g)                        9962
1 pc (150 ml)                         9462
1 pc (180 ml)                         9152
1 pack (150 g)                        7862
1 pack (400 g)                        7796
1 pc (200 g)                          7629
1 pc (400 ml)                         7528
1 pack (500 ml)                       6552
1 pc (30 ml)                          6324
1 pc (1 kg)                           6187
1 pack (6 pcs)                        6009
1 pack (50 g)                         5760
1 pc (300 ml)                         5645
1 pc (250 g)                          5403
1 pc (500 ml)                         5251
1 pc (120 ml)                         4864
1 pack (30 pcs)                       4782
1 pack (10 pcs)                       4742
1 pack (60 g)                         4589
1 pack (100 ml)                       4583
1 pack (5 pcs)                        4530
1 pack (2 pcs)                        4521
1 pack (40 g)                         4501
1 pc (60 ml)                          4449
1 pc (80 g)                           4383
1 pc (75 g)                           4170
1 pc (150 g)                          4063
1 pack (300 g)                        3943
1 pack (3 pcs)                        3839
1 pc (750 ml)                         3816
1 pc (110 ml)                         3635
1 pack (350 g)                        3581
1 pack (25 pcs)                       3572
1 pack (80 g)                         3537
1 pc (400 g)                          3500
2 combo                               3472
1 pc (70 ml)                          3342
1 pack (20 pcs)                       3335
1 pack (75 g)                         3218
1 pack (4 pcs)                        3173
1 pack (120 g)                        3097
1 pack (10 kg)                        2879
1 pc (10 ml)                          2812
1 pc (175 ml)                         2806
1 pack                                2721
1 pc (40 g)                           2698
1 pack (45 g)                         2666
1 pack (40 pcs)                       2644
1 pack (70 g)                         2635
1 pc (300 g)                          2621
1 pack (180 g)                        2599
1 pack (55 g)                         2554
1 pack (450 g)                        2520
1 pc (600 ml)                         2518
1 pack (160 g)                        2506
1 pc (40 ml)                          2505
1 pack (140 g)                        2386
1 pack (25 g)                         2378
1 pc (30 g)                           2263
1 pack (150 ml)                       2171
1 pack (12 pcs)                       2131
1 pc (85 g)                           2067
1 pack (20 g)                         2059
1 pc (80 ml)                          2050
1 pack (210 g)                        2026
1 pc (500 g)                          2018
1 pc (350 g)                          1990
1 pack (85 g)                         1976
1 pc (170 ml)                         1889
1 x 72 pulls                          1831
1 pack (450 ml)                       1777
1 pc (90 g)                           1762
1 pack (30 g)                         1745
1 pack (800 g)                        1736
1 pc (45 g)                           1718
1 pack (16 pcs)                       1667
1 pack (18 pcs)                       1636
1 pack (24 pcs)                       1622
1 pc (70 g)                           1602
1 pack (750 ml)                       1555
1 pc (330 ml)                         1514
1 pc (35 g)                           1454
1 pc (4 g)                            1452
1 pack (35 g)                         1418
1 pack (15 pcs)                       1409
1 pc (6 ml)                           1377
62pcs                                 1368
1 pc (75 ml)                          1365
100 ml                                1361
1 pc (230 ml)                         1359
3 x 72 pulls                          1338
1 pc (510 g)                          1332
54pcs                                 1314
1 pc (125 g)                          1304
1 pc (20 g)                           1275
1 pc (55 g)                           1246
1 pc (180 g)                          1245
1 pc (236 ml)                         1232
1 pc (750 g)                          1231
1 pack (5 x 125 g)                    1229
1 pack (200 ml)                       1221
250 ml X 2                            1215
1 pc (60 g)                           1211
1 pc (105 ml)                         1211
1 pc (190 ml)                         1194
1 pack (125 g)                        1186
1 set (3 pcs)                         1177
1 pc (924 g)                          1163
1 pc (2 L)                            1160
1 pack (700 ml)                       1136
1 pc (125 ml)                         1109
1 pc (120 g)                          1089
1 pack (900 ml)                       1084
100 g                                 1059
1 pack (125 ml)                       1058
1 pack (50 pcs)                       1056
350 ml                                1040
1 pc (220 ml)                         1013
3 pcs                                  995
1 pack (36 pcs)                        968
1 pack (115 ml)                        962
1 pc (10 g)                            961
180 ml                                 944
4 pcs                                  935
1 pack (2 x 150 g)                     930
200 ml                                 927
1 pc (225 ml)                          926
1 pc (4.5 g)                           913
1 pack (850 g)                         907
50 g                                   905
1 pack (750 g)                         902
1 pack (4 x 150 g)                     897
72pcs                                  885
1 pc (170 g)                           878
1 pack (28 g)                          854
1 pc (5 ml)                            851
1 pc (5 L)                             837
1 pc (15 ml)                           822
1 pack (52 g)                          811
1 pc (190 g)                           808
500 g                                  800
1 set (7 pcs)                          798
1 kg                                   793
1 pc (25 ml)                           791
1 pack (600 g)                         784
1 pack (275 g)                         781
1 pack (41 g)                          776
150 g + 60 g                           765
1 pack (25 ml)                         764
1 pack (65 g)                          758
1 pc (20 ml)                           756
1 pc (135 ml)                          755
1 pc (4.8 g)                           754
1 pack (89 g or 95 g)                  750
1 pack (60 g or 64 g)                  745
1 pc (450 g)                           740
1 pc (320 ml)                          731
1 set (2 pcs)                          729
100 g X 2                              714
1 pc (90 ml)                           713
250 ml                                 710
1 pc (4 ml)                            705
60 ml X 2                              705
1 pack (3 x 100 g)                     702
1 pack (250 ml)                        675
1 pack (5 x 100 g)                     671
300 ml                                 662
1 pack (95 g)                          659
1 pc (15 g)                            656
1 L                                    655
70 ml + 60 g                           651
500 ml X 2                             647
1 pc (65 ml)                           638
1 pc (65 g)                            630
1 pack (100 pcs)                       625
1 pc (1.2 L)                           621
1 pack (79 g)                          620
1 pack (43 g)                          611
1 pack (144 g)                         611
1 pack (38 g)                          611
1 pc (0.35 g)                          610
1 pack (130 g)                         609
1 pack (1.2 kg)                        596
1 pc (88 ml)                           595
1 pack (57 g)                          586
1 pc (55 ml)                           582
1 pack (3 x 150 g)                     571
1 pc (5 g)                             571
1 pack (375 g)                         568
1 x 80 pulls                           565
1 pack (19.8 g)                        555
1 pack (3 x 125 g)                     541
1 kg X 2                               540
1 pc (236 ml or 250 ml)                530
1 pack (4 x 70 g)                      526
1.6 g                                  525
1 pc (118 ml or 125 ml)                524
1 pc (9 ml)                            524
1.15 kg                                523
1 pack (153 g)                         520
1 set (11 pcs)                         519
1 pack (44 g)                          515
1 pack (7 pcs)                         514
1 pc (1.25 kg)                         507
1 pack (33 g)                          503
1 pack (120 ml)                        502
1 pc (210 g)                           501
1 pack (6 x 300 ml)                    500
1 pc (180 ml or 190 ml)                500
2 pcs                                  495
500 ml                                 494
1 pack (128 g)                         493
1 pc (245 ml)                          492
1 pack (3 x 40 g)                      491
1 pack (142 g)                         489
1 pack (25 x 1.7 g)                    484
1 pack (280 g)                         480
1 pack (22 g)                          472
1 pc (17 g)                            472
450 ml                                 472
1 pc (1.4 g)                           470
200 ml X 2                             469
1 pc (8 ml)                            466
1 pc (300 ml or 330 ml)                464
1 pc (100 or 110 g)                    462
1 pack (168 g)                         459
1 pack (415 g)                         454
1 pc (25 g)                            454
1 set (8 pcs)                          446
1 pack (225 g)                         445
2 pack (10 pcs)                        440
1 pc (61 g)                            435
1 piece                                433
30 g                                   431
1 pack (55 g or 57 g)                  430
1 set (6 pcs)                          421
1 pc (12 ml)                           420
32pcs                                  420
1 Pack (30 g)                          418
1 pack (66.6 or 75 g)                  417
1 pc (18 ml)                           417
1 pack (4 x 60 ml)                     416
1 pc (110 or 120 ml)                   414
1 set (5 pcs)                          407
1 pack (2 kg)                          407
1 pair                                 406
1 pack (67 g)                          404
1 pack (2 x 100 ml)                    403
1 pc (1.5 L)                           403
1 pack (700 g)                         400
1 pc (18 g)                            399
1 pack (170 g)                         399
1 pack (10 x 10 g)                     397
60 ml X 3                              395
1 set (4 pcs)                          393
1 pack (68 g)                          393
1 pack (99 g)                          393
1 pack (4 x 75 g)                      390
1 pack (48 g or 52.9 g)                389
1 pack (20 g or 16 g)                  386
1 pack (285 g)                         386
1 pc (12 g)                            380
0.35 g                                 379
1 pack (4 x 125 g)                     379
70 ml                                  376
1 pack (48 g)                          372
1 pack (30.6 g or 28.9 g)              369
70 ml X 2                              369
1 pack (1.5 kg)                        369
20 pc X 2                              367
5 ml                                   365
1 pack (67.5 g)                        365
30pcs                                  364
1 pack (830 ml)                        362
1 pc (340 g)                           359
0.3 g                                  359
1.2 kg                                 357
1 pack (90 g)                          355
1 pack (420 g)                         348
1 pc (280 ml)                          345
1 pc (240 ml)                          345
1 pack (8 pcs)                         341
1 pack (34 g)                          338
100 g X 3                              338
1 pack (173 g)                         333
250 ml X 3                             328
70 ml X 3                              325
40pcs                                  324
56pcs                                  322
1 pc (350 ml)                          322
2 x 70 ml                              321
1 pack (36 g)                          321
1 pack (25 x 2 g)                      321
1 pack (165 ml)                        320
1 pc (7 ml)                            319
80g                                    317
400g                                   316
40 ml                                  315
1 pack (59.4 g)                        314
1 pack (69 g)                          313
1 pack (2 x 12.5 g)                    313
1 pack (56 g)                          310
1 pack (108 g)                         307
4 x 75 g                               306
80 g                                   305
1 pack (160 g or 171 g)                305
1 pack (360 g)                         298
1 pack (62.5 g)                        297
1 pc (75 or 80 ml)                     294
750 g                                  293
1 pc (36 g)                            290
250 g X 2                              290
1 pack (42 g)                          287
1 pack (180 ml)                        286
1 pack (77 g)                          285
1 pack (475 g)                         281
1 pc (3 g)                             280
70pcs                                  280
1 pack (6 Sachets)                     280
1 pc (9 g)                             278
1 Pack                                 274
5.6 ml                                 274
4 x 5 ml                               274
1 pack (270 ml)                        272
1 pack (72 pcs)                        271
1 pack (495 g)                         271
1 pack (12 x 32 ml)                    271
1 kg X 3                               271
1 pc X 2                               270
180 ml X 4                             269
1 pack (27 g)                          269
300 g                                  269
1 pc (800 g)                           268
1 pack (48 pcs)                        268
10 ml X 2                              266
1 pack (10 x 20 g)                     266
2 x 2 L                                265
1 pc (80 g or 100 g)                   265
1 pc (196 ml)                          265
1 pc (62 g)                            264
1 pc (6 g)                             264
1 pc (63 g)                            263
1 pack (114 g)                         263
1 pack (585 g)                         263
1 pack (295 g)                         263
1 pack (100 g or 114.1g)               263
1 pack (103.5 g)                       263
1 pack (92 or 100 g)                   263
1 pack (1.05 kg)                       263
1 pack (100 g or 107 g)                263
1 pack (50 or 55 g)                    263
1 pack (198 g or 180 g)                263
1 pack (188 g)                         263
1 pack (70 or 79 g)                    263
1 pack (138 or 152 g)                  263
1 pack (100 g or 115.5 g)              263
1 pack (66.6g)                         263
1 pack (195 g)                         263
1 pack (108.55 g)                      263
1 pack (187.5 g)                       263
1 pack (183 g)                         263
1 pack (696 g)                         263
1 pc (45 or 48.5 g)                    263
1 pack (45 or 48.5 g)                  263
1 pack (827 or 905 g)                  263
1 pack (100 g or 112 g)                263
1 pc (380 g)                           263
1 pack (85 g or 130 g)                 263
1 pack (800 g or 955 g)                263
1 pack (82.7 g or 90.8 g )             263
1 pack (705.6 g)                       263
1 pack (6 x 19 g)                      263
1 pack (960 g)                         263
1 pc (75 ml or 80 ml)                  262
1 pack (160 ml)                        262
67 g                                   262
1 pc (1.2 kg)                          262
1 pc (110 ml or 120 ml)                262
1 pack (29.7 g)                        262
1 pc (185 ml)                          262
1 pack ( 175 ml or 180 ml )            262
7 pack (140 g)                         262
1 pc (28 ml)                           262
1 pack (4 x 250 ml)                    262
1 pack (159 ml)                        262
1 pack (3 x 103.5 g)                   262
1 pack (270 g)                         262
2 x 225 g                              262
1 pack (251 g or 275 g)                262
1 pack (875 g)                         262
1.05 kg                                262
1 pack (385 g)                         262
1 pack (91.7 g or 100 g)               262
1 pack (110 ml)                        262
1 pack (52.9 g or 58 g)                262
1 pack (162 g)                         262
1 pack (48.1 g)                        262
1 pack (3 x 16 g)                      262
1 pack (145 g)                         262
100 g + 72 ml                          262
1 pc (95 ml)                           262
1 pack (172 g)                         262
1 pack (176.4 g)                       262
60 g + 60 ml + 40g                     262
1 pack (130 g or 139 g)                261
1 pc (590 g)                           261
1 pack (75 g or 82 g)                  261
1 pack (100 x 1.4 g)                   261
1 pack (80 g + 80 ml)                  261
1.1 kg                                 261
1 pack (900 g)                         261
1 pack (307.8 g)                       261
1 pc (110 g)                           261
1 pc (56 g)                            261
1 pc (27.5 g or 30 g)                  261
1 pc (960 g)                           261
1 pc (1 L or 1.2 L)                    261
1 pc (45 ml or 50 ml)                  261
1 pack (68.91 or 76.5 g)               261
1 pack (29.7g)                         261
1 pc (100 ml or 118 ml)                261
1 pc (300 g or 400 g)                  261
1 pc (150 g + 60 g)                    261
1 pack (94 g)                          261
1 pack (250 ml or 300 ml)              261
1 pack (380 g or 390 g)                261
1 pc (500 ml or 473 ml)                260
1 pc (390 g)                           260
1 pack(30 pcs)                         260
1 pc (35 ml)                           260
1 pc (1.5 g)                           259
1 pc (120 ml or 110 ml)                259
2 x 25 g + 25 ml                       259
1 pack (165 g)                         258
1 pack (14 pcs)                        258
1 pack (50 x 3.5 g)                    258
1 pack (60 ml)                         256
150 g X 2                              253
1 pack (240 pcs)                       253
1 pc (72 g)                            252
1 pack (192 g)                         251
1 pack (956 g)                         251
1 pack (239.7 g)                       251
1 pack (240 g)                         251
1 pc (1 ml)                            250
1 pack (400 ml or 440 ml)              250
1.4 g                                  250
1 pc (350 ml or 355 ml)                250
1 x 60 pulls                           250

In [5]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Delhi,15268,34027,29089,47684,34820,45805,19276,40825,47002,28909
Ghaziabad,3415,9347,7319,13969,8191,10813,4559,9724,11720,6713
Gurgaon,7297,18570,14075,23397,17035,22058,8920,18319,22063,14269
Jaipur,1817,5785,3392,7483,3946,5132,2223,4443,5927,3614
Lucknow,4211,11314,8513,16353,8571,10876,5884,11173,12681,9909
Noida,6406,15426,12072,19108,14850,19093,7787,17227,19299,12084

In [6]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

category,"Atta, Rice, Oil & Dals",Baby Care,Bath & Body,Biscuits,Breakfast & Sauces,Cold Drinks & Juices,"Dairy, Bread & Eggs",Electronics & Appliances,Feminine Hygiene,Fragrances & Grooming,Frozen Food,Hair Care,Ice Creams & More,Jewellery,Makeup & Beauty,"Masala, Dry Fruits & More",Munchies,Packaged Food,Pharma & Wellness,Skincare,Sweet Cravings,"Tea, Coffee & More",Toys & Sports,Zepto Cafe
city,,,,,,,,,,,,,,,,,,,,,,,,
Gurgaon,11060,8726,10404,9500,7591,11319,14697,437,5336,4179,924,7553,11307,0,4441,5847,10286,7504,122,13214,7240,5729,8490,97
Jaipur,2412,2732,2583,2298,1875,2548,3190,134,1748,1246,329,2036,2769,0,1808,1517,2605,1887,14,3834,1993,1474,2706,24
Lucknow,6378,5677,4937,5726,4917,5626,6633,327,4240,2869,30,4279,7029,0,4203,2695,6815,4535,92,8562,5282,3667,4888,78
Noida,9618,8347,8276,8240,6478,9376,12529,352,5248,3021,1100,5581,9493,0,4838,5175,8936,6274,81,10725,6745,4941,6530,1448

In [8]:
city_category = pd.crosstab(df["city"], df["category"])

print(city_category)

category   Atta, Rice, Oil & Dals  Baby Care  Bath & Body  Biscuits  \
city
Delhi                       23565      18960        20645     19484
Ghaziabad                    5254       4724         5447      4878
Gurgaon                     11060       8726        10404      9500
Jaipur                       2412       2732         2583      2298
Lucknow                      6378       5677         4937      5726
Noida                        9618       8347         8276      8240

category   Breakfast & Sauces  Cold Drinks & Juices  Dairy, Bread & Eggs  \
city
Delhi                   15689                 22939                29407
Ghaziabad                3538                  5255                 7582
Gurgaon                  7591                 11319                14697
Jaipur                   1875                  2548                 3190
Lucknow                  4917                  5626                 6633
Noida                    6478                  9376                12529

category   Electronics & Appliances  Feminine Hygiene  Fragrances & Grooming  \
city
Delhi                           750             12505                   8225
Ghaziabad                       100              3299                   1736
Gurgaon                         437              5336                   4179
Jaipur                          134              1748                   1246
Lucknow                         327              4240                   2869
Noida                           352              5248                   3021

category   Frozen Food  Hair Care  Ice Creams & More  Jewellery  \
city
Delhi             3074      13124              22533          1
Ghaziabad          772       3356               5825          4
Gurgaon            924       7553              11307          0
Jaipur             329       2036               2769          0
Lucknow             30       4279               7029          0
Noida             1100       5581               9493          0

category   Makeup & Beauty  Masala, Dry Fruits & More  Munchies  \
city
Delhi                10235                      12605     21875
Ghaziabad             3424                       3290      5242
Gurgaon               4441                       5847     10286
Jaipur                1808                       1517      2605
Lucknow               4203                       2695      6815
Noida                 4838                       5175      8936

category   Packaged Food  Pharma & Wellness  Skincare  Sweet Cravings  \
city
Delhi              14111                241     28385           17092
Ghaziabad           3636                 51      8339            3265
Gurgaon             7504                122     13214            7240
Jaipur              1887                 14      3834            1993
Lucknow             4535                 92      8562            5282
Noida               6274                 81     10725            6745

category   Tea, Coffee & More  Toys & Sports  Zepto Cafe
city
Delhi                   11575          14342        1343
Ghaziabad                2584           3782         387
Gurgaon                  5729           8490          97
Jaipur                   1474           2706          24
Lucknow                  3667           4888          78
Noida                    4941           6530        1448

In [9]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals]"
1,Baby Care,"[Baby Care, Packaged Food, Pharma & Wellness, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Breakfast & Sauces, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food]"
6,Munchies,"[Masala, Dry Fruits & More, Munchies, Packaged Food]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Skincare]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Fragrances & Grooming, Frozen Food, Ice Creams & More, Jewellery, Munchies, Packaged Food, Sweet Cravings]"

In [10]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag      No    Yes   Total  Out_of_stock_%
city
Ghaziabad           67040  18730   85770           21.84
Delhi              273990  68715  342705           20.05
Jaipur              35786   7976   43762           18.23
Noida              118244  25108  143352           17.51
Gurgaon            138810  27193  166003           16.38
Lucknow             84303  15182   99485           15.26

In [11]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag         No    Yes   Total  Out_of_stock_%
department
Baby Care              74034  20435   94469           21.63
Personal Care          93640  25052  118692           21.11
Dairy & Breakfast      91270  22507  113777           19.78
Sweet Tooth            61064  14434   75498           19.12
Bakery & Biscuits      60537  13923   74460           18.70
Cold Drinks & Juices   72043  15370   87413           17.58
Beauty & Cosmetics    105664  22330  127994           17.45
Atta, Rice & Dal       32081   6333   38414           16.49
Organic & Premium      85506  16205  101711           15.93
Munchies               42334   6315   48649           12.98

In [12]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No    Yes  Total  Out_of_stock_%
category
Zepto Cafe                  1605   1772   3377           52.47
Pharma & Wellness            396    205    601           34.11
Electronics & Appliances    1534    566   2100           26.95
Baby Care                  36868  12298  49166           25.01
Dairy, Bread & Eggs        56616  17422  74038           23.53
Fragrances & Grooming      16476   4800  21276           22.56
Sweet Cravings             32396   9221  41617           22.16
Makeup & Beauty            22747   6202  28949           21.42
Feminine Hygiene           25754   6622  32376           20.45
Biscuits                   40202   9924  50126           19.80
Bath & Body                42399   9893  52292           18.92
Skincare                   60032  13027  73059           17.83
Atta, Rice, Oil & Dals     48278  10009  58287           17.17
Toys & Sports              33767   6971  40738           17.11
Cold Drinks & Juices       47505   9558  57063           16.75
Ice Creams & More          49108   9848  58956           16.70
Hair Care                  30028   5901  35929           16.42
Packaged Food              31883   6064  37947           15.98
Munchies                   47605   8154  55759           14.62
Masala, Dry Fruits & More  26580   4549  31129           14.61
Frozen Food                 5386    843   6229           13.53
Breakfast & Sauces         34849   5239  40088           13.07
Tea, Coffee & More         26154   3816  29970           12.73
Jewellery                      5      0      5            0.00

In [13]:
same_store_diff = (
    df.groupby(["store_id", "store_name_location", "city", "unique_id"])
    .agg(
        product_name=("product_name", "first"),
        price_count=("item_selling_price", "nunique"),
        discount_count=("discount_in_percent", "nunique"),
        mrp_count=("item_mrp", "nunique")
    )
    .reset_index()
)

same_store_diff = same_store_diff[
    (same_store_diff["price_count"] > 1) |
    (same_store_diff["discount_count"] > 1) |
    (same_store_diff["mrp_count"] > 1)
]

same_store_diff

Empty DataFrame
Columns: [store_id, store_name_location, city, unique_id, product_name, price_count, discount_count, mrp_count]
Index: []

In [14]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
126,Ghaziabad,3a9d3627-e56b-4584-ab9f-ed78e1903ed4,0,132,132,100.00
132,Ghaziabad,57a0c2ae-1cf1-4c4a-99eb-eb2e19864075,8,12,20,60.00
17,Delhi,261b9c45-eb5b-4398-be1c-909ccde6f629,1716,1542,3258,47.33
64,Delhi,7e586f3d-8e30-4859-8851-4476b8a965f4,1951,1607,3558,45.17
114,Delhi,f2818431-48b5-4b57-9ec5-02e8eef7bc92,905,740,1645,44.98
203,Gurgaon,e09e8bac-2aad-4634-9d2c-d19833956f3a,196,159,355,44.79
291,Noida,81d2371c-4e12-4122-9799-f8c21807947d,119,94,213,44.13
40,Delhi,4b54927e-5c54-4564-8c9f-1e518e6488e3,2012,1565,3577,43.75
24,Delhi,31a8b99d-0d1a-4f32-a367-e6cf62bb8603,2098,1531,3629,42.19
185,Gurgaon,90f2f25e-b21f-4999-957f-a96a81f01dfb,2236,1417,3653,38.79
137,Ghaziabad,6e5b43c7-af2f-4b55-af47-72c69fb22bf9,1877,1169,3046,38.38
109,Delhi,ead42923-cfd0-4a7d-bb71-b879631773f1,1944,1130,3074,36.76
21,Delhi,2baf335a-045a-4401-8761-a53b44b5cdcd,1741,1009,2750,36.69
66,Delhi,7ed44401-afcd-41bb-9122-fcfaa918a101,1693,961,2654,36.21
65,Delhi,7e7b4df8-a5a1-4acb-9aa4-b5ecf86a6f2b,1947,1103,3050,36.16
0,Delhi,01e98a7e-46d7-48f1-bbcd-8e864116e992,1983,1055,3038,34.73
2,Delhi,05c5bd1a-d9b2-4ea3-848c-d8ae96b1d04a,2401,1250,3651,34.24
9,Delhi,1585f304-7c1d-404d-b925-84bd48e90433,2030,1038,3068,33.83
219,Jaipur,8b0413dd-9188-4002-951a-660ab5a35e7a,660,329,989,33.27
39,Delhi,49d9df40-6b3b-4f3e-ad7d-bda18f57d419,2053,1023,3076,33.26
125,Ghaziabad,31daaa17-a00e-4c92-b4bc-34fb69d5bba7,2058,1023,3081,33.20
130,Ghaziabad,4fd851db-0ec5-499e-9c7b-724a03966eb8,2105,1031,3136,32.88
25,Delhi,321b0b48-7137-4832-ab17-f131421bdb78,2142,1012,3154,32.09
123,Ghaziabad,1a87a0c1-4634-4bd9-987e-8bb455d96027,2453,1127,3580,31.48
47,Delhi,57fbfbc2-6ec0-4465-aff3-81e771faf303,2194,998,3192,31.27
144,Ghaziabad,a0671666-f881-4ee0-aa9b-bcd3ee58d19d,2089,919,3008,30.55
13,Delhi,1edbc6f5-f8dd-4dd0-9555-a8a5d90dd2d7,2101,918,3019,30.41
102,Delhi,da285a58-89f2-448e-b5d7-dddce15e9bba,109,47,156,30.13
93,Delhi,c46cc946-f7eb-4f5b-aaff-cf6fdcba6618,2176,916,3092,29.62
276,Noida,3eced897-a793-4b9d-bc3b-1772a883d8af,2187,913,3100,29.45
20,Delhi,2b2c7579-3735-4ddc-8f77-2ba7f4c1a307,1961,814,2775,29.33
207,Gurgaon,f234bb80-5551-416a-ac32-e3734ecd6258,2262,918,3180,28.87
270,Noida,207df3d7-87f9-4b65-b6be-8e7114d22512,309,125,434,28.80
151,Ghaziabad,e94a9a29-8a14-449a-95d0-f9beb57f3904,2219,893,3112,28.70
284,Noida,5a8602ea-7595-466b-bb0d-8ab128a663e0,2273,911,3184,28.61
67,Delhi,803ae812-e031-4287-9513-8137dac95f3d,1970,786,2756,28.52
86,Delhi,ac3b884c-75d1-48a6-b477-0a0782cf19b4,2579,1012,3591,28.18
302,Noida,c4ae2b4d-5005-4d2e-869a-f340fd7e595b,2638,1027,3665,28.02
99,Delhi,c978abd4-1b79-40d2-ab47-ec19b7c29d41,1286,500,1786,28.00
120,Ghaziabad,08c4b285-4a72-4fe8-b25d-6d4b24982703,2222,863,3085,27.97
89,Delhi,b8aed0f4-59e0-4387-825d-406800150b71,2634,1014,3648,27.80
54,Delhi,6118ee4c-ee70-4b20-b071-f8e5e39fb7be,2317,888,3205,27.71
92,Delhi,c2c05ffc-0eb1-4164-86cc-49cb1271d92a,2083,791,2874,27.52
206,Gurgaon,ebc97fa4-aae3-4ece-9ce9-8025aa679e49,2298,872,3170,27.51
134,Ghaziabad,5c78735a-a78d-4d43-8cb1-9ba75215f8a7,1172,441,1613,27.34
311,Noida,fabff813-eb3d-499a-8f9d-691ab28251fc,2325,874,3199,27.32
98,Delhi,c951a741-faf1-4189-be8c-e441b6985190,2263,844,3107,27.16
46,Delhi,57a0c2ae-1cf1-4c4a-99eb-eb2e19864075,1596,594,2190,27.12
95,Delhi,c70d824a-414c-4204-8ae3-d3f6bac461b4,1764,635,2399,26.47
150,Ghaziabad,e0a0c84c-0819-482e-8b95-55d4b32592d8,320,115,435,26.44
155,Gurgaon,0a493c16-c8cc-4f45-a02c-51e7b1328f53,2635,945,3580,26.40
83,Delhi,a5ff49ab-36f4-4aa6-b66e-de385f5d147b,1159,411,1570,26.18
112,Delhi,f02ef084-eab2-4651-8168-a4814b97ca06,2294,812,3106,26.14
140,Ghaziabad,94a98275-e83a-4a25-ba73-690cbfaa1d55,1151,405,1556,26.03
310,Noida,eb94a416-fd5b-4c8d-a9c2-a5d93a3069d9,2651,929,3580,25.95
57,Delhi,681003a8-bce8-4481-980d-8253746471e6,1261,438,1699,25.78
183,Gurgaon,82dffafa-bf7f-4752-a0b2-561dc1349c4a,2342,805,3147,25.58
301,Noida,bd54e57b-7052-4b6f-a52d-64f90447f943,2782,949,3731,25.44
76,Delhi,93cd2e82-b141-41bc-91c5-2805396da43d,2619,893,3512,25.43
257,Lucknow,c42a2c0f-9fd7-4843-8b42-7c71b32be093,2503,841,3344,25.15
61,Delhi,73b0c599-728d-4642-a0e3-1e5b68836327,2277,763,3040,25.10
113,Delhi,f090d50a-60ed-4b98-9493-3f0d9751a3f3,2366,790,3156,25.03
271,Noida,226297cf-9bae-4e84-9aa6-294d8ef080a3,2318,755,3073,24.57
82,Delhi,a45e53cb-bb72-48b5-84a4-5dc8ca06a2d6,2375,768,3143,24.44
201,Gurgaon,de5f724c-2832-47fb-b811-d0cdcc00157d,2231,717,2948,24.32
60,Delhi,73952e1c-38a1-40a3-b71f-a4150849ee52,2218,707,2925,24.17
124,Ghaziabad,2027ae67-e366-4f60-ab7d-64ffbebfeee0,2323,739,3062,24.13
50,Delhi,5d8ec059-9f5f-4867-8520-b232a1ebde3d,2267,719,2986,24.08
216,Jaipur,5c9e9548-d311-4206-adc5-6d3918731d90,2900,914,3814,23.96
80,Delhi,9bb503dd-63be-4b26-b2ba-8fe51192d2bd,1324,417,1741,23.95
222,Jaipur,b1f236d6-edfd-47eb-a6fe-dd5bbca86e4d,2903,910,3813,23.87
246,Lucknow,75ce4477-9307-4db7-b750-a640a90e0e51,2520,789,3309,23.84
274,Noida,3d914942-fcf7-4222-8029-aff9d8ee3743,1193,372,1565,23.77
111,Delhi,efaa6e99-a68b-4c31-a50a-1bc5712533d7,1282,393,1675,23.46
255,Lucknow,c1490eb7-318a-4ee3-b14c-37e943e3b44a,2761,844,3605,23.41
199,Gurgaon,d8c4ab04-68f0-483f-82be-8b9fb18d17ae,2073,633,2706,23.39
22,Delhi,2fa35ecf-4334-4ec6-b6de-5bae11a3dbf7,2695,821,3516,23.35
267,Noida,0e027a98-e51d-488b-af9b-f81381bb9837,1506,458,1964,23.32
136,Ghaziabad,69458308-5c1d-4c8b-b0d0-71d5fcbe6b45,2142,648,2790,23.23
221,Jaipur,8ec659c9-2faa-4eba-ba2e-158ae485ebb4,705,212,917,23.12
143,Ghaziabad,9979be1b-cc60-4f14-9a4b-853338c8561b,2209,660,2869,23.00
264,Noida,06f57b41-596b-4486-b641-46d309fc4262,2807,837,3644,22.97
90,Delhi,b8d61fbc-eb4a-4836-b785-e3b63aa3fa62,2186,646,2832,22.81
115,Delhi,f2e8316d-0937-4104-bae3-a24d608bb09c,2327,686,3013,22.77
153,Gurgaon,00f978ab-683f-435d-8a45-f1a3c4dac568,2434,715,3149,22.71
210,Gurgaon,fd647cf6-e1e8-417e-b2ce-e3f9cb4fbb4f,2323,681,3004,22.67
27,Delhi,3325a4aa-354c-4c9a-9230-178cbb4286f6,2586,757,3343,22.64
174,Gurgaon,58d6551e-edf2-48df-828c-7deb5a25033f,2838,818,3656,22.37
106,Delhi,dc8d6b1b-1d01-46bd-809c-606fca125ab1,2441,696,3137,22.19
224,Jaipur,c833cd5c-df44-42c9-865f-2035f4aa3c4e,2947,836,3783,22.10
128,Ghaziabad,47a77387-059f-44fc-be76-a81b7ff97e0a,2481,689,3170,21.74
273,Noida,3cd244d7-9f76-467e-b4ab-0d7123ebd606,1207,333,1540,21.62
16,Delhi,2522b064-b9af-4967-9c41-2bfffe8786d3,2324,640,2964,21.59
74,Delhi,8fe0a1ee-0ea0-4a84-ba34-80b0d266ad31,2387,644,3031,21.25
208,Gurgaon,f4626c02-1bd4-4396-9a7c-e111d2fc0170,1385,370,1755,21.08
34,Delhi,41b702ce-4302-4b24-8997-c9bd507d5ea7,2646,693,3339,20.75
152,Gurgaon,005dcc9a-d50c-442f-ae5e-f89f35d1a01a,2504,649,3153,20.58
26,Delhi,32ac84e0-0a29-4c1f-865a-c33780173389,2458,629,3087,20.38
148,Ghaziabad,d000be21-9dc2-4554-9cb0-b2f5ffe340cc,1130,289,1419,20.37
32,Delhi,3d03e7a7-4ded-458a-9349-2978cd333ef0,2812,716,3528,20.29
194,Gurgaon,cb64eb92-03c1-452a-b98d-2582d7818f74,2348,593,2941,20.16
253,Lucknow,b4be4358-8c60-4b61-9d4c-0a2f44c1b2cc,2128,533,2661,20.03
127,Ghaziabad,46447215-f214-4e66-9e93-26a5d8509daa,2495,623,3118,19.98
281,Noida,554896ba-1bc3-493a-84c2-8a0ce07c2611,1196,298,1494,19.95
254,Lucknow,c08f4318-403b-4381-8a30-f9da9735ee2b,1379,341,1720,19.83
184,Gurgaon,9062036c-d6b8-4291-ae86-775d46774b56,3044,749,3793,19.75
272,Noida,3422fce9-9587-44a5-8cff-8ee60c65617d,261,64,325,19.69
300,Noida,ba555bdd-e00d-48f1-b0c8-b323f5de6843,2552,620,3172,19.55
286,Noida,5cc22671-70e0-4077-8f1c-5502c2c5522b,2613,620,3233,19.18
256,Lucknow,c3937bd5-02ec-43db-b411-93951a26a159,2350,554,2904,19.08
135,Ghaziabad,6065ae05-53da-45bf-89ce-474215022b49,2524,590,3114,18.95
295,Noida,93f5e60a-7309-40a8-8533-6eee547b3913,2457,569,3026,18.80
30,Delhi,3a8029df-cae5-4c17-88ea-814f8366b814,2544,587,3131,18.75
186,Gurgaon,96348a97-316b-4e61-963d-05f9827366de,2233,514,2747,18.71
190,Gurgaon,b6ac55e9-9d60-4ea1-86b8-fe554ea1490c,1376,316,1692,18.68
73,Delhi,8dde3f32-eae6-42e2-a9cc-ada2f0a9d22f,1342,308,1650,18.67
138,Ghaziabad,7ace5e2b-b072-4daf-978c-4577484a363d,2519,578,3097,18.66
145,Ghaziabad,aa4c6307-c5ae-46c8-8c4d-9750b2bf193f,2584,591,3175,18.61
244,Lucknow,6c71a1ae-262e-443c-879a-3efbdc6dd8f0,1326,303,1629,18.60
312,Noida,fc05177a-ca9e-4c93-9811-dbb101b0c8f7,1178,268,1446,18.53
269,Noida,1db5fffc-4eca-4f44-8ba6-14c5c107e81f,2476,562,3038,18.50
146,Ghaziabad,b0e1957d-a3c6-4f2e-9b73-ab0c026194e2,2551,572,3123,18.32
107,Delhi,e0a0c84c-0819-482e-8b95-55d4b32592d8,1298,291,1589,18.31
105,Delhi,db68a1c5-3c18-49d4-bd83-87b4f580fd45,2590,574,3164,18.14
77,Delhi,94f50df3-fb2e-4c36-ad6f-8a00bfd1c6af,1345,292,1637,17.84
218,Jaipur,886e9e40-b38e-47ab-a15e-baa95f45f022,2842,615,3457,17.79
215,Jaipur,4db672ad-efd4-44f3-bd91-300233162d1c,2914,630,3544,17.78
33,Delhi,3f23fe21-69e5-4b46-9e90-809b609a3131,1305,281,1586,17.72
299,Noida,a58369d0-5902-4113-b0b7-58f4daae321e,2466,531,2997,17.72
122,Ghaziabad,10c1fc75-a412-40c3-b234-4cd3e18a7986,2293,489,2782,17.58
305,Noida,d9c0b720-ce7d-4571-9df2-5d2069c2f8b4,2643,563,3206,17.56
228,Lucknow,1d0f933a-1268-4bb5-8481-fddf9337e467,1344,286,1630,17.55
162,Gurgaon,1c31b7f9-1213-49ea-8346-4879856906a4,2610,554,3164,17.51
282,Noida,56504520-3ffe-41a2-837b-a020f48c871c,2411,511,2922,17.49
303,Noida,c4f5c474-d916-4cf3-ba6d-7a4c5d26d326,2685,565,3250,17.38
116,Delhi,f36075d2-40c9-4e63-a9d0-4fe36b2ca31f,2590,544,3134,17.36
313,Noida,fe6fabb1-7063-4dba-b83a-6cb00e8a26e2,2490,520,3010,17.28
18,Delhi,266fb1d0-6495-4f65-9bcd-f03b54724799,2636,548,3184,17.21
70,Delhi,84f9975d-cc19-4d21-aa76-43e3aab9779a,2492,517,3009,17.18
36,Delhi,4332c938-8582-4628-95d9-2844086daf78,2451,508,2959,17.17
149,Ghaziabad,d955c760-9c2f-4001-b7bd-24b8b4ce38b0,2568,532,3100,17.16
119,Delhi,f88dd0bb-dc4a-400c-badc-d8fc18aeaeb7,1352,280,1632,17.16
94,Delhi,c620a3ce-ee2e-493f-a83d-5555531fd861,2657,548,3205,17.10
266,Noida,0a978a0b-b48a-47e9-a4b7-f48b6172b5b7,2701,552,3253,16.97
263,Noida,0694297e-1f04-4896-98de-fa6aac6b8a37,2522,514,3036,16.93
147,Ghaziabad,cd3f5394-9700-484e-97d7-7d68e3a620af,2593,523,3116,16.78
31,Delhi,3a9d3627-e56b-4584-ab9f-ed78e1903ed4,2450,492,2942,16.72
56,Delhi,65b4f18b-34d3-43f7-a3ce-361471b15345,2607,522,3129,16.68
96,Delhi,c73b0824-ac1e-43eb-98e4-ed5b849a651b,2944,585,3529,16.58
275,Noida,3dbc1d3e-adfe-47b7-92f8-511a7007b9b7,2717,536,3253,16.48
71,Delhi,852818aa-dfa5-4943-b2b5-1cd51c26bdd5,2714,535,3249,16.47
225,Jaipur,f7caefb4-fd0c-43ee-bf5e-593a7bb33860,2920,574,3494,16.43
314,Noida,ffa891d3-3a9d-495e-9444-c23ba34c0f3c,2696,527,3223,16.35
304,Noida,d4826474-66a7-4a03-98a6-950ae93a634d,2704,527,3231,16.31
52,Delhi,5ebdb9c0-59e0-436c-9e67-5594e00a45af,2552,497,3049,16.30
51,Delhi,5dbd7e40-75db-452c-bd76-7dac3d7c0c0b,2598,503,3101,16.22
133,Ghaziabad,5bc98314-fe7f-490b-a41c-cb478ab34dd9,2642,511,3153,16.21
161,Gurgaon,1b66cb9f-a71a-4a96-896f-a420974a2b32,2656,514,3170,16.21
217,Jaipur,71f5dd56-9925-4eb5-812e-2a64c36c6a42,2594,501,3095,16.19
160,Gurgaon,19196ae9-a62a-4eee-a6c3-b6243c9b3f01,2632,508,3140,16.18
242,Lucknow,67053fe0-7be5-4caf-97d4-d7b0d96f36a7,2389,460,2849,16.15
220,Jaipur,8c76a4e6-4882-4303-a883-e4885678bfa5,2420,463,2883,16.06
211,Gurgaon,fee9d74d-9384-4a9d-9325-d4bdf7ee2ffb,2618,500,3118,16.04
44,Delhi,55bbe2f9-33f4-4ce0-a864-9730284b2a7c,2690,513,3203,16.02
117,Delhi,f429e749-364b-480a-a86d-b3bd2c0d6620,2350,448,2798,16.01
195,Gurgaon,d38c9d04-5703-4156-8431-c27aebbf3dc1,1413,269,1682,15.99
306,Noida,dec6523a-5f38-4de3-9c54-97a50f462913,2473,468,2941,15.91
142,Ghaziabad,968d8cb9-f237-415d-af02-adc67bacce06,2459,464,2923,15.87
250,Lucknow,a13c8b45-35e4-4fd1-beae-f898dd2b9e93,2348,442,2790,15.84
81,Delhi,a122a7fb-b822-45b5-adb5-c92ed4661980,2449,458,2907,15.76
297,Noida,9f128d50-def8-471b-bc47-b041d95b885a,2680,494,3174,15.56
279,Noida,4f8f3e7f-09f6-4bea-924e-c29764c91e48,2747,506,3253,15.55
212,Jaipur,02dc6b57-1dfe-4efe-a57b-4324a830de78,2929,539,3468,15.54
38,Delhi,444a442d-982b-437d-a8eb-9ca9385eaed5,2720,498,3218,15.48
88,Delhi,b5c0eebd-0709-4d34-9530-d4540f4db62f,2799,511,3310,15.44
164,Gurgaon,1f606e33-cc6a-46ae-95d7-21bb5a401d7a,1310,239,1549,15.43
241,Lucknow,63a0ab1c-b753-47cb-83a6-5362d31f5d17,2501,455,2956,15.39
235,Lucknow,3e12177b-60c8-4cef-82ae-20cac5466597,2368,429,2797,15.34
198,Gurgaon,d890c3ec-bdf4-4253-b3b4-60742f691584,1337,240,1577,15.22
265,Noida,0a5bba7b-0f2f-4f65-98a3-44529d3156ff,2744,489,3233,15.13
262,Lucknow,f5eef65e-71fe-4789-bb83-3aba21d1eda4,1369,244,1613,15.13
8,Delhi,10655b62-1ead-42a2-a02c-d7a749951d48,2641,471,3112,15.13
121,Ghaziabad,0ea53a34-8b00-4f97-b9c1-9cab4eba4f40,2723,483,3206,15.07
163,Gurgaon,1d31c12c-1669-4ed5-bf1e-251da70753b8,1324,235,1559,15.07
59,Delhi,70bbc5c2-af73-43f1-a5ee-e76a9ca9019f,2683,471,3154,14.93
293,Noida,8bd95118-90ce-4657-9a63-7ca501bb9c6a,2754,483,3237,14.92
14,Delhi,207df3d7-87f9-4b65-b6be-8e7114d22512,1258,220,1478,14.88
182,Gurgaon,760bb995-e9d4-4372-8a03-6d34c08cec8d,2684,467,3151,14.82
45,Delhi,56c431da-a864-4121-be49-15e003139701,2675,455,3130,14.54
104,Delhi,dad7f2ba-1d52-4c30-8c5a-c7fa01f705a1,2624,446,3070,14.53
43,Delhi,4f0e57e8-9610-41b9-acb0-efe2cd7eb7d9,2658,451,3109,14.51
258,Lucknow,cf175154-9362-4fe8-af7a-8b88d60b978f,2409,409,2818,14.51
214,Jaipur,455d4f27-20fa-488a-ab60-54cb113e4f26,3004,510,3514,14.51
226,Lucknow,0bb92297-286f-45a2-8b94-40bb25c86e55,2477,420,2897,14.50
170,Gurgaon,4db16931-a992-4b6a-805d-be5d594941ba,2612,439,3051,14.39
15,Delhi,23e18cbf-7e46-49ec-a559-d5a6cdb09d3b,2581,430,3011,14.28
309,Noida,eb6b329a-e514-4f86-b1b0-d11991efc00a,2776,461,3237,14.24
245,Lucknow,72b84119-233b-4472-9e3c-651bd462d16f,2464,407,2871,14.18
7,Delhi,0c865653-8eac-4a33-900c-d2ed7f3c0477,2708,447,3155,14.17
91,Delhi,bc4b39b0-c1c4-4b68-aef5-076a323e8cf4,2624,433,3057,14.16
238,Lucknow,52e787a0-2b5c-4184-8ba9-437d1d3408d8,2286,376,2662,14.12
280,Noida,54358b29-1ad2-4c8c-a4cb-95af6d0eabc2,2808,461,3269,14.10
196,Gurgaon,d56e42a4-7150-4aa4-b7fc-84f9caa43963,2806,460,3266,14.08
154,Gurgaon,02d2c306-7699-434b-947e-88c99afc54f9,2690,441,3131,14.08
251,Lucknow,aa0cbb4d-1d2d-4ec6-9ed9-bc998260760f,2440,399,2839,14.05
157,Gurgaon,105471df-6c84-4bcf-87d7-d9308fd4df4a,2693,440,3133,14.04
223,Jaipur,c56338b2-6871-4193-b594-445cdb7706b3,3002,490,3492,14.03
191,Gurgaon,baa090fc-be13-4b34-87c5-2aea256fd4c4,2650,432,3082,14.02
139,Ghaziabad,8a93c269-b281-4e2d-98b8-cce217827cd0,2732,445,3177,14.01
248,Lucknow,913cea7d-879a-46d4-a31d-375e6272a237,2486,405,2891,14.01
252,Lucknow,b0caee9f-aa50-45bf-92bb-b533d55b50a0,2435,396,2831,13.99
229,Lucknow,1df7d024-3938-424e-a351-0c61f146c944,2422,393,2815,13.96
19,Delhi,2a655482-29d6-48fd-bb6c-6051fb5900ee,1382,223,1605,13.89
230,Lucknow,20c47a85-2b47-41d8-a02f-8a9b34c8bb4b,2383,382,2765,13.82
29,Delhi,34420157-825b-4822-acc8-9f20ae822fe3,2730,434,3164,13.72
118,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,2704,428,3132,13.67
249,Lucknow,97aa163f-d50f-4f8b-b76e-0bc21cc1c0c2,2312,366,2678,13.67
260,Lucknow,f4bba239-1eaa-447f-bca5-8ac8d536cec1,2459,389,2848,13.66
35,Delhi,42d58798-26cc-429a-aea6-92dbbecae776,2663,420,3083,13.62
239,Lucknow,562cb7b1-abca-43e3-a6c9-051c96f50712,2496,392,2888,13.57
188,Gurgaon,9bfb7127-8a86-4de2-968a-e7cd9d1b8d51,2737,429,3166,13.55
259,Lucknow,f44aaa81-4dd2-4f45-8695-57b7faa3e66e,2467,386,2853,13.53
167,Gurgaon,2e591664-44a8-491a-9add-0af20446f0cc,2719,419,3138,13.35
78,Delhi,9550ef6d-d1b6-4eb1-b379-580404d9c1d3,2708,417,3125,13.34
236,Lucknow,4bbfd2a7-633f-40bf-91e3-3cfdd08fd6cc,2473,380,2853,13.32
231,Lucknow,2140ad97-8423-4f24-9961-ed3ad44306c0,2475,379,2854,13.28
41,Delhi,4ba5f414-34e0-442c-938e-ef76fc9804bf,2713,414,3127,13.24
240,Lucknow,57a0a941-0dd1-4f11-8c58-92e33fd9e2fd,2453,374,2827,13.23
100,Delhi,d13c1520-9614-4788-940b-b94ebdfa434f,2601,396,2997,13.21
156,Gurgaon,0cdd4ac3-fbeb-4bfd-8960-ebf2192d29b4,1285,195,1480,13.18
278,Noida,415a53bb-ae7f-4d84-b58f-e36e425769e5,2825,429,3254,13.18
173,Gurgaon,5858e2d0-74e9-4250-bdca-c6949282438b,2657,403,3060,13.17
58,Delhi,6e87b960-71e6-414e-b6f7-55d08e324811,2530,382,2912,13.12
177,Gurgaon,607dfe88-5e9b-4db8-bfb0-73bea3e8fb54,2736,413,3149,13.12
213,Jaipur,085097a9-564c-45fe-98d8-23d7fd268328,3046,453,3499,12.95
72,Delhi,8a63a860-9ec1-4fcc-b37a-523a34647742,2807,417,3224,12.93
179,Gurgaon,6917bb0a-e50f-4a8e-99aa-5d1cc6bed71a,2803,415,3218,12.90
268,Noida,0ee686e2-fe05-4ea1-9740-46835a298b6b,2822,417,3239,12.87
166,Gurgaon,2809502a-1c2c-4305-9b1d-f00d75bf65c3,2777,410,3187,12.86
141,Ghaziabad,961f1f02-65c5-403a-a32f-edaf705eadfd,2807,413,3220,12.83
234,Lucknow,2f8b56d8-3d1a-4dd3-ad94-2fc67df39b4f,2472,363,2835,12.80
232,Lucknow,27fa1d6b-96f7-43db-af92-e38f4313ee09,2226,326,2552,12.77
159,Gurgaon,1879c01a-f20c-4987-9ce4-0f47f75ad4f9,2785,407,3192,12.75
285,Noida,5c59e348-7c63-47e6-92e8-ad748aa75242,2781,406,3187,12.74
165,Gurgaon,225cd095-2106-490a-81c8-de5faa97ac65,2721,395,3116,12.68
129,Ghaziabad,4ab87b63-ecc0-48ff-9f76-1ab67b5495bd,2748,399,3147,12.68
187,Gurgaon,9a51d2b1-9708-4648-a294-0f5a5909cf5a,2795,406,3201,12.68
247,Lucknow,871ffc63-229f-4a33-b9f5-13644d79fb07,2495,362,2857,12.67
28,Delhi,33622370-e10f-4996-aaf2-84076a8f66c2,2516,365,2881,12.67
197,Gurgaon,d8507dc4-e2dc-4b97-96f6-c7d285da48bf,2734,394,3128,12.60
6,Delhi,08d249a3-3f40-428b-8ec5-cd9beb33ed41,2674,385,3059,12.59
193,Gurgaon,c2e46a52-b65f-4fbe-8332-06856db49e25,2707,390,3097,12.59
158,Gurgaon,14f1a8ec-192a-49d1-95fd-514b5e14f919,2786,401,3187,12.58
12,Delhi,1c3ca061-43e6-4119-85c3-76e51106a606,2642,380,3022,12.57
108,Delhi,e1befcff-e3d0-4fce-929c-50b9b6ae296f,21,3,24,12.50
49,Delhi,5cad640b-fe79-43bb-aac2-849733defb55,2677,382,3059,12.49
3,Delhi,05d5e1df-5159-4484-8322-87e02e4655c3,2551,363,2914,12.46
205,Gurgaon,e9aae2cf-8473-4e4c-ba53-3aa73354576c,2775,394,3169,12.43
55,Delhi,656bef79-0f91-45cd-9f93-8fedf1a932ce,2776,393,3169,12.40
110,Delhi,ebc222f1-119b-457b-a137-3a4cfa10c571,2692,381,3073,12.40
233,Lucknow,2d176779-fc34-4f74-9e2b-cf260ef82d26,2393,337,2730,12.34
283,Noida,581b1461-3a0b-4698-adb6-93a51207b2e1,2796,390,3186,12.24
79,Delhi,96a968d7-aca7-4b78-9302-ef72fbb1cc57,2694,375,3069,12.22
288,Noida,67aa2c02-3b10-4736-b493-aad9f07d28e0,267,37,304,12.17
307,Noida,e5b38f40-f9c0-4355-baa9-269c4d85396b,2862,395,3257,12.13
169,Gurgaon,48a75423-507c-4e6d-8eaa-603c77f48b05,718,99,817,12.12
10,Delhi,17a221cb-335d-4a8c-a04a-694435f615c3,2579,354,2933,12.07
294,Noida,917688f6-e1ca-4cd5-9b42-4190feb6e75d,1254,170,1424,11.94
209,Gurgaon,f5e682bc-1124-4bcf-8fca-734bd8b59d7f,2776,376,3152,11.93
175,Gurgaon,5d205066-36a5-4929-982a-7571c60f876b,2841,384,3225,11.91
287,Noida,5cc508cc-2f15-4990-bf48-fae5c13283d6,2596,347,2943,11.79
23,Delhi,3072e208-7b9a-4821-a000-e121ba8a43fa,2875,383,3258,11.76
292,Noida,89f3ad21-ce3d-41d6-a3f5-54563135c339,1253,167,1420,11.76
168,Gurgaon,40632fc7-b3f8-4ebc-b2e7-db803accef4e,2874,382,3256,11.73
4,Delhi,082229f8-d7ec-4b29-8220-db1d7776d7e9,2909,383,3292,11.63
178,Gurgaon,6596a71b-54df-4556-9119-7de895a9c300,2787,366,3153,11.61
180,Gurgaon,6c3a340a-8c23-4518-95ff-4e7aebe0ff6a,2692,353,3045,11.59
200,Gurgaon,dbce85ee-e3de-44b6-994d-72bc38c63389,2828,370,3198,11.57
298,Noida,a2c38983-ad00-4c89-88f7-7bc7d463d4c4,2664,346,3010,11.50
290,Noida,6bd939bc-7b5a-47de-a0da-25b436e46853,2789,362,3151,11.49
69,Delhi,834e1acb-7f03-424e-9b2b-3bebefbdde9a,2587,335,2922,11.46
171,Gurgaon,4e5abfcd-fda7-4e76-8f19-96ef2c343491,2813,359,3172,11.32
131,Ghaziabad,526b1499-dbae-4fc6-b67d-70e350768cae,2843,362,3205,11.29
261,Lucknow,f571c16f-aefa-42e9-818c-ff8193f48b61,1370,174,1544,11.27
192,Gurgaon,bcfaff62-217e-4fab-b8cd-a89d81ccfc4a,2569,324,2893,11.20
189,Gurgaon,a05f78f8-00f3-4105-b850-f8bf851e5996,2487,312,2799,11.15
5,Delhi,08562d04-1972-4d6f-819c-4111321529e6,2871,360,3231,11.14
308,Noida,ead3cbf3-0bb8-4089-8283-45d337b4a3b9,2857,356,3213,11.08
237,Lucknow,4e9be954-763d-417a-94b5-04c7a7dc27d4,2392,296,2688,11.01
243,Lucknow,6af4daba-3f48-4037-a5e4-0bb3c4042203,2396,294,2690,10.93
53,Delhi,5ee3f39d-3d7b-44b2-bbeb-b17e8457dc4e,2881,351,3232,10.86
101,Delhi,d9b656fe-41ad-4645-9fad-af3bf1cf7d8f,2777,338,3115,10.85
37,Delhi,433bb54d-7e04-4f91-ac03-bee784a3102c,2599,315,2914,10.81
277,Noida,3ed41d5c-5bb0-4ea9-b041-4d40c2b1f963,2853,343,3196,10.73

In [15]:
out_of_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "Yes",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (Out of Stock):", len(out_of_stock_urls))
out_of_stock_urls.head()

Products to verify (Out of Stock): 162900

,unique_id,product_name,city,store_id,product_url
24,233829d0-8d17-4c99-9318-1f45ef8e2f82,Indimix Moong Dal Chila From The House Of Pansari,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,https://www.zepto.com/pn/indimix-moong-dal-chila-from-the-house-of-pansari/pvid/233829d0-8d17-4c99-9318-1f45ef8e2f82
25,64e6a6ed-3436-4985-9396-510286d682fa,Praakritik Organic Sprouted Ragi Atta,Delhi,681003a8-bce8-4481-980d-8253746471e6,https://www.zepto.com/pn/praakritik-organic-sprouted-ragi-atta/pvid/64e6a6ed-3436-4985-9396-510286d682fa
26,11f413c3-3f89-4b0b-8715-9af3c79eda5d,True Story Organic Ragi Flour/ Nachni Flour,Delhi,681003a8-bce8-4481-980d-8253746471e6,https://www.zepto.com/pn/true-story-organic-ragi-flour-nachni-flour/pvid/11f413c3-3f89-4b0b-8715-9af3c79eda5d
28,8f1de715-723a-40a4-8434-8965004bb417,Anugrah Cold Pressed Sprouted Ragi Atta,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,https://www.zepto.com/pn/anugrah-cold-pressed-sprouted-ragi-atta/pvid/8f1de715-723a-40a4-8434-8965004bb417
29,205460d9-749d-4b2c-af07-7b8c406e1617,Manna Sprouted Ragi Flour,Delhi,681003a8-bce8-4481-980d-8253746471e6,https://www.zepto.com/pn/manna-sprouted-ragi-flour/pvid/205460d9-749d-4b2c-af07-7b8c406e1617

In [16]:
in_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "No",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (In Stock):", len(in_stock_urls))
in_stock_urls.head()

Products to verify (In Stock): 718172

,unique_id,product_name,city,store_id,product_url
0,31ad3e8b-e689-48c1-956c-ca36d9fcac2c,Daily Good Corn Flour/Starch,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,https://www.zepto.com/pn/daily-good-corn-flourstarch/pvid/31ad3e8b-e689-48c1-956c-ca36d9fcac2c
1,c0781799-72e5-4bb2-8b82-d96ffe9aab6f,Organic Tattva Ragi Atta,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,https://www.zepto.com/pn/organic-tattva-ragi-atta/pvid/c0781799-72e5-4bb2-8b82-d96ffe9aab6f
2,7ff95977-a477-4d2a-acec-61fc8d1bcea2,Weikfield Corn Starch Powder| Gluten-Free Cornflour for Baking| Perfect Thickening,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,https://www.zepto.com/pn/weikfield-corn-starch-powder-gluten-free-cornflour-for-baking-perfect-thickening/pvid/7ff95977-a477-4d2a-acec-61fc8d1bcea2
3,76f03c75-396d-4c1a-89c3-44f50a7a5458,Organic Tattva Jowar Flour,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,https://www.zepto.com/pn/organic-tattva-jowar-flour/pvid/76f03c75-396d-4c1a-89c3-44f50a7a5458
4,4321e603-486d-4de8-a146-48d353992e19,Tata Sampann Easy Cook Ragi Atta,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,https://www.zepto.com/pn/tata-sampann-easy-cook-ragi-atta/pvid/4321e603-486d-4de8-a146-48d353992e19

In [17]:
import re

# Normalize brand names
df["productname_norm"] = (
    df["product_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
name_issue = (
    df.groupby("productname_norm")
    .agg(
        variant_count=("product_name", "nunique"),
        name_variants=("product_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

name_issue = name_issue[name_issue["variant_count"] > 1]

name_issue

,productname_norm,variant_count,name_variants
29,4700bccheesepopcornjumbosizezeropalmoil,2,"[4700BC Cheese Popcorn | Jumbo Size | Zero Palm Oil, 4700BC Cheese Popcorn | Jumbo Size,Zero Palm Oil]"
184,altcooatmilknzs1,2,"[Alt Co. Oat Milk nzs 1, Alt Co. Oat MilkN Z S 1]"
358,andaahnaturalwhiteeggs,2,"[Andaah Natural White Eggs, Andaah Natural+ White Eggs]"
532,babysebamedgentlewashph55babybodywashsoapfreetearfree,2,"[Baby Sebamed Gentle Wash | pH 5.5 | Baby Body Wash | Soap Free | Tear Free, Baby Sebamed Gentle Wash | pH 5.5 | Baby Body Wash | Soap Free| Tear Free]"
783,bisleripackageddrinkingwater,2,"[Bisleri Packaged Drinking Water, Bisleri Packaged Drinking Water.]"
1118,carmesidisposableperiodpantiesallnightprotectionsm,2,"[Carmesi Disposable Period Panties | All Night Protection | S-M, Carmesi Disposable Period Panties | All-Night Protection | S-M]"
1119,carmesidisposableperiodpantiesallnightprotectionxlxxl,2,"[Carmesi Disposable Period Panties | All Night Protection | XL-XXL, Carmesi Disposable Period Panties | All-Night Protection | XL-XXL]"
1351,cleananddryintimatewash,2,"[Clean And Dry Intimate Wash, Clean and Dry Intimate Wash]"
1354,cleanclearfoamingfacewash,2,"[Clean & Clear Foaming Face Wash, Clean & Clear Foaming Facewash]"
1398,colgatekids2yearsextrasofttoothbrush,2,"[Colgate Kid's 2+ Years Extra Soft Toothbrush, Colgate Kids 2+ Years Extra Soft Toothbrush]"
1409,colgatemaxfreshplaxmouthwashfreshmint,2,"[Colgate Max Fresh Plax Mouthwash - Fresh Mint, Colgate Max Fresh Plax Mouthwash Freshmint]"
1680,dailygoodalmondbadamcalifornia,2,"[Daily Good Almond - Badam | California, Daily Good Almond / Badam | California]"
1747,dailygoodunpolishedtoorturarhardal,2,"[Daily Good Unpolished Toor - Tur - Arhar Dal, Daily Good Unpolished Toor / Tur / Arhar Dal]"
1862,dermatouchkojicacid1soapwithglutathioneforpigmentationsundamagesoapformenwomen,2,"[Dermatouch Kojic Acid 1% Soap With Glutathione For Pigmentation & Sun Damage Soap For Men & Women, Dermatouch Kojic Acid 1% Soap With Glutathione For Pigmentation & Sun Damage Soap | For Men & Women]"
2194,epigamiagreekyogurtnaturalcombo,2,"[Epigamia Greek Yogurt- Natural Combo, Epigamia Greek Yogurt- Natural | Combo]"
2475,fortunekachighanimustardoilbottle,2,"[Fortune Kachi Ghani Mustard Oil Bottle, Fortune Kachi Ghani Mustard Oil | Bottle]"
2561,frubonrabrimalaikulfiicecreamstickcombo,2,"[FruBon Rabri Malai Kulfi Ice Cream Stick Combo, Frubon Rabri Malai Kulfi Ice Cream Stick Combo]"
2569,fruitchillicepopsfrozenjuicebarsmultipackmangostrawberryorangenimboogrape,2,"[Fruitchill Ice Pops/ Frozen Juice Bars Multipack- Mango, Strawberry, Orange, Nimboo, Grape, Fruitchill Ice Pops/Frozen Juice Bars Multipack- Mango, Strawberry, Orange, Nimboo, Grape]"
2784,gozeromadovermangolowcalorieguiltfreeicecreamcup,2,"[Go Zero Mad Over Mango Low Calorie Guilt Free Ice Cream Cup, Go Zero Mad Over Mango Low Calorie Guilt Free Ice Cream Cup .]"
2852,gubbtonguecleanertassorted,2,"[GUBB Tongue Cleaner T | Assorted, GUBB Tongue Cleaner T+ | Assorted]"
2896,haldiramschipsclassicsaltedcrispysalty,2,"[Haldiram's Chips Classic Salted | Crispy & Salty, Haldiram's Chips | Classic Salted | Crispy & Salty]"
3144,himalayagentlebabysoapwith100naturalalmondoliveoilnopostbathdryness,2,"[Himalaya Gentle Baby Soap with 100% Natural Almond & Olive Oil -| No Post Bath Dryness, Himalaya Gentle Baby Soap with 100% Natural Almond & Olive Oil| No Post Bath Dryness]"
4329,maggirichtomatoketchup,2,"[MAGGI Rich Tomato Ketchup, Maggi Rich Tomato Ketchup]"
4721,minusthirtydarkchocolateseasaltedcaramel,2,"[MINUS THIRTY Dark Chocolate Sea Salted Caramel, Minus Thirty Dark Chocolate Sea Salted Caramel]"
4722,minusthirtydarkchocolateveganandsugarfree,2,"[MINUS THIRTY Dark Chocolate Vegan And Sugar Free, Minus Thirty Dark Chocolate Vegan And Sugar Free]"
5163,nicalphonsomangoicecreamcuppreservativefreenoartificialflavors,2,"[NIC Alphonso Mango Ice Cream Cup | Preservative Free | No Artificial Flavors, NIC Alphonso Mango Ice Cream Cup| Preservative Free | No Artificial Flavors]"
5220,niveasoftdailyuvlightmoisturisingcreamwithspf15,2,"[NIVEA Soft Daily UV Light Moisturising Cream with SPF-15, Nivea Soft Daily UV Light Moisturising Cream With SPF-15]"
5454,oralbprohealthgumcaretoothbrushmedium,2,"[Oral B Pro Health Gum Care Toothbrush Medium, Oral-B Pro Health Gum Care Toothbrush Medium]"
5745,patanjalidantkantinaturaltoothpasteherbaloralcarefightscavitiesandgerms,2,"[Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care ,Fights Cavities and Germs, Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care,Fights Cavities and Germs]"
5792,peesafecomfortperiodpantylxl,2,"[Pee Safe Comfort Period Panty (L-XL), Pee Safe Comfort Period Panty L-XL]"
5963,pintolaallnaturalpeanutbuttercrunchy,2,"[Pintola All Natural Peanut Butter - Crunchy, Pintola All Natural Peanut Butter Crunchy]"
6643,skin1004madagascarcentellatonebrighteningcapsuleampoule,2,"[SKIN1004 Madagascar Centella Tone Brightening Capsule Ampoule, Skin1004 Madagascar Centella Tone Brightening Capsule Ampoule]"
6945,superbottomsnewborngiftset0to3months,2,"[Super Bottoms Newborn Gift Set | 0 to 3 Months, SuperBottoms Newborn Gift Set | 0 to 3 Months]"
7061,tatasampannunpolishedtoordalarhardal,2,"[Tata Sampann Unpolished Toor Dal | Arhar Dal, Tata Sampann Unpolished Toor Dal/Arhar Dal]"
7179,thedermaco1hyaluronicsunscreenspf50paaquagelfornormaltooilyskin,2,"[The Derma Co 1% Hyaluronic Sunscreen SPF 50 PA++++ Aqua Gel For Normal To Oily Skin, The Derma Co 1% Hyaluronic Sunscreen Spf 50 Pa+++ Aqua Gel For Normal To Oily Skin]"
7728,vaselinecocoaglowseruminlotion100purecocoasheabutterforglowingsoftskin,2,"[Vaseline Cocoa Glow Serum In Lotion, 100% Pure Cocoa & Shea Butter for Glowing & Soft Skin, Vaseline Cocoa Glow Serum In Lotion100% Pure Cocoa & Shea Butter For Glowing & Soft Skin]"
7730,vaselinedeepmoisturebodylotionwithceramidehyaluron10xmoremoisturefordryskin,2,"[Vaseline Deep Moisture Body Lotion With Ceramide Hyaluron | 10X More Moisture | For Dry Skin, Vaseline Deep Moisture Body Lotion With Ceramide Hyaluron | 10X More Moisture| For Dry Skin]"
7833,vlccsandalcleansingmilk,2,"[VLCC Sandal Cleansing Milk, Vlcc Sandal Cleansing Milk]"
7923,whisperultraskinlovesoftsanitarypadsforwomenxl15napkins,2,"[Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL 15 Napkins, Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL+ 15 Napkins]"
7924,whisperultraskinlovesoftsanitarypadsforwomenxl30napkins,2,"[Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL 30 Napkins, Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL+ 30 Napkins]"
7925,whisperultrauptonogapnoleakssanitarypads15xlpadsbasedonpgtechnicaldata,2,"[Whisper Ultra Upto No Gap No Leaks Sanitary Pads, 15 XL Pads (Based on P&G Technical Data), Whisper Ultra Upto No Gap No Leaks Sanitary Pads, 15 XL+ Pads (Based on P&G Technical Data)]"

In [18]:
import re

# Normalize brand names
df["brand_norm"] = (
    df["brand_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
brand_issue = (
    df.groupby("brand_norm")
    .agg(
        variant_count=("brand_name", "nunique"),
        brand_variants=("brand_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

brand_issue = brand_issue[brand_issue["variant_count"] > 1]

brand_issue

          brand_norm  variant_count                             brand_variants
156             bonn              2                               [Bonn, bonn]
229       cocacolaus              2               [Coca-Cola US, Coca-cola US]
290         delichic              2                      [Deli Chic, Delichic]
577       kharifoods              2                 [KHARI FOODS, Khari Foods]
787             noto              2                               [NOTO, Noto]
858        patanjali              2                     [PATANJALI, Patanjali]
887  plixtheplantfix              2  [Plix -The Plant Fix, Plix The Plant Fix]

In [1]:
group_cols = [
    "product_url",
    "unique_id",
    "product_id_upc_ean",
    "product_grammage",
    "net_quantity"
]

# Find groups where product_name differs
name_issue = (
    df.groupby(group_cols, dropna=False)
      .agg(
          name_count=("product_name", "nunique"),
          name_variants=("product_name", lambda x: sorted(set(x.dropna())))
      )
      .reset_index()
)

name_issue = name_issue[name_issue["name_count"] > 1]

print(f"Groups with different product names: {len(name_issue)}")
name_issue

NameError: name 'df' is not defined