In [5]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [6]:
df = pd.read_csv(r"/home/user/Documents/zepto_2026_07_09.csv",low_memory=False)
df.head()

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-07-09 00:35:32,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,31ad3e8b-e689-48c1-956c-ca36d9fcac2c,e036add7-94c1-4287-b83b-ffd2794806cf,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Daily Good,Daily Good Corn Flour/Starch,NaN,500 g,NaN,1 pack (500 g),NaN,70.0,61.0,No,Yes,61.0,NaN,₹9 OFF,61.0,12,1,https://www.zepto.com/pn/daily-good-corn-flourstarch/pvid/31ad3e8b-e689-48c1-956c-ca36d9fcac2c,NaN
1,2026-07-09 00:35:32,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,f4f9fcc5-11f2-4258-a498-a18bfd72994d,cb0c7910-52bc-4b04-a0fe-23a93ff89494,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Bhagirathi,Bhagirathi Jowar Atta,NaN,500 g,NaN,1 pack (500 g),NaN,53.0,50.0,No,Yes,50.0,NaN,₹3 OFF,50.0,5,5,https://www.zepto.com/pn/bhagirathi-jowar-atta/pvid/f4f9fcc5-11f2-4258-a498-a18bfd72994d,NaN
2,2026-07-09 00:35:32,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,9557fec4-be71-4f91-99ef-4e92b4dc851a,0173d036-3906-4f0d-b906-9907c2bdd2cb,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Satyam,Satyam Nachani | Ragi Flour,NaN,500 g,NaN,1 pack (500 g),NaN,54.0,51.0,No,Yes,51.0,NaN,₹3 OFF,51.0,5,2,https://www.zepto.com/pn/satyam-nachani-ragi-flour/pvid/9557fec4-be71-4f91-99ef-4e92b4dc851a,NaN
3,2026-07-09 00:35:32,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,295dca45-3a22-4ce7-a3ca-5345c2549eb0,58974140-c679-466b-9971-2114f9b3a753,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Daily Good,Daily Good Jowar Flour / Sorghum Millet,NaN,500 g,NaN,1 pack (500 g),NaN,75.0,43.0,No,Yes,43.0,NaN,₹32 OFF,43.0,42,1,https://www.zepto.com/pn/daily-good-jowar-flour-sorghum-millet/pvid/295dca45-3a22-4ce7-a3ca-5345c2549eb0,NaN
4,2026-07-09 00:35:32,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,7f3b60c4-ae3a-473c-be64-218c114458ac,cb279c01-9a60-46f0-bda3-c6e00c192758,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Katdare,Katadre Thalipeeth Bhajani,NaN,500 g,NaN,1 pack (500 g),NaN,125.0,125.0,No,No,125.0,NaN,No offer,125.0,0,4,https://www.zepto.com/pn/katadre-thalipeeth-bhajani/pvid/7f3b60c4-ae3a-473c-be64-218c114458ac,NaN

### Data exploration

In [5]:
df.shape

(1049475, 31)

In [4]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls'],
      dtype='object')

In [5]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

crawl_date_and_time              0
platform_name                    0
store_id                         0
store_name_location              0
city                             0
pin_code                         0
unique_id                        0
product_id_upc_ean               0
department                       0
category                         0
sub_category                     0
product_type               1049475
brand_name                       0
product_name                     0
product_description        1049475
product_grammage            188690
package_type               1049475
net_quantity                     0
variants                   1021025
item_mrp                         0
item_selling_price               0
out_of_stock_flag                0
discount_flag                    0
product_price                    0
unit_price                 1049475
promo_offer_description          0
promo_offer_price                0
discount_in_percent              0
stock_count                      0
product_url                      0
product_image_urls         1049475
dtype: int64

In [6]:
df.nunique()

crawl_date_and_time        25166
platform_name                  1
store_id                     369
store_name_location          291
city                          56
pin_code                     250
unique_id                  16566
product_id_upc_ean         16090
department                    10
category                      27
sub_category                 159
product_type                   0
brand_name                  1697
product_name               14815
product_description            0
product_grammage            1039
package_type                   0
net_quantity                2022
variants                     311
item_mrp                    1180
item_selling_price          2151
out_of_stock_flag              2
discount_flag                  2
product_price               2151
unit_price                     0
promo_offer_description     1491
promo_offer_price           2151
discount_in_percent           95
stock_count                   58
product_url                16566
product_image_urls             0
dtype: int64

In [7]:
df.city.unique()

array(['Pune', 'Kolkata', 'Bangalore', 'Belagavi', 'Mumbai', 'Chennai',
       'Vellore', 'Hyderabad', 'Surat', 'Varanasi', 'Ludhiana', 'Thane',
       'Hosur', 'Karimnagar', 'Chhatrapati Sambhajinagar', 'Agra',
       'Dehradun', 'Faridabad', 'Kalyan', 'Ahmedabad', 'Jaipur',
       'Patiala', 'Amritsar', 'Kochi', 'Ulhasnagar', 'Hubballi',
       'Davanagere', 'Prayagraj', 'Jalandhar', 'Gorakhpur', 'Mehsana',
       'Vijayawada', 'Kurukshetra', 'Puducherry', 'Saharanpur', 'Mysuru',
       'Gandhinagar', 'Udaipur', 'Mohali', 'Bareilly', 'Vadodra', 'Kota',
       'Nashik', 'S.A.S Nagar', 'Hisar', 'Kanpur', 'Chandigarh', 'Nagpur',
       'Coimbatore', 'Phagwara', 'Indore', 'Panipat', 'Karnal',
       'Talegaon Dabhade', 'Guntur', 'Navsari'], dtype=object)

In [8]:
pin_check = (
    df.groupby("store_name_location")["pin_code"]
        .nunique()
        .sort_values(ascending=False)
)

pin_check[pin_check > 1]

Series([], Name: pin_code, dtype: int64)

In [9]:
missing_grammage = df[df["product_grammage"].isna()]

print("Rows with missing product_grammage:", len(missing_grammage))
missing_grammage.head()

Rows with missing product_grammage: 188690

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
57,2026-07-09 00:35:32,zepto,285e3359-d42c-4b88-9edb-35550d7f3b41,"5/8, Kaikhali, Kolkata, West Bengal, 700136, India",Kolkata,700136,c0ffd674-fc8a-4458-8d7a-fdaa621c8eaf,2a035497-97d9-4b65-9cf1-1894cfeeb75e,"Atta, Rice & Dal","Atta, Rice, Oil & Dals","Besan, Sooji & Maida",NaN,Satyendra,Satyendra Sattoo,NaN,NaN,NaN,500 g,NaN,93.5,93.5,No,No,93.5,NaN,No offer,93.5,0,6,https://www.zepto.com/pn/satyendra-sattoo/pvid/c0ffd674-fc8a-4458-8d7a-fdaa621c8eaf,NaN
134,2026-07-09 00:35:33,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,ad55222c-5d4e-4a69-965c-373894458cf0,85a6b6bb-babf-424c-bba5-c05adb3a4c88,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Dals & Pulses,NaN,Fortune,Fortune Unpolished Arhar Dal,NaN,NaN,NaN,500 g,NaN,129.0,105.0,No,Yes,105.0,NaN,₹24 OFF,105.0,18,6,https://www.zepto.com/pn/fortune-unpolished-arhar-dal/pvid/ad55222c-5d4e-4a69-965c-373894458cf0,NaN
154,2026-07-09 00:35:33,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,73f81346-fc52-4bbb-8d88-d6dc847179d6,3d4bbf1c-3261-409b-a4c6-65b607427ad5,Baby Care,Packaged Food,Infant Food,NaN,Nestle Nutrition,Nestle NAN PRO Stage 2 Follow-up Powder | 6 - 12 M,NaN,NaN,NaN,1.2 kg,NaN,2170.0,2170.0,No,No,2170.0,NaN,No offer,2170.0,0,1,https://www.zepto.com/pn/nestle-nan-pro-stage-2-follow-up-powder-6-12-m/pvid/73f81346-fc52-4bbb-8d88-d6dc847179d6,NaN
157,2026-07-09 00:35:34,zepto,3f82b919-5cc7-42a9-8e0a-147da44f9114,"Aditya Woods, Sector No. 9, Moshi, Pune, Pimpri-Chinchwad, Maharashtra, 412105, India",Pune,412105,12a38d25-34c4-4433-bdae-26bca9b20e65,7f06994d-51cf-4056-91dc-99de7f9544aa,Baby Care,Packaged Food,Infant Food,NaN,Nestle Nutrition,Nestle NAN PRO Stage 1 Infant Formula | 0 - 6 M,NaN,NaN,NaN,1.2 kg,NaN,2170.0,2170.0,No,No,2170.0,NaN,No offer,2170.0,0,2,https://www.zepto.com/pn/nestle-nan-pro-stage-1-infant-formula-0-6-m/pvid/12a38d25-34c4-4433-bdae-26bca9b20e65,NaN
192,2026-07-09 00:35:33,zepto,285e3359-d42c-4b88-9edb-35550d7f3b41,"5/8, Kaikhali, Kolkata, West Bengal, 700136, India",Kolkata,700136,ecba9a6e-88d2-4570-bb24-58e4f23b5815,1504f65b-a599-4093-9749-0c5ab5d9f670,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Atta,NaN,Ganesh,GANESH PREMIUM SHARBATI ATTA,NaN,NaN,NaN,1 kg,NaN,78.0,64.0,Yes,Yes,64.0,NaN,₹14 OFF,64.0,17,0,https://www.zepto.com/pn/ganesh-premium-sharbati-atta/pvid/ecba9a6e-88d2-4570-bb24-58e4f23b5815,NaN

In [ ]:
df.net_quantity.value_counts()

net_quantity
1 pc                                  72632
1 pack (200 g)                        37339
1 pack (500 g)                        35306
1 pack (1 kg)                         29976
1 pc (100 ml)                         26234
1 pc (200 ml)                         22197
1 pc (250 ml)                         21978
1 pack (100 g)                        21069
1 pc (1 L)                            19867
1 pc (100 g)                          19191
1 set                                 18518
1 pc (50 g)                           17185
1 pc (50 ml)                          14618
1 pack (5 kg)                         13905
1 pack (250 g)                        11796
1 pack (1 L)                          10917
1 pack (400 g)                        10504
1 pc (150 ml)                         10231
1 pack (500 ml)                        8854
1 pc (400 ml)                          8836
1 pc (30 ml)                           8194
1 pack (150 g)                         8149
1 pc (180 ml)                          7742
1 pc (200 g)                           7622
1 pack (6 pcs)                         7369
1 pack (50 g)                          7137
1 pc (300 ml)                          6847
1 pack (2 pcs)                         6379
1 pack (10 pcs)                        6218
1 pc (120 ml)                          6195
1 pc (500 ml)                          5776
1 pc (250 g)                           5690
1 pack (60 g)                          5633
1 pc (80 g)                            5562
1 pack (100 ml)                        5561
1 pc (150 g)                           5556
1 pc (1 kg)                            5483
1 pack (5 pcs)                         5482
1 pack (3 pcs)                         5416
1 pack (40 g)                          5416
1 pc (60 ml)                           5359
1 pack (300 g)                         4769
1 pc (75 g)                            4761
1 pack (30 pcs)                        4507
1 pack                                 4497
2 combo                                4345
1 pc (300 g)                           4304
1 pack (20 pcs)                        4284
1 pack (80 g)                          4108
1 pack (4 pcs)                         4063
1 pc (70 ml)                           3942
1 pc (10 ml)                           3889
1 pack (25 pcs)                        3604
1 pc (30 g)                            3405
1 pc (400 g)                           3393
1 pc (750 ml)                          3386
1 pc (110 ml)                          3345
1 pc (40 ml)                           3344
1 pack (70 g)                          3253
1 pack (12 pcs)                        3213
1 pack (120 g)                         3121
1 pack (45 g)                          3043
1 pc (40 g)                            3033
1 pc (600 ml)                          2981
1 pack (25 g)                          2964
1 pc (500 g)                           2884
1 pc (175 ml)                          2867
1 pc (80 ml)                           2838
1 pack (160 g)                         2834
1 pack (40 pcs)                        2801
1 pack (75 g)                          2791
1 pack (20 g)                          2711
1 pc (45 g)                            2650
1 pc (125 ml)                          2598
1 pc (350 g)                           2518
1 pack (180 g)                         2510
1 pack (10 kg)                         2451
1 pack (450 g)                         2431
1 pack (140 g)                         2367
1 x 72 pulls                           2357
1 pack (55 g)                          2311
1 pack (200 ml)                        2172
1 pack (350 g)                         2170
1 pack (30 g)                          2086
1 pack (85 g)                          2074
1 pc (4 g)                             2039
1 pc (170 ml)                          1974
1 pc (70 g)                            1937
1 pack (750 ml)                        1932
1 pc (125 g)                           1919
1 pack (35 g)                          1893
1 pc (330 ml)                          1882
1 pack (24 pcs)                        1839
1 pc (6 ml)                            1829
1 pack (18 pcs)                        1814
1 pack (700 ml)                        1806
1 pack (16 pcs)                        1790
1 pc (15 ml)                           1779
62pcs                                  1758
1 pc (90 g)                            1671
1 pack (125 ml)                        1628
1 set (3 pcs)                          1602
1 pc (85 g)                            1585
250 ml X 2                             1583
1 pc (55 g)                            1574
1 pack (800 g)                         1545
3 pcs                                  1529
1 pc (510 g)                           1508
1 pc (225 ml)                          1492
1 pc (5 ml)                            1489
1 pc (230 ml)                          1489
1 pc (75 ml)                           1486
1 pc (236 ml)                          1463
100 g                                  1458
1 pack (450 ml)                        1457
1 pc (190 ml)                          1445
3 x 72 pulls                           1443
1 pc (35 g)                            1431
1 pc (105 ml)                          1414
1 pack (15 pcs)                        1414
50 g                                   1391
1 pack (125 g)                         1384
54pcs                                  1377
1 pc (220 ml)                          1343
1 pc (60 g)                            1340
1 set (2 pcs)                          1310
1 pack (5 x 125 g)                     1309
1 pack (28 g)                          1261
1 pc (924 g)                           1223
1 pack (50 pcs)                        1222
1 pack (150 ml)                        1202
1 pack (25 ml)                         1176
1 pack (675 ml)                        1172
1 pc (10 g)                            1171
72pcs                                  1161
1 pc (180 g)                           1153
1 pc (65 ml)                           1143
100 ml                                 1126
1 pack (2 x 150 g)                     1110
1 pc (4.5 g)                           1109
1 pc (1.2 L)                           1099
1 pack (77 g)                          1084
1 set (5 pcs)                          1043
1 pc (25 ml)                           1042
1 pc (120 g)                           1041
1 pc (9 g)                             1024
200 ml                                 1021
1 pack (36 pcs)                        1007
1 pc (20 ml)                            995
4 pcs                                   992
350 ml                                  989
1 pc (9 ml)                             966
1 pc (15 g)                             965
1 pack (850 g)                          961
1 pc (20 g)                             960
250 ml                                  956
1 set (7 pcs)                           956
150 g + 60 g                            949
1 pack (65 g)                           936
1 pc (190 g)                            930
1 pc (170 g)                            902
2 pcs                                   899
1 pack (4 x 150 g)                      896
1 pack (115 ml)                         894
180 ml                                  893
1 pc (750 g)                            890
1 pc (25 g)                             885
1 pc (5 L)                              878
200 ml X 2                              868
1 pack (57 g)                           863
100 g X 2                               853
1 pc (0.35 g)                           850
1 pc (4.8 g)                            839
1 pc (8 ml)                             837
1 pack (3 x 100 g)                      811
1 pack (41 g)                           809
1 set (4 pcs)                           808
1 pc (350 ml)                           802
1 pack (170 g)                          785
1 pc (12 g)                             784
1 pc (135 ml)                           777
200 g                                   774
1 pc (236 ml or 250 ml)                 774
1 pack (2 kg)                           773
1 pc (450 g)                            771
0.35 g                                  761
1 pc (88 ml)                            751
1 pack (750 g)                          751
1 pc (2.25 L)                           745
500 ml X 2                              745
1 pc (90 ml)                            739
1 pack (130 g)                          737
1 pack (144 g)                          734
300 ml                                  722
2 x 72 pulls                            713
1 pack (19.8 g)                         711
1 pack (60 g or 64 g)                   708
1 pc (175 g)                            703
1 pack (375 g)                          702
60 ml X 2                               701
1 kg                                    696
1 pc (12 ml)                            694
5 ml                                    687
1 pc (2 L)                              683
1 pair                                  675
2 pack (10 pcs)                         668
1 set (8 pcs)                           667
1 pack (240 g)                          665
1 pack (43 g)                           664
1 pack (7 pcs)                          664
500 g                                   657
1 pack (52 g)                           647
1 pc (4 ml)                             643
1 pack (600 g)                          639
1 pc (17 g)                             634
1 pack (100 pcs)                        633
3 combo                                 618
1 piece                                 616
1 pc (55 ml)                            609
1 pack (250 ml)                         606
1 set (4 x 25 ml)                       605
1 pack (275 g)                          601
1 set (4 x 20 ml)                       600
1 pack (900 g)                          599
10 ml X 2                               599
74pcs                                   599
1 kg X 2                                596
1 pc (5 g)                              590
250 ml X 3                              588
1 pc (61 g)                             581
1 pack (3 x 40 g)                       579
1 x 80 pulls                            579
1 pack (3 x 150 g)                      578
30 ml                                   576
1 pc (6 g)                              573
1 pack (79 g)                           570
1 pack (99 g)                           569
1 pack (44 g)                           567
1 pc (118 ml or 125 ml)                 566
1 L X 2                                 554
1 pack (14 pcs)                         553
1.3 L                                   553
1 pack (142 g)                          552
1 pack (210 g)                          549
1.35 L                                  547
1 pack (48 g or 52.9 g)                 547
1 pack (8 pcs)                          547
1.2 kg                                  546
1 pc (3.5 ml)                           545
1.15 kg                                 545
1 pc (45 ml)                            544
1 pc (196 ml)                           540
1 pack (3 x 125 g)                      539
1 pack (4 x 70 g)                       539
1 L X 3                                 539
1 pcs                                   538
1 pack (280 g)                          537
1 pack (270 g)                          536
100 g X 3                               533
70pcs                                   532
1 pc (18 ml)                            531
1 set (6 pcs)                           530
2 x 200 ml                              528
1 pack (160 g or 171 g)                 523
1 pc (320 ml)                           521
1 pc (340 ml)                           518
56pcs                                   515
1 pack (67.5 g)                         512
5.6 ml                                  511
0.3 g                                   510
1 pack (4 x 125 g)                      509
1 pc (245 ml)                           508
70 ml + 60 g                            508
1 pack (168 g)                          507
1 pack (38 g)                           505
1 pack (55 g or 57 g)                   499
1 pack (90 g)                           496
1 pack (900 ml)                         495
450 ml                                  493
2 pcs (375 ml)                          489
1 pack (1.2 kg)                         487
1 pc (240 ml)                           484
1 pack (25 x 1.7 g)                     483
1 pc (180 ml or 190 ml)                 482
230 g                                   481
1 pack (33 g)                           478
1 pc (3 g)                              478
1 set (11 pcs)                          475
80 g                                    475
1 pc (300 ml or 330 ml)                 467
1 pack (128 g)                          461
1 pc (340 g)                            459
1 pc (1.25 kg)                          456
1 pack (30.6 g or 28.9 g)               454
40pcs                                   453
400 g                                   453
1 pack (8 x 250 ml)                     450
1 pack (25 x 2 g)                       450
1 pc (227 g)                            448
1 pack (10 x 10 g)                      446
1 pack (153 g)                          446
1 pack (48 g)                           442
1 pack (95 g)                           440
1 pc (4.5 ml)                           437
1 pack (37.5 g)                         433
1 pack (415 g)                          426
1 pc (210 g)                            425
60 ml X 3                               421
1 pack (225 g)                          420
1 pack (2 x 100 ml)                     420
1 pack (69 g)                           419
150 g X 2                               414
1 pc (1.5 L)                            413
1 pack (20 g or 16 g)                   413
1 pc (175 ml or 180 ml)                 413
1 pack (165 g)                          409
1 pack (110 g)                          407
1 pc (280 ml)                           402
1 pc (35 ml)                            394
1 L                                     394
30 g                                    392
75 g                                    392
250 g X 2                               390
1 set (60 g)                            389
1 pack (4 x 100 g)                      389
1.5 L                                   388
1 pack (120 ml)                         388
1 pack (700 g)                          385
1 pc (225 g)                            380
1 pack (60 pcs)                         379
30pcs                                   378
1 pack (72 pcs)                         376
1 pc (700 g)                            372
1 pack (6 x 12.5 g)                     370
1 pack (159 g)                          368
1 pc (140 g)                            363
1 pc (7 ml)                             362
1 pack (180 ml)                         361
87.5 g + 72 ml                          360
1 pc (65 g)                             358
260 g                                   357
1 pack (5 x 100 g)                      357
1 pack (34 g)                           355
1 kg X 3                                353
1 pack (108 g)                          352
1 pack (27.3 g or 28.2 g)               352
1 pack (2 x 12.5 g)                     350
1 pack (248 g)                          345
400 g X 2                               345
60 g                                    344
1 pc (1.5 g)                            343
1 pack (240 pcs)                        342
1 pc (600 g)                            342
500 g X 2                               339
1 pc (18 g)                             339
1 pc (100 or 110 g)                     335
90 g                                    333
400g                                    332
1 pack (110 ml)                         332
1 pc (1 ml)                             332
200 g X 2                               330
1 pc (46 g)                             329
1 pack (22 g)                           329
55 g X 2                                327
1 pc (36 g)                             326
1 pack (6 Sachets)                      322
1 pack (135 g or 140 g)                 321
1 set (9 pcs)                           321
70 ml X 2                               320
20 pc X 2                               316
1 pack (650 ml)                         314
32pcs                                   312
1 pack (360 g)                          312
180 g                                   311
1 pack (32 g)                           308
1 pc (63 g)                             305
1 pack (70 g or 75 g)                   302
1 pack (950 g)                          302
1 pc (110 g)                            301
144 g X 2                               298
1 pack (59.4 g)                         298
200 ml X 3                              296
1 pc (354 ml)                           296
1 set (10 pcs)                          295
1 pack (75 g or 80 g)                   292
1 pack (16 g)                           291
1 pack (42 g)                           290
1 pack (56 g)                           289
1 x 60 pulls                            289
1 pack (70 g or 100 g)                  288
1 kg X 4                                287
6X1L                                    287
1000 ml                                 285
1 pack (10 x 20 g)                      284
1 pc (380 g)                            283
1 pack (80 ml)                          283
1 pc (100 ml or 118 ml)                 283
120 g X 2                               282
1 pc (80 g or 100 g)                    282
1 Pack (40 g)                           281
1 pc (56 g)                             281
1 pc (500 ml or 473 ml)                 280
52pcs                                   280
1 pack (150 g + 60 g)                   280
1 pc (150 g + 60 g)                     280
1 pack (145 g)                          280
1 pack (48 pcs)                         280
1 pack (62.5 g)                         280
1 pack (29.7 g)                         279
1 pc (27.5 g or 30 g)                   279
1 pack (29.7g)                          279
1 pack (9 pcs)                          278
1 pc (78 g)                             278
1 pack (0.5 g)                          278
2 x 150 g                               278
1.6 g                                   277
500 ml                                  277
2 x 70 ml                               277
1 L X 4                                 276
1 pack (183 g)                          276
1 pack (172 g)                          276
1 pc (825 ml)                           276
1 pack (67 g)                           276
1 pack (100 g or 112 g)                 276
1 pc (62 g)                             276
350 g                                   276
1 pack (4 x 250 ml)                     275
1 pack (188 g)                          275
1 pack (250 ml or 300 ml)               275
1 pack (960 g)                          275
1 pack (475 g)                          275
3 x 75 g                                275
1 pack (52.9 g or 58 g)                 274
1 pack (295 g)                          274
1 pack (91.7 g or 100 g)                274
1 pack (4 x 75 g)                       274
1 pc (47 g or 50 g)                     273
2 x 675 ml                              273
2 x 25 g + 25 ml                        273
1 pack (20 ml)                          272
1 pack (5 x 20 g)                       272
500 ml X 3                              272
10 x 1.3 g                              271
1 pack (192 g)                          271
1 pack (100 g or 115.5 g)               271
1 pack (696 g)                          271
1 pack (172 ml)                         271
1 pack(30 pcs)                          270
70 g                                    270
1 pack (84 g)                           270
5 x 72 pulls                            270
1 pack (585 g)                          269
1 pc (473 ml or 500 ml)                 269
1 pack (159 ml)                         269

:

In [4]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Agra,310,794,575,1270,640,668,379,823,993,516
Ahmedabad,1119,3387,1858,4442,2155,2949,1335,2492,3885,1875
Amritsar,155,331,260,543,259,324,188,385,421,243
Bangalore,7786,26902,14007,28825,16411,20780,9221,21825,29760,15087
Bareilly,160,452,305,667,314,329,192,409,533,288
Belagavi,320,1081,595,1356,712,831,383,838,1117,604
Chandigarh,156,334,264,574,274,386,182,401,438,237
Chennai,3396,11085,6570,13126,7568,9666,4298,9129,13186,6642
Chhatrapati Sambhajinagar,320,920,552,1285,643,726,381,831,1004,576
Coimbatore,156,453,302,660,338,406,192,413,524,316
Davanagere,160,590,292,708,359,418,191,427,575,276
Dehradun,377,1531,918,1975,1036,1140,571,1246,1720,945
Faridabad,925,2620,1882,3996,2256,2663,1142,2525,3524,1786
Gandhinagar,160,468,273,645,310,427,192,376,538,271
Gorakhpur,160,521,320,693,342,308,191,405,556,308
Guntur,160,447,304,688,354,371,192,416,540,273
Hisar,160,342,319,604,352,376,192,414,441,301
Hosur,160,436,304,631,355,395,192,420,493,297
Hubballi,320,942,590,1346,720,801,372,830,1078,606
Hyderabad,6066,21535,11348,25153,13474,17804,7338,17055,23519,11713
Indore,157,401,278,622,293,344,192,402,489,284
Jaipur,751,2213,1387,3105,1616,2130,922,1842,2635,1502
Jalandhar,475,1599,904,2019,989,1159,576,1233,1722,894
Kalyan,156,657,295,721,321,456,191,436,682,290
Kanpur,316,879,566,1243,604,687,384,812,1029,609
Karimnagar,314,858,627,1288,716,744,382,835,1084,550
Karnal,158,470,301,636,355,417,187,409,533,311
Kochi,314,881,602,1238,672,843,382,867,1095,599
Kolkata,1936,6982,4340,8882,4983,6099,2823,5956,7431,3686
Kota,146,380,252,590,275,341,191,402,470,291
Kurukshetra,154,489,319,621,338,379,186,418,551,269
Ludhiana,638,1829,1228,2615,1275,1463,768,1647,2098,1197
Mehsana,160,441,308,667,372,348,192,408,494,300
Mohali,311,1164,598,1297,677,870,329,881,1261,610
Mumbai,5157,14744,10285,20922,13460,16221,6486,15450,19190,9724
Mysuru,636,1815,1153,2636,1306,1582,760,1667,1993,1191
Nagpur,160,541,291,655,357,390,192,424,565,280
Nashik,160,445,310,673,341,353,188,408,568,309
Navsari,152,335,257,532,275,308,190,382,452,288
Panipat,314,890,579,1212,589,647,380,824,1017,527
Patiala,159,586,311,719,307,401,192,412,594,292
Phagwara,147,317,229,553,261,291,188,388,437,200
Prayagraj,320,885,582,1325,643,575,384,821,1051,578
Puducherry,160,626,302,671,364,373,192,421,576,307
Pune,3384,11115,6547,12906,7197,9925,4145,9090,13677,6937
S.A.S Nagar,150,394,286,553,334,434,160,428,557,313
Saharanpur,160,538,320,689,355,330,190,415,526,267
Surat,1091,3206,1967,4233,2177,2558,1338,2754,3756,2161
Talegaon Dabhade,146,238,261,378,246,412,184,351,389,270
Thane,294,894,572,1198,705,900,372,861,1123,568
Udaipur,160,517,301,707,318,403,189,400,568,314
Ulhasnagar,132,195,244,434,281,411,181,372,373,254
Vadodra,160,444,313,666,371,396,192,404,501,310
Varanasi,478,1431,922,2027,992,925,575,1214,1553,910
Vellore,320,1040,600,1417,710,762,384,847,1179,610
Vijayawada,160,481,286,642,345,379,192,414,551,301

In [5]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

category,"Atta, Rice, Oil & Dals",Baby Care,Bath & Body,Biscuits,Breakfast & Sauces,Cold Drinks & Juices,"Dairy, Bread & Eggs",Electronics & Appliances,Feminine Hygiene,Fragrances & Grooming,Frozen Food,Hair Care,Home Needs,Ice Creams & More,Makeup & Beauty,"Masala, Dry Fruits & More",Munchies,Packaged Food,Pharma & Wellness,Protein & Nutrition,Skincare,Stationery & Books,Sweet Cravings,"Tea, Coffee & More",Toys & Sports,Unlisted1,Zepto Cafe
city,,,,,,,,,,,,,,,,,,,,,,,,,,,
Agra,461,417,421,416,314,457,274,23,266,193,54,357,0,436,311,252,432,320,70,4,622,0,283,250,330,0,5
Ahmedabad,1626,1617,1504,1408,1105,1479,1750,131,1022,716,207,1172,5,1493,1138,683,1541,928,250,0,2403,1,796,861,1570,0,91
Amritsar,219,183,182,169,155,197,137,3,127,79,26,162,0,155,118,121,217,154,33,1,264,0,167,122,116,0,2
Bangalore,12084,12708,11773,9574,7527,11306,12889,957,7336,4416,1132,7659,120,11706,6596,6058,10747,8073,1655,0,18397,116,8604,5825,12122,45,1179
Bareilly,230,236,220,211,158,235,171,28,144,100,0,187,0,224,168,129,217,160,34,1,330,0,148,128,188,0,2
Belagavi,474,502,473,443,316,502,417,60,290,198,62,360,0,478,366,262,437,325,70,0,670,0,358,256,514,0,4
Chandigarh,224,175,187,169,156,207,199,3,132,85,28,155,0,155,132,126,212,162,32,0,286,0,165,127,127,0,2
Chennai,5342,5559,5483,4451,3196,5306,6136,419,2877,1957,299,3577,35,5075,2785,2704,5055,2806,784,23,8369,28,4073,2513,5151,0,663
Chhatrapati Sambhajinagar,466,392,430,416,316,460,285,37,267,206,62,373,0,445,315,261,440,317,69,0,603,0,356,256,462,0,4
Coimbatore,230,240,218,224,157,254,211,13,141,108,31,176,0,226,168,129,223,163,34,0,329,0,170,127,185,0,3
Davanagere,240,261,250,221,158,255,205,31,145,111,31,189,0,242,180,131,222,160,36,0,351,0,149,128,298,0,2
Dehradun,600,771,733,647,474,723,584,61,460,319,91,549,0,737,528,381,667,469,114,0,972,0,529,376,664,4,6
Faridabad,1398,1147,1497,1306,799,1490,1876,96,948,664,162,1074,2,1434,1032,780,1305,945,204,6,1980,0,1043,755,1355,0,21
Gandhinagar,233,227,219,207,158,213,259,0,151,104,29,171,0,215,169,98,220,133,36,0,340,0,115,122,209,0,32
Gorakhpur,230,256,211,224,158,235,170,30,144,94,1,188,1,230,191,129,216,162,34,0,352,0,176,128,242,0,2
Guntur,236,221,231,220,158,253,170,20,140,112,30,183,0,245,178,128,219,163,35,1,334,0,145,128,193,0,2
Hisar,233,153,202,224,160,245,193,3,126,98,30,160,0,239,158,129,215,160,34,0,271,0,181,128,156,1,2
Hosur,234,231,216,208,158,243,219,5,134,85,32,158,0,238,172,130,222,160,34,0,322,0,177,128,175,0,2
Hubballi,464,480,454,438,316,506,400,59,276,201,62,351,0,476,356,248,436,321,68,0,663,0,360,252,412,2,4
Hyderabad,9505,10524,9318,7742,6099,8795,11797,697,5981,3909,862,6305,87,9837,6373,4808,8657,6004,1393,0,14696,34,6224,4821,9765,0,772
Indore,226,209,201,195,159,206,149,4,136,92,29,178,0,210,139,129,218,153,34,1,320,0,171,127,174,0,2
Jaipur,996,1083,1072,936,771,1055,1320,50,736,531,137,846,0,1153,741,624,1084,749,164,0,1591,0,839,614,994,5,12
Jalandhar,694,860,653,643,473,739,581,77,456,322,80,563,6,689,475,388,669,480,108,0,1069,0,492,382,664,0,7
Kalyan,252,341,246,202,157,230,277,30,148,124,30,189,5,214,171,125,218,173,37,0,454,2,179,127,272,1,1
Kanpur,453,479,416,380,320,439,370,20,282,184,2,334,0,430,310,256,446,321,68,0,658,0,349,256,352,0,4
Karimnagar,465,443,459,437,317,508,369,37,286,216,62,328,0,486,334,258,438,324,68,4,644,0,296,251,364,0,4
Karnal,228,257,222,207,156,254,233,17,144,103,30,165,0,244,163,128,217,156,35,0,325,0,178,124,189,0,2
Kochi,475,494,424,422,314,492,468,38,300,204,60,333,0,451,344,252,438,320,71,0,628,0,353,250,326,0,36
Kolkata,2859,3307,2955,2926,2361,3363,3658,204,1856,1334,439,2359,6,3131,2398,1890,3236,2347,518,14,4759,4,1952,1847,3148,0,247
Kota,213,190,194,177,158,196,139,5,134,88,25,176,0,209,121,128,217,159,31,1,310,0,175,127,163,0,2
Kurukshetra,226,257,226,224,158,239,227,15,151,99,0,174,0,236,156,128,216,156,35,1,322,0,147,126,203,0,2
Ludhiana,925,942,841,844,636,961,723,67,574,413,107,732,3,876,623,520,888,637,128,0,1330,0,700,509,770,0,9
Mehsana,227,203,207,219,158,252,201,18,140,91,0,179,0,242,176,130,219,161,34,1,322,0,177,128,203,0,2
Mohali,463,569,513,415,311,489,498,46,308,189,54,344,5,423,306,249,390,323,69,0,788,0,347,252,529,0,118
Mumbai,8211,7886,7428,7161,5351,8432,10879,584,4550,3603,954,4837,70,7887,5345,4345,7574,5141,1184,0,12541,28,5645,4183,5920,35,1865
Mysuru,930,869,887,819,636,912,839,36,530,406,117,716,0,918,663,516,868,626,138,0,1272,0,687,508,832,4,10
Nagpur,238,229,231,215,158,250,185,31,143,112,29,172,2,250,174,130,221,171,33,1,316,0,150,128,282,1,3
Nashik,233,231,228,216,154,242,192,15,155,103,1,178,0,246,175,128,218,154,35,0,355,0,180,125,187,0,4
Navsari,217,167,189,176,155,208,121,2,129,89,29,116,0,214,135,123,214,150,32,0,289,0,158,117,139,0,2
Panipat,460,432,436,419,313,428,259,16,272,174,60,353,1,431,295,250,434,325,66,2,612,0,279,254,404,0,4
Patiala,229,282,235,215,160,232,214,31,157,101,28,189,0,203,181,128,220,167,34,0,386,0,177,128,274,0,2
Phagwara,215,177,183,153,151,200,96,3,127,81,24,164,0,148,117,118,219,159,33,0,274,0,131,118,118,0,2
Prayagraj,461,498,420,415,316,453,272,22,296,182,2,369,0,401,321,256,440,322,72,0,691,0,352,250,349,0,4
Puducherry,234,300,237,208,158,256,187,31,157,102,31,191,0,246,167,129,224,160,35,0,334,0,178,128,297,0,2
Pune,5320,5580,5487,4512,3416,4837,6213,336,3389,2017,674,3623,45,5120,2916,2816,4789,3415,793,0,7812,0,3433,2666,5122,0,592
S.A.S Nagar,222,231,229,197,153,242,250,14,145,93,27,154,0,223,122,122,191,155,33,0,323,0,171,124,131,0,57
Saharanpur,233,251,213,224,158,252,143,22,149,107,31,187,0,237,178,128,215,163,35,0,335,0,145,128,253,1,2
Surat,1565,1676,1550,1336,1113,1643,1250,107,1009,776,205,922,3,1616,1020,881,1505,1095,241,0,2368,0,1170,862,1307,0,21
Talegaon Dabhade,210,141,165,171,149,167,244,1,104,54,30,130,0,199,66,126,215,126,31,0,204,0,136,107,97,0,2
Thane,473,480,435,395,307,465,568,39,264,202,60,284,5,453,305,247,430,300,66,0,721,2,324,240,355,2,65
Udaipur,228,263,228,221,158,238,206,31,146,110,27,188,0,224,171,129,215,162,36,0,368,0,173,128,225,0,2
Ulhasnagar,200,103,168,160,145,205,245,1,96,69,29,91,0,207,113,119,215,123,30,0,234,0,136,108,78,1,1
Vadodra,229,231,212,217,159,255,222,9,141,93,30,184,0,243,171,130,217,162,34,0,323,0,176,128,188,0,3
Varanasi,687,727,641,666,474,702,464,34,440,289,2,558,1,676,524,384,650,484,102,0,1001,0,493,384,638,0,6
Vellore,482,507,495,438,317,499,381,56,297,230,58,363,0,483,371,264,435,317,68,0,712,0,358,256,478,0,4
Vijayawada,233,232,226,209,158,247,169,23,142,89,31,161,0,244,182,130,218,163,34,0,329,0,176,127,225,1,2

In [6]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals]"
1,Baby Care,"[Baby Care, Dairy, Bread & Eggs, Home Needs, Packaged Food, Pharma & Wellness, Skincare, Stationery & Books, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Bath & Body, Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare, Unlisted1]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Biscuits, Breakfast & Sauces, Cold Drinks & Juices, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food, Protein & Nutrition, Sweet Cravings, Unlisted1]"
6,Munchies,"[Biscuits, Masala, Dry Fruits & More, Munchies, Packaged Food, Unlisted1]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Home Needs, Makeup & Beauty, Pharma & Wellness, Skincare, Unlisted1]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Frozen Food, Ice Creams & More, Munchies, Packaged Food, Sweet Cravings]"

In [4]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag              No    Yes   Total  Out_of_stock_%
city
S.A.S Nagar                  2296   1313    3609           36.38
Karimnagar                   5045   2353    7398           31.81
Mumbai                      90239  41400  131639           31.45
Thane                        5147   2340    7487           31.25
Kalyan                       2971   1234    4205           29.35
Vijayawada                   2652   1099    3751           29.30
Kolkata                     39117  14001   53118           26.36
Ulhasnagar                   2139    738    2877           25.65
Chennai                     64217  20449   84666           24.15
Udaipur                      2960    917    3877           23.65
Guntur                       2916    829    3745           22.14
Pune                        66135  18788   84923           22.12
Nashik                       2968    787    3755           20.96
Ahmedabad                   20383   5114   25497           20.06
Jaipur                      14489   3614   18103           19.96
Surat                       20311   4930   25241           19.53
Coimbatore                   3033    727    3760           19.34
Jalandhar                    9349   2221   11570           19.20
Gandhinagar                  2975    685    3660           18.72
Faridabad                   19058   4261   23319           18.27
Navsari                      2592    579    3171           18.26
Mohali                       6557   1441    7998           18.02
Hyderabad                  127151  27854  155005           17.97
Kochi                        6172   1321    7493           17.63
Gorakhpur                    3148    656    3804           17.25
Amritsar                     2575    534    3109           17.18
Puducherry                   3330    662    3992           16.58
Chhatrapati Sambhajinagar    6101   1137    7238           15.71
Bangalore                  161397  29207  190604           15.32
Patiala                      3383    590    3973           14.85
Bareilly                     3120    529    3649           14.50
Dehradun                     9806   1653   11459           14.43
Vellore                      6738   1131    7869           14.37
Hubballi                     6512   1093    7605           14.37
Prayagraj                    6153   1011    7164           14.11
Belagavi                     6732   1105    7837           14.10
Mehsana                      3175    515    3690           13.96
Davanagere                   3448    548    3996           13.71
Chandigarh                   2801    445    3246           13.71
Kurukshetra                  3215    509    3724           13.67
Ludhiana                    12741   2017   14758           13.67
Vadodra                      3246    511    3757           13.60
Varanasi                     9542   1485   11027           13.47
Nagpur                       3366    489    3855           12.68
Karnal                       3312    465    3777           12.31
Hisar                        3078    423    3501           12.08
Mysuru                      13009   1730   14739           11.74
Kanpur                       6313    816    7129           11.45
Indore                       3079    383    3462           11.06
Hosur                        3297    386    3683           10.48
Kota                         3010    328    3338            9.83
Agra                         6300    668    6968            9.59
Saharanpur                   3431    359    3790            9.47
Panipat                      6359    620    6979            8.88
Talegaon Dabhade             2624    251    2875            8.73
Phagwara                     2924     87    3011            2.89

In [7]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag         No    Yes   Total  Out_of_stock_%
department
Bakery & Biscuits      61409  19352   80761           23.96
Dairy & Breakfast      90328  26696  117024           22.81
Personal Care         121874  35741  157615           22.68
Baby Care             105611  30480  136091           22.40
Organic & Premium      93795  23160  116955           19.80
Atta, Rice & Dal       34583   7929   42512           18.65
Beauty & Cosmetics    138716  31763  170479           18.63
Cold Drinks & Juices   77056  17236   94292           18.28
Munchies               44721   7562   52283           14.46
Sweet Tooth            70044  11419   81463           14.02

In [8]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No    Yes  Total  Out_of_stock_%
category
Zepto Cafe                   833   5070   5903           85.89
Unlisted1                     16     87    103           84.47
Home Needs                   235    167    402           41.54
Electronics & Appliances    2911   1837   4748           38.69
Dairy, Bread & Eggs        50032  21122  71154           29.68
Stationery & Books           158     57    215           26.51
Fragrances & Grooming      20226   6601  26827           24.61
Protein & Nutrition           46     15     61           24.59
Baby Care                  51221  16206  67427           24.03
Feminine Hygiene           30471   9125  39596           23.05
Biscuits                   43364  12524  55888           22.41
Toys & Sports              47313  13171  60484           21.78
Makeup & Beauty            32714   8889  41603           21.37
Sweet Cravings             35838   9564  45402           21.07
Skincare                   78644  19230  97874           19.65
Bath & Body                51217  12157  63374           19.18
Atta, Rice, Oil & Dals     52676  12265  64941           18.89
Frozen Food                 5498   1267   6765           18.73
Hair Care                  36502   8034  44536           18.04
Packaged Food              35148   7436  42584           17.46
Pharma & Wellness           8003   1581   9584           16.50
Masala, Dry Fruits & More  28893   5598  34491           16.23
Breakfast & Sauces         35894   6852  42746           16.03
Munchies                   50992   9729  60721           16.02
Cold Drinks & Juices       54099  10050  64149           15.67
Tea, Coffee & More         28816   4932  33748           14.61
Ice Creams & More          56377   7772  64149           12.12

In [9]:
same_store_diff = (
    df.groupby(["store_id", "store_name_location", "city", "unique_id"])
    .agg(
        product_name=("product_name", "first"),
        price_count=("item_selling_price", "nunique"),
        discount_count=("discount_in_percent", "nunique"),
        mrp_count=("item_mrp", "nunique")
    )
    .reset_index()
)

same_store_diff = same_store_diff[
    (same_store_diff["price_count"] > 1) |
    (same_store_diff["discount_count"] > 1) |
    (same_store_diff["mrp_count"] > 1)
]

same_store_diff

Empty DataFrame
Columns: [store_id, store_name_location, city, unique_id, product_name, price_count, discount_count, mrp_count]
Index: []

In [10]:
import re

# Normalize brand names
df["brand_norm"] = (
    df["brand_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
brand_issue = (
    df.groupby("brand_norm")
    .agg(
        variant_count=("brand_name", "nunique"),
        brand_variants=("brand_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

brand_issue = brand_issue[brand_issue["variant_count"] > 1]

brand_issue

,brand_norm,variant_count,brand_variants
209,bonn,2,"[Bonn, bonn]"
213,borges,2,"[BORGES, Borges]"
299,cocacolaus,2,"[Coca-Cola US, Coca-cola US]"
380,delichic,2,"[Deli Chic, Delichic]"
782,kharifoods,2,"[KHARI FOODS, Khari Foods]"
1066,noto,2,"[NOTO, Noto]"
1144,paperboat,2,"[PAPER BOAT, Paper Boat]"
1157,patanjali,2,"[PATANJALI, Patanjali]"
1192,plixtheplantfix,2,"[Plix -The Plant Fix, Plix The Plant Fix]"
1405,star,2,"[STAR, Star]"
1437,sunscoop,2,"[SunScoop, Sunscoop]"

In [11]:
productid_name_issue = (
    df.groupby("product_id_upc_ean")
    .agg(
        product_name_count=("product_name", "nunique"),
        product_names=("product_name", lambda x: sorted(x.unique()))
    )
    .reset_index()
)

productid_name_issue = productid_name_issue[
    productid_name_issue["product_name_count"] > 1
]

productid_name_issue

Empty DataFrame
Columns: [product_id_upc_ean, product_name_count, product_names]
Index: []

In [12]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
254,Mumbai,1b11ac6b-6de6-411b-80bf-a72874a80c51,1437,1926,3363,57.27
273,Mumbai,52917883-e475-4632-9fa3-9c99ba0f4b78,322,331,653,50.69
120,Chennai,ee6f8d8a-94dc-47c7-a4c5-7ea1efe3031b,1961,1695,3656,46.36
359,Thane,5223893f-f150-4fb3-9f8b-2e86a7c15af1,26,22,48,45.83
123,Chennai,fb0d381c-e38f-4bcc-a5f8-872e3e033e62,2000,1681,3681,45.67
233,Kolkata,8bf314ef-f9e5-4425-a4a9-9a535764e613,2043,1617,3660,44.18
261,Mumbai,2c911eaa-a276-47bc-92d8-447d166f2dfa,1803,1422,3225,44.09
229,Kolkata,5fdc5ed4-7a93-4c29-88bc-f40964758005,1982,1503,3485,43.13
249,Mumbai,01185b5e-b794-4cfb-99c9-625397e548ac,1870,1403,3273,42.87
292,Mumbai,bc2668de-4e8e-4ffb-a2c9-91bf4a5dd846,1819,1343,3162,42.47
296,Mumbai,cc72f206-e146-43c5-a01b-56ddc8d11464,2008,1355,3363,40.29
285,Mumbai,a20f91f9-3e2c-48fd-a720-a6bf6685a6fe,777,513,1290,39.77
297,Mumbai,d390ee2b-1c8f-4236-9c8b-b60173fd330a,1199,791,1990,39.75
262,Mumbai,329deb14-183d-4581-90eb-8c40a5e91fd5,2280,1479,3759,39.35
269,Mumbai,4a54d5f5-0bd9-4b8f-b08a-120d8e7926d7,2016,1264,3280,38.54
294,Mumbai,c688da38-967b-4e15-862f-458ce8ea6821,2032,1255,3287,38.18
288,Mumbai,ab5b8567-c808-4008-8793-b83489a3c6fa,1979,1200,3179,37.75
289,Mumbai,ab94c840-ae17-491f-95b5-b32bf84ca808,2093,1256,3349,37.50
277,Mumbai,684a75ae-c944-480c-a64f-76a1a9cfa393,1865,1111,2976,37.33
286,Mumbai,a5d48a70-31d9-4c5f-b61f-daae4ab4e3b3,2100,1239,3339,37.11
228,Kolkata,5d94bdb2-32fe-42f1-bc68-732d1d7ccb11,430,253,683,37.04
348,S.A.S Nagar,856f5f52-8b1c-4089-b242-6c5dd371777e,2296,1313,3609,36.38
110,Chennai,691e4cd7-b08a-421b-a35d-6c89173b796e,2178,1243,3421,36.33
272,Mumbai,5223893f-f150-4fb3-9f8b-2e86a7c15af1,867,494,1361,36.30
238,Kolkata,eedbad6f-ada7-40cd-922e-828198efed50,2377,1316,3693,35.63
121,Chennai,efe487f5-0138-496c-9360-ba76a80cd46f,2315,1277,3592,35.55
347,Pune,fe4a16ca-6c7c-4f1a-88a7-fecda52d8057,2312,1254,3566,35.17
193,Hyderabad,d54cc989-bc58-4cb9-9c2e-3a3468546c3f,2322,1249,3571,34.98
284,Mumbai,9ab4aaf2-f0b5-477c-b633-b3a555b0db42,2389,1276,3665,34.82
275,Mumbai,5feee4ae-dfd9-4484-b060-722c7802c642,2129,1129,3258,34.65
236,Kolkata,cd098e80-d516-4508-b4fc-3d7f10461033,2247,1175,3422,34.34
217,Karimnagar,a06b81f7-ce53-499c-bcd0-768ec804abae,2438,1264,3702,34.14
196,Hyderabad,de95e00b-0ebf-4f65-8f27-df66fd91dc13,655,334,989,33.77
259,Mumbai,291264cf-55b8-4ae3-93b2-cb23fd795054,2173,1104,3277,33.69
176,Hyderabad,a2271e79-a91e-4f7a-8a89-c69982cb5fbc,2143,1082,3225,33.55
214,Kalyan,dcd44f07-e040-4b33-a69b-c1f10b201b89,1978,993,2971,33.42
274,Mumbai,5f267ad5-446b-4a8b-86f0-df174ad545dd,2153,1080,3233,33.41
317,Pune,315e9d84-2c4a-45b2-88fb-f6733794efba,2106,1054,3160,33.35
222,Kolkata,0af692ee-167f-4903-bf7c-959643e47899,2346,1126,3472,32.43
260,Mumbai,292b8fc9-b6f3-43c3-a2a0-349f135c6e8a,2468,1183,3651,32.40
98,Chennai,22cd61da-18f7-490b-9394-24abc3780214,2448,1173,3621,32.39
258,Mumbai,238a227d-697c-4fa9-a4f5-4fd064760098,2232,1066,3298,32.32
360,Thane,89644478-a004-4d2c-a04d-ced0f26ede4f,1958,928,2886,32.16
113,Chennai,839c4631-7b88-4c92-b55f-fe1fd4a12303,2427,1132,3559,31.81
345,Pune,f737581f-b7f3-450a-8cf7-f5fb6e6184a0,2185,1011,3196,31.63
252,Mumbai,0ef81b30-ea84-46ec-98b0-6f3894d1ca1d,1772,817,2589,31.56
361,Thane,95d6c1a2-b071-4cf3-a322-30b5754d7cb6,835,383,1218,31.44
270,Mumbai,50be453c-91e9-4a62-913c-3d6add84eb57,2228,1006,3234,31.11
256,Mumbai,2050a7de-e13c-4947-bac7-7995d8c6e72d,2254,1018,3272,31.11
282,Mumbai,95d6c1a2-b071-4cf3-a322-30b5754d7cb6,9,4,13,30.77
279,Mumbai,7333c09a-d46f-4c45-845d-360e2ed38c8e,2158,953,3111,30.63
99,Chennai,2a82431b-9c30-453e-a6b9-4dc586ae5e75,2504,1093,3597,30.39
362,Thane,cf7f18ae-84f3-429a-a19d-f35f08e97c58,2328,1007,3335,30.19
298,Mumbai,dae4ebff-33f8-425f-88c1-aae075ee7a52,2128,918,3046,30.14
328,Pune,8f1d26b5-d168-42b5-9aa2-fc76bbd55a9f,2076,895,2971,30.12
264,Mumbai,37b900f0-25c0-448b-825a-74d62c8ceb41,2306,994,3300,30.12
276,Mumbai,662012a6-9b5c-4471-8051-f83675b0d84c,2288,986,3274,30.12
268,Mumbai,48018697-39cd-458a-a2dc-b6ac22e6b5c0,2097,893,2990,29.87
293,Mumbai,c2279e92-0a29-4470-861e-28a8798e031f,2348,986,3334,29.57
250,Mumbai,0b45bb12-e3bd-415b-b298-ee97db10a222,2618,1094,3712,29.47
218,Karimnagar,d096ba7c-7e56-41ec-adc1-8b71b0107da1,2607,1089,3696,29.46
371,Vijayawada,086819d5-945b-4e11-b392-bf9a421d9fd2,2652,1099,3751,29.30
344,Pune,f68f6daf-2bba-450e-9a05-082e29e9129d,2594,1066,3660,29.13
112,Chennai,7fbf2dd5-101c-4f92-802d-728264804add,2588,1062,3650,29.10
115,Chennai,a98f0f81-73ab-4839-8d06-4e9427680054,2224,909,3133,29.01
323,Pune,4cc5f8ae-6495-44d0-9212-b63fe11a3af5,2590,1055,3645,28.94
322,Pune,4b7f2491-a77d-4e8d-9317-08f5a29fc821,2579,1045,3624,28.84
271,Mumbai,5116a0c5-42bc-487c-ac82-37af432606b0,2198,872,3070,28.40
33,Bangalore,3fdf2ec3-0ac0-4e8d-a7f0-e184ef12fbe6,2614,1027,3641,28.21
223,Kolkata,285e3359-d42c-4b88-9edb-35550d7f3b41,2673,1024,3697,27.70
3,Ahmedabad,1105d3fb-0556-4f7e-bd83-416274e9924a,2687,998,3685,27.08
281,Mumbai,8a278c72-1366-4926-b81e-ecc6e64df2a7,776,287,1063,27.00
265,Mumbai,38ac846f-6255-4a51-8bad-bf50f3c23827,2423,883,3306,26.71
166,Hyderabad,77acda94-75cc-4146-952c-813f5bd745dd,2763,1003,3766,26.63
340,Pune,dd520c1a-80de-4060-9e8a-7b2156223efe,2547,908,3455,26.28
151,Hyderabad,2d8ae8c3-c7c3-4826-8802-e386af7f5385,2309,816,3125,26.11
364,Ulhasnagar,0dc96e2e-5de7-461c-b162-d8ee5de175f8,2139,738,2877,25.65
154,Hyderabad,33a1d02e-1bb7-44cc-8d38-9697bcc23dba,906,310,1216,25.49
210,Jalandhar,1fc29afb-f9cf-4819-8af5-dc02edf25642,2959,998,3957,25.22
225,Kolkata,4d3f28cf-646c-49cb-833b-0dbce82498d5,2650,880,3530,24.93
106,Chennai,5d83d37a-c7fa-4891-b9dd-72c9d308f862,2649,867,3516,24.66
94,Chennai,01c75445-012e-4df6-b075-6856318038cc,2295,750,3045,24.63
156,Hyderabad,477d50e9-2c13-435c-8db4-dd0077b4ab2e,958,310,1268,24.45
237,Kolkata,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,464,150,614,24.43
28,Bangalore,376dd638-f05e-4171-b4e1-b97650b79fe7,2813,907,3720,24.38
318,Pune,34597f4e-8acd-434a-a983-4c7d80c7afd7,2205,704,2909,24.20
148,Hyderabad,26ec9b6b-b566-4f36-b5dd-eb6fb92a0caf,2528,804,3332,24.13
246,Mohali,376a9a5f-23b2-40c8-9e64-07c14070f06d,2686,854,3540,24.12
80,Bangalore,e044093d-2a02-4fd7-a1e9-5542edbe746a,2315,732,3047,24.02
188,Hyderabad,c96055f6-ed06-46e5-93af-58fa1a374792,2726,856,3582,23.90
114,Chennai,8e706906-0373-4de9-b9f7-cbfcc5ab2bca,2685,843,3528,23.89
329,Pune,8f1fca85-ee88-4e44-8993-d22b98cd6c1b,2756,865,3621,23.89
155,Hyderabad,43b12c97-dc99-431a-9ba3-e3cde9c716bb,2844,892,3736,23.88
363,Udaipur,29d47abc-4861-444d-baf6-b32eb28f98a6,2960,917,3877,23.65
171,Hyderabad,8dcc9bd0-fb05-42e9-96c7-ef15a999c522,983,302,1285,23.50
96,Chennai,1669ccf3-23b3-4ba3-b5c5-8a984549717c,2132,645,2777,23.23
206,Jaipur,32989280-a610-4395-aca5-5ba4823af4bd,2944,884,3828,23.09
209,Jaipur,e4a1792d-8ffa-4015-a415-e91fe2f01493,2920,875,3795,23.06
66,Bangalore,a7860f3d-39d4-4275-811d-904d4c2438f4,1213,363,1576,23.03
132,Faridabad,3d277bf6-7a5f-498a-a956-56fd8ab9ef82,2949,878,3827,22.94
73,Bangalore,ccc9dc9b-9c6f-421e-bedc-f2e7463a75e9,2834,837,3671,22.80
353,Surat,4eeabcee-900c-419e-a2bb-102bbb205c7a,2574,758,3332,22.75
187,Hyderabad,c58033dc-cb75-414a-8c20-b1e0825c812d,2903,854,3757,22.73
331,Pune,97a88d32-5435-4ba1-b678-b881529ce97d,2436,712,3148,22.62
7,Ahmedabad,84bf9085-f4e6-4c8c-9cf6-9876beafada3,2845,820,3665,22.37
339,Pune,db4ee2ab-1f56-4e37-9969-3407620c48f5,2520,717,3237,22.15
140,Guntur,f39c8468-8ad4-41c4-b159-1b0d9a2d0a6f,2916,829,3745,22.14
231,Kolkata,74039f14-48e6-4a32-b70f-7ddda4c42900,2727,774,3501,22.11
346,Pune,f931724a-0140-4c06-b832-027e03fc320a,1049,297,1346,22.07
283,Mumbai,97a25366-1a8e-4834-9d57-a976e76af3dc,2530,716,3246,22.06
47,Bangalore,6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a,1191,337,1528,22.05
205,Jaipur,133688fc-cadd-4750-bb5f-f595c5eca821,2959,835,3794,22.01
190,Hyderabad,cd6c08c9-56dc-4f63-8aee-c53fbd38927b,2890,812,3702,21.93
89,Bangalore,ff56ec59-36c7-41a0-ab98-1a3390126da5,2492,695,3187,21.81
116,Chennai,b51017b6-8aed-4bff-a391-ba12ec8f9cee,2426,676,3102,21.79
83,Bangalore,e6ebaf4d-7f47-44bd-bb8f-f7ab1e884191,2897,804,3701,21.72
355,Surat,b13fc494-3fe6-4797-a8e5-1038a797140d,2850,787,3637,21.64
350,Surat,21217c69-8530-4f00-9366-e96ab493bfe8,2582,701,3283,21.35
17,Bangalore,0cde9637-ca43-45b6-a89c-08c1e32bae57,2394,643,3037,21.17
71,Bangalore,c647bfb4-1b5a-433d-ba29-0c75c2da883e,506,135,641,21.06
307,Nashik,1794eede-9e42-4a9c-b132-0be5b0e4e4a4,2968,787,3755,20.96
32,Bangalore,3bf7d17f-4fa3-481d-b14d-66ca5c4f14da,1189,313,1502,20.84
337,Pune,befaa444-90e6-4691-a2d0-614d59ac0f1d,2550,669,3219,20.78
64,Bangalore,a1c67132-94e3-41b9-975b-4ef4e4851406,3319,869,4188,20.75
56,Bangalore,843e630a-7896-462d-b7cf-712140483ed3,1151,300,1451,20.68
356,Surat,e7cfb807-6977-42cb-90de-2a3a2527d6c3,2735,707,3442,20.54
257,Mumbai,21db1e24-d6a7-484a-b5aa-b43e1aafb8fc,902,232,1134,20.46
253,Mumbai,13d9641e-8c4f-4bca-b2e9-a1f6ceaa55dd,2643,679,3322,20.44
150,Hyderabad,2b293e1e-3e46-4377-aa87-b860c58730c9,2797,717,3514,20.40
23,Bangalore,2240913f-e14f-46cc-94e8-ff6f5c32ffab,2409,616,3025,20.36
21,Bangalore,1c9e155e-83a8-457a-a687-01eabb1e7a36,1293,328,1621,20.23
74,Bangalore,cd653888-0a9a-4251-8d70-7df4c8c2f22a,2564,649,3213,20.20
266,Mumbai,3b18ee5e-9d22-44cd-acff-646042e546bf,955,241,1196,20.15
53,Bangalore,774a725c-2c4b-4dc2-94d1-72b737f7e1f6,1240,312,1552,20.10
63,Bangalore,a09f04ca-3c1d-4523-8606-386ce213a7ae,2592,646,3238,19.95
235,Kolkata,a747aca8-5583-4f32-aa16-e804cefaa95a,2903,722,3625,19.92
153,Hyderabad,314533d4-8bd7-4985-8ca5-9b737431149b,2975,738,3713,19.88
183,Hyderabad,b8586096-1740-4c36-a7cf-e23a30ff3abb,409,101,510,19.80
101,Chennai,3994880c-5e18-4de9-9f68-847c18108e27,2791,687,3478,19.75
9,Ahmedabad,be8c29f7-cb07-48e2-8239-5df581ba541b,2796,684,3480,19.66
161,Hyderabad,5ca7734d-e625-4328-8588-a4a102966b36,2789,679,3468,19.58
8,Ahmedabad,9c6fce71-3aec-455c-969f-075ba74fa0d5,2927,712,3639,19.57
76,Bangalore,cf384ecd-5e1f-47e9-9194-8e9dc940e8c3,2578,627,3205,19.56
330,Pune,931f1ec1-e287-4412-9b52-df3f8ab9c95c,1112,270,1382,19.54
213,Kalyan,a9588bc2-3d75-410c-88c3-ec029bf4593a,993,241,1234,19.53
14,Bangalore,055af6e1-5726-4e98-84fa-2ce7da4d382d,1277,310,1587,19.53
104,Chennai,59099ea0-3411-4169-9c90-206cb03ef12a,1085,263,1348,19.51
57,Bangalore,856b33b6-5cfb-4b67-8702-62b49fc5db26,2927,707,3634,19.46
226,Kolkata,4e626392-c497-4cf8-9a07-d2576c1d8988,2876,694,3570,19.44
133,Faridabad,425e3ad2-0f08-4dbb-b90b-c892dc41be83,2872,691,3563,19.39
126,Coimbatore,6e8bac7d-b774-43ae-9fba-3a2c9ce4637a,3033,727,3760,19.34
357,Surat,ffa16021-e499-4c0b-80b1-aabca4b46cfd,2960,706,3666,19.26
167,Hyderabad,7a85bcbe-fbfc-4ad8-be93-9da42c05a380,2942,700,3642,19.22
75,Bangalore,cf1fab3e-edc1-4a8a-8054-5abe91c20f69,2347,548,2895,18.93
304,Mysuru,95fb7963-3983-4250-9151-301261f84b3e,3116,726,3842,18.90
224,Kolkata,311ccac4-761e-4862-beeb-f41ba7e37bec,2721,632,3353,18.85
200,Hyderabad,e531dd78-694e-4025-afdb-76adec0f6d48,877,203,1080,18.80
343,Pune,e9da3e70-081c-4c4d-abad-5d88303ced92,2477,571,3048,18.73
138,Gandhinagar,4ef0ca3e-626a-4770-8efe-9eda4c147b0b,2975,685,3660,18.72
60,Bangalore,97301572-98d1-4b4d-8e40-d52748fe5233,2622,599,3221,18.60
326,Pune,7a75116f-d14e-49b3-bfde-a6c2a4d180a7,1088,248,1336,18.56
336,Pune,ba4957a9-6519-443e-9919-8c71440d61dc,2654,602,3256,18.49
220,Kochi,a0cc192c-a4e7-4671-aacd-ce6891b53bba,3058,691,3749,18.43
2,Ahmedabad,0bbde96c-7012-4731-afad-78c7bf7b381e,878,198,1076,18.40
6,Ahmedabad,754e6a75-5f25-4e49-ad20-d4034241e11c,2652,598,3250,18.40
173,Hyderabad,936f8969-5c1b-4ebc-976b-ee4324c0accb,3048,687,3735,18.39
149,Hyderabad,29f978f1-5bc3-4358-a811-4b817ebebfcb,2650,596,3246,18.36
308,Navsari,bdd193e6-8ee2-4ee4-bf18-22ed8772b20d,2592,579,3171,18.26
338,Pune,ca7b9f78-e53b-480a-8e1b-11ebd8cde4e2,2609,582,3191,18.24
301,Mumbai,eb92685d-4aad-4424-b38f-f876e41640a8,1042,231,1273,18.15
131,Faridabad,04c98d7c-c6bf-41f6-8d43-dc50e7c0edb1,3181,705,3886,18.14
203,Hyderabad,fc88e94a-f4b7-4eab-8ce0-fdecf2e29d5f,990,219,1209,18.11
263,Mumbai,3608083a-c098-4f58-bc13-4a729a103909,984,216,1200,18.00
251,Mumbai,0e8c4509-c9cd-4235-9da5-18fbede8ce72,902,197,1099,17.93
137,Faridabad,ccb84935-4941-4c2f-a0cf-a65d8a6cf57a,3190,691,3881,17.80
158,Hyderabad,56d50978-df14-48ba-aec8-79644b36fd6a,999,216,1215,17.78
342,Pune,e8d2b0f5-541c-4bc5-812d-67f6ed429043,2649,572,3221,17.76
327,Pune,7c05017d-f3fd-4845-9a6f-81e9f9a60231,678,146,824,17.72
162,Hyderabad,67ec5278-78c4-4654-b67d-c0433f5406c7,2651,570,3221,17.70
212,Jalandhar,6d105ce4-1dd6-416f-86d3-310f7f2ffaab,3208,690,3898,17.70
157,Hyderabad,4c93e224-40da-4c86-a5ff-c9c2cfee1168,954,203,1157,17.55
186,Hyderabad,bd86f0fb-6044-45d9-be30-8b58c26e3688,3288,699,3987,17.53
5,Ahmedabad,46b54f69-c5ff-4595-934d-3d98fbf33ec0,2102,445,2547,17.47
319,Pune,34d81293-1443-44be-9db9-043f95f184ee,1251,264,1515,17.43
351,Surat,2918790f-421a-493e-84a3-e9a2d8f0b60d,537,113,650,17.38
136,Faridabad,b463b5a9-6661-4ee9-b58b-03b285ac536e,3210,673,3883,17.33
164,Hyderabad,700d1509-0a10-4ca8-87b9-f8c3e612fb5c,3008,630,3638,17.32
105,Chennai,5a9291a1-3743-44ad-9c10-9d458d5b6325,2504,524,3028,17.31
197,Hyderabad,e052e083-dbfe-4156-a86e-e2fd848f8c3e,965,202,1167,17.31
139,Gorakhpur,3a410c47-9ebf-410e-8c86-c68c3fafab29,3148,656,3804,17.25
185,Hyderabad,bb713aac-cd12-4b4d-9026-704e3deaaac3,2357,490,2847,17.21
232,Kolkata,805076d8-aa2c-49c6-870b-413044b130bf,2960,614,3574,17.18
11,Amritsar,b9438b1f-1c27-4708-855d-f1b31b36186d,2575,534,3109,17.18
109,Chennai,65833924-5a42-4378-9556-8d10945f5a37,2587,532,3119,17.06
95,Chennai,13e48e2d-b274-45cf-a675-0b6b7a05a36b,2557,526,3083,17.06
40,Bangalore,5e36e56b-2449-4262-b397-f8af3464f5e3,2689,552,3241,17.03
227,Kolkata,4e83b4d2-bda8-4274-a104-8f0ae5412b9d,2505,511,3016,16.94
332,Pune,9a3a478d-31f5-468f-b32a-d4324844b5b2,2700,550,3250,16.92
324,Pune,68e86539-d883-4fc2-b735-0ab599643721,2691,547,3238,16.89
221,Kochi,ea99ba63-8772-44b9-8a98-1c2b78fe3759,3114,630,3744,16.83
244,Ludhiana,9fb7a7ca-e61c-4904-b339-749b6b45bf09,3095,626,3721,16.82
26,Bangalore,2a03ca86-cefc-4372-b2e8-eb577889f48c,2673,538,3211,16.75
159,Hyderabad,5afbd13c-b8be-4b40-a643-b0322e48117e,2857,573,3430,16.71
62,Bangalore,9fb087cf-076d-40a0-b974-8d26eaa69f44,2355,470,2825,16.64
144,Hubballi,913e4d9c-179c-43fc-b130-b0c9c39d3800,3156,630,3786,16.64
147,Hyderabad,207f5863-3807-437d-bb18-593da3befb60,2556,509,3065,16.61
315,Puducherry,560c2c80-71e4-4cba-bfdc-a228a6174054,3330,662,3992,16.58
198,Hyderabad,e096acfe-3139-4927-b2c8-f36e3587fcf8,982,195,1177,16.57
27,Bangalore,312fd0bd-4163-4768-8e94-ea1dc57783dd,2399,476,2875,16.56
230,Kolkata,627273fe-a446-443c-b412-1f09a9131a72,2997,594,3591,16.54
354,Surat,62648dc2-e2ea-48d9-8d26-314169b943ac,3021,596,3617,16.48
278,Mumbai,6ccfc337-2950-40f6-8bab-c7b5905c0f43,2727,536,3263,16.43
316,Pune,281082b4-7a69-4373-a3c3-385b02d134b1,1091,214,1305,16.40
134,Faridabad,8f4404df-c3e2-4a76-9e9c-ade81e757c3e,2947,578,3525,16.40
10,Ahmedabad,e677968e-5901-4ff2-8613-ebd72359a67c,459,90,549,16.39
177,Hyderabad,a898c8dc-70a7-4af3-9bf8-7907d6d6f5de,2719,533,3252,16.39
299,Mumbai,dd0aebf0-fb91-4644-bf64-5ac156a4b57f,938,183,1121,16.32
174,Hyderabad,9ea894e0-db78-45f7-beb1-10b6a52c3fb8,1026,200,1226,16.31
341,Pune,e2305bd9-95df-47f0-8b81-54b606b1497e,1074,209,1283,16.29
118,Chennai,c8f9f22d-b083-4eb1-894d-47b4daeeb2b5,2630,511,3141,16.27
321,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,2621,505,3126,16.15
124,Chhatrapati Sambhajinagar,83f44cd9-3310-40dc-9ccb-e3ed8c988fd7,3166,608,3774,16.11
97,Chennai,166f8ba8-c333-4c60-9d12-faeab29ac22c,1075,205,1280,16.02
325,Pune,76763e89-ac03-4897-b7c4-f2569eb37f35,2670,509,3179,16.01
77,Bangalore,d4205b92-165a-4ad5-89c1-f857521a047f,1189,225,1414,15.91
37,Bangalore,5400933d-3c5d-4015-a767-daed27781a0d,2688,506,3194,15.84
54,Bangalore,7c3e8dc3-8781-489c-a2c7-8f8f67149083,2641,497,3138,15.84
234,Kolkata,946909f7-f694-4d3f-adf5-7ed81dfe612a,2216,416,2632,15.81
4,Ahmedabad,37abf3a3-594f-4498-97df-be8059e950d4,3037,569,3606,15.78
34,Bangalore,40382f4d-61eb-4e99-9a0f-201fd9926f40,2704,504,3208,15.71
146,Hyderabad,1a13c8ef-91b4-462b-b27d-45451693f7a2,2814,519,3333,15.57
352,Surat,2cad2a10-1a07-4006-971e-6b305738e8e4,3052,562,3614,15.55
52,Bangalore,76cae5a0-b75d-456b-9aab-df0b0b7559c2,1247,229,1476,15.51
207,Jaipur,a2b0affb-b0fd-4bdb-bc10-76882b406860,2636,484,3120,15.51
194,Hyderabad,d71ff3ac-0dbd-43de-bf48-6a1b0ba17c12,1003,184,1187,15.50
68,Bangalore,abd85a95-f3f3-42fd-aeb0-71b9127335f5,1189,218,1407,15.49
201,Hyderabad,ebad4c79-770a-495f-88bf-6d99b2acc4e8,2853,521,3374,15.44
160,Hyderabad,5c0fc39e-c234-49c0-ab86-52cd7733e89c,1042,190,1232,15.42
179,Hyderabad,aed3e474-bd2f-4577-bd79-b74b53ce9e4e,2835,515,3350,15.37
92,Belagavi,ac3f4c36-1bc5-4305-b093-f3100f7877ed,3401,613,4014,15.27
125,Chhatrapati Sambhajinagar,e94ce78f-6b7b-4c04-b125-d52e1669f97d,2935,529,3464,15.27
369,Vellore,1dee02ae-10d8-449b-8dbc-162dcb20edbe,3334,590,3924,15.04
208,Jaipur,aec2283f-be4f-4545-87b0-febac02c9fc1,3030,536,3566,15.03
191,Hyderabad,cdfc1ee0-04f2-4bf1-afa7-ce41be802b28,2850,502,3352,14.98
247,Mohali,4889c148-d24c-4837-888b-fbb7c0d86a91,2664,466,3130,14.89
311,Patiala,044b3951-b27e-4dc4-b831-5698618b65d0,3383,590,3973,14.85
368,Varanasi,7e698981-3429-454f-8dae-16347b53eeed,3223,561,3784,14.83
129,Dehradun,2607025a-3900-4f19-a9b9-d158be8b4858,3158,549,3707,14.81
333,Pune,aa27f94a-ddda-47a5-91c4-8677ef56052a,1195,207,1402,14.76
145,Hyderabad,18073c2e-7d0d-4096-b0e0-c8b5f7454446,2888,499,3387,14.73
130,Dehradun,89c66d8a-45f7-48b3-adc9-9271cb4684f6,3443,591,4034,14.65
172,Hyderabad,8ecd89b5-1413-49cd-8087-320f363c0ede,70,12,82,14.63
19,Bangalore,1a2ba310-07de-4a70-946c-b54f2a487646,2740,469,3209,14.62
90,Bareilly,e28ae9bc-cda0-445f-a13a-a2ebe0260fef,3120,529,3649,14.50
170,Hyderabad,8d94ae95-db29-44f7-b705-d533f7c66176,1042,175,1217,14.38
211,Jalandhar,5e770e6a-d0c6-4c35-b3b3-090a9d1f157b,3182,533,3715,14.35
313,Prayagraj,dc25c005-8cd2-4be9-ae80-3cf6e5b80481,3025,507,3532,14.35
86,Bangalore,eeea2403-3a6e-49b7-874b-3d8743ef3cd8,2767,462,3229,14.31
59,Bangalore,94528e28-a7cb-4b41-8127-6a5625f4516f,2743,456,3199,14.25
36,Bangalore,49879539-9538-42ca-b59e-952cdd73b506,1182,195,1377,14.16
243,Ludhiana,9ac5f009-7623-4d1f-9b6a-d86e2f7c073e,3295,540,3835,14.08
0,Agra,49e49285-a768-494f-9429-89a6cf673007,3218,527,3745,14.07
43,Bangalore,631ed664-2717-487d-9979-1e294b7a1b4e,996,163,1159,14.06
165,Hyderabad,778b5c2b-0468-4f1e-8fa0-241cc91608a2,1027,168,1195,14.06
58,Bangalore,93e0e2c3-23a6-471f-9025-8dd79ef87d60,1235,202,1437,14.06
22,Bangalore,1d852498-590f-4ffa-babf-aae026e3584d,2774,454,3228,14.06
87,Bangalore,f6807d7c-9f71-49c7-9a15-50919b30fccf,2744,447,3191,14.01
195,Hyderabad,da5149e0-007e-4134-bc25-497d6ea3c5b2,2874,467,3341,13.98
245,Mehsana,20e1fb39-8704-49ca-8bf1-6de8f4040084,3175,515,3690,13.96
314,Prayagraj,fee654ba-4ae4-4295-89f0-fbd9116eb24a,3128,504,3632,13.88
168,Hyderabad,7aad3d3f-1dcc-4bad-baeb-d0640bf7ab86,945,152,1097,13.86
128,Dehradun,06bc0cca-b09b-4c18-b6c5-8358f91c7201,3205,513,3718,13.80
82,Bangalore,e4a9d9d2-dcea-46bb-b683-83dda1e9e6d6,75,12,87,13.79
108,Chennai,600240d4-efb5-484c-ac8a-2dbfe997975a,2779,443,3222,13.75
93,Chandigarh,ce51ee77-3c09-4d9f-9c98-558809e0c0e4,2801,445,3246,13.71
127,Davanagere,06031ad9-0300-4c0d-bc7d-cc16959c7467,3448,548,3996,13.71
370,Vellore,8ee2719c-97ed-44a2-a32e-7dceac0a7e55,3404,541,3945,13.71
184,Hyderabad,b9881384-2b90-44c7-8af2-e22c10f20ca2,2960,469,3429,13.68
240,Kurukshetra,b3304ce8-554f-455c-a62d-7a52f82ef223,3215,509,3724,13.67
280,Mumbai,803931bb-511e-48bc-8611-4b9910682bb4,1066,168,1234,13.61
365,Vadodra,e5eedfad-51fc-488d-9061-f56ebaed8440,3246,511,3757,13.60
290,Mumbai,b26ca2be-f12b-4645-a83a-adf09ecfd28b,1037,163,1200,13.58
255,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,1053,165,1218,13.55
18,Bangalore,0f2d3f82-cf97-45e8-bd80-759fe5dfbf6c,2763,430,3193,13.47
13,Bangalore,0059ff6a-7eb0-477a-a7f5-69256f2c444b,1228,190,1418,13.40
45,Bangalore,658cf319-0b10-4dbe-809e-ea5c913974cb,1207,186,1393,13.35
215,Kanpur,01084781-096d-4da8-bc1c-cd56769e8d87,3257,498,3755,13.26
163,Hyderabad,6893b298-d63b-4c4f-b155-2e4a0ca502d5,2911,444,3355,13.23

In [13]:
out_of_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "Yes",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (Out of Stock):", len(out_of_stock_urls))
out_of_stock_urls.head()

Products to verify (Out of Stock): 211338

,unique_id,product_name,city,store_id,product_url
25,eb96d63f-1c2d-436a-85f5-582ddbce6df3,Puramate Corn Flour | Starch,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/puramate-corn-flour-starch/pvid/eb96d63f-1c2d-436a-85f5-582ddbce6df3
27,d7f12a7b-70ff-4a2b-8392-e4fe297ec4be,Satyam Bajari Flour,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/satyam-bajari-flour/pvid/d7f12a7b-70ff-4a2b-8392-e4fe297ec4be
48,08aa72b7-cac2-4cbb-84d9-525c812f19fa,Aashirvaad Shudh Chakki Atta | Pure Atta 0% Maida,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/aashirvaad-shudh-chakki-atta-pure-atta-0-maida/pvid/08aa72b7-cac2-4cbb-84d9-525c812f19fa
50,14a11cfe-fd72-4901-bf2e-22bc0aba21c0,Fortune Chakki Fresh Atta,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/fortune-chakki-fresh-atta/pvid/14a11cfe-fd72-4901-bf2e-22bc0aba21c0
51,02f06d00-5bfc-4574-9fe3-d96d443da0f8,Whole Wheat Chakki Atta,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/whole-wheat-chakki-atta/pvid/02f06d00-5bfc-4574-9fe3-d96d443da0f8

In [14]:
in_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "No",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (In Stock):", len(in_stock_urls))
in_stock_urls.head()

Products to verify (In Stock): 838137

,unique_id,product_name,city,store_id,product_url
0,31ad3e8b-e689-48c1-956c-ca36d9fcac2c,Daily Good Corn Flour/Starch,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/daily-good-corn-flourstarch/pvid/31ad3e8b-e689-48c1-956c-ca36d9fcac2c
1,f4f9fcc5-11f2-4258-a498-a18bfd72994d,Bhagirathi Jowar Atta,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/bhagirathi-jowar-atta/pvid/f4f9fcc5-11f2-4258-a498-a18bfd72994d
2,9557fec4-be71-4f91-99ef-4e92b4dc851a,Satyam Nachani | Ragi Flour,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/satyam-nachani-ragi-flour/pvid/9557fec4-be71-4f91-99ef-4e92b4dc851a
3,295dca45-3a22-4ce7-a3ca-5345c2549eb0,Daily Good Jowar Flour / Sorghum Millet,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/daily-good-jowar-flour-sorghum-millet/pvid/295dca45-3a22-4ce7-a3ca-5345c2549eb0
4,7f3b60c4-ae3a-473c-be64-218c114458ac,Katadre Thalipeeth Bhajani,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,https://www.zepto.com/pn/katadre-thalipeeth-bhajani/pvid/7f3b60c4-ae3a-473c-be64-218c114458ac