In [1]:
import json
import os
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [7]:
import pandas as pd

df = pd.read_json(
    "/home/user/Downloads/qatarliving_qat_2026_07_03.json",
    lines=True
)

print(df.shape)
df.head()

(24587, 32)

,id,reference_number,title,url,category,category_url,broker_display_name,broker,price,currency,price_per,details,number_of_photos,location,bathrooms,bedrooms,furnished,description,sub_category_1,sub_category_2,agent_name,scraped_ts,depth,iteration_number,phone_number,date,rera_permit_number,user_id,property_type,amenities,dtcm_licence,published_at
0,257061,EB19-1BHK-FF-A78,Affordable 1BR Furnished Apartment in Al Ghanim,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/affordable_1br_furnished_apartment_in_al_ghanim/257061,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Ezdan,EZDAN,4000,QAR,Month,75 Sqm,11,"Old Al Ghanim,Doha,Qatar",1,1,Fully furnished,"This fully furnished one-bedroom apartment is ideally located in the vibrant Al Ghanim area of Doha, offering a comfortable and convenient urban living experience. Designed to maximize space and natural light, the apartment features a spacious and airy layout that creates a warm and welcoming atmosphere from the moment you step inside. The living area is bright and well-lit, providing an ideal setting for relaxation or entertaining guests, with the dining area just a few steps away for everyday convenience.The kitchen is thoughtfully designed and fully equipped with major appliances to meet your daily cooking needs, making it both practical and pleasant to use. The bedroom has been carefully planned to ensure maximum comfort and relaxation, offering a peaceful retreat at the end of the day. High-quality modern furniture and stylish fixtures are used throughout the apartment, enhancing both functionality and visual appeal.Residents benefit from a range of essential services, including 24/7 security, professional maintenance, and dedicated call center support to ensure a hassle-free living experience. The property is surrounded by key facilities such as malls, hospitals, and Doha Municipality offices, placing everything you need within close reach. Additionally, Doha Metro and Metro Link bus services are readily available, providing easy access to the rest of the city. With limited availability, now is the perfect time to book your unit and secure your new home.",Residential,,,2026-07-20,FEATURED,20260703,+97440403000,2026-07-20,,193738,apartment,"Security,Car Park,Study room,Lounge",,2026-07-05
1,242844,CAP51MTZ,PRIME LOCATION MUNTAZAH NEAR ALMEERA 1BHK FURNISHED BILLS INCL NO FEE,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/prime_muntazah_1bhk_furnished_bills_incl_no_fee/242844,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capital One Real Estate,CAPITAL ONE REAL ESTATE,5700,QAR,Month,80 Sqm,18,"Al Muntazah,Doha,Qatar",2,1,Fully furnished,"Property Name: CAP51MTZ Location: Ibn Naeem Street, Muntazah Introducing our newly launched residential building in the sought-after area of Al Muntazah, featuring elegant fully furnished 1-bedroom apartments crafted for modern, comfortable living. Residents benefit from a prime location with easy access to major roads, shopping centers, dining options, and essential services, making it the perfect choice for families and working professionals seeking convenience and quality living. Monthly rent options: - 1 BHK QAR 5,700 per month - 2 BHK QAR 6,500 per month - 3 BHK QAR 7,500 per month Unit Details for 1BHK: • 1 Bedroom • 1 Bathroom • Guest Toilet • Living Room • Kitchen Property Features / Amenities: – Dedicated Parking Space (as per the unit) – Maintenance Service – 24/7 Security with CCTV system Requirements: • One Month Refundable Security Deposit • Kahramaa Deposit • Post-Dated Cheques *Terms and Conditions Apply **No Commission Charged** Contact us now to know more about this property and for viewing! DISCLAIMER: All images used are for illustrative purposes only, photos and the actual property may have some minimal variation due to editing and property designs. All images and dimensions are not intended to be relied upon for.",Residential,,,2026-07-20,FEATURED,20260703,+974 5089 9555,2026-07-20,,254906,apartment,"Elevator,Kitchen Appliances,Maintenance,Security,Near School,Near Mosque",,2026-06-10
2,78669,CAP28ADJ-1,Excellent 1Bhk Furnished Apartment Near Bank Street No Commission,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/excellent_1bhk_furnished_apartment_near_bank_street_no_commission/78669,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capital One Real Estate,CAPITAL ONE REAL ESTATE,4000,QAR,Month,75 Sqm,13,"Al Doha Al Jadeeda,Doha,Qatar",2,1,Fully furnished,"Property Name: CAP28ADJ Location: Al Doha Al Jadeeda Near Metro Redline Street Name: Zurara Bin Amr Fully Furnished 1 Bedroom Apartments in a well-maintained building located at The Heart Of Doha Al Doha Al Jadeeda (Near Corniche, West Bay, Close To Sword Signal) with a very easy access to all major roads of Doha. Unit Details: • 1 Bedroom • 1 Bathroom • Living Room • Kitchen Property Details: ●Including Water And Electricity Charges with the Limit of QAR-150 ●Complimentary Wi-Fi ●Property Care-Taker ●Maintenance Service Contact us now to know more about this property and for viewing! Requirements: ●One Month Security Deposit ● Kahramaa Deposit ● Post-Dated Cheques Terms and Conditions Apply *** No Commission Charged *** Disclaimer: All images are for illustrative purpose only. Photos and actual property may have some minimal variation due to editing and property designs. All images and dimensions are not intended to be relied upon for.",Residential,,,2026-07-20,FEATURED,20260703,+974 5089 9555,2026-07-20,,254906,apartment,"Elevator,Near Metro,Near School,Bills Included,Maintenance,Security",,2026-05-02
3,176601,CAP21DJ,SPACIOUS 2BHK FF DOHA AL JADEEDA NEAR SOUQ WAQIF,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/spacious_2bhk_all_bills_included_no_commission/176601,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capital One Real Estate,CAPITAL ONE REAL ESTATE,4700,QAR,Month,100 Sqm,16,"Al Doha Al Jadeeda,Doha,Qatar",2,2,Fully furnished,"Property Name: CAP21DJ Location: Al Doha Al Jadeeda Step into modern living with our Furnished Two-Bedroom Apartments in the vibrant neighborhood of Al Doha Al Jadeeda. Perfectly located near the iconic Sword Signal and with convenient access to all major roads, this property combines style, comfort, and affordability, making it ideal for families and professionals alike. Unit Details: - Master Bedroom: With an en-suite bathroom for privacy and convenience. - Guest Toilet: Perfect for hosting visitors. - Living Room: Spacious and designed for comfort. - Fully Fitted Open Kitchen: Equipped with high-quality appliances to meet your needs. Key Features and Amenities: - All Bills Included: Water, electricity, and complimentary Wi-Fi at no extra cost. - Dedicated Parking Space: Secure and convenient. - 24/7 Security: Ensuring your safety and peace of mind. Terms and Conditions Apply Requirements: - One Month Security Deposit ( Undated Cheque). - Kahramaa QAR-2000 Deposit Required (Refundable) - Post-Dated Cheques for rental payments. No Commission Charged: Save more with direct leasing! Disclaimer: All images used are for illustrative purposes only. Photos and the actual property may have some minimal variation due to editing and property designs. All images and dimensions are not intended to be relied upon for.",Residential,,,2026-07-20,FEATURED,20260703,+974 5089 9555,2026-07-20,,254906,apartment,"Elevator,Near Metro,Near School,Bills Included,Maintenance",,2026-07-16
4,265320,CAP09OAP,2BHK OLD AIRPORT NEAR LULU D RING BILLS INCLUDED,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/2bhk_old_airport_near_lulu_d_ring_bills_included/265320,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capital One Real Estate,CAPITAL ONE REAL ESTATE,5500,QAR,Month,100 Sqm,17,"Old Airport,Doha,Qatar",2,2,Fully furnished,"Reference: CAP9OAP Location: Old Airport Discover the perfect home for your family with these fully furnished 2 bedroom apartments in the Old Airport area! Ideally located near Lulu Hypermarket on D Ring Road and surrounded by cozy cafes, these apartments offer both convenience and comfort. With quick access to major roads like Airport Road and C-Ring Road, you’re never far from the best of Doha. A walking distance from Lulu Hypermarket and other coffee shops. Unit Details: • 2 Bedrooms • 1 Bathroom • Guest Toilet • Spacious Living Room • Kitchen Requirements: * One-month security deposit * Post-dated cheques * Bills included (Capped) Contact us now to know more about this property and for viewing! Requirements: • One Month Security Deposit • Post-Dated Cheques *** No Commission Charged *** Disclaimer: All images used are for illustrative purposes only. Photos and the actual property may have some minimal variation due to editing and property designs. All images and dimensions are not intended to be relied upon for.",Residential,,,2026-07-20,FEATURED,20260703,+974 5089 9555,2026-07-20,,254906,apartment,"Kitchen Appliances,Bills Included,Maintenance,Security",,2026-07-18

In [9]:
req_cols = """reference_number, id, url, broker_display_name, broker, category, category_url, title, description, location, price, currency, price_per, bedrooms, bathrooms, furnished, rera_permit_number, dtcm_licence, scraped_ts, amenities, details, agent_name, number_of_photos, user_id, phone_number, date, iteration_number, depth, sub_category_1, property_type, sub_category_2, published_at"""

req_cols = [c.strip() for c in req_cols.split(",") if c.strip()]

missing = [c for c in req_cols if c not in df.columns]
extra = [c for c in df.columns if c not in req_cols]

print("Requirement columns:", len(req_cols))
print("File columns:", len(df.columns))
print("Missing:", missing)
print("Extra:", extra)
print("Order matches:", req_cols == list(df.columns))

Requirement columns: 32
File columns: 32
Missing: []
Extra: []
Order matches: False

In [10]:
print(df.columns.tolist())

['id', 'reference_number', 'title', 'url', 'category', 'category_url', 'broker_display_name', 'broker', 'price', 'currency', 'price_per', 'details', 'number_of_photos', 'location', 'bathrooms', 'bedrooms', 'furnished', 'description', 'sub_category_1', 'sub_category_2', 'agent_name', 'scraped_ts', 'depth', 'iteration_number', 'phone_number', 'date', 'rera_permit_number', 'user_id', 'property_type', 'amenities', 'dtcm_licence', 'published_at']

In [11]:
broker = df["broker"].fillna("").astype(str).str.strip()
display_name = df["broker_display_name"].fillna("").astype(str).str.strip()

# Find invalid rows
invalid = df[
    broker != display_name.str.upper()
][["id", "url", "broker", "broker_display_name"]]

print(f"Invalid rows: {len(invalid)}")
display(invalid)

Invalid rows: 0

Empty DataFrame
Columns: [id, url, broker, broker_display_name]
Index: []

In [12]:
df.iteration_number.value_counts()

iteration_number
20260703    24587
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [13]:
duplicates = df[df.duplicated(subset="url", keep=False)]

print(f"Duplicate URLs: {len(duplicates)}")
display(duplicates.sort_values("url"))

Duplicate URLs: 0

Empty DataFrame
Columns: [id, reference_number, title, url, category, category_url, broker_display_name, broker, price, currency, price_per, details, number_of_photos, location, bathrooms, bedrooms, furnished, description, sub_category_1, sub_category_2, agent_name, scraped_ts, depth, iteration_number, phone_number, date, rera_permit_number, user_id, property_type, amenities, dtcm_licence, published_at]
Index: []

In [39]:
df1 = df.copy()

for col in df1.columns:
    if df1[col].apply(lambda x: isinstance(x, list)).any():
        df1[col] = df1[col].astype(str)

duplicates = df1[df1.duplicated(keep=False)]

print(f"Duplicate rows: {len(duplicates)}")
display(duplicates)

Duplicate rows: 0

Empty DataFrame
Columns: [url, title, location, developer_start_price, resale_start_price, type, property_type, developer_name, amenties, description, payment_plans, property_count, iteration_number, date]
Index: []

In [15]:
import pandas as pd

df1 = df.replace(r'^\s*$', pd.NA, regex=True)

empty_columns = df1.columns[df1.isna().all()]

print("Completely empty columns:")
print(list(empty_columns))

Completely empty columns:
['sub_category_2', 'agent_name', 'rera_permit_number', 'dtcm_licence']

In [16]:
import re

url_pattern = re.compile(
    r'^(https?://)'
    r'([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}'
    r'(/[^\s]*)?$'
)

invalid_url = df[
    ~df["url"].fillna("").astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_url)}")
display(invalid_url[[ "url"]])

Invalid URLs: 0

Empty DataFrame
Columns: [url]
Index: []

In [17]:
phone_pattern = re.compile(r'^\+?\d+$')

invalid_phone = df[
    ~df["phone_number"].fillna("").astype(str).str.match(phone_pattern)
]

display(invalid_phone[["id", "phone_number"]])

            id    phone_number
1       242844  +974 5089 9555
2        78669  +974 5089 9555
3       176601  +974 5089 9555
4       265320  +974 5089 9555
5        81005  +974 5089 9555
6       113582  +974 5089 9555
8       232308  +974 3067 0262
11      265318  +974 5089 9444
13      252778  +974 5089 9444
14      255057  +974 5089 9444
15      174564  +974 5089 9444
16      223499  +974 5089 9444
17      242842  +974 5089 9444
41      255058  +974 5069 9333
42      252780  +974 5069 9333
43      242837  +974 5069 9333
44      223501  +974 5069 9333
46      260380  +974 3085 2146
50      247319  +974 5089 9555
51       92765  +974 6005 4441
53      255059  +974 5089 9555
54      256370  +974 3030 2484
55      125127  +974 3129 5262
60      205722
68      182729  +974 6634 6605
70       78929  +974 5069 9333
72      263262
77      243464  +974 5566 4292
78     2440226  +974 7117 8449
79      140379  +974 7117 8449
80     2440993  +974 3089 3111
81      194569  +974 7117 8449
82      165091  +974 3089 3111
88      253260  +974 6663 7475
90      230807  +974 7447 8827
98     2431165  +974 7117 8449
101      63821  +974 7447 8827
102    2530513  +974 7117 8449
105     194448  +974 7447 8827
108     265448  +974 6688 8771
109     103520  +974 7447 8827
110     265452  +974 6688 8771
119     265586  +974 3066 7011
121     212212  +974 7171 4965
122    2385083  +974 5134 6000
129     264014  +974 7000 5376
133     100898  +974 3382 9000
134     151327  +974 5134 6000
135     127083  +974 5134 6000
137     152172  +974 5128 3000
141      79174  +974 5006 1983
145      79546  +974 3066 7011
146     227625  +974 5555 0491
147     228605  +974 5555 0491
148     239170  +974 5555 0491
150     232366  +974 5555 0491
151      78381  +974 5069 9333
152     165068  +974 5069 9333
161     265013  +974 7776 5490
170     263208  +974 7007 1511
171     264214  +974 3357 2372
172     249159  +974 5134 7000
176     249208  +974 3133 5508
178     254999  +974 3001 1650
183    2466739  +974 3118 3737
186     814945  +974 5552 2743
188     123315  +974 5552 2743
189    1280008  +974 4413 4400
191     761580  +974 4413 4400
194     261217  +974 3359 8672
198     195379  +974 6611 6499
199     264172  +974 3359 8672
201     250142  +974 6611 6499
204     202412  +974 6611 6499
206     197248  +974 7776 5490
209     256829  +974 7776 5490
210     221383  +974 7767 3002
211     585154  +974 7767 3002
212     201575  +974 7767 3002
213     243404  +974 6696 3559
214     243406  +974 6696 3559
215     162634  +974 5509 1010
218    2412708  +974 3073 2000
219     161700  +974 5134 6000
221     237760  +974 5134 6000
222     177180  +974 5132 7000
223    1531528  +974 3382 9000
229      80766  +974 5069 9333
241     131121  +974 6645 5503
242     261148  +974 3066 7011
250     248288  +974 5001 0208
252     977708  +974 7448 6210
258     213875  +974 5060 2038
261      74663  +974 6005 4441
262     127205  +974 5128 3000
263     186889  +974 5993 3307
264     171986  +974 7199 8866
267     265237  +974 3000 4996
268     265240  +974 3000 4996
269     188497  +974 6000 4509
271     187989  +974 6000 4509
272     263142  +974 3066 7036
276     261921  +974 5100 1238
281     265220  +974 7783 4276
287     153150  +974 5055 6669
289     119717  +974 7127 4744
290     250090  +974 7127 4744
293     263174  +974 3077 7266
299     238197  +974 5530 0586
303     238191  +974 5530 0586
306     194605  +974 7448 6210
307     189790  +974 7171 0086
308     241699  +974 3030 2484
309     190911  +974 3369 9957
317      74097  +974 5530 0586
318     255988  +974 7224 4949
319     239646  +974 7224 4997
320     259311  +974 7224 4949
322     255938  +974 3313 8590
334     215012  +974 7007 1511
352     179650  +974 5569 9691
354     180214  +974 5569 9691
355     237530  +974 5569 9691
356     214971  +974 5569 9691
362     614071  +974 5064 4491
364     239100  +974 3077 7266
366      78746  +974 5089 9444
370     152933  +974 5089 9444
375     233908  +974 5018 3838
376     227822  +974 6663 9504
380     229729  +974 3034 3406
382      85002  +974 3037 3762
384     226170  +974 3037 1846
385     226173  +974 3124 2224
391     611763  +974 5128 3000
401     239862  +974 7039 2789
402     246884  +974 3004 4996
406     255979  +974 5580 0638
407     140699  +974 5992 1306
415     249936  +974 5075 0828
417     122285  +974 6007 5021
419     206097  +974 5503 8922
423     229359  +974 7771 9971
426     226864   +974 3005 900
428     226840  +974 3350 1746
429     227438  +974 3005 6900
430     226770  +974 3005 6900
433     265416  +974 7747 8916
435     265589  +974 7760 8497
457     253379  +974 5075 0828
469     250676  +974 7181 1517
471     251524  +974 7181 1517
472     252546  +974 7181 1517
473     251057  +974 7181 1517
474     252471  +974 7181 1517
476     265730  +974 7171 4965
477     232301  +974 7171 4965
478     265729  +974 7171 4965
491     240903
492     236720  +974 7224 4995
518     250793  +974 7181 1517
532     251387  +974 7181 1517
533     252536  +974 7181 1517
534     116934  +974 3344 2261
542     252563  +974 7181 1517
560     208349  +974 3067 0262
572     250490  +974 7224 4995
590     250994  +974 7181 1517
591     251271  +974 7181 1517
598     250809  +974 7181 1517
623     253194  +974 7181 1517
626     250639  +974 7181 1517
636     251599  +974 7181 1517
660     262094  +974 3344 2261
673     256436  +974 5089 9444
674     265323  +974 5089 9444
675     256002  +974 5089 9444
677     256429  +974 5089 9444
678     255051  +974 5089 9444
679     255991  +974 5089 9444
680     242836  +974 5089 9444
681     255960  +974 5089 9444
682     247313  +974 5089 9444
683     240657  +974 5089 9444
684     239684  +974 5089 9444
685     168806  +974 5089 9444
686     168606  +974 5089 9444
687     228682  +974 5089 9444
688     229683  +974 5089 9444
689     175866  +974 5089 9444
690     178578  +974 5089 9444
691     168409  +974 5089 9444
984     203633  +974 3067 0262
985     234566  +974 3067 0262
989     265627  +974 3023 3349
993     265595  +974 3066 7011
996     265501  +974 3077 7266
998     263973  +974 3077 7266
1001    265503  +974 3077 7266
1004    213453  +974 3067 0262
1023    252427  +974 7181 1517
1028    251517  +974 7181 1517
1030    251010  +974 7181 1517
1036    265324  +974 5069 9333
1038    265319  +974 5069 9333
1039    256437  +974 5069 9333
1040    256564  +974 5069 9333
1041    255992  +974 5069 9333
1042    256431  +974 5069 9333
1043    256003  +974 5069 9333
1044    255961  +974 5069 9333
1045    243481  +974 5069 9333
1046    255052  +974 5069 9333
1047    247316  +974 5069 9333
1048    242843  +974 5069 9333
1049    239685  +974 5069 9333
1050    241012  +974 5069 9333
1051    239171  +974 5069 9333
1052    228683  +974 5069 9333
1053    179670  +974 5069 9333
1054    229692  +974 5069 9333
1055    200708  +974 5069 9333
1062     91673  +974 6005 4441
1083    263283  +974 7068 5772
1084    150534  +974 6005 4441
1085    261144  +974 6005 4441
1086     78663  +974 5089 9555
1087     78171  +974 5089 9555
1088    252784  +974 5089 9555
1089    165076  +974 5089 9555
1090    256378  +974 3030 2484
1091    255993  +974 5089 9555
1092    265325  +974 5089 9555
1094    259616  +974 3129 5262
1095    259617  +974 3129 5262
1096    234977  +974 3129 5262
1097    234975  +974 3129 5262
1098    110909  +974 3129 5262
1099    238319  +974 3129 5262
1100    221405  +974 3129 5262
1101    201563  +974 3129 5262
1102    220467  +974 3129 5262
1103    106146  +974 3129 5262
1104    201562  +974 3129 5262
1105     79561  +974 3129 5262
1106    108906  +974 3129 5262
1107    186673  +974 3129 5262
1108    104899  +974 3129 5262
1109    104890  +974 3129 5262
1111     73283  +974 3129 5262
1116    204094  +974 3067 0262
1117    248840  +974 3067 0262
1118    238292  +974 5585 7911
1119    231432  +974 5524 6307
1123    250425  +974 6654 5180
1136    250615  +974 5570 2961
1137    265262  +974 7008 1919
1139    142374  +974 5570 2961
1141    250845  +974 7181 1517
1143    250980  +974 7181 1517
1145    251065  +974 7181 1517
1146    251483  +974 7181 1517
1147    253334  +974 7181 1517
1148    252409  +974 7181 1517
1149    250714  +974 7181 1517
1150    250744  +974 7181 1517
1151    250716  +974 7181 1517
1152    250747  +974 7181 1517
1153    250773  +974 7181 1517
1154    250805  +974 7181 1517
1155    250748  +974 7181 1517
1156    250819  +974 7181 1517
1157    250820  +974 7181 1517
1158    250850  +974 7181 1517
1159    250888  +974 7181 1517
1160    250862  +974 7181 1517
1161    250900  +974 7181 1517
1162    250915  +974 7181 1517
1163    250903  +974 7181 1517
1164    251074  +974 7181 1517
1165    251073  +974 7181 1517
1166    251043  +974 7181 1517
1167    251077  +974 7181 1517
1168    251040  +974 7181 1517
1169    251248  +974 7181 1517
1170    250996  +974 7181 1517
1171    251001  +974 7181 1517
1172    251242  +974 7181 1517
1173    251235  +974 7181 1517
1174    251211  +974 7181 1517
1175    251207  +974 7181 1517
1176    251162  +974 7181 1517
1177    251178  +974 7181 1517
1178    251201  +974 7181 1517
1179    251142  +974 7181 1517
1180    251148  +974 7181 1517
1181    251114  +974 7181 1517
1182    251128  +974 7181 1517
1183    251385  +974 7181 1517
1184    251373  +974 7181 1517
1185    251117  +974 7181 1517
1186    251351  +974 7181 1517
1187    251356  +974 7181 1517
1188    251347  +974 7181 1517
1189    251337  +974 7181 1517
1190    251340  +974 7181 1517
1191    251328  +974 7181 1517
1192    251335  +974 7181 1517
1193    251319  +974 7181 1517
1194    251293  +974 7181 1517
1195    251303  +974 7181 1517
1196    251295  +974 7181 1517
1197    251282  +974 7181 1517
1198    251292  +974 7181 1517
1199    251503  +974 7181 1517
1200    251441  +974 7181 1517
1201    251495  +974 7181 1517
1202    251481  +974 7181 1517
1203    253192  +974 7181 1517
1204    252415  +974 7181 1517
1205    252431  +974 7181 1517
1206    252425  +974 7181 1517
1207    252445  +974 7181 1517
1208    252446  +974 7181 1517
1209    252458  +974 7181 1517
1210    252457  +974 7181 1517
1211    253187  +974 7181 1517
1212    252571  +974 7181 1517
1213    252460  +974 7181 1517
1214    252565  +974 7181 1517
1215    251550  +974 7181 1517
1216    251561  +974 7181 1517
1217    252434  +974 7181 1517
1218    252478  +974 7181 1517
1219    252476  +974 7181 1517
1220    252466  +974 7181 1517
1221    252523  +974 7181 1517
1222    252464  +974 7181 1517
1223    252556  +974 7181 1517
1224    251285  +974 7181 1517
1225    253185  +974 7181 1517
1226    251322  +974 7181 1517
1227    252433  +974 7181 1517
1228    253205  +974 7181 1517
1229    253201  +974 7181 1517
1231    251048  +974 7181 1517
1233    250715  +974 7181 1517
1238    251247  +974 7181 1517
1243    251615  +974 7181 1517
1244    250697  +974 7181 1517
1245    250723  +974 7181 1517
1246    250728  +974 7181 1517
1247    250691  +974 7181 1517
1248    162750  +974 7181 1517
1249    250656  +974 7181 1517
1250    250762  +974 7181 1517
1251    162735  +974 7181 1517
1252    162712  +974 7181 1517
1253    250858  +974 7181 1517
1254    250857  +974 7181 1517
1255    250797  +974 7181 1517
1256    250902  +974 7181 1517
1257    250937  +974 7181 1517
1258    250870  +974 7181 1517
1259    251069  +974 7181 1517
1260    251044  +974 7181 1517
1261    250943  +974 7181 1517
1262    250923  +974 7181 1517
1263    251032  +974 7181 1517
1264    251249  +974 7181 1517
1265    251007  +974 7181 1517
1266    251202  +974 7181 1517
1267    251416  +974 7181 1517
1268    251406  +974 7181 1517
1269    251378  +974 7181 1517
1270    251145  +974 7181 1517
1271    252455  +974 7181 1517
1272    252422  +974 7181 1517
1273    252550  +974 7181 1517
1274    253190  +974 7181 1517
1275    253186  +974 7181 1517
1276    251583  +974 7181 1517
1277    252412  +974 7181 1517
1278    252528  +974 7181 1517
1279    252418  +974 7181 1517
1280    252560  +974 7181 1517
1281    253333  +974 7181 1517
1282    253191  +974 7181 1517
1283    251521  +974 7181 1517
1284    251514  +974 7181 1517
1285    251552  +974 7181 1517
1286    251540  +974 7181 1517
1287    251549  +974 7181 1517
1288    251545  +974 7181 1517
1289    251538  +974 7181 1517
1290    251608  +974 7181 1517
1291    251572  +974 7181 1517
1292    252411  +974 7181 1517
1293    251611  +974 7181 1517
1294    251621  +974 7181 1517
1295    252441  +974 7181 1517
1296    252417  +974 7181 1517
1297    252485  +974 7181 1517
1298    252450  +974 7181 1517
1299    252429  +974 7181 1517
1300    252482  +974 7181 1517
1301    252508  +974 7181 1517
1302    252465  +974 7181 1517
1303    252513  +974 7181 1517
1304    252504  +974 7181 1517
1305    252530  +974 7181 1517
1306    252535  +974 7181 1517
1307    252539  +974 7181 1517
1308    252555  +974 7181 1517
1309    252551  +974 7181 1517
1310    253199  +974 7181 1517
1311    250657  +974 7181 1517
1312    252487  +974 7181 1517
1313    251100  +974 7181 1517
1314    253203  +974 7181 1517
1315    253325  +974 7181 1517
1316    253332  +974 7181 1517
1317    253335  +974 7181 1517
1318    253336  +974 7181 1517
1325    214537  +974 6634 6605
1327   2363698  +974 6634 6605
1328   2433505  +974 6634 6605
1329    265585  +974 3085 2146
1355    262006  +974 7224 4949
1356    265276  +974 7224 4949
1357    265281  +974 7224 4949
1358    265280  +974 7224 4949
1375    170751  +974 7171 0086
1391    265601  +974 6663 7475
1394    202034  +974 3089 3111
1395     72190  +974 3091 9900
1396   2391985  +974 7447 8827
1397    256783  +974 3072 0144
1398    218545  +974 7447 8827
1399    202033  +974 3091 9900
1402    260412  +974 6663 7475
1403    257668  +974 6663 7475
1404    194898  +974 7741 8032
1408    262002  +974 5203 0396
1424   2368934  +974 7447 8827
1425   2391083  +974 7447 8827
1429     77939  +974 7117 8449
1431    265424  +974 6688 8771
1433    265426  +974 6688 8771
1434    265429  +974 6688 8771
1435    265432  +974 6688 8771
1436    265434  +974 6688 8771
1437    265437  +974 6688 8771
1438    265438  +974 6688 8771
1439    265440  +974 6688 8771
1440    265445  +974 6688 8771
1441    265441  +974 6688 8771
1443    265444  +974 6688 8771
1445    265454  +974 6688 8771
1446    232823  +974 7075 1515
1451    118442  +974 7075 1515
1464    136039  +974 7031 1129
1466    265587  +974 3066 7011
1467   1838249  +974 5132 7000
1468   1439361  +974 5128 3000
1470    198606  +974 7171 4965
1471    165490  +974 7171 4965
1472    201489  +974 7171 4965
1473    165525  +974 7171 4965
1474    203620  +974 7171 4965
1475    208350  +974 7171 4965
1476    198610  +974 7171 4965
1477    208354  +974 7171 4965
1478    212770  +974 7171 4965
1479    244866  +974 7171 4965
1482    264015  +974 7000 5376
1483    263274  +974 7000 5376
1484    264012  +974 7000 5376
1485    264010  +974 7000 5376
1486    264013  +974 7000 5376
1488    265584  +974 6688 8771
1489    107937  +974 3382 9000
1490    119183  +974 5552 2743
1491    128159  +974 5128 3000
1493    253926  +974 3382 9000
1494    259435  +974 5128 3000
1497    263865  +974 3382 9000
1499    213446  +974 3067 0262
1500    255500  +974 7171 0086
1512    253281  +974 3066 7011
1521    127569  +974 5006 1983
1522   2478228  +974 6602 7858
1523     75237  +974 6602 7858
1524   2501486  +974 5006 1983
1525    124810  +974 5006 1983
1526    148960  +974 6602 7858
1527     79173  +974 6602 7858
1542    110777  +974 7136 7575
1543    116146  +974 7136 7575
1544    265431  +974 3085 2146
1545    146024  +974 7136 7575
1546    265168  +974 7760 8497
1547    128346  +974 7136 7575
1549    265457  +974 7760 8497
1556    237195  +974 7006 2201
1557    265574  +974 5999 0306
1558    184682  +974 3066 7011
1559   2513291  +974 3019 0951
1560    263849  +974 3066 7011
1562    230855  +974 5555 0491
1563    264177  +974 5529 3718
1564    228218  +974 5555 0491
1565    231427  +974 5555 0491
1566    239444  +974 5555 0491
1567    237839  +974 5555 0491
1568    239872  +974 5555 0491
1569    239445  +974 5555 0491
1570    242466  +974 5555 0491
1571    243445  +974 5555 0491
1572    248879  +974 5555 0491
1573    250176  +974 5555 0491
1575    255831  +974 5555 0491
1576    255835  +974 5555 0491
1577    257685  +974 5555 0491
1578    259622  +974 5555 0491
1579    257693  +974 5555 0491
1580    257697  +974 5555 0491
1581    168411  +974 5069 9333
1582     78123  +974 5069 9333
1583     78588  +974 5069 9333
1626    128046  +974 6000 3348
1628    255020  +974 6000 3348
1629    232873  +974 6000 3348
1630    229620  +974 6000 3348
1631    166165  +974 6000 3348
1655    114881  +974 3322 9368
1656    114884  +974 3322 9368
1658    215231  +974 3322 9368
1659    215233  +974 3322 9368
1663    248034  +974 3322 9368
1664    229731  +974 3034 3406
1665    261155  +974 3322 9368
1666    229476  +974 3034 3406
1667    258272  +974 3034 3406
1668    258267  +974 3034 3406
1669    261085  +974 3034 3406
1670    261092  +974 3034 3406
1671    244559  +974 3034 3406
1672    243957  +974 3034 3406
1674    265555  +974 6611 6499
1677    265553  +974 6611 6499
1682    259647  +974 7471 8707
1684    258240  +974 5999 0306
1686    265535  +974 7030 2392
1687    261903  +974 5999 0306
1688    263915  +974 5999 0306
1689    244891  +974 7224 4997
1690    244892  +974 7224 4997
1691    257680  +974 7224 4997
1692    255981  +974 7224 4997
1693    241407  +974 7224 4997
1694    258347  +974 7224 4997
1695    265014  +974 7224 4997
1696    260696  +974 7224 4997
1697    258350  +974 7224 4997
1716    232513  +974 7745 4353
1719    191298  +974 6000 1469
1722    215829  +974 6000 1469
1723    210779  +974 7113 2333
1724    261241  +974 7113 2333
1725    265208  +974 7113 2333
1754    264058  +974 5590 0127
1764    237776  +974 5566 4292
1773    265475  +974 3090 9150
1785    261864  +974 3357 2372
1786    260375  +974 3357 2372
1787    264325  +974 3070 9070
1793    254998  +974 7007 1511
1794    264304  +974 7007 1511
1795    253819  +974 5132 7000
1796    264305  +974 7007 1511
1798    263162  +974 5128 3000
1799     87026  +974 5552 2743
1800    256374  +974 3030 2484
1801    250360  +974 3030 2484
1802     86454  +974 5552 2743
1803   2298898  +974 5552 2743
1804     88276  +974 5552 2743
1805    256375  +974 3030 2484
1806    235010  +974 3359 8672
1807    260569  +974 3359 8672
1808    129312  +974 3048 0956
1811     74054  +974 3048 0956
1812    212840  +974 3067 0262
1842    259427  +974 3077 7266
1845    263975  +974 3077 7266
1846    264022  +974 3077 7266
1848    252578  +974 3300 5758
1849    241020  +974 7171 0086
1856    220935  +974 3133 5508
1858    229631  +974 3133 5508
1859   1309557  +974 5502 4778
1860    233894  +974 3133 5508
1861    158147  +974 5004 9704
1862   1712929  +974 5502 4778
1863    222157  +974 5004 9704
1864    165972  +974 5004 9704
1865    189032  +974 5004 9704
1866    264192  +974 3133 5508
1867    264200  +974 3133 5508
1879    265016
1886    254935  +974 3001 1650
1888    256699  +974 3001 1650
1889    259634  +974 3001 1650
1920    188755  +974 7407 4488
1929    140245  +974 5552 2743
1936    232895  +974 3359 8672
1958    584446  +974 4413 4400
1959    661165  +974 4413 4400
1960    116490  +974 4413 4400
1961    807377  +974 4413 4400
1962    584299  +974 4413 4400
1963    967703  +974 4413 4400
1964    116487  +974 4413 4400
1965    584710  +974 4413 4400
1966    172233  +974 4413 4400
1967    967699  +974 4413 4400
1973    584305  +974 4413 4400
1974    967701  +974 4413 4400
1975    584397  +974 4413 4400
1976    770187  +974 4413 4400
1977    584388  +974 4413 4400
1978    584719  +974 4413 4400
1979    594053  +974 4413 4400
1981    558888  +974 4413 4400
1982    584293  +974 4413 4400
1983    584300  +974 4413 4400
1984    584709  +974 4413 4400
1985    584390  +974 4413 4400
1986    584718  +974 4413 4400
1987    584301  +974 4413 4400
1988    584303  +974 4413 4400
1989    584444  +974 4413 4400
1990    584309  +974 4413 4400
1991    584297  +974 4413 4400
1992    584295  +974 4413 4400

In [19]:
duplicates = df[df.duplicated("id", keep=False)]

print(f"Duplicate IDs: {duplicates.shape[0]}")
display(duplicates[["id"]])

Duplicate IDs: 0

Empty DataFrame
Columns: [id]
Index: []

In [20]:
allowed = [
    "Apartments",
    "Rooms",
    "Villas",
    "Commercial",
    "Multiple-units",
    "Buildings",
    "Garage",
    "Chalet",
    "land",
    "Rentals-wanted"
]

invalid = df[~df["property_type"].isin(allowed)]

display(invalid[["id", "property_type"]])

            id property_type
136  120318743          Land
137  120318176          Land
138  120317387          Land
139  120308999          Land
140  120303767          Land
141  120303853          Land
142  120315877          Land
143  120294731          Land
144  120315876          Land
145  120181744          Land
146  120297280          Land
147  120344185          Land
148  120351369          Land
149  120305133          Land
150  120316551          Land
151  120319532          Land
152  120367839          Land
153  120343944          Land
154  120304734          Land
155  120359315          Land
156  120213694          Land
157  120343703          Land
158  120358966          Land
159  120208727          Land
160  120317180          Land
198  120269386          Land
199  120317397          Land
200  120294178          Land
201  120308318          Land

In [18]:
date_regex = r"^\d{4}-\d{2}-\d{2}$"

for col in ["scraped_ts", "date"]:
    invalid = df[
        ~df[col].fillna("").astype(str).str.match(date_regex)
    ]
    print(col, len(invalid))

scraped_ts 0
date 0

In [22]:
broker = df["broker"].fillna("").astype(str).str.strip()
display_name = df["broker_display_name"].fillna("").astype(str).str.strip()

invalid = df[
    broker != display_name.str.upper()
]

display(invalid[["id", "broker", "broker_display_name"]])

Empty DataFrame
Columns: [id, broker, broker_display_name]
Index: []

In [44]:
df.type.value_counts()

type
Compound    842
Name: count, dtype: int64

In [45]:
import pandas as pd

df1 = df.replace(r'^\s*$', pd.NA, regex=True)

empty_columns = df1.columns[df1.isna().all()]

print("Completely empty columns:")
print(list(empty_columns))

Completely empty columns:
[]

In [46]:
df.date.value_counts()

date
2026-07-20    842
Name: count, dtype: int64

In [47]:
df.iteration_number.value_counts()

iteration_number
20260703    842
Name: count, dtype: int64

In [51]:
import pandas as pd

invalid = df[
   
     df["developer_start_price"].replace(r'^\s*$', pd.NA, regex=True).isna() 
]

print(f"Rows where both prices are missing: {len(invalid)}")
display(invalid)

Rows where both prices are missing: 433

                                                                               url  \
3              https://www.nawy.com/compound/393-al-jazi-first-marriott-residences
4                         https://www.nawy.com/compound/397-palm-hills-new-alamein
5                                        https://www.nawy.com/compound/401-green-3
10                                         https://www.nawy.com/compound/399-kinda
12                   https://www.nawy.com/compound/423-mountain-view-chillout-park
15                               https://www.nawy.com/compound/434-jebal-el-sokhna
20   https://www.nawy.com/compound/451-mountain-view-executive-residence--katameya
21                                         https://www.nawy.com/compound/452-d-bay
22                                     https://www.nawy.com/compound/453-belle-vie
23                             https://www.nawy.com/compound/446-midtown-new-cairo
26                                     https://www.nawy.com/compound/462-creektown
33                                 https://www.nawy.com/compound/490-il-bosco-city
34                                     https://www.nawy.com/compound/487-mangroovy
37                                          https://www.nawy.com/compound/510-june
38                                 https://www.nawy.com/compound/528-bianchi-ilios
40                                   https://www.nawy.com/compound/500-la-capitale
41                                      https://www.nawy.com/compound/464-unitower
43                                     https://www.nawy.com/compound/546-the-curve
45                                     https://www.nawy.com/compound/583-city-view
46                                   https://www.nawy.com/compound/586-west-elgolf
47                                    https://www.nawy.com/compound/587-dream-land
48                                https://www.nawy.com/compound/535-montenapoleone
49                              https://www.nawy.com/compound/612-emirates-heights
53                          https://www.nawy.com/compound/622-noor-capital-gardens
54                                       https://www.nawy.com/compound/624-privado
55                             https://www.nawy.com/compound/626-golf-porto-marina
56                              https://www.nawy.com/compound/632-katameya-gardens
57                          https://www.nawy.com/compound/628-botanica-residential
59                                      https://www.nawy.com/compound/645-el-rehab
60                        https://www.nawy.com/compound/611-lasirena-sokhna-resort
63                                          https://www.nawy.com/compound/617-yaru
65                             https://www.nawy.com/compound/655-mountain-view-1.1
67                                 https://www.nawy.com/compound/665-moon-valley-i
68                                         https://www.nawy.com/compound/623-celia
70                                         https://www.nawy.com/compound/678-aroma
71                               https://www.nawy.com/compound/669-aster-residence
74                                 https://www.nawy.com/compound/712-zayed-regency
75                                       https://www.nawy.com/compound/635-green-6
76                                       https://www.nawy.com/compound/711-green-5
79                                  https://www.nawy.com/compound/647-porto-sokhna
80                                        https://www.nawy.com/compound/726-kardia
83                             https://www.nawy.com/compound/731-nile-pearl--tower
86                                 https://www.nawy.com/compound/739-porto-october
91                                          https://www.nawy.com/compound/758-soul
92                                       https://www.nawy.com/compound/759-d.o.s.e
95                                      https://www.nawy.com/compound/775-eco-west
100                                https://www.nawy.com/compound/790-nyoum-october
104                                 https://www.nawy.com/compound/804-regents-park
106                               https://www.nawy.com/compound/816-nyom-new-cairo
108               https://www.nawy.com/compound/685-modon-hotels-&-residence-tower
109                                    https://www.nawy.com/compound/836-naia-west
110                          https://www.nawy.com/compound/828-promenade-new-cairo
112                               https://www.nawy.com/compound/720-marsellia-land
114                          https://www.nawy.com/compound/875-la-mirada-new-cairo
115                         https://www.nawy.com/compound/734-lasirena-north-coast
119                                   https://www.nawy.com/compound/881-green-yard
121                         https://www.nawy.com/compound/892-nyoum-mostaqbal-city
122                                    https://www.nawy.com/compound/910-park-view
123                               https://www.nawy.com/compound/913-orla-residence
125                                https://www.nawy.com/compound/916-highland-park
126                                          https://www.nawy.com/compound/917-ivy
127                                 https://www.nawy.com/compound/922-garden-hills
128                                      https://www.nawy.com/compound/925-eastown
129                                         https://www.nawy.com/compound/927-salt
131                                         https://www.nawy.com/compound/935-koun
136                                     https://www.nawy.com/compound/946-el-safwa
137                                https://www.nawy.com/compound/948-stella-marina
140                               https://www.nawy.com/compound/956-stella-heights
141                                    https://www.nawy.com/compound/873-4t1-tower
143                                       https://www.nawy.com/compound/992-diar-i
145                               https://www.nawy.com/compound/997-nile-boulevard
146                                      https://www.nawy.com/compound/990-amorada
152                       https://www.nawy.com/compound/1008-lake-view-residence-2
153                                       https://www.nawy.com/compound/1005-dijar
154                                   https://www.nawy.com/compound/1026-el-fustat
161                         https://www.nawy.com/compound/1047-lagoon-new-allamein
162                                       https://www.nawy.com/compound/929-solare
167                             https://www.nawy.com/compound/1068-eelaf-residence
169                        https://www.nawy.com/compound/947-hadayek-el-mohandesin
170                                 https://www.nawy.com/compound/1076-ivoire-east
174                             https://www.nawy.com/compound/1098-valencia-valley
178                              https://www.nawy.com/compound/1123-ever-new-cairo
180                                     https://www.nawy.com/compound/1127-menorca
183                              https://www.nawy.com/compound/1131-porto-pyramids
187                                 https://www.nawy.com/compound/1153-icon-garden
190                                       https://www.nawy.com/compound/3-new-giza
192                 https://www.nawy.com/compound/1063-lumia-residence-new-capital
193                                   https://www.nawy.com/compound/4-uptown-cairo
194                                         https://www.nawy.com/compound/6-mivida
195                                        https://www.nawy.com/compound/5-marassi
196                           https://www.nawy.com/compound/12-lake-view-residence
197                                 https://www.nawy.com/compound/19-beverly-hills
198                                          https://www.nawy.com/compound/20-casa
200                               https://www.nawy.com/compound/25-kattameya-plaza
201                            https://www.nawy.com/compound/26-forty-west-phase-i
203                            https://www.nawy.com/compound/30-westown-residences
204                                https://www.nawy.com/compound/31-the-courtyards
205                                         https://www.nawy.com/compound/1152-sq1
207                                  https://www.nawy.com/compound/43-hacienda-bay
208                                   https://www.nawy.com/compound/44-zayed-dunes
209                       https://www.nawy.com/compound/46-village-garden-katameya
210                    https://www.nawy.com/compound/45-mountain-view-ras-el-hekma
211                                    https://www.nawy.com/compound/47-the-square
213                                https://www.nawy.com/compound/58-village-avenue
214                            https://www.nawy.com/compound/61-palm-hills-october
215                                   https://www.nawy.com/compound/60-the-village
216                        https://www.nawy.com/compound/7-mountain-view-hyde-park
218                     https://www.nawy.com/compound/62-palm-hills-golf-extension
219                                      https://www.nawy.com/compound/67-botanica
220                                         https://www.nawy.com/compound/73-amwaj
221                             https://www.nawy.com/compound/72-marina-el-alamein
223                                          https://www.nawy.com/compound/88-azha
224                                  https://www.nawy.com/compound/87-telal-sokhna
225                                      https://www.nawy.com/compound/99-l’avenir
227                             https://www.nawy.com/compound/117-waterside-condos
228                                   https://www.nawy.com/compound/29-westown-hub
230                                     https://www.nawy.com/compound/124-bay-west
231                                  https://www.nawy.com/compound/126-soma-breeze
232                                https://www.nawy.com/compound/145-october-plaza
235                                https://www.nawy.com/compound/151-pyramid-hills
236                                        https://www.nawy.com/compound/163-joulz
238                                      https://www.nawy.com/compound/165-jefaira
239                              https://www.nawy.com/compound/167-capital-gardens
242                          https://www.nawy.com/compound/187-cairo-festival-city
244                           https://www.nawy.com/compound/190-jewar-sheikh-zayed
247                              https://www.nawy.com/compound/57-the-village-gate
250                                      https://www.nawy.com/compound/196-haptown
251                               https://www.nawy.com/compound/197-the-capitalway
257                               https://www.nawy.com/compound/85-karma-residence
258                                         https://www.nawy.com/compound/216-vida
259                                         https://www.nawy.com/compound/218-aria
261                                 https://www.nawy.com/compound/220-la-vista-ray
264                                 https://www.nawy.com/compound/227-address-east
265                                         https://www.nawy.com/compound/228-alma
267                                    https://www.nawy.com/compound/232-el-masyaf
268                                     https://www.nawy.com/compound/233-six-west
269                                     https://www.nawy.com/compound/237-the-loft
271                                  https://www.nawy.com/compound/254-axis-x-iwan
272                         https://www.nawy.com/compound/255-la-fontaine-province
276                           https://www.nawy.com/compound/276-allegria-residence
282                                     https://www.nawy.com/compound/299-madinaty
286                                         https://www.nawy.com/compound/305-gaia
287                                       https://www.nawy.com/compound/325-sawary
288                                   https://www.nawy.com/compound/344-one-ninety
289                                     https://www.nawy.com/compound/315-carnelia
291                                   https://www.nawy.com/compound/343-cairo-gate
293                                 https://www.nawy.com/compound/347-green-square
299                          https://www.nawy.com/compound/217-the-city-of-odyssia
305                      https://www.nawy.com/compound/2296-creek-hotel-residences
312                         https://www.nawy.com/compound/1624-the-island-marina-5
318                                    https://www.nawy.com/compound/1691-the-city
324                              https://www.nawy.com/compound/1772-mivida-gardens
339                                      https://www.nawy.com/compound/1852-yardin
346                                 https://www.nawy.com/compound/1976-neo-gardens
349                                https://www.nawy.com/compound/1999-royal-valley
353                     https://www.nawy.com/compound/1159-lyv-caesar-ras-el-hekma
354                              https://www.nawy.com/compound/1195-icon-residence
355                                      https://www.nawy.com/compound/1196-acasia
356                          https://www.nawy.com/compound/1199-safia-ras-el-hekma
365                             https://www.nawy.com/compound/1261-hacienda-waters
367                        https://www.nawy.com/compound/1212-mar-bay-ras-el-hekma
370                                      https://www.nawy.com/compound/1290-jamila
372                                  https://www.nawy.com/compound/1293-zayed-2000
384                                   https://www.nawy.com/compound/1334-kings-way
385                               https://www.nawy.com/compound/1345-isola-quattro
390                                     https://www.nawy.com/compound/1223-the-101
393                              https://www.nawy.com/compound/1377-jade-residence
395                                      https://www.nawy.com/compound/1384-blanks
402                                   https://www.nawy.com/compound/1415-west-clay
405                                       https://www.nawy.com/compound/1449-maliv
407                               https://www.nawy.com/compound/1361-lumia-lagoons
410                                        https://www.nawy.com/compound/1456-alca
411                                   https://www.nawy.com/compound/1367-eastville
416                                       https://www.nawy.com/compound/1500-acasa
417                            https://www.nawy.com/compound/1476-pyramids-heights
429                                   https://www.nawy.com/compound/387-caesar-bay
430                                       https://www.nawy.com/compound/1445-stoda
432                    https://www.nawy.com/compound/512-stella-di-mary-ein-sokhna
434                                   https://www.nawy.com/compound/561-la-vista-1
435                                   https://www.nawy.com/compound/541-almaza-bay
436                                       https://www.nawy.com/compound/594-blumar
439                                   https://www.nawy.com/compound/697-la-vista-3
440                                     https://www.nawy.com/compound/699-blue-bay
443                                  https://www.nawy.com/compound/729-coral-hills
444                        https://www.nawy.com/compound/376-seashell-ras-el-hekma
445                                 https://www.nawy.com/compound/753-hacienda-red
449                                   https://www.nawy.com/compound/785-la-vista-4
451                                   https://www.nawy.com/compound/786-la-vista-5
452                            https://www.nawy.com/compound/834-porto-south-beach
457                          https://www.nawy.com/compound/933-bo-sidi-abdelrahman
458                       https://www.nawy.com/compound/950-agora-sidi-abdelrahman
459                                    https://www.nawy.com/compound/964-blue-blue
461                                     https://www.nawy.com/compound/766-sea-view
462                 https://www.nawy.com/compound/970-heaven-hills-porto-el-sokhna
463                                        https://www.nawy.com/compound/974-saada
464                                https://www.nawy.com/compound/1064-arc-soma-bay
467                              https://www.nawy.com/compound/1091-blumar-el-dome
468                                      https://www.nawy.com/compound/1132-nice-4
469                        https://www.nawy.com/compound/1110-la-vento-oyoun-mousa
470                       https://www.nawy.com/compound/1129-palm-beach-ain-sokhna
471                                        https://www.nawy.com/compound/21-caesar
473                                  https://www.nawy.com/compound/17-la-vista-bay
474                                       https://www.nawy.com/compound/33-g-cribs
475                              https://www.nawy.com/compound/71-la-vista-cascada
476                    https://www.nawy.com/compound/48-seashell-sidi-abdel-rahman
477                                   https://www.nawy.com/compound/82-ghazala-bay
478                                     https://www.nawy.com/compound/1019-diplo-3
479                             https://www.nawy.com/compound/79-marseilia-beach-4
480                             https://www.nawy.com/compound/74-telal-north-coast
481                                     https://www.nawy.com/compound/91-ein-hills
482                                       https://www.nawy.com/compound/96-piacera
483                                    https://www.nawy.com/compound/92-laguna-bay
484                          https://www.nawy.com/compound/83-swanlake-north-coast
485            https://www.nawy.com/compound/153-stella-di-mare-sidi-abdelrahman-1
487                                 https://www.nawy.com/compound/97-little-venice
488                          https://www.nawy.com/compound/94-mountain-view-sokhna
489                                      https://www.nawy.com/compound/214-ein-bay
493                                  https://www.nawy.com/compound/316-majada-iwan
494                                   https://www.nawy.com/compound/308-la-vista-7
495                     https://www.nawy.com/compound/221-the-waterway-north-coast
496                                   https://www.nawy.com/compound/318-la-vista-2
503                                      https://www.nawy.com/compound/1648-crysta
507                                 https://www.nawy.com/compound/1849-marassi-red
509                               https://www.nawy.com/compound/1197-playa-ghazala
512                                       https://www.nawy.com/compound/1276-playa
517                                        https://www.nawy.com/compound/384-tawny
518                          https://www.nawy.com/compound/378-the-waterway-villas
519                              https://www.nawy.com/compound/394-azzar-new-cairo
520                               https://www.nawy.com/compound/407-al-karma-gates
521                                    https://www.nawy.com/compound/431-lake-west
523                                https://www.nawy.com/compound/70-hacienda-white
524                    https://www.nawy.com/compound/443-midtown-new-capital-villa
525                                    https://www.nawy.com/compound/486-dyar-park
526                                https://www.nawy.com/compound/567-grand-heights
527                              https://www.nawy.com/compound/554-grand-residence
528                                      https://www.nawy.com/compound/680-villino
529                                    https://www.nawy.com/compound/745-eastshire
530                                https://www.nawy.com/compound/716-azzar--island
532                             https://www.nawy.com/compound/756-mena-garden-city

In [50]:
import pandas as pd

missing_url = df[
    df["url"].replace(r'^\s*$', pd.NA, regex=True).isna()
]

print(f"Rows with missing URL: {len(missing_url)}")
display(missing_url)

Rows with missing URL: 0

Empty DataFrame
Columns: [url, title, location, developer_start_price, resale_start_price, type, property_type, developer_name, amenties, description, payment_plans, property_count, iteration_number, date]
Index: []

In [19]:
df.value_counts("currency")

currency
QAR    24587
Name: count, dtype: int64

In [23]:
import pandas as pd

empty_price = df[
    df["number_of_photos"].replace(r'^\s*$', pd.NA, regex=True).isna()
]

print(f"Rows with empty price: {len(empty_price)}")
display(empty_price)

Rows with empty price: 94

,id,reference_number,title,url,category,category_url,broker_display_name,broker,price,currency,price_per,details,number_of_photos,location,bathrooms,bedrooms,furnished,description,sub_category_1,sub_category_2,agent_name,scraped_ts,depth,iteration_number,phone_number,date,rera_permit_number,user_id,property_type,amenities,dtcm_licence,published_at
1025,264263,CAP-9816,BILLS INCLUDED | FURNISHED 2 BR | 1 MONTH GRACE,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/bills_included_furnished_2_br_1_month_grace/264263,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capstone Property,CAPSTONE PROPERTY,7000,QAR,,100 Sqm,,"Al Mansoura / Fereej Bin Dirham,Doha,Qatar",2,2,Fully furnished,"ALL BILLS INCLUDED!Fully-furnished two-bedroom apartments in Al Muntaza. Unique property services. Equipped with high quality furniture and appliances. This property is 5 mins away from Al Meera - Mansoura, walking distance from Al Muntazah Park and with quick access to C-ring Road.Monthly Rent:Original Rate: QAR 7,500 monthly plus one month grace periodProrated Rate: QAR 6,923 monthly over 13 monthsFacilities & Services Included:• Water and Electricity Charges Included• Complimentary WiFi Access• Swimming Pool• Sauna• Fully Equipped Gymnasium• 24hrs SecurityReference ID: AP5884 Book a viewing today! Call us now!*One year contract*Subject to agency feeDISCLAIMER: Please expect also some minimal variations between the photos and the actual due to valid factors e.g. exact total area of the unit, lighting enhancements made in the photos, and the like.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Gym,Concierge,Security",,2026-07-16
1539,257804,CAP-9589,BILLS INCLUDED | 1 MONTH GRACE PERIOD | SPACIOUS,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/bills_included_1_month_grace_period_spacious/257804,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capstone Property,CAPSTONE PROPERTY,6500,QAR,,130 Sqm,,"Erkiyah,Lusail,Qatar",3,2,Fully furnished,"BILLS INCLUDED | ONE MONTH GRACE PERIODFully-furnished 2-Bedroom Apartment for rent in Al Erkyah City, Lusail. Conveniently located near Lusail Stadium, University, Tram Station and quick access to main road.MONTHLY RENT STARTING FROM QR 5,250 with Utility Bills Included (One year contract)UNIT FEATURES:• 2 Bedroom• 3 Bathrooms• Centralized A/C• 1 Dedicated Parking Space• Dining and Living Area• BalconyRESIDENCES FACILITIES• Beach Access• Covered Parking• Kitchen Appliances• Shared Pool• Security• Concierge• Shared Gym• View of Landmark• Lobby in BuildingBook a viewing today! Call us now or visit capstoneproperty. com*Subject to agency feeDISCLAIMER: Photos are for marketing purposes only. The actual unit may vary depending on the availability of properties.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Balcony,Gym,Concierge",,2026-07-06
6501,202417,1E0HABA8J0QH0PHR96XANQ6QR8,2BHK FF FLAT IN MUNTAZA FOR FAMILY 1 MONTH FREE,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/2bhk_ff_flat_in_muntaza_for_family_1_month_free/202417,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,MRS Real Estate,MRS REAL ESTATE,5500,QAR,Month,130 Sqm,,"Rawdat Al Khail,Doha,Qatar",3,2,Fully furnished,"MRS REAL ESTATE is pleased to offer you a Modern Living in the Heart of MUNGAZA – Prime Rental OpportunityExperience the perfect blend of comfort and convenience in this beautifully appointed apartment located in Mansoora, one of Doha’s most vibrant and sought-after neighborhoods.Property Highlights:Spacious Layout: Enjoy a well-designed floor plan featuring [2] bedrooms and [3] bathrooms, complemented by a modern kitchen and a bright living area.Prime Location: Situated just off Mansoora Street, the apartment offers easy access to key areas of Doha, making daily commutes and errands effortless.Proximity to Amenities: Live moments away from popular shopping destinations like Royal Plaza and Centrepoint Mall, a variety of dining options, fitness centers, and essential services.Excellent Connectivity: Benefit from close proximity to Najma , Umm ghuwalina and musharib Metro Stations, ensuring quick and convenient travel across the city.Family-Friendly Environment: The neighborhood boasts reputable schools, healthcare facilities, and recreational areas, making it ideal for families.Rental Details:Monthly Rent: Starting from QAR [5500] (Excluding Bills) and furnished].Availability: Immediate occupancy available.Contact: For more information or to schedule a viewing, please contact [+97431117140].M. SOHAIL MUKHTAR AGENT FEE: HALF MONTH RENT OF MONTHLY RENT AT ONCE.---Feel free to customize the details such as the number of bedrooms, bathrooms, and rental price to match the specific property. If you need assistance with a particular listing or have further questions, don't hesitate to ask!Thank You for choosing MRS REAL ESTATE.",Residential,,,2026-07-20,,20260703,+97431117184,2026-07-20,,2085450,apartment,"Security,Car Park,Lounge",,2026-06-05
11415,134039,AR-005681-2723,READY FOR OCCUPANCY 2 BEDROOMS SEA and CITY VIEW,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/amazing_2_bedroom_apartment_for_rent_breathtaking_sea_and_city_views/134039,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,FGREALTY,FGREALTY,14000,QAR,,185 Sqm,,"Al Maha Island,Lusail,Qatar",3,2,Fully furnished,"Find Great Residences with FGREALTY.Enjoy elevated waterfront living in this beautiful 2-bedroom apartment with breathtaking panoramic sea and city views. Designed for comfort and convenience, this home offers bright interiors, modern finishes, and a spacious layout, making it ideal for professionals, couples, or small families seeking a premium lifestyle in Lusail Marina.The apartment features two spacious bedrooms with built-in wardrobes, a bright living and dining area with floor-to-ceiling windows, a fully equipped modern kitchen, 2.5 stylish bathrooms, and a private balcony where you can relax while taking in spectacular sea and skyline views.Property Features:2 Spacious BedroomsBuilt-in WardrobesBright Living AreaFully Equipped Kitchen2.5 Modern BathroomsPrivate BalconyPanoramic Sea & City ViewsFloor-to-Ceiling WindowsBuilding Amenities:Swimming PoolFully Equipped GymResidents' LoungeEntertainment AreaCovered Parking24/7 SecurityConcierge ServiceLocation Highlights:Prime Lusail Marina LocationWalking Distance to the Marina PromenadeNear Cafés & RestaurantsClose to Retail & SupermarketsEasy Access to Lusail BoulevardConvenient Access to Public TransportThis exceptional apartment combines comfort, style, and a prestigious waterfront address, making it an ideal home for those looking to enjoy the best of Lusail Marina living.Contact FGREALTY today to arrange your private viewing.",Residential,,,2026-07-20,,20260703,+974 3344 2261,2026-07-20,,219595,apartment,"Balcony,Outdoor Pool,Pet-Friendly,Gym,Security,Near Metro,Sea View,Shared Pool,Near Mall,Express Market,Security Access,Near Mosque,Near Public Transport,City View",,NaT
12278,264284,CAP-9815,BILLS INCLUDED | FULLY-FURNISHED 2 BR APARTMENT,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/bills_included_fully_furnished_2_br_apartment/264284,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capstone Property,CAPSTONE PROPERTY,7500,QAR,,100 Sqm,,"Al Mansoura / Fereej Bin Dirham,Doha,Qatar",2,2,Fully furnished,"ALL BILLS INCLUDED!Fully-furnished two-bedroom apartments in Al Muntaza. Unique property services. Equipped with high quality furniture and appliances. This property is 5 mins away from Al Meera - Mansoura, walking distance from Al Muntazah Park and with quick access to C-ring Road.Monthly Rent:Original Rate: QAR 7,500 monthly plus one month grace periodProrated Rate: QAR 6,923 monthly over 13 monthsFacilities & Services Included:• Water and Electricity Charges Included• Complimentary WiFi Access• Swimming Pool• Sauna• Fully Equipped Gymnasium• 24hrs SecurityReference ID: AP5884 Book a viewing today! Call us now!*One year contract*Subject to agency feeDISCLAIMER: Please expect also some minimal variations between the photos and the actual due to valid factors e.g. exact total area of the unit, lighting enhancements made in the photos, and the like.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Gym,Concierge,Security",,2026-07-16
12284,264271,CAP-9904,BILLS INCLUDED | LUXURY PENTHOUSE | 4 BALCONIES,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/bills_included_luxury_penthouse_4_balconies/264271,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capstone Property,CAPSTONE PROPERTY,40499,QAR,,316 Sqm,,"Marina,Lusail,Qatar",6,4,Fully furnished,"Experience luxury waterfront living in this spacious 4-bedroom apartment with a maid's room, located in one of the most prestigious residential towers in Lusail Marina District. Designed with generous living spaces, premium finishes, and expansive outdoor areas, this home is ideal for families seeking comfort, privacy, and convenience.Apartment Layout* 4 Spacious Bedrooms* Maid's Room* Bright Living & Dining Area* 2 Halls* Modern Kitchen* 4 Bathrooms* 1 Private Terrace* 4 Balconies* Built-in Wardrobes* Dedicated ParkingBuilding Amenities* Swimming Pool* Fully Equipped Gym* Children's Play Area* Multi-Purpose Room* Concierge Service* 24/7 Security* Covered Parking* Elegant LobbyLocation OverviewIdeally located in the heart of Lusail Marina District, the tower is just minutes from Place Vendôme Mall, Lusail Marina Promenade, restaurants, cafés, retail outlets, and Metro Link stations, with easy access to Lusail Boulevard, West Bay, and major highways.Contact Capstone Property today to arrange your private viewing.Disclaimer: Images are for illustrative purposes only. The actual apartment may vary in layout, size, floor level, finishes, furnishings, and views. Availability is subject to confirmation. Terms and conditions apply. Agency fee applies.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Maids Room,Balcony,Gym,Concierge,Security",,2026-07-16
13928,257813,CAP-9594,BILLS INCLUDED | 1 MONTH GRACE PERIOD | SPACIOUS,https://qlp.qatarliving.com/en/properties/rent/residential/apartment/bills_included_1_month_grace_period_spacious/257813,For rent,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent,Capstone Property,CAPSTONE PROPERTY,5250,QAR,,80 Sqm,,"Erkiyah,Lusail,Qatar",2,1,Fully furnished,"BILLS INCLUDED | ONE MONTH GRACE PERIODFully-furnished 1-Bedroom Apartment for rent in Al Erkyah City, Lusail. Conveniently located near Lusail Stadium, University, Tram Station and quick access to main road.MONTHLY RENT STARTING FROM QR 5,250 with Utility Bills Included (One year contract)UNIT FEATURES:• 1 Bedroom• 2 Bathrooms• Centralized A/C• 1 Dedicated Parking Space• Dining and Living Area• BalconyRESIDENCES FACILITIES• Beach Access• Covered Parking• Kitchen Appliances• Shared Pool• Security• Concierge• Shared Gym• View of Landmark• Lobby in BuildingBook a viewing today! Call us now or visit capstoneproperty.com*Subject to agency feeDISCLAIMER: Photos are for marketing purposes only. The actual unit may vary depending on the availability of properties.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Balcony,Gym,Concierge",,2026-07-06
21428,234286,CAP-6678,BRAND NEW | READY | 5 YEARS PAYMENT PLAN,https://qlp.qatarliving.com/en/properties/sale/residential/apartment/brand_new_ready_5_years_payment_plan/234286,For sale,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Sale,Capstone Property,CAPSTONE PROPERTY,1684269,QAR,,127 Sqm,,"Al Wessil,Lusail,Qatar",3,2,Fully furnished,"Own your brand new ready apartment at Bliss Residences, Fox Hills, Lusail, with 5 years payment plan.• Fully-furnished 1, 2 and 3-bedroom apartments• Ready to move-in• Freehold Ownership• Prime location near Lusail Boulevard, Place Vendome, Family Park, and easy access to Lusail Expressway.FOR SALES, Call or Whatsapp us!Amenities:• Swimming Pool• Fully Equipped Gym• Outdoor Seatings• 24/7 SecurityStarting selling prices:• 1BR from QR 1,498,000• 2BR from QR 1,684,269• 3BR from QR 1,933,500Discover a new standard of luxury and convenience in Lusail’s newest residential project. Contact us today to learn more about available apartments.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Gym,Concierge,Walk-In Closet,Kids Play Area,Security",,2026-05-19
21431,168362,CAP-8132,FREEHOLD VILLA | 5YRS PAYMENT | PRIVATE POOL,https://qlp.qatarliving.com/en/properties/sale/residential/villa/freehold_villa_5yrs_payment_private_pool/168362,For sale,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Sale,Capstone Property,CAPSTONE PROPERTY,4290000,QAR,,464 Sqm,,"New Salata / Al Asiri,Doha,Qatar",6,5,Semi-furnished,"Bliss Gardens – Premium Freehold Villas for Sale in New SlataOwn a high-end, semi-furnished villa in the heart of Doha - New Slata, designed to offer elegance, comfort, and exclusivity. Featuring a private swimming pool, spacious interiors, and high-end finishes, this property represents the perfect blend of modern architecture and timeless sophistication. • 5 Years Payment Plan• 10% Downpayment• Handover: October 2027• Freehold for expats Features & Specifications:• Semi-furnished villa• 5 Bedrooms• 4 Living rooms• Private swimming pool• Private garden• Dedicated parking space• Area: 464 SQM Starting price from QR 4,290,000Discover a new standard of luxury and convenience in Doha’s newestresidential project. Contact us today to learn more about available villas.FOR SALES, Call or WhatsApp us on +97430473333",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,villa,Indoor Pool,,2026-03-08
21460,238668,CAP-9448,Freehold Sea View | Renovated 1BR The Pearl,https://qlp.qatarliving.com/en/properties/sale/residential/apartment/freehold_sea_view_renovated_1br_the_pearl/238668,For sale,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Sale,Capstone Property,CAPSTONE PROPERTY,2000000,QAR,,128 Sqm,,"Viva Bahriya,The Pearl,Qatar",2,1,Fully furnished,"Own a Piece of Qatar's Most Prestigious Address — Freehold.Positioned in the iconic Viva Bahryia tower, this beautifully renovated 1-bedroom, 2-bathroom apartment offers an exceptional opportunity for both end-users and investors seeking a foothold in one of the Middle East's most sought-after freehold communities — The Pearl, Qatar.Property Highlights:• 1 Bedroom | 2 Bathrooms | 128.29 sqm• Sea View with direct beach access• Balcony for outdoor living• Secure underground parking • Located in Viva Bahryia — one of The Pearl's most iconic towersWhether you're building a high-yield portfolio or securing a luxury lifestyle residence with income upside, this apartment delivers both — without compromise.Act now. Freehold opportunities at this price point in The Pearl do not last.Ready to invest or arrange a viewing? Contact Capstone today — our experts are on hand to guide you through every step of the process.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Balcony,Gym,Concierge,Sea View",,2026-06-01
21462,231869,CAP-9403,SPACIOUS 2BR+M | RENTED | FREEHOLD,https://qlp.qatarliving.com/en/properties/sale/residential/apartment/spacious_2br_m_rented_freehold/231869,For sale,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Sale,Capstone Property,CAPSTONE PROPERTY,2430000,QAR,,173 Sqm,,"Al Maha Island,Lusail,Qatar",3,2,Fully furnished,"For Sale Fully-Furnished Apartment at First-Row Tower, Lusail MarinaReady-to-move-in, these fully-furnished high-quality apartments offer the perfect blend of luxury, comfort, and convenience in one of Qatar’s most prestigious seafront communities. Ideal whether you’re looking for a smart investment or a beautiful place to call home. Prime Location:• City Views• Walking Distance to Tram Station and Lusail Marina Promenade• Close to Place Vendome Mall and Al Maha Island Enjoy modern living with stunning views and world-class amenities right at your doorstep.Call now to book your free consultation.Disclaimer: Photos may vary from the actual unit and layout.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Maids Room,Balcony,Gym,Security",,2026-05-15
21463,158891,CAP-7945,DUPLEX WITH PRIVATE POOL | BRAND NEW | FREEHOLD,https://qlp.qatarliving.com/en/properties/sale/residential/apartment/new_penthouse_with_private_pool_luxury/158891,For sale,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Sale,Capstone Property,CAPSTONE PROPERTY,7000000,QAR,,633 Sqm,,"Al Kharayej,Lusail,Qatar",5,4,Fully furnished,"Brand-new luxury penthouse for sale in Lusail City. Designed for exclusivity and comfort, this two-floor residence features 4 spacious bedrooms plus a maid’s room, complemented by two elegant living areas that create the perfect setting for both relaxation and entertainment. The crown jewel is your very own private swimming pool, offering unmatched privacy and a lifestyle of sophistication.As a freehold property with title deed available, this penthouse is not only a dream home but also a secure investment in one of Qatar’s most prestigious locations. Residents also enjoy access to premium shared amenities, including a large swimming pool, modern gym, and dedicated children’s play area, ensuring comfort for the whole family.Features:• Freehold property with title deed available• 4 bedrooms plus maid’s room• 2 spacious living areas• Spacious kitchen• Private Elevator• Private swimming pool• Access to shared pool, gym, and children’s play area• Prime location in Lusail CityLuxury, privacy, and investment value come together in this rare opportunity. Contact Capstone Property today to book your private viewing and own this exceptional penthouse in Lusail.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Maids Room,Balcony,Gym,Indoor Pool,Kids Play Area,Security",,NaT
21464,168356,CAP-8176,Bliss Tower | Smart Ownership Program,https://qlp.qatarliving.com/en/properties/sale/residential/apartment/6_years_payment_plan_5_dp_premium_apartments/168356,For sale,https://qlp.qatarliving.com/en/properties/residential?purpose=For+Sale,Capstone Property,CAPSTONE PROPERTY,1462669,QAR,,84 Sqm,,"Al Kharayej,Lusail,Qatar",2,1,Fully furnished,"Capstone Property proudly presents the exclusive Bliss Tower Ownership Program — a smarter, stress-free way to own in Lusail.3 Years. Worry Free.Enjoy unmatched peace of mind with:* 3 Years No Service Charge* 3 Years Post-Handover Payment Plan* 3 Years Leasing & Property ManagementOwn with confidence while we take care of everything.Visit us at our Open House and discover a better way to own.Flexible Plan:* 6 Years Payment Plan* Only 5% DownpaymentLocated in the heart of Waterfront Lusail, Bliss Tower offers more than just a home — it’s a lifestyle. Enjoy panoramic views of the sea, Qetaifan Island, Lusail Boulevard, the stadium, and the city skyline.Available Units:* Fully Furnished 1 Bedroom* 2 Bedrooms + Maid’s Room* 3 Bedroom Duplex + Maid’s RoomHandover: November 2028Starting Price: From QAR 1,384,000Tower Amenities:* Outdoor Swimming Pool* Fully Equipped Gym* Massage and Sauna Rooms* Multi-Purpose Hall* Kids’ Play AreaExperience a new level of ownership where comfort, convenience, and smart investment come together.",Residential,,,2026-07-20,,20260703,+97444448474,2026-07-20,,165999,apartment,"Balcony,Gym,Concierge,Walk-In Closet,Kids Play Area,Security",,NaT

In [ ]:
import re

pattern = re.compile(r'[\u200B\u200C\u200D\u2060\uFEFF\u00A0]')

for col in df.select_dtypes(include="object").columns:
    mask = df[col].fillna("").astype(str).str.contains(pattern, regex=True)
    if mask.any():
        print(f"\nColumn: {col}")
        display(df.loc[mask, [col]])