In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv(r'/home/user/Documents/zepto_2026_07_21.csv',  low_memory=False)

In [3]:
df.shape

(539534, 31)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls'],
      dtype='object')

In [6]:
df.city.value_counts()

city
Mumbai                       99787
Bangalore                    83692
Hyderabad                    62279
Pune                         33993
Chennai                      26077
Kolkata                      21216
Ahmedabad                    18239
Jaipur                       14676
Coimbatore                   10819
Surat                         7681
Faridabad                     7626
Kochi                         7526
Vijayawada                    7488
Rajkot                        7468
Dehradun                      7422
Ludhiana                      7157
Chandigarh                    6909
Panchkula                     6569
Kalamassery                   4406
Thane                         4118
Kurukshetra                   4018
Tumakuru                      3988
Kanpur                        3951
Vellore                       3936
Amritsar                      3897
Agra                          3831
Udaipur                       3812
Davanagere                    3789
Prayagraj                     3780
Gorakhpur                     3763
Guntur                        3746
Vadodra                       3730
Kota                          3683
Ambala                        3669
Chhatrapati Sambhajinagar     3665
Indore                        3638
Mohali                        3618
Kharar                        3607
Bareilly                      3597
Madurai                       3584
Haridwar                      3555
Jalandhar                     3555
Vrindavan                     3109
Thrippunithura                3095
Ghaziabad                     3017
Sankhol                       2753
Name: count, dtype: int64

In [7]:
df.isnull().sum()

crawl_date_and_time             0
platform_name                   0
store_id                        0
store_name_location             0
city                            0
pin_code                        0
unique_id                       0
product_id_upc_ean              0
department                      0
category                        0
sub_category                    0
product_type               539534
brand_name                      0
product_name                    0
product_description        539534
product_grammage            97443
package_type               539534
net_quantity                    1
variants                   524745
item_mrp                        0
item_selling_price              0
out_of_stock_flag               0
discount_flag                   0
product_price                   0
unit_price                 539534
promo_offer_description         0
promo_offer_price               0
discount_in_percent             0
stock_count                     0
product_url                     0
product_image_urls         539534
dtype: int64

In [11]:
df[df['net_quantity'].isna()]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
356954,2026-07-21 03:09:05,zepto,f640034b-60ca-4426-8b7b-edcf408846ec,"JKS-38, Elamakkara, Kochi, Kerala, 682026, India",Kochi,682026,97c5b0ef-8be4-441a-b4fa-caead460faa6,fed45baf-f2e7-4eb8-8068-0498dd77e5e7,Personal Care,Bath & Body,Handwash & Sanitizers,NaN,Santoor,Santoor Handwash Mild,NaN,NaN,NaN,NaN,NaN,99.0,84.0,No,Yes,84.0,NaN,₹15 OFF,84.0,15,3,https://www.zepto.com/pn/santoor-handwash-mild/pvid/97c5b0ef-8be4-441a-b4fa-caead460faa6,NaN

In [12]:
df.nunique()

crawl_date_and_time        14075
platform_name                  1
store_id                     194
store_name_location          147
city                          46
pin_code                     135
unique_id                  16636
product_id_upc_ean         16141
department                    10
category                      24
sub_category                 160
product_type                   0
brand_name                  1680
product_name               14844
product_description            0
product_grammage            1071
package_type                   0
net_quantity                2061
variants                     301
item_mrp                    1159
item_selling_price          2020
out_of_stock_flag              2
discount_flag                  2
product_price               2020
unit_price                     0
promo_offer_description     1350
promo_offer_price           2020
discount_in_percent           95
stock_count                   51
product_url                16636
product_image_urls             0
dtype: int64

In [13]:
df.net_quantity.value_counts()

net_quantity
1 pc                                  39178
1 pack (200 g)                        19219
1 pack (500 g)                        18201
1 pack (1 kg)                         15051
1 pc (100 ml)                         13625
1 pc (200 ml)                         11490
1 pack (100 g)                        10864
1 pc (250 ml)                         10853
1 pc (1 L)                            10312
1 pc (100 g)                           9909
1 set                                  9817
1 pc (50 g)                            8997
1 pc (50 ml)                           7621
1 pack (5 kg)                          7307
1 pack (250 g)                         6079
1 pack (1 L)                           5529
1 pack (400 g)                         5371
1 pc (150 ml)                          5366
1 pc (400 ml)                          4669
1 pc (30 ml)                           4502
1 pack (500 ml)                        4366
1 pack (150 g)                         4293
1 pc (200 g)                           4108
1 pc (180 ml)                          3827
1 pack (6 pcs)                         3825
1 pack (50 g)                          3623
1 pc (300 ml)                          3491
1 pack (2 pcs)                         3469
1 pack (10 pcs)                        3261
1 pc (500 ml)                          3238
1 pc (120 ml)                          3069
1 pc (250 g)                           2979
1 pack (3 pcs)                         2907
1 pc (150 g)                           2870
1 pc (1 kg)                            2841
1 pc (80 g)                            2825
1 pack (5 pcs)                         2818
1 pack (60 g)                          2794
1 pack (40 g)                          2771
1 pack (100 ml)                        2724
1 pc (60 ml)                           2713
1 pc (75 g)                            2622
1 pack (300 g)                         2423
1 pack                                 2419
1 pack (20 pcs)                        2246
1 pack (4 pcs)                         2170
1 pack (30 pcs)                        2160
1 pc (300 g)                           2137
1 pack (80 g)                          2085
1 pc (10 ml)                           2054
2 combo                                1961
1 pack (25 pcs)                        1909
1 pc (70 ml)                           1903
1 pc (750 ml)                          1840
1 pc (30 g)                            1839
1 pc (400 g)                           1757
1 pack (12 pcs)                        1692
1 pack (70 g)                          1653
1 pc (110 ml)                          1648
1 pc (40 ml)                           1646
1 pc (175 ml)                          1582
1 pc (40 g)                            1578
1 pack (45 g)                          1576
1 pack (160 g)                         1542
1 pack (75 g)                          1519
1 pack (25 g)                          1511
1 pc (600 ml)                          1502
1 pack (40 pcs)                        1469
1 pc (500 g)                           1411
1 pack (120 g)                         1400
1 pc (125 ml)                          1362
1 pc (80 ml)                           1349
1 pack (20 g)                          1335
1 pc (45 g)                            1317
1 pack (180 g)                         1271
1 pc (350 g)                           1268
1 pack (10 kg)                         1238
1 x 72 pulls                           1236
1 pack (450 g)                         1220
1 pack (140 g)                         1166
1 pack (55 g)                          1159
1 pack (85 g)                          1109
1 pack (30 g)                          1098
1 pc (4 g)                             1096
1 pack (350 g)                         1094
1 pc (330 ml)                          1092
1 pack (200 ml)                        1050
1 pc (70 g)                            1021
1 pc (90 g)                            1012
1 pc (15 ml)                            980
1 pack (24 pcs)                         977
1 pack (16 pcs)                         975
1 pc (170 ml)                           967
1 pc (6 ml)                             956
1 pc (125 g)                            944
1 pack (18 pcs)                         920
1 pack (35 g)                           912
1 set (3 pcs)                           889
62pcs                                   862
1 pc (85 g)                             858
1 pack (800 g)                          839
1 pack (125 ml)                         826
250 ml X 2                              817
1 pc (510 g)                            802
3 pcs                                   796
1 pc (225 ml)                           792
1 pc (5 ml)                             790
1 pc (236 ml)                           777
1 pc (75 ml)                            773
1 pack (125 g)                          767
100 g                                   762
1 pc (55 g)                             761
1 pc (230 ml)                           759
50 g                                    758
1 pack (15 pcs)                         748
1 pack (450 ml)                         734
1 pc (220 ml)                           731
3 x 72 pulls                            720
1 pc (105 ml)                           716
1 pc (35 g)                             705
54pcs                                   680
1 pc (60 g)                             671
1 pack (5 x 125 g)                      669
100 ml                                  652
1 pack (28 g)                           652
1 pc (10 g)                             650
1 set (2 pcs)                           647
1 pack (50 pcs)                         639
1 pc (924 g)                            630
1 pc (190 ml)                           612
1 pack (150 ml)                         608
1 pack (25 ml)                          596
1 pc (180 g)                            595
1 set (5 pcs)                           594
1 pc (25 ml)                            584
1 pc (9 ml)                             583
72pcs                                   578
1 pack (77 g)                           576
1 pc (4.5 g)                            563
1 pc (65 ml)                            561
1 pc (1.2 L)                            556
1 pack (36 pcs)                         551
200 ml                                  543
1 pc (20 g)                             534
1 set (7 pcs)                           532
1 pc (120 g)                            527
1 pack (700 ml)                         525
1 pc (15 g)                             525
1 pc (9 g)                              519
1 pack (2 x 150 g)                      513
1 pack (65 g)                           505
4 pcs                                   504
1 pc (20 ml)                            500
1 pack (750 ml)                         498
350 ml                                  493
2 pcs                                   491
150 g + 60 g                            488
250 ml                                  488
1 pc (8 ml)                             488
1 pack (850 g)                          479
1 pc (190 g)                            471
1 pc (170 g)                            469
1 pc (25 g)                             468
1 pc (750 g)                            468
1 pc (5 L)                              466
100 g X 2                               460
180 ml                                  460
1 set (4 pcs)                           454
1 pack (4 x 150 g)                      452
1 pack (170 g)                          448
1 pc (0.35 g)                           447
1 pc (4.8 g)                            438
1 pc (12 g)                             436
1 pc (90 ml)                            428
1 pack (57 g)                           426
1 pack (115 ml)                         421
1 pair                                  419
200 ml X 2                              416
1 pc (350 ml)                           415
1 pack (750 g)                          412
1 pc (450 g)                            410
1 pack (3 x 100 g)                      410
1 kg                                    409
0.35 g                                  409
2 x 72 pulls                            404
1 pack (41 g)                           399
1 pc (236 ml or 250 ml)                 396
500 ml X 2                              396
1 pc (88 ml)                            387
1 pack (19.8 g)                         384
1 pack (144 g)                          383
300 ml                                  380
1 pc (12 ml)                            379
1 pack (375 g)                          371
1 pack (2 kg)                           371
1 pack (130 g)                          369
1 pc (135 ml)                           360
5 ml                                    355
1 piece                                 354
1 pack (60 g or 64 g)                   354
1 pc (2.25 L)                           351
1 set (8 pcs)                           350
200 g                                   349
1 set (4 x 20 ml)                       346
1 pc (175 g)                            345
2 pack (10 pcs)                         342
1 pc (4 ml)                             340
1 pc (2 L)                              339
500 g                                   338
60 ml X 2                               337
1 pack (100 pcs)                        335
1 pc (17 g)                             335
1 pack (275 g)                          335
1 pc (6 g)                              329
1 pack (600 g)                          326
1 set (4 x 25 ml)                       322
1 pack (7 pcs)                          322
250 ml X 3                              319
1 pack (250 ml)                         315
1 set (6 pcs)                           314
1 pc (5 g)                              310
1 pc (61 g)                             307
1 pack (900 ml)                         306
1 pack (900 g)                          304
1 pack (1.2 kg)                         303
1 pack (43 g)                           303
74pcs                                   302
5.6 ml                                  301
1 pack (8 pcs)                          301
1 pc (55 ml)                            301
1 pack (52 g)                           299
1 pack (99 g)                           298
1 x 80 pulls                            298
1 pack (79 g)                           297
1 pack (240 g)                          291
1 pack (3 x 40 g)                       291
1 pack (3 x 150 g)                      289
1 pc (118 ml or 125 ml)                 288
1 pcs                                   286
30 ml                                   286
1 pc (320 ml)                           284
1 pack (67.5 g)                         282
1 pack (142 g)                          281
1 pack (48 g or 52.9 g)                 280
1 pack (3 x 125 g)                      278
70 ml + 60 g                            277
1 pc (18 ml)                            277
1 L X 3                                 276
1 pack (4 x 70 g)                       275
1 kg X 2                                271
70pcs                                   269
1 pack (168 g)                          269
1 pc (196 ml)                           268
1 pc (340 ml)                           266
1 pack (14 pcs)                         264
1 pack (160 g or 171 g)                 261
1 pack (270 g)                          261
100 g X 3                               261
1 pack (90 g)                           259
1.15 kg                                 258
1 pack (55 g or 57 g)                   257
1 set (11 pcs)                          257
0.3 g                                   257
10 ml X 2                               256
1 pc (3.5 ml)                           254
1 pack (25 x 1.7 g)                     252
1 pc (245 ml)                           250
1 pack (280 g)                          248
1 pc (240 ml)                           248
56pcs                                   248
1 pack (8 x 250 ml)                     246
1 pack (30.6 g or 28.9 g)               245
1 pack (38 g)                           245
1 pack (48 g)                           244
3 combo                                 244
40pcs                                   243
1 pack (4 x 125 g)                      243
1 pc (227 g)                            242
1 pc (1.25 kg)                          242
400 g                                   241
1 pack (10 x 10 g)                      238
1 pack (25 x 2 g)                       235
1 pc (3 g)                              235
1 pack (33 g)                           235
1 pack (69 g)                           235
1 pack (128 g)                          234
230 g                                   234
1 pc (4.5 ml)                           233
1 pc (45 ml)                            230
1 L X 2                                 229
450 ml                                  229
1 pack (44 g)                           229
1 pc (340 g)                            229
1 pc (300 ml or 330 ml)                 228
150 g X 2                               223
1 pack (700 g)                          223
1 L                                     223
1 pack (5 x 100 g)                      221
1 pack (95 g)                           219
30 g                                    217
1 pack (2 x 100 ml)                     217
1 pc (175 ml or 180 ml)                 217
1 pc (180 ml or 190 ml)                 215
1 pack (153 g)                          214
1 pc (65 g)                             214
1 set (9 pcs)                           214
1 set (60 g)                            213
1 pack (225 g)                          213
1 pack (37.5 g)                         212
1 pc (210 g)                            211
30pcs                                   211
1 pc (280 ml)                           210
1 pc (35 ml)                            209
1 pc (1.5 L)                            209
60 ml X 3                               208
1 pack (110 g)                          208
1 pack (240 pcs)                        208
1 pack (415 g)                          207
250 g X 2                               206
1 pack (72 pcs)                         205
1 pack (60 pcs)                         199
1.2 kg                                  197
1 pack (165 g)                          195
400g                                    192
87.5 g + 72 ml                          192
1 kg X 4                                189
1 pack (210 g)                          189
200 g X 2                               188
1 pack (27.3 g or 28.2 g)               187
1 pc (18 g)                             187
1 pack (108 g)                          186
55 g X 2                                186
1 pack (159 g)                          185
60 g                                    184
1 pc (7 ml)                             184
1 kg X 3                                183
1 pc (600 g)                            183
1 pack (6 x 12.5 g)                     183
1 pack (4 x 100 g)                      182
1 pack (120 ml)                         179
1 pc (1.5 g)                            179
1 pack (6 Sachets)                      177
1 pack (2 x 12.5 g)                     174
1 pack (110 ml)                         174
1 set (10 pcs)                          174
1 pc (700 g)                            173
1 pc (225 g)                            173
260 g                                   169
1 pack (20 g or 16 g)                   169
1 pack (22 g)                           169
1.6 g                                   168
500 ml                                  167
1 pc (36 g)                             167
1 pack (62.5 g)                         165
1 pc (140 g)                            165
1 pc (63 g)                             165
70 ml X 2                               165
1 pc (46 g)                             162
32pcs                                   162
1 pack (950 g)                          161
1 pc (354 ml)                           161
1 pack (4 x 75 g)                       161
1 pack (135 g or 140 g)                 159
6X1L                                    159
1 pack (34 g)                           158
1 pack (248 g)                          157
1 pc (110 g)                            157
1 pack (59.4 g)                         156
1 pack (165 ml)                         155
120 g X 2                               155
1 pack (180 ml)                         155
1 pc (1 ml)                             155
1 pack (66.6 or 75 g)                   154
1 pack (475 g)                          153
400 g X 2                               151
1 pack (32 g)                           151
1 pack (56 g)                           151
300 g                                   149
1 pack (84 g)                           149
500 g X 2                               149
1 pack (75 g or 80 g)                   148
1 pack (20 ml)                          148
1 pc (380 g)                            147
350 g                                   147
1 pc (100 or 110 g)                     147
180 g                                   147
1 pc (56 g)                             146
1 pack (48 pcs)                         145
1 x 60 pulls                            145
144 g X 2                               145
85 g X 2                                145
2 x 70 ml                               145
1 Pack (40 g)                           144
1 pack (70 g or 75 g)                   144
1 pc (100 ml or 118 ml)                 144
20 pc X 2                               144
1 pack (80 ml)                          144
80 g                                    143
1 pc (185 ml)                           143
1 pack (10 x 20 g)                      143
1 pc (500 ml or 473 ml)                 143
1 pc (80 g or 100 g)                    143
500 ml X 4                              143
1 pack (173 g)                          142
1 pack (9 pcs)                          142
1 pack (29.7g)                          142
1 pc (78 g)                             142
1 pack (360 g)                          142
1 pack (295 g)                          142
1 pack (150 g + 60 g)                   141
1 pack (5 x 65 ml)                      141
1 pack (29.7 g)                         141
1 pack (960 g)                          141
1 pack (188 g)                          141
1 pack (100 g or 114.1g)                141
1 pack (50 or 55 g)                     141
1 pc (27.5 g or 30 g)                   141
1 pack (24 x 250 ml)                    141
1 pc (150 g + 60 g)                     141
1 pack (145 g)                          140
1 pack (91.7 g or 100 g)                140
1 pack (100 g or 112 g)                 140
1 pc (825 ml)                           140
1 pc (47 g or 50 g)                     139
2 x 25 g + 25 ml                        139
1 pack (696 g)                          139
5 x 72 pulls                            139
70 g                                    138
1 pack (52.9 g or 58 g)                 138
1 pack (183 g)                          138
1 pack (585 g)                          138
2 x 225 g                               138
1 L X 4                                 137
7 pack (140 g)                          137
1 pack (159 ml)                         137
1 Pack(350 g)                           136
1 pc (473 ml or 500 ml)                 136
1 pack (250 ml or 300 ml)               136
1 pc (45 or 48.5 g)                     136
4 x 5 ml                                136
1 pack (100 g or 115.5 g)               135
1 pc (62 g)                             135
44pcs                                   135
1 pack (112.5 g)                        135
1 pack (705.6 g)                        135
1 pack (70 g or 100 g)                  135
1 pack (405 g)                          135
100 ml X 2                              135
1 pc (28 ml)                            134
1 pack (4 x 250 ml)                     134
1 pack (16 g)                           134
1 pack (850 g or 900 g)                 134
1000 ml                                 134
1 pack (66 g or 61.6 g)                 134

In [14]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Agra,159,536,310,691,347,359,192,418,547,272
Ahmedabad,798,2542,1302,3178,1525,2115,945,1812,2689,1333
Ambala,157,422,308,633,330,424,191,400,493,311
Amritsar,160,561,314,680,329,381,192,412,586,282
Bangalore,3189,13556,6040,13529,6961,8771,3803,9088,12854,5901
Bareilly,157,511,294,665,307,304,191,410,477,281
Chandigarh,316,757,582,1258,595,819,374,809,859,540
Chennai,1045,3578,1987,4134,2271,3082,1310,2798,3984,1888
Chhatrapati Sambhajinagar,160,464,283,655,346,373,191,417,486,290
Coimbatore,468,1348,838,1936,942,1169,569,1214,1445,890
Davanagere,160,482,292,688,352,414,191,422,513,275
Dehradun,249,909,600,1335,681,758,380,829,1052,629
Faridabad,304,821,634,1309,760,926,379,843,1090,560
Ghaziabad,127,259,265,509,282,406,178,353,421,217
Gorakhpur,160,521,320,692,342,306,191,404,520,307
Guntur,160,454,304,680,354,369,192,416,515,302
Haridwar,157,436,306,627,349,309,189,412,497,273
Hyderabad,2450,9072,4667,10325,5234,6851,2941,6853,8628,5258
Indore,160,442,292,654,336,361,192,406,494,301
Jaipur,613,2014,1149,2604,1214,1671,742,1493,2033,1143
Jalandhar,153,405,275,664,312,379,192,408,500,267
Kalamassery,160,769,317,775,336,424,192,463,662,308
Kanpur,160,590,319,732,324,365,191,408,542,320
Kharar,150,403,274,549,331,434,184,427,542,313
Kochi,314,883,603,1276,645,844,382,882,1081,616
Kolkata,783,2689,1749,3725,2002,2435,1139,2361,2896,1437
Kota,160,475,304,674,313,401,192,402,455,307
Kurukshetra,160,591,320,726,359,388,190,426,587,271
Ludhiana,318,856,595,1298,625,742,384,822,957,560
Madurai,158,456,261,636,313,361,189,408,517,285
Mohali,150,405,271,557,329,431,185,428,549,313
Mumbai,3891,11990,7605,16681,9957,12099,4810,11351,14125,7278
Panchkula,309,740,525,1205,548,761,382,786,852,461
Prayagraj,160,520,311,694,345,292,191,413,562,292
Pune,1380,4577,2652,5053,2993,3923,1700,3883,5123,2709
Rajkot,320,976,612,1351,718,761,383,804,985,558
Sankhol,153,250,256,501,223,306,187,386,358,133
Surat,316,1106,589,1343,648,756,384,795,1114,630
Thane,154,644,286,730,314,439,192,434,643,282
Thrippunithura,154,342,235,520,273,337,190,398,408,238
Tumakuru,160,551,318,702,381,445,192,419,514,306
Udaipur,159,518,301,704,289,398,189,401,539,314
Vadodra,160,442,313,668,370,402,192,404,470,309
Vellore,160,562,306,721,347,382,192,423,546,297
Vijayawada,320,954,571,1340,696,756,382,835,1035,599
Vrindavan,156,338,253,603,303,220,190,397,395,254

In [15]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

category,"Atta, Rice, Oil & Dals",Baby Care,Bath & Body,Biscuits,Breakfast & Sauces,Cold Drinks & Juices,"Dairy, Bread & Eggs",Electronics & Appliances,Feminine Hygiene,Fragrances & Grooming,Frozen Food,Hair Care,Ice Creams & More,Makeup & Beauty,"Masala, Dry Fruits & More",Munchies,Packaged Food,Pharma & Wellness,Skincare,Stationery & Books,Sweet Cravings,"Tea, Coffee & More",Toys & Sports,Zepto Cafe
city,,,,,,,,,,,,,,,,,,,,,,,,
Agra,236,285,248,224,160,247,164,32,145,100,29,189,230,181,128,219,160,4,344,0,146,128,230,2
Ambala,227,233,220,216,156,246,243,12,148,91,28,174,230,165,127,216,155,0,324,0,170,126,160,2
Amritsar,234,277,247,218,160,244,193,32,155,91,28,192,196,160,131,220,164,6,388,0,177,128,254,2
Bangalore,5023,6139,5424,4140,3173,4794,5434,507,3200,1842,476,3489,4551,3282,2525,4407,3461,51,8725,0,3537,2476,6589,447
Bareilly,227,241,226,199,160,227,148,15,137,91,0,193,215,163,128,217,159,2,328,0,147,128,244,2
Chandigarh,454,382,389,391,319,444,453,8,277,174,56,372,372,295,253,430,325,1,603,0,338,255,314,4
Chennai,1654,1833,1797,1343,988,1654,1864,162,894,606,215,1148,1366,885,818,1541,937,15,2621,0,1228,780,1606,122
Chhatrapati Sambhajinagar,233,211,229,214,160,245,153,22,133,100,31,192,231,161,131,220,161,3,308,0,177,128,219,3
Coimbatore,676,680,639,600,479,709,579,54,405,310,90,531,613,469,385,659,485,7,958,0,517,376,591,7
Davanagere,238,235,240,223,159,248,200,24,140,104,31,185,241,187,131,221,160,4,327,0,149,124,216,2
Dehradun,400,495,462,423,320,474,379,34,299,202,60,364,488,358,256,442,298,12,672,0,356,248,376,4
Faridabad,461,386,481,442,309,507,622,32,309,205,54,379,436,347,260,435,311,4,635,0,352,253,401,5
Ghaziabad,198,137,201,169,137,173,285,4,118,54,28,116,220,129,128,207,130,1,306,0,93,89,92,2
Gorakhpur,230,256,211,224,160,235,169,32,144,88,1,192,229,190,128,216,162,2,348,0,174,128,242,2
Guntur,235,224,235,220,160,253,168,20,140,108,31,182,246,176,129,218,163,3,332,0,174,128,199,2
Haridwar,229,236,222,212,158,248,155,13,142,92,0,171,237,155,128,218,147,3,334,0,148,126,179,2
Indore,229,218,214,207,160,248,166,13,138,87,30,185,227,153,129,218,157,2,346,0,172,128,207,4
Jaipur,816,1002,846,780,627,757,1020,63,585,427,108,695,918,601,504,867,631,7,1406,0,613,493,900,10
Jalandhar,225,225,216,188,160,234,186,12,147,100,26,185,213,156,128,222,161,4,340,0,144,126,155,2
Kalamassery,245,329,265,222,160,252,234,32,155,113,30,193,222,192,129,220,171,4,488,0,180,127,409,34
Kanpur,230,278,226,223,160,237,209,32,150,88,1,192,234,192,128,219,162,2,394,0,175,128,289,2
Kharar,222,244,229,185,155,240,254,14,149,94,27,154,218,122,122,212,155,3,316,0,171,124,140,57
Kochi,474,491,425,420,314,492,475,39,300,201,60,336,436,350,252,438,319,39,677,0,356,249,330,53
Kolkata,1166,1240,1271,1175,954,1363,1428,77,769,541,180,978,1245,1031,756,1311,947,19,2002,0,708,760,1229,66
Kota,227,232,196,225,160,201,210,5,141,88,26,192,247,174,128,219,164,1,330,0,173,128,214,2
Kurukshetra,237,289,246,224,160,253,235,32,170,97,0,193,237,191,128,220,179,3,381,0,148,128,265,2
Ludhiana,461,441,419,405,320,467,374,28,285,196,54,372,395,303,260,440,319,0,657,0,348,254,354,5
Madurai,230,247,240,189,157,238,162,12,140,97,28,178,195,152,130,217,159,1,327,0,168,124,191,2
Mohali,222,243,231,183,155,239,252,15,149,92,27,158,218,118,122,213,153,3,330,0,172,122,143,58
Mumbai,6159,6673,5408,5300,4027,6281,7928,501,3667,2728,760,4016,5778,4162,3196,5505,3837,91,10239,0,4247,3118,4793,1373
Panchkula,445,389,381,336,320,405,392,9,269,178,55,374,292,262,259,419,314,2,584,0,337,254,289,4
Prayagraj,231,267,213,223,160,241,145,32,156,87,1,192,208,169,128,219,162,4,392,0,176,128,242,4
Pune,2133,2225,2201,1835,1412,2059,2440,153,1299,737,245,1455,1954,1140,1155,1954,1374,21,3094,0,1544,1099,2234,230
Rajkot,454,453,438,450,319,500,370,36,282,200,60,373,500,345,262,429,320,6,672,0,288,256,451,4
Sankhol,221,114,166,160,144,171,168,3,87,81,0,161,83,103,131,215,157,0,269,0,108,108,103,0
Surat,453,589,467,405,320,485,382,45,302,223,60,333,470,295,254,428,325,6,790,0,338,253,451,7
Thane,250,343,240,196,158,224,258,32,156,114,30,189,205,171,126,217,177,4,465,0,172,127,263,1
Thrippunithura,225,192,183,166,156,207,132,3,129,73,30,140,150,145,124,219,148,3,252,0,172,119,125,2
Tumakuru,234,245,236,223,160,252,280,32,141,103,31,191,243,192,131,220,161,3,329,0,180,128,271,2
Udaipur,227,264,228,221,160,207,201,32,143,107,27,191,227,170,129,216,162,6,368,0,171,128,225,2
Vadodra,229,227,215,217,158,253,231,11,141,88,30,188,243,172,128,217,163,2,323,0,176,128,187,3
Vellore,240,256,244,224,160,243,191,28,146,112,29,192,228,178,132,219,164,2,363,0,177,128,278,2
Vijayawada,472,474,455,413,320,495,341,51,278,178,61,371,489,366,260,432,326,4,656,0,355,255,432,4
Vrindavan,226,161,188,178,160,225,40,4,119,87,0,173,182,138,134,212,154,2,285,0,163,128,148,2

In [16]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals]"
1,Baby Care,"[Baby Care, Dairy, Bread & Eggs, Packaged Food, Pharma & Wellness, Stationery & Books, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Breakfast & Sauces, Cold Drinks & Juices, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food]"
6,Munchies,"[Biscuits, Masala, Dry Fruits & More, Munchies, Packaged Food]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Pharma & Wellness, Skincare]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Frozen Food, Ice Creams & More, Munchies, Packaged Food, Sweet Cravings]"

In [17]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No    Yes  Total  Out_of_stock_%
city
Mumbai                     62914  36873  99787           36.95
Kharar                      2353   1254   3607           34.77
Vijayawada                  4950   2538   7488           33.89
Madurai                     2499   1085   3584           30.27
Thane                       2949   1169   4118           28.39
Kolkata                    15480   5736  21216           27.04
Mohali                      2710    908   3618           25.10
Guntur                      2827    919   3746           24.53
Kochi                       5757   1769   7526           23.51
Udaipur                     2922    890   3812           23.35
Chennai                    20017   6060  26077           23.24
Faridabad                   5925   1701   7626           22.31
Indore                      2848    790   3638           21.72
Jaipur                     11639   3037  14676           20.69
Hyderabad                  49765  12514  62279           20.09
Coimbatore                  8668   2151  10819           19.88
Ambala                      2986    683   3669           18.62
Kalamassery                 3588    818   4406           18.57
Ahmedabad                  14858   3381  18239           18.54
Ludhiana                    5838   1319   7157           18.43
Haridwar                    2902    653   3555           18.37
Amritsar                    3182    715   3897           18.35
Gorakhpur                   3076    687   3763           18.26
Pune                       27980   6013  33993           17.69
Chandigarh                  5688   1221   6909           17.67
Bangalore                  68972  14720  83692           17.59
Rajkot                      6163   1305   7468           17.47
Davanagere                  3133    656   3789           17.31
Chhatrapati Sambhajinagar   3036    629   3665           17.16
Kota                        3054    629   3683           17.08
Kanpur                      3276    675   3951           17.08
Ghaziabad                   2508    509   3017           16.87
Dehradun                    6173   1249   7422           16.83
Surat                       6407   1274   7681           16.59
Jalandhar                   2991    564   3555           15.86
Vellore                     3321    615   3936           15.62
Vadodra                     3178    552   3730           14.80
Agra                        3279    552   3831           14.41
Prayagraj                   3241    539   3780           14.26
Bareilly                    3131    466   3597           12.96
Kurukshetra                 3518    500   4018           12.44
Tumakuru                    3568    420   3988           10.53
Panchkula                   5974    595   6569            9.06
Thrippunithura              2849    246   3095            7.95
Vrindavan                   2867    242   3109            7.78
Sankhol                     2627    126   2753            4.58

In [18]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag        No    Yes  Total  Out_of_stock_%
department
Personal Care         57935  19205  77140           24.90
Baby Care             54930  17787  72717           24.46
Bakery & Biscuits     31475  10033  41508           24.17
Dairy & Breakfast     45596  14053  59649           23.56
Cold Drinks & Juices  36952  11199  48151           23.26
Beauty & Cosmetics    71442  19768  91210           21.67
Organic & Premium     46971  12802  59773           21.42
Atta, Rice & Dal      17281   4486  21767           20.61
Sweet Tooth           32960   7950  40910           19.43
Munchies              22045   4664  26709           17.46

In [19]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No    Yes  Total  Out_of_stock_%
category
Zepto Cafe                   611   2279   2890           78.86
Electronics & Appliances    1702   1059   2761           38.36
Dairy, Bread & Eggs        24773  10967  35740           30.69
Pharma & Wellness            295    129    424           30.42
Fragrances & Grooming       9440   4093  13533           30.24
Baby Care                  26389   9630  36019           26.74
Makeup & Beauty            16714   5713  22427           25.47
Feminine Hygiene           15390   5167  20557           25.13
Biscuits                   22114   6658  28772           23.14
Toys & Sports              25219   7504  32723           22.93
Sweet Cravings             18288   5106  23394           21.83
Skincare                   41064  11356  52420           21.66
Cold Drinks & Juices       25732   7076  32808           21.57
Atta, Rice, Oil & Dals     26021   7116  33137           21.47
Hair Care                  19040   5063  24103           21.01
Bath & Body                26116   6547  32663           20.04
Ice Creams & More          25093   6281  31374           20.02
Munchies                   24926   5846  30772           19.00
Packaged Food              17776   4153  21929           18.94
Masala, Dry Fruits & More  14336   3344  17680           18.91
Breakfast & Sauces         18571   3659  22230           16.46
Tea, Coffee & More         14780   2680  17460           15.35
Frozen Food                 3187    521   3708           14.05
Stationery & Books            10      0     10            0.00

In [20]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
157,Mumbai,f6080683-4654-4500-ba97-74aafe1e2019,17,2757,2774,99.39
154,Mumbai,e92b6e46-2f9f-46b5-99ab-56d2db0a90a6,1074,2493,3567,69.89
130,Mumbai,2c911eaa-a276-47bc-92d8-447d166f2dfa,1128,2260,3388,66.71
135,Mumbai,5223893f-f150-4fb3-9f8b-2e86a7c15af1,512,844,1356,62.24
111,Kolkata,5d94bdb2-32fe-42f1-bc68-732d1d7ccb11,382,439,821,53.47
138,Mumbai,71ca681c-6ee4-467d-9d0a-8d761ce8400f,1642,1589,3231,49.18
144,Mumbai,960c0c9b-3602-42c5-bea7-b9f8a737e68f,1609,1412,3021,46.74
158,Mumbai,f9e3aef6-a8b9-4bb4-9177-a7ca316dfd71,1913,1577,3490,45.19
192,Vijayawada,456f820f-097c-49b2-8b2b-8f9dc11addd3,2243,1540,3783,40.71
139,Mumbai,74aa405e-238e-4103-abb3-096bd7e6f553,1854,1270,3124,40.65
142,Mumbai,8988d40f-12d3-42d5-9a8e-243712f8e37f,2207,1497,3704,40.42
124,Mumbai,0e8c4509-c9cd-4235-9da5-18fbede8ce72,574,389,963,40.39
185,Thane,95d6c1a2-b071-4cf3-a322-30b5754d7cb6,756,488,1244,39.23
140,Mumbai,84e7185d-375b-4386-ad42-ae55139e9e0f,2117,1314,3431,38.30
126,Mumbai,178dbe40-5ad9-4ddf-99ec-18192cb71db7,2172,1342,3514,38.19
123,Mumbai,01185b5e-b794-4cfb-99c9-625397e548ac,2164,1257,3421,36.74
115,Kolkata,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,2237,1290,3527,36.57
159,Mumbai,fab4fc54-b957-4a4b-9e1b-eb5642c9e224,2114,1212,3326,36.44
107,Kharar,856f5f52-8b1c-4089-b242-6c5dd371777e,2353,1254,3607,34.77
49,Chennai,198b7ff3-353f-4735-bf3f-75b180544478,2345,1247,3592,34.72
167,Pune,559d99e4-56b4-4659-9022-07abdf9329b2,689,360,1049,34.32
141,Mumbai,884a853d-1386-4114-a4eb-d60cc898406f,2378,1238,3616,34.24
132,Mumbai,329deb14-183d-4581-90eb-8c40a5e91fd5,2461,1272,3733,34.07
143,Mumbai,8a278c72-1366-4926-b81e-ecc6e64df2a7,719,360,1079,33.36
92,Hyderabad,de95e00b-0ebf-4f65-8f27-df66fd91dc13,683,340,1023,33.24
129,Mumbai,238a227d-697c-4fa9-a4f5-4fd064760098,2175,1061,3236,32.79
146,Mumbai,ab5b8567-c808-4008-8793-b83489a3c6fa,2114,1028,3142,32.72
150,Mumbai,d390ee2b-1c8f-4236-9c8b-b60173fd330a,2216,1069,3285,32.54
110,Kolkata,547ab61d-8d0e-47b5-a5b4-82952f43e814,2338,1077,3415,31.54
80,Hyderabad,77acda94-75cc-4146-952c-813f5bd745dd,2541,1130,3671,30.78
136,Mumbai,5f267ad5-446b-4a8b-86f0-df174ad545dd,2381,1054,3435,30.68
168,Pune,60252717-a8c5-4891-9b23-3db778b14477,1548,681,2229,30.55
121,Madurai,bbac9ca2-197d-4500-b9d8-20ecea9d1a81,2499,1085,3584,30.27
160,Mumbai,fec59a85-00e2-4551-a354-869500f18e23,1554,670,2224,30.13
50,Chennai,27f14bc8-3989-446f-b877-52a87b4f39fb,2560,1053,3613,29.14
125,Mumbai,102af115-4cad-419f-9bd5-567159eefc5c,2366,949,3315,28.63
156,Mumbai,ebabbe83-2299-49ca-bbd8-edfd8dd03d60,2567,1025,3592,28.54
116,Kolkata,cd098e80-d516-4508-b4fc-3d7f10461033,2445,956,3401,28.11
72,Hyderabad,13ffc117-24d6-4854-a53e-a51d7330973e,2351,915,3266,28.02
145,Mumbai,a5d48a70-31d9-4c5f-b61f-daae4ab4e3b3,2385,925,3310,27.95
137,Mumbai,684a75ae-c944-480c-a64f-76a1a9cfa393,2127,818,2945,27.78
131,Mumbai,2d89c87c-884c-41c3-89bb-12f9dcddc03f,2385,893,3278,27.24
191,Vijayawada,308d5afe-f44d-443b-ab47-5f6e43f3fcbd,2707,998,3705,26.94
148,Mumbai,badfd8b4-f39a-41ec-8f0a-4f86184f0953,1030,379,1409,26.90
155,Mumbai,eb92685d-4aad-4424-b38f-f876e41640a8,1006,365,1371,26.62
33,Bangalore,a1cbdf77-8824-4c12-85b4-3b114318497d,2186,790,2976,26.55
81,Hyderabad,7ed513e4-0a4c-453d-9446-7ab609bafdbf,2344,846,3190,26.52
108,Kochi,4a23af0e-df8c-46c5-a68f-78fe1e0909f3,2759,983,3742,26.27
34,Bangalore,a7860f3d-39d4-4275-811d-904d4c2438f4,1063,372,1435,25.92
61,Coimbatore,7c110981-0c36-40b5-bb49-0747b65c619d,2886,997,3883,25.68
52,Chennai,49e487f6-07bf-48f9-b379-203f76c11964,2573,883,3456,25.55
102,Jaipur,e4a1792d-8ffa-4015-a415-e91fe2f01493,2753,936,3689,25.37
122,Mohali,1fe58380-341b-4509-b712-a66f5aea2e86,2710,908,3618,25.10
95,Hyderabad,e9c206f4-5e36-40ea-9d34-071b0c016be3,2785,930,3715,25.03
40,Bangalore,c30df9f0-06c1-4d33-97ff-10ed99190a4d,2700,888,3588,24.75
82,Hyderabad,83e33858-a13f-4c67-a016-07de0cce8043,2452,801,3253,24.62
21,Bangalore,4f54ea62-0269-4b93-87cd-ef7ed796c6b1,485,158,643,24.57
70,Guntur,f39c8468-8ad4-41c4-b159-1b0d9a2d0a6f,2827,919,3746,24.53
51,Chennai,3054cc18-1476-426c-a67b-51028bd50319,1952,616,2568,23.99
66,Faridabad,3d277bf6-7a5f-498a-a956-56fd8ab9ef82,2893,902,3795,23.77
30,Bangalore,97301572-98d1-4b4d-8e40-d52748fe5233,2453,765,3218,23.77
184,Thane,89644478-a004-4d2c-a04d-ced0f26ede4f,2193,681,2874,23.70
19,Bangalore,3bf7d17f-4fa3-481d-b14d-66ca5c4f14da,1096,337,1433,23.52
188,Udaipur,29d47abc-4861-444d-baf6-b32eb28f98a6,2922,890,3812,23.35
98,Jaipur,32989280-a610-4395-aca5-5ba4823af4bd,2878,872,3750,23.25
38,Bangalore,b1403534-cd6b-49d0-a7cd-ce20e6497768,2007,608,2615,23.25
127,Mumbai,2050a7de-e13c-4947-bac7-7995d8c6e72d,2520,737,3257,22.63
2,Ahmedabad,885c5a49-6ecc-47fa-ac1e-87310b08de65,2835,816,3651,22.35
114,Kolkata,a935152c-9baa-46c1-b2ac-37701a227a19,2586,739,3325,22.23
56,Chennai,6ed3a9c3-c895-4156-be65-4643c5f91b0f,2488,707,3195,22.13
112,Kolkata,74039f14-48e6-4a32-b70f-7ddda4c42900,2695,759,3454,21.97
97,Indore,6cb7f877-c543-4be9-8c74-5fd19956f937,2848,790,3638,21.72
60,Coimbatore,02e94766-b296-4233-b2ec-4989686163ec,2916,806,3722,21.66
134,Mumbai,3b18ee5e-9d22-44cd-acff-646042e546bf,963,266,1229,21.64
85,Hyderabad,8dcc9bd0-fb05-42e9-96c7-ef15a999c522,934,257,1191,21.58
90,Hyderabad,cdbf7442-0998-4c3d-b6a4-cf8c41efed5f,92,25,117,21.37
152,Mumbai,e278914b-34ce-4bd8-a961-1a4456c620cc,946,254,1200,21.17
67,Faridabad,6a871d62-f77e-41ca-bd6e-b9754de4a90b,3032,799,3831,20.86
109,Kochi,f640034b-60ca-4426-8b7b-edcf408846ec,2998,786,3784,20.77
170,Pune,931f1ec1-e287-4412-9b52-df3f8ab9c95c,954,250,1204,20.76
39,Bangalore,b4dc8d65-ed2e-4142-81b6-373982b13500,2423,634,3057,20.74
26,Bangalore,6abd3309-1e45-4411-943a-81f5c32fef41,2506,655,3161,20.72
176,Pune,f68f6daf-2bba-450e-9a05-082e29e9129d,2611,681,3292,20.69
77,Hyderabad,5ca7734d-e625-4328-8588-a4a102966b36,2591,665,3256,20.42
22,Bangalore,5400933d-3c5d-4015-a767-daed27781a0d,2513,637,3150,20.22
175,Pune,dd520c1a-80de-4060-9e8a-7b2156223efe,2803,696,3499,19.89
151,Mumbai,dd0aebf0-fb91-4644-bf64-5ac156a4b57f,967,239,1206,19.82
1,Ahmedabad,6e46b50c-08d0-49c8-a89a-4d29ce4ed370,2919,721,3640,19.81
105,Kalamassery,8a71c5dd-fc7e-42e0-b56d-7d3b7df30187,693,171,864,19.79
91,Hyderabad,d71ff3ac-0dbd-43de-bf48-6a1b0ba17c12,864,213,1077,19.78
64,Dehradun,06bc0cca-b09b-4c18-b6c5-8358f91c7201,2982,734,3716,19.75
46,Chandigarh,809ea1fc-cf81-4257-b2b5-7d53a911cae0,2947,706,3653,19.33
14,Bangalore,1d852498-590f-4ffa-babf-aae026e3584d,2594,611,3205,19.06
119,Ludhiana,2a607d6c-27cf-4475-a804-e99a363919c4,2826,656,3482,18.84
179,Rajkot,836c17f0-d2b2-4ec1-9a02-5365d6cac742,3065,709,3774,18.79
75,Hyderabad,4c93e224-40da-4c86-a5ff-c9c2cfee1168,953,220,1173,18.76
76,Hyderabad,5afbd13c-b8be-4b40-a643-b0322e48117e,2715,626,3341,18.74
83,Hyderabad,8c84e7ae-6e94-48f2-b4c8-af6c199aef1b,2763,635,3398,18.69
12,Bangalore,0c02c311-65e5-4495-bcb4-ee96476882bb,2569,588,3157,18.63
7,Ambala,7a6201d1-93ae-4a45-bdb1-fbf73c1255a8,2986,683,3669,18.62
100,Jaipur,c4bf6cd0-029d-4266-b96e-44f8db888e4c,2467,560,3027,18.50
5,Ahmedabad,e8906fc6-3925-4713-bca4-3388408415d9,3030,684,3714,18.42
71,Haridwar,b9bb6846-a7b6-423a-8c44-5b35c3ba8745,2902,653,3555,18.37
8,Amritsar,848af961-1a54-410e-b220-59a42507d39a,3182,715,3897,18.35
104,Kalamassery,74eedd8a-1705-46c3-8dd3-bbfcc0289ec3,2895,647,3542,18.27
48,Chennai,166f8ba8-c333-4c60-9d12-faeab29ac22c,1069,239,1308,18.27
69,Gorakhpur,3a410c47-9ebf-410e-8c86-c68c3fafab29,3076,687,3763,18.26
93,Hyderabad,e052e083-dbfe-4156-a86e-e2fd848f8c3e,959,214,1173,18.24
54,Chennai,6940d67b-8f25-4a93-a0b1-9bad67479c03,700,155,855,18.13
55,Chennai,6e16ae4d-592d-4017-a51c-37c7d85989e0,77,17,94,18.09
120,Ludhiana,9fb7a7ca-e61c-4904-b339-749b6b45bf09,3012,663,3675,18.04
18,Bangalore,37531a1f-495c-4f67-bd1e-e3a6158fbf10,2567,559,3126,17.88
89,Hyderabad,aed3e474-bd2f-4577-bd79-b74b53ce9e4e,2680,575,3255,17.67
174,Pune,db4ee2ab-1f56-4e37-9969-3407620c48f5,2707,580,3287,17.65
3,Ahmedabad,be8c29f7-cb07-48e2-8239-5df581ba541b,2846,607,3453,17.58
10,Bangalore,044a06cd-5792-44a6-be6b-d5747683349b,2653,566,3219,17.58
78,Hyderabad,67ec5278-78c4-4654-b67d-c0433f5406c7,2575,547,3122,17.52
32,Bangalore,9eebbbc9-3fb9-45c1-ab71-312606cf9852,2612,553,3165,17.47
182,Surat,a08faf0a-3921-4ebd-a076-a551e2a9c91d,2999,635,3634,17.47
9,Bangalore,0059ff6a-7eb0-477a-a7f5-69256f2c444b,1157,244,1401,17.42
181,Surat,2918790f-421a-493e-84a3-e9a2d8f0b60d,496,104,600,17.33
63,Davanagere,a3cc5aa4-5a26-4b97-90f9-e38e7be0685b,3133,656,3789,17.31
59,Chhatrapati Sambhajinagar,3d1b28be-1e25-471f-a4d9-f2151a7d1bfc,3036,629,3665,17.16
177,Pune,f931724a-0140-4c06-b832-027e03fc320a,999,206,1205,17.10
117,Kota,bf18569a-7111-4e13-b389-edf020a1218d,3054,629,3683,17.08
106,Kanpur,8b5992ad-b397-4fdb-be52-0d780c7cc501,3276,675,3951,17.08
36,Bangalore,abd85a95-f3f3-42fd-aeb0-71b9127335f5,1096,223,1319,16.91
68,Ghaziabad,e85e67f1-ab37-4e67-be93-1a2d5ab95185,2508,509,3017,16.87
94,Hyderabad,e096acfe-3139-4927-b2c8-f36e3587fcf8,981,198,1179,16.79
15,Bangalore,2614cabb-fff2-4ef6-aa5b-e94c2b875880,1267,255,1522,16.75
4,Ahmedabad,e677968e-5901-4ff2-8613-ebd72359a67c,449,90,539,16.70
79,Hyderabad,6893b298-d63b-4c4f-b155-2e4a0ca502d5,2731,544,3275,16.61
58,Chennai,c8f9f22d-b083-4eb1-894d-47b4daeeb2b5,2584,514,3098,16.59
164,Pune,04b8b5aa-15dd-49f9-ada0-df4d94f119a4,2751,545,3296,16.54
86,Hyderabad,a466fff3-62f1-4065-bfab-4ed019c39afc,2757,545,3302,16.51
28,Bangalore,774a725c-2c4b-4dc2-94d1-72b737f7e1f6,1115,218,1333,16.35
169,Pune,8c4a9155-85ec-409f-a9d8-84b193ec06ad,1041,203,1244,16.32
165,Pune,2c5f4d5e-e4b5-40d2-9230-d35756cfd601,2594,501,3095,16.19
88,Hyderabad,ad87f09e-6b7e-40d4-99e7-2776aaf587a1,2806,540,3346,16.14
178,Rajkot,64ad2a25-3ff0-4a5a-b168-6b1593e38467,3098,596,3694,16.13
101,Jaipur,d15971f7-4774-4119-badc-8c239a0b88ca,2892,549,3441,15.95
103,Jalandhar,adff0588-4405-4d2c-ba0f-059a9e563839,2991,564,3555,15.86
47,Chandigarh,ce51ee77-3c09-4d9f-9c98-558809e0c0e4,2741,515,3256,15.82
190,Vellore,8ee2719c-97ed-44a2-a32e-7dceac0a7e55,3321,615,3936,15.62
99,Jaipur,8ec659c9-2faa-4eba-ba2e-158ae485ebb4,649,120,769,15.60
183,Surat,ebc8fa1c-02ba-4a0a-a544-0854ce8beead,2912,535,3447,15.52
53,Chennai,5a9291a1-3743-44ad-9c10-9d458d5b6325,2527,462,2989,15.46
96,Hyderabad,fc88e94a-f4b7-4eab-8ce0-fdecf2e29d5f,1030,187,1217,15.37
128,Mumbai,21db1e24-d6a7-484a-b5aa-b43e1aafb8fc,984,178,1162,15.32
73,Hyderabad,29f978f1-5bc3-4358-a811-4b817ebebfcb,2695,487,3182,15.30
37,Bangalore,afc14c75-c874-46d8-9877-e66bfa0c7299,2627,470,3097,15.18
35,Bangalore,a7c548c8-f8e5-41c6-9462-1b4d7e8de41e,1156,205,1361,15.06
16,Bangalore,2fc208e2-13ec-407a-b947-51c8fe777f71,2734,480,3214,14.93
25,Bangalore,658cf319-0b10-4dbe-809e-ea5c913974cb,1166,204,1370,14.89
189,Vadodra,e5eedfad-51fc-488d-9061-f56ebaed8440,3178,552,3730,14.80
74,Hyderabad,43b12c97-dc99-431a-9ba3-e3cde9c716bb,2744,476,3220,14.78
20,Bangalore,49879539-9538-42ca-b59e-952cdd73b506,1147,199,1346,14.78
27,Bangalore,76cae5a0-b75d-456b-9aab-df0b0b7559c2,1183,205,1388,14.77
42,Bangalore,e749e734-9e20-4090-b5c3-a66ed53b5e23,2727,470,3197,14.70
113,Kolkata,77e44380-aa2a-4eeb-b923-24c653aa6732,2797,476,3273,14.54
41,Bangalore,e0e12ce6-3431-4ed8-a74b-b0de26426220,2624,445,3069,14.50
84,Hyderabad,8d94ae95-db29-44f7-b705-d533f7c66176,1056,178,1234,14.42
0,Agra,805ea004-3262-4094-9df6-0b87ad6d1476,3279,552,3831,14.41
31,Bangalore,992bee8f-8936-4b04-9d17-546cd0ba1b76,1145,192,1337,14.36
6,Ahmedabad,f0700405-c162-4855-8b39-3a75fe3a9d35,2779,463,3242,14.28
133,Mumbai,3608083a-c098-4f58-bc13-4a729a103909,1003,167,1170,14.27
163,Prayagraj,a704a05d-0f16-42da-a511-627c9f613d33,3241,539,3780,14.26
147,Mumbai,b26ca2be-f12b-4645-a83a-adf09ecfd28b,1010,167,1177,14.19
153,Mumbai,e5319547-8bba-4fee-862c-7d9ab6dc97c8,970,159,1129,14.08
65,Dehradun,2607025a-3900-4f19-a9b9-d158be8b4858,3191,515,3706,13.90
13,Bangalore,1ba2b8e0-aa82-4a78-b38b-477b97eac054,2614,418,3032,13.79
44,Bangalore,eacc5aad-4e93-4266-8cde-bee3b70926a8,1162,185,1347,13.73
29,Bangalore,843e630a-7896-462d-b7cf-712140483ed3,1139,181,1320,13.71
171,Pune,9ede85f3-c387-40b0-a6c7-fa07f64da718,2753,432,3185,13.56
87,Hyderabad,a98b17a7-c155-4e4e-8b87-bfb5ac1a44a2,2683,420,3103,13.54
43,Bangalore,ea49abf1-77df-4575-8022-fbcf9e25b3b4,2628,411,3039,13.52
149,Mumbai,c8140214-bf94-42c0-8f7f-ea6767170196,2590,387,2977,13.00
45,Bareilly,ea4957dd-2004-479b-8817-569aa932f824,3131,466,3597,12.96
57,Chennai,7732ead5-8482-4815-9559-7f4cb2a72f3e,1142,167,1309,12.76
11,Bangalore,055af6e1-5726-4e98-84fa-2ce7da4d382d,1214,175,1389,12.60
118,Kurukshetra,77f731b8-a268-437a-b89c-7356dda3e298,3518,500,4018,12.44
166,Pune,3516f4f6-dec8-4e36-abb0-77f26d0f4a16,2719,373,3092,12.06
172,Pune,ac91c141-986b-4bb1-9bb8-5b0be08b65de,1067,145,1212,11.96
17,Bangalore,3123bc8b-6f8b-4eab-828e-5715162320e5,2692,362,3054,11.85
161,Panchkula,68072b30-73d7-493c-8d6f-a61998fba1d8,2964,393,3357,11.71
173,Pune,c014a827-2aa9-4e90-ae1e-e5dbc8867100,2744,360,3104,11.60
62,Coimbatore,db5cae25-1e09-4b8d-8e24-7c10938265e3,2866,348,3214,10.83
23,Bangalore,5ec071fd-78df-41f6-b3ae-7298d9f96a3d,2658,321,2979,10.78
187,Tumakuru,f0fa4a29-bff9-43fa-bbbf-8c843ce7b579,3568,420,3988,10.53
24,Bangalore,6252e437-b1f6-4ea7-9062-d90fba216c6f,1294,136,1430,9.51
186,Thrippunithura,540c73ee-1fc7-43aa-a239-58f94400f241,2849,246,3095,7.95
193,Vrindavan,76c8ac24-4dc8-4419-9bae-eb904960cbcc,2867,242,3109,7.78
162,Panchkula,b916220e-7ace-4784-bdbf-a359f4411fa3,3010,202,3212,6.29
180,Sankhol,79c6102c-cce8-425f-a59a-0c74ccb9a645,2627,126,2753,4.58

In [21]:
import pandas as pd

# Ensure stock_count is numeric
df["stock_count"] = pd.to_numeric(df["stock_count"], errors="coerce")

# Normalize out_of_stock_flag
flag = df["out_of_stock_flag"].astype(str).str.strip().str.lower()

# 1. out_of_stock_flag = Yes, but stock_count > 0
yes_stock_gt0 = df[
    (flag == "yes") &
    (df["stock_count"] > 0)
]

print(f"Rows with out_of_stock_flag='Yes' but stock_count > 0: {len(yes_stock_gt0)}")
print(yes_stock_gt0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

# 2. out_of_stock_flag = No, but stock_count = 0
no_stock_0 = df[
    (flag == "no") &
    (df["stock_count"] == 0)
]

print(f"\nRows with out_of_stock_flag='No' but stock_count = 0: {len(no_stock_0)}")
print(no_stock_0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

Rows with out_of_stock_flag='Yes' but stock_count > 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

Rows with out_of_stock_flag='No' but stock_count = 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

In [22]:
import pandas as pd

# Convert price columns to numeric
price_cols = [
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]

for col in price_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Normalize discount flag
flag = df["discount_flag"].astype(str).str.strip().str.lower()

# 1. Selling Price > MRP
selling_gt_mrp = df[df["item_selling_price"] > df["item_mrp"]]

print(f"1. Selling Price > MRP : {len(selling_gt_mrp)} rows")
print(selling_gt_mrp[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price"
]])

# 2. Discount Flag = Yes but MRP == Selling Price
discount_no_difference = df[
    (flag == "yes") &
    (df["item_mrp"] == df["item_selling_price"])
]

print(f"\n2. Discount Flag = Yes but MRP == Selling Price : {len(discount_no_difference)} rows")
print(discount_no_difference[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_flag"
]])

# 3. Discount % > 100
discount_gt_100 = df[df["discount_in_percent"] > 100]

print(f"\n3. Discount % > 100 : {len(discount_gt_100)} rows")
print(discount_gt_100[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]])

1. Selling Price > MRP : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price]
Index: []

2. Discount Flag = Yes but MRP == Selling Price : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_flag]
Index: []

3. Discount % > 100 : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_in_percent]
Index: []

In [23]:
import re

# Normalize brand names
df["brand_norm"] = (
    df["brand_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
brand_issue = (
    df.groupby("brand_norm")
    .agg(
        variant_count=("brand_name", "nunique"),
        brand_variants=("brand_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

brand_issue = brand_issue[brand_issue["variant_count"] > 1]

brand_issue

,brand_norm,variant_count,brand_variants
206,bonn,2,"[Bonn, bonn]"
210,borges,2,"[BORGES, Borges]"
376,delichic,2,"[Deli Chic, Delichic]"
770,kharifoods,2,"[KHARI FOODS, Khari Foods]"
1050,noto,2,"[NOTO, Noto]"
1126,paperboat,2,"[PAPER BOAT, Paper Boat]"
1139,patanjali,2,"[PATANJALI, Patanjali]"
1173,plixtheplantfix,2,"[Plix -The Plant Fix, Plix The Plant Fix]"
1384,star,2,"[STAR, Star]"
1418,sunscoop,2,"[SunScoop, Sunscoop]"
1587,vijay,2,"[VIJAY, Vijay]"

In [24]:
import re

# Normalize brand names
df["productname_norm"] = (
    df["product_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
name_issue = (
    df.groupby("productname_norm")
    .agg(
        variant_count=("product_name", "nunique"),
        name_variants=("product_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

name_issue = name_issue[name_issue["variant_count"] > 1]

name_issue

,productname_norm,variant_count,name_variants
45,4700bccheesepopcornjumbosizezeropalmoil,2,"[4700BC Cheese Popcorn | Jumbo Size | Zero Palm Oil, 4700BC Cheese Popcorn | Jumbo Size,Zero Palm Oil]"
378,altcooatmilknzs1,2,"[Alt Co. Oat Milk nzs 1, Alt Co. Oat MilkN Z S 1]"
507,amulgoldtriconechocolateicecreamcone,2,"[Amul Gold TriCone Chocolate Ice Cream Cone, Amul Gold TriCone Chocolate Ice Cream Cone.]"
624,amulshaktifreshmilkpouch,2,"[Amul Shakti Fresh Milk (Pouch), Amul Shakti Fresh Milk | Pouch]"
707,andaahnaturalwhiteeggs,2,"[Andaah Natural White Eggs, Andaah Natural+ White Eggs]"
999,babiqueoctopussittingplushsofttoycutekidsanimalhomedecorboysgirls17cm,2,"[Babique Octopus Sitting Plush Soft Toy Cute Kids Animal Home Decor Boys/Girls (17 cm), Babique Octopus Sitting Plush Soft Toy Cute Kids Animal Home Decor Boys/Girls | 17 cm]"
1029,babysebamedgentlewashph55babybodywashsoapfreetearfree,2,"[Baby Sebamed Gentle Wash | pH 5.5 | Baby Body Wash | Soap Free | Tear Free, Baby Sebamed Gentle Wash | pH 5.5 | Baby Body Wash | Soap Free| Tear Free]"
1080,bakersloafzeropreservativesmultigrainbread,2,"[Baker's Loaf Zero Preservatives Multigrain Bread, Baker's Loaf- Zero Preservatives Multigrain Bread]"
1081,bakersloafzeropreservativeswholewheatbread,2,"[Baker's Loaf - Zero Preservatives Whole Wheat Bread, Baker's Loaf Zero Preservatives Whole Wheat Bread]"
1367,beyondsnackkeralabananachipsperiperi,2,"[Beyond Snack Kerala Banana Chips | Peri Peri, Beyond Snack Kerala Banana chips | Peri Peri]"
1378,bhagirathipremiummpsharabatiatta,2,"[Bhagirathi Premium MP Sharabati Atta, Bhagirathi Premium Mp Sharabati Atta]"
1525,bisleripackageddrinkingwater,2,"[Bisleri Packaged Drinking Water, Bisleri Packaged Drinking Water.]"
1718,bombayshavingcompanypostshavebalm,2,"[Bombay Shaving Company Post Shave Balm, Bombay Shaving Company Post-Shave Balm]"
1794,braunsilkepilatorse3031forlonglastinghairremovalfromrootswhitepink,2,"[Braun Silk Epilator Se 3031 For Long-Lasting Hair Removal From Roots,White & Pink, Braun Silk Epilator Se 3031 For Long-Lasting Hair Removal From Roots,White & Pink.]"
1911,britanniatreatrichcremeorangeflavouredwafers,2,"[Britannia Treat Rich Creme Orange Flavoured Wafers, Britannia Treat Rich Creme Orange Flavoured Wafers ..]"
1919,britanniavitarichsandwichpremiumwhitebread,2,"[Britannia Vita Rich Sandwich Premium White Bread, Britannia Vitarich Sandwich Premium White Bread]"
2032,cadburychoclayeredcakeminionpack,2,"[Cadbury Choc Layered Cake Minion Pack, Cadbury Choc Layered Cake Minion pack]"
2100,carmesidisposableperiodpantiesallnightprotectionxlxxl,2,"[Carmesi Disposable Period Panties | All Night Protection | XL-XXL, Carmesi Disposable Period Panties | All-Night Protection | XL-XXL]"
2166,cetaphilbabywashshampoowithorganiccalendula,2,"[Cetaphil Baby Wash & Shampoo With Organic Calendula, Cetaphil Baby Wash & Shampoo with Organic Calendula]"
2177,cetaphildamdailyadvanceultrahydratinglotion,2,"[Cetaphil DAM Daily Advance Ultra Hydrating Lotion, Cetaphil Dam Daily Advance Ultra Hydrating Lotion]"
2425,cintholsandalfoambodywashsuitableforallskintypes,2,"[Cinthol Sandal Foam Body Wash - Suitable for All Skin Types, Cinthol Sandal Foam Body Wash | Suitable for All Skin Types]"
2458,cleananddryintimatewash,2,"[Clean And Dry Intimate Wash, Clean and Dry Intimate Wash]"
2461,cleanclearfoamingfacewash,2,"[Clean & Clear Foaming Face Wash, Clean & Clear Foaming Facewash]"
2519,colgatekids2yearsextrasofttoothbrush,2,"[Colgate Kid's 2+ Years Extra Soft Toothbrush, Colgate Kids 2+ Years Extra Soft Toothbrush]"
2534,colgatemaxfreshplaxmouthwashfreshmint,2,"[Colgate Max Fresh Plax Mouthwash - Fresh Mint, Colgate Max Fresh Plax Mouthwash Freshmint]"
2986,dailygoodalmondbadamcalifornia,2,"[Daily Good Almond - Badam | California, Daily Good Almond / Badam | California]"
2996,dailygoodblackpepperkalimirch,2,"[Daily Good Black Pepper - Kali Mirch, Daily Good Black Pepper / Kali Mirch]"
3037,dailygoodidlyanddosabatter,2,"[Daily Good - Idly And Dosa Batter, Daily Good Idly And Dosa Batter]"
3110,dailygoodsaunffennel,2,"[Daily Good Saunf - Fennel, Daily Good Saunf / Fennel]"
3143,dailygoodunpolishedtoorturarhardal,2,"[Daily Good Unpolished Toor - Tur - Arhar Dal, Daily Good Unpolished Toor | Tur | Arhar Dal]"
3329,delmontepineappleslices,2,"[Del Monte Pineapple - Slices, Del Monte Pineapple Slices]"
3411,dettolskincarehandwashrefillmoisturizinghandwashphbalancegentleonskin,2,"[Dettol Skincare Hand Wash Refill | Moisturizing Handwash | pH Balance | Gentle on Skin, Dettol Skincare Handwash Refill | Moisturizing Handwash | pH Balance | Gentle on Skin]"
3818,eggoneggsgradeaeggs,2,"[Egg On Eggs Grade A Eggs, Egg On Eggs Grade-A Eggs]"
4034,epigamiagreekyogurtnaturalcombo,2,"[Epigamia Greek Yogurt- Natural Combo, Epigamia Greek Yogurt- Natural | Combo]"
4291,facescanadastrobecreamrosegoldprimerhighlightermoisturizer,2,"[FACES CANADA Strobe Cream - Rose Gold | Primer + Highlighter + Moisturizer, Faces Canada Strobe Cream | Rose Gold, Primer + Highlighter + Moisturizer]"
4295,facescanadaultimeprohdintensemattelipsprimerperfection01,2,"[Faces Canada Ultime Pro HD Intense Matte Lips + Primer - Perfection 01, Faces Canada Ultime Pro Hd Intense Matte Lips + Primer - Perfection 01]"
4440,fitnestclassicwhiteeggs,2,"[FitNest Classic White Eggs, Fitnest Classic White Eggs]"
4505,fortunekachighanimustardoilbottle,2,"[Fortune Kachi Ghani Mustard Oil Bottle, Fortune Kachi Ghani Mustard Oil | Bottle]"
4666,frubonrabrimalaikulfiicecreamstickcombo,2,"[FruBon Rabri Malai Kulfi Ice Cream Stick Combo, Frubon Rabri Malai Kulfi Ice Cream Stick Combo]"
4675,fruitchillicepopsfrozenjuicebarsmultipackmangostrawberryorangenimboogrape,2,"[Fruitchill Ice Pops/ Frozen Juice Bars Multipack- Mango, Strawberry, Orange, Nimboo, Grape, Fruitchill Ice Pops/Frozen Juice Bars Multipack- Mango, Strawberry, Orange, Nimboo, Grape]"
4679,fullbodytrimmerwith5in1magneticattachmentsformultigroomingsolutions,2,"[Full Body Trimmer With 5-in-1 Magnetic Attachments For Multi-Grooming Solutions, Full Body Trimmer With 5-in-1 Magnetic Attachments For Multi-Grooming Solutions.]"
4996,godrejjerseyspicybuttermilkpouch,2,"[Godrej Jersey Spicy Butter Milk Pouch, Godrej Jersey Spicy Buttermilk Pouch]"
5104,gozeromadovermangolowcalorieguiltfreeicecreamcup,2,"[Go Zero Mad Over Mango Low Calorie Guilt Free Ice Cream Cup, Go Zero Mad Over Mango Low Calorie Guilt Free Ice Cream Cup .]"
5116,gozeroraspberryduetlowcalorieguiltfreeicecreamstick,2,"[Go Zero Raspberry Duet Low Calorie Guilt Free Ice Cream Stick ., Go Zero Raspberry Duet Low Calorie Guilt Free Ice Cream Stick ..]"
5223,gubbtonguecleanertassorted,2,"[GUBB Tongue Cleaner T | Assorted, GUBB Tongue Cleaner T+ | Assorted]"
5337,haldiramschipsclassicsaltedcrispysalty,2,"[Haldiram's Chips Classic Salted | Crispy & Salty, Haldiram's Chips | Classic Salted | Crispy & Salty]"
5579,havells1000wvolumizerhairdryerprestylingbrushcurlersrollerbrushblackhc4085,2,"[Havells 1000W Volumizer Hair Dryer|Pre-Styling Brush, Curlers, Roller Brush|Black|Hc4085, Havells 1000W Volumizer Hair Dryer|Pre-Styling Brush, Curlers, Roller Brush|Black|Hc4085.]"
5581,havellsbrushhairstraightener50whs4201,2,"[Havells Brush Hair Straightener (50 W, HS4201), Havells Brush Hair Straightener (50 W, HS4201).]"
5612,hbbakerschoicealmondcakerusk,2,"[HB BAKERS CHOICE Almond Cake Rusk, HB Bakers Choice Almond Cake Rusk]"
5615,hbbakerschoicemawacakerusk,2,"[HB Bakers Choice Mawa Cake Rusk, hb bakers choice mawa cake rusk]"
5699,heritagefullcreamfreshmilkpouch,2,"[Heritage Full Cream Fresh Milk (Pouch), Heritage Full Cream Fresh Milk | Pouch]"
5814,himalayagentlebabysoapwith100naturalalmondoliveoilnopostbathdryness,2,"[Himalaya Gentle Baby Soap with 100% Natural Almond & Olive Oil -| No Post Bath Dryness, Himalaya Gentle Baby Soap with 100% Natural Almond & Olive Oil| No Post Bath Dryness]"
6241,insightcosmeticsnontransferliquidlipstickcoffeecommandcrueltyfree,2,"[Insight Cosmetics Non Transfer Liquid Lipstick - Coffee Command | Cruelty Free, Insight Cosmetics Non Transfer Liquid Lipstick | Coffee Command | Cruelty Free]"
6242,insightcosmeticsnontransferliquidlipstickmoltenpinkcrueltyfree,2,"[Insight Cosmetics Non Transfer Liquid Lipstick - Molten Pink | Cruelty Free, Insight Cosmetics Non Transfer Liquid Lipstick | Molten Pink | Cruelty Free]"
6347,jhalmuri,2,"[Jhal Muri, Jhalmuri]"
6681,kelloggsmueslinutsandseedscrunch12in1powerbreakfast,2,"[Kellogg's Muesli Nuts and Seeds Crunch | 12 in 1 Power Breakfast, Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast]"
7210,lalbabaricesuperiorbanskathirice,2,"[LALBABA Rice Superior Banskathi Rice, Lalbaba Rice Superior Banskathi Rice]"
7738,lovebeautyplanetonionblackseedpatchoulihairfallcontrolconditioner,2,"[Love Beauty & Planet Onion Blackseed & Patchouli Hairfall Control Conditioner, Love Beauty & Planet Onion, Blackseed & Patchouli Hairfall Control Conditioner]"
7864,luxsoftrosebodywashwithfrenchrosealmondoil,2,"[LUX Soft Rose Bodywash with French Rose & Almond Oil, Lux Soft Rose Bodywash with French Rose & Almond Oil]"
7895,maggirichtomatoketchup,2,"[MAGGI Rich Tomato Ketchup, Maggi Rich Tomato Ketchup]"
7901,maggivegattanoodlesmadewithonlyattaflour,2,"[Maggi Veg Atta Noodles Made with Only Atta Flour, Maggi Veg Atta Noodles Made with Only Atta flour]"
7974,mamaearthonionhairoilforhairfallcontrolwithonionredensyl,2,"[Mamaearth Onion Hair Oil For Hair Fall Control With Onion & Redensyl, Mamaearth Onion Hair Oil for Hair Fall Control with Onion & Redensyl]"
8607,minimalist35maleicbondrepairshampoofordamageddryfrizzyhair,2,"[Minimalist 3.5% Maleic Bond Repair Shampoo For Damaged, Dry & Frizzy Hair, Minimalist 3.5% Maleic Bond Repair Shampoo for Damaged, Dry & Frizzy Hair]"
9223,nandinigoodlifetoneduhtmilkfinopouch,2,"[Nandini Good Life Toned UHT Milk (Fino Pouch), Nandini Goodlife Toned UHT Milk (Fino Pouch)]"
9224,nandinigoodlifetoneduhtmilkfinopouchcombo,2,"[Nandini Good Life Toned UHT Milk (Fino Pouch) Combo, Nandini Goodlife Toned UHT Milk (Fino Pouch) Combo]"
9233,nandiniprocessedcheeseslices,2,"[Nandini Processed Cheese Slices, Nandini Processed Cheese- Slices]"
9439,nicalphonsomangoicecreamcupcombopreservativefreenoartificialflavors,2,"[NIC Alphonso Mango Ice Cream Cup Combo | Preservative Free | No Artificial Flavors, NIC Alphonso Mango Ice Cream Cup Combo| Preservative Free | No Artificial Flavors]"
9441,nicalphonsomangoicecreamcuppreservativefreenoartificialflavors,2,"[NIC Alphonso Mango Ice Cream Cup | Preservative Free | No Artificial Flavors, NIC Alphonso Mango Ice Cream Cup| Preservative Free | No Artificial Flavors]"
9534,niveasoftdailyuvlightmoisturisingcreamwithspf15,2,"[NIVEA Soft Daily UV Light Moisturising Cream with SPF-15, Nivea Soft Daily UV Light Moisturising Cream With SPF-15]"
9651,nutrajcaliforniaalmondbadam,2,"[Nutraj California Almond | Badam, Nutraj California Almond/Badam]"
9662,nutrajclassickalimirchblackpepperpouch,2,"[Nutraj Classic Kali Mirch (Black Pepper) - Pouch, Nutraj Classic Kali Mirch | Black Pepper - Pouch]"
9893,oralbprohealthgumcaretoothbrushmedium,2,"[Oral B Pro Health Gum Care Toothbrush Medium, Oral-B Pro Health Gum Care Toothbrush Medium]"
10130,pantenehairsciencehairfallcontrolshampoolesserhairfallwithvitaminb,2,"[Pantene Hairscience Hairfall Control Shampoo Lesser Hairfall,With Vitaminb, Pantene Hairscience Hairfall Control Shampoo, Lesser Hair Fall With Vitamin B]"
10180,parachuteadvansedbhringrajhibiscusenrichedcoconuthairoil,2,"[Parachute Advansed Bhringraj & Hibiscus Enriched Coconut Hair Oil, Parachute Advansed Bhringraj & Hibiscus-Enriched Coconut Hair Oil]"
10238,parasnandancowgheetetrapack,2,"[Paras Nandan Cow Ghee Tetra Pack, Paras Nandan Cow Ghee Tetrapack]"
10382,patanjalidantkantinaturaltoothpasteherbaloralcarefightscavitiesandgerms,3,"[Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care ,Fights Cavities and Germs, Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care, Fights Cavities and Germs, Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care,Fights Cavities and Germs]"
10450,peesafecomfortperiodpantylxl,2,"[Pee Safe Comfort Period Panty (L-XL), Pee Safe Comfort Period Panty L-XL]"
10605,philipsfemalefacetrimmerhp638800eyebrowsfacialtrimmerwhite,2,"[Philips Female Face Trimmer Hp6388/00 Eyebrows& Facial Trimmer (White), Philips Female Face Trimmer Hp6388/00 Eyebrows& Facial Trimmer (White).]"
10723,pintolaallnaturalpeanutbuttercrunchy,2,"[Pintola All Natural Peanut Butter - Crunchy, Pintola All Natural Peanut Butter Crunchy]"
10761,plixtheplantfixjamunsalicylicacidcleansergelforactiveacneforoilyacneproneskin,2,"[Plix The Plant Fix Jamun Salicylic Acid Cleanser Gel For Active Acne | For Oily - Acne Prone Skin, Plix The Plant Fix Jamun Salicylic Acid Cleanser Gel For Active Acne | For Oily | Acne Prone Skin]"
10802,plumbodylovinvanillavibeseaudeparfum,2,"[Plum Body Lovin' Vanilla Vibes Eau De Parfum, Plum Bodylovin' Vanilla Vibes Eau De Parfum]"
11255,realactivcoconutwaternoaddedsugarsbottle,2,"[Real Activ Coconut Water - No Added Sugars | Bottle, Real Activ Coconut Water | No Added Sugars | Bottle]"
11303,redbullenergydrinkreadytodrinkbeverage,2,"[Red Bull Energy Drink | Ready To Drink Beverage, Red Bull Energy Drink | Ready to Drink Beverage]"
11304,redbullenergydrinkreadytodrinkbeveragecombo,2,"[Red Bull Energy Drink | Ready To Drink Beverage | Combo, Red Bull Energy Drink | Ready to Drink Beverage | Combo]"
11981,skin1004madagascarcentellatonebrighteningcapsuleampoule,2,"[SKIN1004 Madagascar Centella Tone Brightening Capsule Ampoule, Skin1004 Madagascar Centella Tone Brightening Capsule Ampoule]"
12495,sundroppeanutbuttercrunchywith26proteinpremiumroastedpeanutsnopreservatives,2,"[Sundrop Peanut Butter | Crunchy | With 26% Protein | Premium Roasted Peanuts | No Preservatives, Sundrop Peanut Butter | Crunchy | With 26% Protein |Premium Roasted Peanuts | No Preservatives]"
12573,superbottomsnewborngiftset0to3months,2,"[Super Bottoms Newborn Gift Set | 0 to 3 Months, SuperBottoms Newborn Gift Set | 0 to 3 Months]"
12789,tatasampannpremiumkalmidatesrichinfibrenaturallysweetnaturallylowfatfood,2,"[Tata Sampann Premium Kalmi Dates Rich In Fibre Naturally Sweet Naturally Low-Fat Food, Tata Sampann Premium Kalmi Dates | Rich In Fibre | Naturally Sweet | Naturally Low-Fat Food]"
12810,tatasampannunpolishedtoordalarhardal,3,"[Tata Sampann Unpolished Toor Dal | Arhar Dal, Tata Sampann Unpolished Toor Dal-Arhar Dal, Tata Sampann Unpolished Toor Dal/Arhar Dal]"
12876,tenalidoublehorseuraddalsplit,2,"[Tenali Double Horse Urad Dal - Split, Tenali Double Horse Urad Dal Split]"
13027,thedermaco1hyaluronicsunscreenspf50paaquagelfornormaltooilyskin,2,"[The Derma Co 1% Hyaluronic Sunscreen SPF 50 PA++++ Aqua Gel For Normal To Oily Skin, The Derma Co 1% Hyaluronic Sunscreen Spf 50 Pa+++ Aqua Gel For Normal To Oily Skin]"
13159,theobromazeromaidawholewheatbreadnopreservativesnopalmoil,2,"[Theobroma Zero Maida Whole Wheat Bread | No Preservatives | No Palm Oil, Theobroma Zero Maida Whole wheat bread | No Preservatives | No Palm Oil]"
13655,tresemmekeratinsmoothshampoo,2,"[TRESemme Keratin Smooth Shampoo, Tresemme Keratin Smooth Shampoo]"
13777,udhaiyamdhallmoong,2,"[Udhaiyam Dhall - Moong, Udhaiyam Dhall Moong]"
13934,vaselinecocoaglowseruminlotion100purecocoasheabutterforglowingsoftskin,2,"[Vaseline Cocoa Glow Serum In Lotion, 100% Pure Cocoa & Shea Butter for Glowing & Soft Skin, Vaseline Cocoa Glow Serum In Lotion100% Pure Cocoa & Shea Butter For Glowing & Soft Skin]"
13937,vaselinedeepmoisturebodylotionwithceramidehyaluron10xmoremoisturefordryskin,2,"[Vaseline Deep Moisture Body Lotion With Ceramide Hyaluron | 10X More Moisture | For Dry Skin, Vaseline Deep Moisture Body Lotion With Ceramide Hyaluron | 10X More Moisture| For Dry Skin]"
13992,veetpurehairremovalcreamnormalskin,2,"[Veet Pure Hair Removal Cream - Normal Skin, Veet Pure Hair Removal Cream Normal Skin]"
13993,veetpurehairremovalcreamsensitiveskin,2,"[Veet Pure Hair Removal Cream - Sensitive Skin, Veet Pure Hair Removal Cream Sensitive Skin]"
14045,vegasmartoneseriess2vhth31fullywaterprooftrimmer160minruntime40lengthsettingsblue,2,"[VEGA Smartone Series S2, Vhth-31 Fully Waterproof Trimmer 160 Min Runtime 40 Length Settings (Blue), VEGA Smartone Series S2, Vhth-31 Fully Waterproof Trimmer 160 Min Runtime 40 Length Settings (Blue).]"
14056,vegavhdh25goprohairdryerwithcoolshotbuttonrosegold2100w,2,"[VEGA Vhdh-25 Go Pro Hair Dryer With Cool Shot Button (Rose Gold, 2100 W), VEGA Vhdh-25 Go Pro Hair Dryer With Cool Shot Button (Rose Gold, 2100 W).]"
14200,vlccsandalcleansingmilk,2,"[VLCC Sandal Cleansing Milk, Vlcc Sandal Cleansing Milk]"
14361,whisperultraskinlovesoftsanitarypadsforwomenxl15napkins,2,"[Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL 15 Napkins, Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL+ 15 Napkins]"
14362,whisperultraskinlovesoftsanitarypadsforwomenxl30napkins,2,"[Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL 30 Napkins, Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL+ 30 Napkins]"
14363,whisperultrauptonogapnoleakssanitarypads15xlpadsbasedonpgtechnicaldata,2,"[Whisper Ultra Upto No Gap No Leaks Sanitary Pads, 15 XL Pads (Based on P&G Technical Data), Whisper Ultra Upto No Gap No Leaks Sanitary Pads, 15 XL+ Pads (Based on P&G Technical Data)]"
14452,wishcarehairgrowthserumconcentrateresdensylanagaincaffeinebiotinkeratinricewater,2,"[WishCare Hair Growth Serum Concentrate Resdensyl, Anagain, Caffeine, Biotin, Keratin, Rice Water, WishCare Hair Growth Serum Concentrate-Resdensyl,Anagain,Caffeine,Biotin, Keratin & Rice Water]"

In [25]:
df[df.product_name == "Kellogg's Muesli Nuts and Seeds Crunch | 12 in 1 Power Breakfast"]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls,brand_norm,productname_norm
244138,2026-07-21 02:07:41,zepto,79c6102c-cce8-425f-a59a-0c74ccb9a645,"GT Eurogroove Pvt Ltd. Aluminium & UPVC Windows, Plot No. 115, HSIIDC, Sector 16, Bahadurgarh, Haryana, 124508, India",Sankhol,124508,9d0565a0-6129-48c8-8e6f-2232cca91284,20c6a991-1d53-4211-bc79-ebc8b522d7a2,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12 in 1 Power Breakfast,NaN,500 g,NaN,1 pc (500 g),NaN,365.0,328.0,No,Yes,328.0,NaN,₹37 OFF,328.0,10,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/9d0565a0-6129-48c8-8e6f-2232cca91284,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast

In [26]:
df[df.product_name == "Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast"]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls,brand_norm,productname_norm
14558,2026-07-21 00:14:11,zepto,32989280-a610-4395-aca5-5ba4823af4bd,"National Insurance Company Limited, H-1/H-2, V.K. Complex, Sahakar Marg, Near Laxmi Mandir Cinema, Lalkothi, Jaipur, Rajasthan, 302015, India",Jaipur,302015,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
15137,2026-07-21 00:14:22,zepto,c014a827-2aa9-4e90-ae1e-e5dbc8867100,"Kamlesh Auto, Dhakatya Paduka, Pune - Alandi Rd, Alandi Devachi, Alandi, Pune, Maharashtra, 412105, India",Pune,412105,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
15448,2026-07-21 00:14:34,zepto,dd520c1a-80de-4060-9e8a-7b2156223efe,"Maha NGO Federation, Office No. 9 & 10, Sujay Garden Commercial Complex, Mukund Nagar, Pune, Gokul Nagar, Kondhwa Budruk, Pune, Maharashtra, 411046, India",Pune,411046,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,Yes,Yes,488.0,NaN,₹252 OFF,488.0,34,0,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
24889,2026-07-21 00:18:31,zepto,74039f14-48e6-4a32-b70f-7ddda4c42900,"111/1C, Sarat Ghosh Garden Rd, Dhakuria, Sarat Ghosh Garden, Kolkata, West Bengal, 700031, India",Kolkata,700031,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
27573,2026-07-21 00:19:57,zepto,37531a1f-495c-4f67-bd1e-e3a6158fbf10,"Lucky Paws Veterinary Hospital, Budigere Cross Branch (Multi Specialty Pet Hospital), Apartments, 135/4, Opposite To Brigade Buena Vista, Off Old Madras Road, Budigere Cross, Bommenahalli, Bengaluru, Karnataka 560049, India",Bangalore,560049,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
27714,2026-07-21 00:20:01,zepto,ebabbe83-2299-49ca-bbd8-edfd8dd03d60,"Shivam Greens, Opposite Mohan Greenwoods, Near Shashwat Park, Valivali Gaon, Manjarli, Badlapur, Maharashtra, 421503, India",Mumbai,421503,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
29972,2026-07-21 00:21:14,zepto,9ede85f3-c387-40b0-a6c7-fa07f64da718,"Mahindra Service Center, Shinde Vasti, Hadapsar, Pune, Maharashtra, 411036, India",Pune,411036,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
31166,2026-07-21 00:22:00,zepto,9fb7a7ca-e61c-4904-b339-749b6b45bf09,"Blinkit Store, SBS Nagar, Jagjit Nagar, New Sham Nagar, Sarabha Nagar, Ludhiana, Punjab, 141001, India",Ludhiana,141001,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
32245,2026-07-21 00:22:27,zepto,97301572-98d1-4b4d-8e40-d52748fe5233,"Manuvana, Service Rd, Hoshalli Extension, Stage 1, Vijayanagar, Bengaluru, Karnataka 560040, India",Bangalore,560040,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
33451,2026-07-21 00:22:51,zepto,198b7ff3-353f-4735-bf3f-75b180544478,"The Parion Business Class Hotel, Hosanna TV HD, Sambu, Prasad, Avenue, Sambu Prasad Avanue, 87-4, Arcot Rd, Opp. Adyar Ananda Bhavan, Vadapalani, Chennai, Tamil Nadu, 600026, India",Chennai,600026,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,3,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
41431,2026-07-21 00:26:48,zepto,856f5f52-8b1c-4089-b242-6c5dd371777e,"Katani Dhaba & Sweets, Shivjot Enclave, Kharar - Kurali Rd, Guru Teg Bahadur Nagar, Kharar, Punjab, 140301, India",Kharar,140301,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
42766,2026-07-21 00:28:08,zepto,e4a1792d-8ffa-4015-a415-e91fe2f01493,"Laxmi Dharam Kanta, Near, 22 Godam Cir, Patel Nagar, Hawa Sadak, Geejgarh Vihar Colony, Bais Godam, Jaipur, Rajasthan, 302006, India",Jaipur,302006,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
48686,2026-07-21 00:31:17,zepto,f68f6daf-2bba-450e-9a05-082e29e9129d,"New Sai Balaji Luxury PG, Sakhare Vasti Rd, Hinjawadi Rajiv Gandhi InfoTech Park, Hinjawadi, Pimpri-Chinchwad, Maharashtra, 411057, India",Pune,411057,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
50555,2026-07-21 00:32:11,zepto,547ab61d-8d0e-47b5-a5b4-82952f43e814,"Blue Pools, Kushtia, Kolkata, West Bengal, 700039, India",Kolkata,700039,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
51056,2026-07-21 00:32:24,zepto,fab4fc54-b957-4a4b-9e1b-eb5642c9e224,"Baburao Parulekar Road, Baburao Parulekar Rd, Madhav Nagar CoOperative Housing Society, Babasaheb Ambedkar Nagar, Mumbai, Maharashtra, 400028, India",Mumbai,400028,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,Yes,Yes,488.0,NaN,₹252 OFF,488.0,34,0,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
55845,2026-07-21 00:35:14,zepto,74eedd8a-1705-46c3-8dd3-bbfcc0289ec3,"88, Pipeline Rd, Marottichuvadu, Edappally, Ernakulam, Kochi, Kerala, 682021, India",Kalamassery,682021,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
57825,2026-07-21 00:36:17,zepto,044a06cd-5792-44a6-be6b-d5747683349b,"SLV Tea Store, Electronics City Phase 1, Electronic City, Bengaluru, Karnataka, 560100, India",Bangalore,560100,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
89526,2026-07-21 00:53:39,zepto,60252717-a8c5-4891-9b23-3db778b14477,"Zepto Store, Friendship Residency, Veerbhadra Nagar Rd, Veerbhadra Nagar, Baner, Pune, Maharashtra, 411045, India",Pune,411045,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
97235,2026-07-21 00:57:59,zepto,102af115-4cad-419f-9bd5-567159eefc5c,"Sahyadri Darshan Co. So, RH-21, MIDC, Dombivli East, Dombivli, Maharashtra, 421203, India",Mumbai,421203,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,Yes,Yes,488.0,NaN,₹252 OFF,488.0,34,0,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
100528,2026-07-21 00:59:26,zepto,540c73ee-1fc7-43aa-a239-58f94400f241,"SN Junction Metro Station, SN Junction, Refinery Road, Petta, Thrippunithura, Kanayannur, Ernakulam, Kerala, 682301, India",Thrippunithura,682301,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
102775,2026-07-21 01:00:24,zepto,5400933d-3c5d-4015-a767-daed27781a0d,"Glam Salon Makeup And Nail Academy, 442, 7th Main, Mallathalli Lake Road, Bangalore 56, Mallathahalli Lake Rd, Bengaluru, Karnataka 560056",Bangalore,560056,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
107129,2026-07-21 01:02:38,zepto,0c02c311-65e5-4495-bcb4-ee96476882bb,"Surajilal Choud MahaLakshmi Collection, Hosapalaya, Muneshwara Nagar, Bengaluru, Karnataka, 560068, India",Bangalore,560068,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,Yes,Yes,488.0,NaN,₹252 OFF,488.0,34,0,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
109551,2026-07-21 01:04:03,zepto,3d1b28be-1e25-471f-a4d9-f2151a7d1bfc,"Medicover Hospitals Gate, Cidco, Chhatrapati Sambhajinagar, Maharashtra, 431003, India",Chhatrapati Sambhajinagar,431003,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
110426,2026-07-21 01:04:24,zepto,1d852498-590f-4ffa-babf-aae026e3584d,"Sobha Chrysanthemum Road, Sobha Chrysanthemum Rd, Kothanur, Bengaluru, Karnataka, 560077, India",Bangalore,560077,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,1,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
112315,2026-07-21 01:05:08,zepto,6cb7f877-c543-4be9-8c74-5fd19956f937,"Digamber Jain Panch Balyati Temple, Chikitsak Nagar, Indore, Madhya Pradesh, 452010, India",Indore,452010,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
115626,2026-07-21 01:06:23,zepto,f9e3aef6-a8b9-4bb4-9177-a7ca316dfd71,"Prashal CoOperative Housing Society, Sant Janabai Rd, Nav Prabhat Society, Navpada, Park Road, Vile Parle, Mumbai, Maharashtra, 400057, India",Mumbai,400057,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,3,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
117807,2026-07-21 01:07:14,zepto,8ee2719c-97ed-44a2-a32e-7dceac0a7e55,"Food Grains Godown, Aruganthampoondi St, Vellore, Tamil Nadu, 632004, India",Vellore,632004,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,738.0,486.0,No,Yes,486.0,NaN,₹252 OFF,486.0,34,2,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast
128588,2026-07-21 01:11:10,zepto,6940d67b-8f25-4a93-a0b1-9bad67479c03,"Kundan Mobile's Sales And Service Nanmangalam Post Kovilambakkam, 2/217A Elumalai Salai Nanmangalam, Post, Chinna Kovilambakkam, Kovilambakkam, Chennai, Tamil Nadu, 600117, India",Chennai,600117,0fbd5e93-6d69-4930-ab73-7d72a8366515,84c6a4cd-3736-40cb-8033-e666a6c0ed17,Dairy & Breakfast,Breakfast & Sauces,Muesli & Oats,NaN,Kellogg's,Kellogg's Muesli Nuts and Seeds Crunch | 12-in-1 Power Breakfast,NaN,950 g,NaN,1 pack (950 g),NaN,740.0,488.0,No,Yes,488.0,NaN,₹252 OFF,488.0,34,4,https://www.zepto.com/pn/kelloggs-muesli-nuts-and-seeds-crunch-12-in-1-power-breakfast/pvid/0fbd5e93-6d69-4930-ab73-7d72a8366515,NaN,kelloggs,kelloggsmueslinutsandseedscrunch12in1powerbreakfast

In [27]:
result = (
    df.groupby("product_url")
      .agg(
          product_count=("product_name", "nunique"),
          product_names=("product_name", lambda x: sorted(set(x))),
          unique_ids=("unique_id", lambda x: sorted(set(x))),
          product_ids=("product_id_upc_ean", lambda x: sorted(set(x)))
      )
      .reset_index()
)

# Keep only URLs mapped to multiple product names
result = result[result["product_count"] > 1]

print(f"Found {len(result)} URLs with different product names.")
result

Found 2 URLs with different product names.

,product_url,product_count,product_names,unique_ids,product_ids
12892,https://www.zepto.com/pn/red-bull-energy-drink-ready-to-drink-beverage-combo/pvid/9a534329-4743-431f-9df6-d6c731976ebd,2,"[Red Bull Energy Drink | Ready To Drink Beverage | Combo, Red Bull Energy Drink | Ready to Drink Beverage | Combo]",[9a534329-4743-431f-9df6-d6c731976ebd],[448610cc-47c6-4186-9761-18b23a2baf03]
12897,https://www.zepto.com/pn/red-bull-energy-drink-ready-to-drink-beverage/pvid/45494dcb-43dd-4209-9d72-e674d82db8c0,2,"[Red Bull Energy Drink | Ready To Drink Beverage, Red Bull Energy Drink | Ready to Drink Beverage]",[45494dcb-43dd-4209-9d72-e674d82db8c0],[694f6932-8863-4d2d-b7a3-7833905d1401]

In [28]:
top10_longest = (
    df.drop_duplicates(subset="product_name")
      .assign(name_length=lambda x: x["product_name"].fillna("").str.len())
      .sort_values("name_length", ascending=False)
      [["unique_id", "name_length", "product_name", "product_url"]]
      .head(10)
)

print(top10_longest)

                                   unique_id  name_length  \
13390   95e2be62-4c82-41ce-8b88-81aabe1b60ae          389
52159   2bdf7ef7-4796-4969-ba37-5fca1e01b31c          259
61755   87f116b2-3b3e-4b23-a98d-30a0021aeaae          259
52155   678a3f11-8e00-498d-8454-ae313c7d8842          254
236280  b1941154-ef86-4b75-979a-6992ea0f01b1          249
18573   7a8b5c44-5df6-4c61-9f82-114b659d19df          216
120888  5fab59e1-8d29-4863-9267-9f816e627832          212
11686   91a5bd82-b407-426f-a9f7-39af4a53b38f          206
13389   edd24376-4a56-4c30-bc25-17740efa5f75          206
52156   58caf284-73d7-4a9e-ab54-eb51f6b197f5          204

                                                                                                                                                                                                                                                                                                                                                                                                 product_name  \
13390   Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo
52159                                                                                                                                     Sirona Heavy Flow Tampons | Organic Cotton Core | Ultra-High Absorbency And Leak-Proof Protection (20pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) & Sirona Sanitary Pads And Diapers Disposal Bag (15pc) Combo
61755                                                                                                                                     Sirona Regular Flow Tampons | Organic Cotton Core | Ultra-High Absorbency | Leak-Proof Protection (20pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) & Sirona Sanitary Pads And Diapers Disposal Bag (15pc) Combo
52155                                                                                                                                          Sirona Super Plus Tampons For Heavy Flow | Organic Cotton Core | High Absorbency | Leak-Proof (1pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) & Sirona Sanitary Pads And Diapers Disposal Bag (15pc) Combo
236280                                                                                                                                              Sirona Disposable Period Panties 2Xl-3Xl, 5X More Absorption, 100% Rash Free, Leak-Proof (5pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) & Sirona Sanitary Pads And Diapers Disposal Bag (15pc) Combo
18573                                                                                                                                                                                Nivea Soft Daily Uv Light Moisturising Cream With Spf-15 (50ml) & Nivea Luminous Even Glow Face Wash | Oil Free Formula, Aha, Aloe Vera, Guarana Extract | Deep Clean (50ml) & Nivea Fresh Pure Shower Gel (125ml) Combo
120888                                                                                                                                                                                   Hatsun Curd Pouch (500g) & Aavin Premium Full Cream Fresh Milk (Pouch) (500ml) & Baidyanath Honey | Zero Added Sugar (50g) & Parrys White Label Sugar (1kg) & Aashirvaad Pure Cow Ghee, Pouch, Rich Aroma (1l) Combo
11686                                                                                                                                                                                          Mcaffeine Summer Breeze Perfume Body Lotion With Niacinamide - Cocoa Butter|Fresh Aquatic Fragrance (300g) & Mcaffeine Detan Body Wash | 1% Glycolic 5% Niacinamide-Kojic Acid Reduce Dark Spots (300ml) Combo
13389                                                                                                                                                                                          Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) Combo
52156                                                                                                                                                                                            Sirona Heavy Flow Tampons | Organic Cotton Core | Ultra-High Absorbency And Leak-Proof Protection (20pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) Combo

                                                                                                                                                                                                                                                                                                                                                                                                                        product_url
13390   https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae
52159                                                                                                         https://www.zepto.com/pn/sirona-heavy-flow-tampons-organic-cotton-core-ultra-high-absorbency-and-leak-proof-protection-20pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-sirona-sanitary-pads-and-diapers-disposal-bag-15pc-combo/pvid/2bdf7ef7-4796-4969-ba37-5fca1e01b31c
61755                                                                                                           https://www.zepto.com/pn/sirona-regular-flow-tampons-organic-cotton-core-ultra-high-absorbency-leak-proof-protection-20pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-sirona-sanitary-pads-and-diapers-disposal-bag-15pc-combo/pvid/87f116b2-3b3e-4b23-a98d-30a0021aeaae
52155                                                                                                                https://www.zepto.com/pn/sirona-super-plus-tampons-for-heavy-flow-organic-cotton-core-high-absorbency-leak-proof-1pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-sirona-sanitary-pads-and-diapers-disposal-bag-15pc-combo/pvid/678a3f11-8e00-498d-8454-ae313c7d8842
236280                                                                                                                  https://www.zepto.com/pn/sirona-disposable-period-panties-2xl-3xl-5x-more-absorption-100-rash-free-leak-proof-5pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-sirona-sanitary-pads-and-diapers-disposal-bag-15pc-combo/pvid/b1941154-ef86-4b75-979a-6992ea0f01b1
18573                                                                                                                                                    https://www.zepto.com/pn/nivea-soft-daily-uv-light-moisturising-cream-with-spf-15-50ml-nivea-luminous-even-glow-face-wash-oil-free-formula-aha-aloe-vera-guarana-extract-deep-clean-50ml-nivea-fresh-pure-shower-gel-125ml-combo/pvid/7a8b5c44-5df6-4c61-9f82-114b659d19df
120888                                                                                                                                                              https://www.zepto.com/pn/hatsun-curd-pouch-500g-aavin-premium-full-cream-fresh-milk-pouch-500ml-baidyanath-honey-zero-added-sugar-50g-parrys-white-label-sugar-1kg-aashirvaad-pure-cow-ghee-pouch-rich-aroma-1l-combo/pvid/5fab59e1-8d29-4863-9267-9f816e627832
11686                                                                                                                                                          https://www.zepto.com/pn/mcaffeine-summer-breeze-perfume-body-lotion-with-niacinamide-cocoa-butterfresh-aquatic-fragrance-300g-mcaffeine-detan-body-wash-1-glycolic-5-niacinamide-kojic-acid-reduce-dark-spots-300ml-combo/pvid/91a5bd82-b407-426f-a9f7-39af4a53b38f
13389                                                                                                                                                                       https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-combo/pvid/edd24376-4a56-4c30-bc25-17740efa5f75
52156                                                                                                                                                            https://www.zepto.com/pn/sirona-heavy-flow-tampons-organic-cotton-core-ultra-high-absorbency-and-leak-proof-protection-20pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-combo/pvid/58caf284-73d7-4a9e-ab54-eb51f6b197f5

In [29]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls', 'brand_norm', 'productname_norm'],
      dtype='object')