In [1]:
from pathlib import Path
import pandas as pd

DATA_FOLDER = Path("/home/user/Documents/zepto")

files = sorted(DATA_FOLDER.glob("*.csv"))

print(f"Found {len(files)} files")

for f in files:
    print(f.name)

Found 12 files
zepto_2026_07_04.csv
zepto_2026_07_07.csv
zepto_2026_07_08.csv
zepto_2026_07_09.csv
zepto_2026_07_10.csv
zepto_2026_07_14.csv
zepto_2026_07_15.csv
zepto_2026_07_16.csv
zepto_2026_07_20.csv
zepto_2026_07_21.csv
zepto_2026_07_22.csv
zepto_2026_07_23.csv

In [2]:
import pandas as pd
from pathlib import Path

DATA_FOLDER = Path("/home/user/Documents/zepto")

dfs = {}

for file in sorted(DATA_FOLDER.glob("*.csv")):
    print(f"Loading {file.name}...")

    df = pd.read_csv(file, low_memory=False)

    # filename
    df["source_file"] = file.name

    # crawl date
    df["crawl_date"] = pd.to_datetime(
        df["crawl_date_and_time"]
    ).dt.date

    dfs[file.stem] = df

print(f"\nLoaded {len(dfs)} datasets.")

Loading zepto_2026_07_04.csv...
Loading zepto_2026_07_07.csv...
Loading zepto_2026_07_08.csv...
Loading zepto_2026_07_09.csv...
Loading zepto_2026_07_10.csv...
Loading zepto_2026_07_14.csv...
Loading zepto_2026_07_15.csv...
Loading zepto_2026_07_16.csv...
Loading zepto_2026_07_20.csv...
Loading zepto_2026_07_21.csv...
Loading zepto_2026_07_22.csv...
Loading zepto_2026_07_23.csv...

Loaded 12 datasets.

In [3]:
for name, df in dfs.items():
    print(name, df.shape)

zepto_2026_07_04 (1037455, 33)
zepto_2026_07_07 (1043504, 33)
zepto_2026_07_08 (1026016, 33)
zepto_2026_07_09 (1049475, 33)
zepto_2026_07_10 (711405, 33)
zepto_2026_07_14 (881077, 33)
zepto_2026_07_15 (553752, 33)
zepto_2026_07_16 (530232, 33)
zepto_2026_07_20 (552107, 33)
zepto_2026_07_21 (539534, 33)
zepto_2026_07_22 (443539, 33)
zepto_2026_07_23 (165326, 33)

In [4]:
summary = []

for name, df in dfs.items():
    summary.append({
        "Date": name.replace("zepto_", ""),
        "Rows": len(df),
        "Unique IDs": df["unique_id"].nunique(),
        "Unique URLs": df["product_url"].nunique(),
        "Stores": df["store_id"].nunique(),
        "Store Locations": df["store_name_location"].nunique(),
        "Cities": df["city"].nunique(),
        "Departments": df["department"].nunique(),
        "Categories": df["category"].nunique(),
        "Sub Categories": df["sub_category"].nunique(),
        "Brands": df["brand_name"].nunique(),
        "OOS %": round((df["out_of_stock_flag"]=="Yes").mean()*100,2)
    })

summary = pd.DataFrame(summary)
summary

,Date,Rows,Unique IDs,Unique URLs,Stores,Store Locations,Cities,Departments,Categories,Sub Categories,Brands,OOS %
0,2026_07_04,1037455,17349,17351,381,292,54,10,28,161,1766,18.66
1,2026_07_07,1043504,16351,16351,375,295,48,10,27,160,1687,21.01
2,2026_07_08,1026016,17374,17374,357,287,57,10,27,159,1714,21.25
3,2026_07_09,1049475,16566,16566,369,291,56,10,27,159,1697,20.14
4,2026_07_10,711405,8855,8855,253,259,6,10,26,158,1226,21.09
5,2026_07_14,881077,8824,8825,310,292,6,10,24,159,1222,18.49
6,2026_07_15,553752,14936,14940,206,147,34,10,23,159,1622,21.03
7,2026_07_16,530232,14804,14804,198,146,34,10,23,159,1624,21.61
8,2026_07_20,552107,15827,15827,196,146,42,10,24,159,1626,22.60
9,2026_07_21,539534,16636,16636,194,147,46,10,24,160,1680,22.60
10,2026_07_22,443539,7229,7231,159,148,2,10,25,158,1099,18.66
11,2026_07_23,165326,5508,5508,63,60,1,10,24,150,939,25.18

In [5]:
missing_summary = {}

for name, df in dfs.items():
    missing_summary[name] = df.isna().sum()

missing_df = pd.DataFrame(missing_summary)
missing_df

,zepto_2026_07_04,zepto_2026_07_07,zepto_2026_07_08,zepto_2026_07_09,zepto_2026_07_10,zepto_2026_07_14,zepto_2026_07_15,zepto_2026_07_16,zepto_2026_07_20,zepto_2026_07_21,zepto_2026_07_22,zepto_2026_07_23
crawl_date_and_time,0,0,0,0,0,0,0,0,0,0,0,0
platform_name,0,0,0,0,0,0,0,0,0,0,0,0
store_id,0,0,0,0,0,0,0,0,0,0,0,0
store_name_location,0,0,0,0,0,0,0,0,0,0,0,0
city,0,0,0,0,0,0,0,0,0,0,0,0
pin_code,0,0,0,0,0,0,0,0,0,0,0,0
unique_id,0,0,0,0,0,0,0,0,0,0,0,0
product_id_upc_ean,0,0,0,0,0,0,0,0,0,0,0,0
department,0,0,0,0,0,0,0,0,0,0,0,0
category,0,0,0,0,0,0,0,0,0,0,0,0
sub_category,0,0,0,0,0,0,0,0,0,0,0,0
product_type,1037455,1043504,1026016,1049475,711405,881077,553752,530232,552107,539534,443539,165326
brand_name,0,0,0,0,0,0,0,0,0,0,0,0
product_name,0,0,0,0,0,0,0,0,0,0,0,0
product_description,1037455,1043504,1026016,1049475,711405,881077,553752,530232,552107,539534,443539,165326
product_grammage,193073,188620,186391,188690,116583,136210,100852,95917,101347,97443,67591,28257
package_type,1037455,1043504,1026016,1049475,711405,881077,553752,530232,552107,539534,443539,165326
net_quantity,2,0,0,0,0,0,0,0,0,1,1,0
variants,1010928,1015138,998160,1021025,698531,873787,538835,515612,537119,524745,435208,162457
item_mrp,1,0,0,0,0,0,1,0,0,0,0,0
item_selling_price,0,0,0,0,0,0,0,0,0,0,0,0
out_of_stock_flag,0,0,0,0,0,0,0,0,0,0,0,0
discount_flag,0,0,0,0,0,0,0,0,0,0,0,0
product_price,0,0,0,0,0,0,0,0,0,0,0,0
unit_price,1037455,1043504,1026016,1049475,711405,881077,553752,530232,552107,539534,443539,165326
promo_offer_description,0,0,0,0,0,0,0,0,0,0,0,0
promo_offer_price,0,0,0,0,0,0,0,0,0,0,0,0
discount_in_percent,0,0,0,0,0,0,0,0,0,0,0,0
stock_count,0,0,0,0,0,0,0,0,0,0,0,0
product_url,0,0,0,0,0,0,0,0,0,0,0,0
product_image_urls,1037455,1043504,1026016,1049475,711405,881077,553752,530232,552107,539534,443539,165326
source_file,0,0,0,0,0,0,0,0,0,0,0,0
crawl_date,0,0,0,0,0,0,0,0,0,0,0,0

In [8]:
# Get dataset names in chronological order
keys = sorted(dfs.keys())

for i in range(len(keys)-1):

    d1 = set(dfs[keys[i]]["department"].dropna())
    d2 = set(dfs[keys[i+1]]["department"].dropna())

    print(f"\n{keys[i]} -> {keys[i+1]}")

    print("Added:", sorted(d2-d1))
    print("Removed:", sorted(d1-d2))

zepto_2026_07_04 -> zepto_2026_07_07
Added: []
Removed: []

zepto_2026_07_07 -> zepto_2026_07_08
Added: []
Removed: []

zepto_2026_07_08 -> zepto_2026_07_09
Added: []
Removed: []

zepto_2026_07_09 -> zepto_2026_07_10
Added: []
Removed: []

zepto_2026_07_10 -> zepto_2026_07_14
Added: []
Removed: []

zepto_2026_07_14 -> zepto_2026_07_15
Added: []
Removed: []

zepto_2026_07_15 -> zepto_2026_07_16
Added: []
Removed: []

zepto_2026_07_16 -> zepto_2026_07_20
Added: []
Removed: []

zepto_2026_07_20 -> zepto_2026_07_21
Added: []
Removed: []

zepto_2026_07_21 -> zepto_2026_07_22
Added: []
Removed: []

zepto_2026_07_22 -> zepto_2026_07_23
Added: []
Removed: []

In [9]:
for i in range(len(keys)-1):

    c1 = set(dfs[keys[i]]["category"].dropna())
    c2 = set(dfs[keys[i+1]]["category"].dropna())

    print(f"\n{keys[i]} -> {keys[i+1]}")

    print("Added:", sorted(c2-c1))
    print("Removed:", sorted(c1-c2))

zepto_2026_07_04 -> zepto_2026_07_07
Added: []
Removed: ['Paan Corner']

zepto_2026_07_07 -> zepto_2026_07_08
Added: []
Removed: []

zepto_2026_07_08 -> zepto_2026_07_09
Added: []
Removed: []

zepto_2026_07_09 -> zepto_2026_07_10
Added: ['Jewellery']
Removed: ['Protein & Nutrition', 'Unlisted1']

zepto_2026_07_10 -> zepto_2026_07_14
Added: []
Removed: ['Home Needs', 'Stationery & Books']

zepto_2026_07_14 -> zepto_2026_07_15
Added: []
Removed: ['Jewellery']

zepto_2026_07_15 -> zepto_2026_07_16
Added: []
Removed: []

zepto_2026_07_16 -> zepto_2026_07_20
Added: ['Stationery & Books']
Removed: []

zepto_2026_07_20 -> zepto_2026_07_21
Added: []
Removed: []

zepto_2026_07_21 -> zepto_2026_07_22
Added: ['Jewellery']
Removed: []

zepto_2026_07_22 -> zepto_2026_07_23
Added: []
Removed: ['Jewellery']

In [10]:
for i in range(len(keys)-1):

    s1 = set(dfs[keys[i]]["sub_category"].dropna())
    s2 = set(dfs[keys[i+1]]["sub_category"].dropna())

    print(f"\n{keys[i]} -> {keys[i+1]}")

    print("Added:", sorted(s2-s1))
    print("Removed:", sorted(s1-s2))

zepto_2026_07_04 -> zepto_2026_07_07
Added: ['Tampons & Menstrual Cups']
Removed: ['Sets', 'Toothpaste & Mouthwash']

zepto_2026_07_07 -> zepto_2026_07_08
Added: []
Removed: ['Tampons & Menstrual Cups']

zepto_2026_07_08 -> zepto_2026_07_09
Added: []
Removed: []

zepto_2026_07_09 -> zepto_2026_07_10
Added: ['Sets']
Removed: ['Desserts', 'Hydration Drinks']

zepto_2026_07_10 -> zepto_2026_07_14
Added: ['Crafts & Hobby', 'Tampons & Menstrual Cups']
Removed: ['Handwash & Sanitizers']

zepto_2026_07_14 -> zepto_2026_07_15
Added: ['Desserts', 'Hydration Drinks']
Removed: ['Sets', 'Tampons & Menstrual Cups']

zepto_2026_07_15 -> zepto_2026_07_16
Added: []
Removed: []

zepto_2026_07_16 -> zepto_2026_07_20
Added: []
Removed: []

zepto_2026_07_20 -> zepto_2026_07_21
Added: ['Handwash & Sanitizers', 'Non-Alcoholic & Energy Drink']
Removed: ['Hydration Drinks']

zepto_2026_07_21 -> zepto_2026_07_22
Added: ['Sets']
Removed: ['Desserts', 'Handwash & Sanitizers', 'Non-Alcoholic & Energy Drink']

zepto_2026_07_22 -> zepto_2026_07_23
Added: []
Removed: ['Asian', 'Bakery', 'Dessert Mixes', 'Italian', 'Powders & Pastes', 'Sandwiches', 'Sets', 'Sides']

In [11]:
store_summary = []

for name, df in dfs.items():

    store_summary.append(
        df.groupby("store_id")
          .size()
          .reset_index(name="Products")
          .assign(Date=name)
    )

store_summary = pd.concat(store_summary)

In [14]:
store_summary

                                 store_id  Products              Date
0    0053a04d-aeb4-46b5-99fe-d740491e3843      3192  zepto_2026_07_04
1    0059ff6a-7eb0-477a-a7f5-69256f2c444b      1471  zepto_2026_07_04
2    005dcc9a-d50c-442f-ae5e-f89f35d1a01a      3131  zepto_2026_07_04
3    01185b5e-b794-4cfb-99c9-625397e548ac      3287  zepto_2026_07_04
4    02d2c306-7699-434b-947e-88c99afc54f9      3200  zepto_2026_07_04
5    02dc6b57-1dfe-4efe-a57b-4324a830de78      3740  zepto_2026_07_04
6    06031ad9-0300-4c0d-bc7d-cc16959c7467      3997  zepto_2026_07_04
7    06bc0cca-b09b-4c18-b6c5-8358f91c7201      3735  zepto_2026_07_04
8    07a6d7c0-aea9-434c-846e-9308e495db6a      1362  zepto_2026_07_04
9    085097a9-564c-45fe-98d8-23d7fd268328      3689  zepto_2026_07_04
10   0a493c16-c8cc-4f45-a02c-51e7b1328f53      3582  zepto_2026_07_04
11   0bd6dc44-83ca-40ef-9025-d8b881f999bf      3323  zepto_2026_07_04
12   0be324c2-79de-426d-8d78-24b4d50cd9b4      3636  zepto_2026_07_04
13   0c02c311-65e5-4495-bcb4-ee96476882bb      3122  zepto_2026_07_04
14   0c865653-8eac-4a33-900c-d2ed7f3c0477      3172  zepto_2026_07_04
15   0cdd4ac3-fbeb-4bfd-8960-ebf2192d29b4      1468  zepto_2026_07_04
16   0cde9637-ca43-45b6-a89c-08c1e32bae57      3006  zepto_2026_07_04
17   0e8c4509-c9cd-4235-9da5-18fbede8ce72      1098  zepto_2026_07_04
18   0fbf57e9-75ca-499b-94d5-479f33b564ea      3910  zepto_2026_07_04
19   102af115-4cad-419f-9bd5-567159eefc5c      3302  zepto_2026_07_04
20   133688fc-cadd-4750-bb5f-f595c5eca821      3791  zepto_2026_07_04
21   13ffc117-24d6-4854-a53e-a51d7330973e      3335  zepto_2026_07_04
22   146ab60b-09e2-4856-8aa2-2f7c1a6977e6      3656  zepto_2026_07_04
23   166f8ba8-c333-4c60-9d12-faeab29ac22c      1300  zepto_2026_07_04
24   16755fdd-f32e-40f1-a39b-397bc73f7e5d      3496  zepto_2026_07_04
25   176da4ba-5563-43ce-bb78-5568a4b8f0d0      3487  zepto_2026_07_04
26   1794eede-9e42-4a9c-b132-0be5b0e4e4a4      3707  zepto_2026_07_04
27   18073c2e-7d0d-4096-b0e0-c8b5f7454446      3436  zepto_2026_07_04
28   188961a6-213a-4ab6-9d5d-2aaa495042aa      4010  zepto_2026_07_04
29   19a99791-6f27-4c54-a851-62d3a7d0884c      3423  zepto_2026_07_04
30   1a2ba310-07de-4a70-946c-b54f2a487646      2884  zepto_2026_07_04
31   1a87a0c1-4634-4bd9-987e-8bb455d96027      3595  zepto_2026_07_04
32   1a96b304-c2cb-4a59-88cc-8e3496e1b525      3755  zepto_2026_07_04
33   1ad29aa7-34e9-4268-9238-5a3a3fcd1bd2      3182  zepto_2026_07_04
34   1ba2b8e0-aa82-4a78-b38b-477b97eac054      2992  zepto_2026_07_04
35   1c31b7f9-1213-49ea-8346-4879856906a4       831  zepto_2026_07_04
36   1c9e155e-83a8-457a-a687-01eabb1e7a36      1615  zepto_2026_07_04
37   1cf40b2e-95cd-4581-9ab9-bca81d4932ab      1301  zepto_2026_07_04
38   1d31c12c-1669-4ed5-bf1e-251da70753b8      1461  zepto_2026_07_04
39   1db5fffc-4eca-4f44-8ba6-14c5c107e81f      3093  zepto_2026_07_04
40   1df7d024-3938-424e-a351-0c61f146c944      3317  zepto_2026_07_04
41   1dfb0f79-3c66-45e8-8b24-9d79ab1b2477      3745  zepto_2026_07_04
42   1f606e33-cc6a-46ae-95d7-21bb5a401d7a      1383  zepto_2026_07_04
43   2027ae67-e366-4f60-ab7d-64ffbebfeee0      3061  zepto_2026_07_04
44   207df3d7-87f9-4b65-b6be-8e7114d22512      1390  zepto_2026_07_04
45   20b71590-dbe0-4666-b941-017436eae4d4      1411  zepto_2026_07_04
46   2175898f-b70e-46d9-8def-aba7f0745662      1370  zepto_2026_07_04
47   22cd61da-18f7-490b-9394-24abc3780214      3162  zepto_2026_07_04
48   238a227d-697c-4fa9-a4f5-4fd064760098      3249  zepto_2026_07_04
49   2522b064-b9af-4967-9c41-2bfffe8786d3      3149  zepto_2026_07_04
50   2614cabb-fff2-4ef6-aa5b-e94c2b875880      1364  zepto_2026_07_04
51   266f0f16-dcf8-4ab0-bbfb-2860b57c3c9b      3071  zepto_2026_07_04
52   281082b4-7a69-4373-a3c3-385b02d134b1      1291  zepto_2026_07_04
53   291264cf-55b8-4ae3-93b2-cb23fd795054      3267  zepto_2026_07_04
54   2916f784-3ab0-4749-896b-702f58275041      3675  zepto_2026_07_04
55   2918790f-421a-493e-84a3-e9a2d8f0b60d       137  zepto_2026_07_04
56   2a607d6c-27cf-4475-a804-e99a363919c4      3511  zepto_2026_07_04
57   2a655482-29d6-48fd-bb6c-6051fb5900ee      1456  zepto_2026_07_04
58   2a82431b-9c30-453e-a6b9-4dc586ae5e75      3593  zepto_2026_07_04
59   2abca56f-4918-4aa7-b110-34068bd40d7e      3888  zepto_2026_07_04
60   2b25b1fd-8ab2-4065-9f8b-caef224c087c      4091  zepto_2026_07_04
61   2b8584f6-f986-4414-a288-885d34d7a1ab      3479  zepto_2026_07_04
62   2cfbd70a-856b-4e58-8d32-0b5d389c4458      3748  zepto_2026_07_04
63   2f8b56d8-3d1a-4dd3-ad94-2fc67df39b4f      3269  zepto_2026_07_04
64   300a1056-ad32-430e-b5e4-41624b0494ed       385  zepto_2026_07_04
65   312fd0bd-4163-4768-8e94-ea1dc57783dd      2842  zepto_2026_07_04
66   314533d4-8bd7-4985-8ca5-9b737431149b      3708  zepto_2026_07_04
67   31a7478c-9eed-4599-881a-9616df850bfe      3676  zepto_2026_07_04
68   31a8b99d-0d1a-4f32-a367-e6cf62bb8603      3104  zepto_2026_07_04
69   320121c9-8af7-4921-9eea-5c456b7a900d      3186  zepto_2026_07_04
70   329deb14-183d-4581-90eb-8c40a5e91fd5      3348  zepto_2026_07_04
71   32ac84e0-0a29-4c1f-865a-c33780173389      1795  zepto_2026_07_04
72   33a1d02e-1bb7-44cc-8d38-9697bcc23dba      1215  zepto_2026_07_04
73   3422fce9-9587-44a5-8cff-8ee60c65617d      3281  zepto_2026_07_04
74   34d81293-1443-44be-9db9-043f95f184ee      1383  zepto_2026_07_04
75   3516f4f6-dec8-4e36-abb0-77f26d0f4a16      2994  zepto_2026_07_04
76   35225fcb-30cc-4ab8-939b-a0a5e0887285      3242  zepto_2026_07_04
77   3583fadc-1d44-42ff-b09d-68d09b0aec89      3210  zepto_2026_07_04
78   3608083a-c098-4f58-bc13-4a729a103909      1182  zepto_2026_07_04
79   376dd638-f05e-4171-b4e1-b97650b79fe7      3215  zepto_2026_07_04
80   37906ef4-331c-471c-b332-0bf7a979fc07      1210  zepto_2026_07_04
81   37b900f0-25c0-448b-825a-74d62c8ceb41      3274  zepto_2026_07_04
82   37e0300a-af5d-494a-a88e-de79f61c4dde      3291  zepto_2026_07_04
83   38caa147-31a6-4fae-a5b6-1c21d1bbfa1d       390  zepto_2026_07_04
84   3994880c-5e18-4de9-9f68-847c18108e27      3486  zepto_2026_07_04
85   3b18ee5e-9d22-44cd-acff-646042e546bf      1173  zepto_2026_07_04
86   3bf7d17f-4fa3-481d-b14d-66ca5c4f14da      1662  zepto_2026_07_04
87   3c0de1fa-d7b5-4cef-b867-cad33562463c      3784  zepto_2026_07_04
88   3cd244d7-9f76-467e-b4ab-0d7123ebd606      1482  zepto_2026_07_04
89   3d914942-fcf7-4222-8029-aff9d8ee3743      1302  zepto_2026_07_04
90   3eced897-a793-4b9d-bc3b-1772a883d8af      3156  zepto_2026_07_04
91   3ed41d5c-5bb0-4ea9-b041-4d40c2b1f963      2270  zepto_2026_07_04
92   3f391c43-b41c-43e8-b378-34f272c6296c      2206  zepto_2026_07_04
93   3fdf2ec3-0ac0-4e8d-a7f0-e184ef12fbe6      3185  zepto_2026_07_04
94   411fefdc-6597-4e1e-ad2c-1cd7cdeadb5a      3527  zepto_2026_07_04
95   415a53bb-ae7f-4d84-b58f-e36e425769e5      3285  zepto_2026_07_04
96   425e2ef0-02bc-4c87-b423-cfbc6e56984a       728  zepto_2026_07_04
97   42d58798-26cc-429a-aea6-92dbbecae776      3125  zepto_2026_07_04
98   433bb54d-7e04-4f91-ac03-bee784a3102c      2958  zepto_2026_07_04
99   43b12c97-dc99-431a-9ba3-e3cde9c716bb      3311  zepto_2026_07_04
100  44e000f6-7a95-4723-ac5d-af4b508056c1      1346  zepto_2026_07_04
101  4565fffb-f4fa-4808-91e1-31e69f6ac9df       476  zepto_2026_07_04
102  46b54f69-c5ff-4595-934d-3d98fbf33ec0      3506  zepto_2026_07_04
103  471b6b1b-6289-47bf-ac72-a61684f86181      3702  zepto_2026_07_04
104  4778fa3d-0494-484a-b488-e2b40088ddd7      1273  zepto_2026_07_04
105  47cc42b0-3e50-42e3-bd10-0ecbf677c981      1181  zepto_2026_07_04
106  48ff71eb-60ab-412e-937c-cdef9b1d3a33      3926  zepto_2026_07_04
107  49879539-9538-42ca-b59e-952cdd73b506      1422  zepto_2026_07_04
108  49e487f6-07bf-48f9-b379-203f76c11964      3501  zepto_2026_07_04
109  4b54927e-5c54-4564-8c9f-1e518e6488e3      3613  zepto_2026_07_04
110  4b7f2491-a77d-4e8d-9317-08f5a29fc821      3644  zepto_2026_07_04
111  4be1c14d-98a6-42a7-aea9-488538abd03c      3791  zepto_2026_07_04
112  4c93e224-40da-4c86-a5ff-c9c2cfee1168      1261  zepto_2026_07_04
113  4db672ad-efd4-44f3-bd91-300233162d1c      3571  zepto_2026_07_04
114  4eeabcee-900c-419e-a2bb-102bbb205c7a      3320  zepto_2026_07_04
115  4f54ea62-0269-4b93-87cd-ef7ed796c6b1      2766  zepto_2026_07_04
116  4fd851db-0ec5-499e-9c7b-724a03966eb8      3110  zepto_2026_07_04
117  50be453c-91e9-4a62-913c-3d6add84eb57      3276  zepto_2026_07_04
118  5223893f-f150-4fb3-9f8b-2e86a7c15af1      1181  zepto_2026_07_04
119  52917883-e475-4632-9fa3-9c99ba0f4b78      3303  zepto_2026_07_04
120  5400933d-3c5d-4015-a767-daed27781a0d      3150  zepto_2026_07_04
121  542cf806-1216-4d13-b888-c3da22c20db0      1548  zepto_2026_07_04
122  553c9cfa-5a00-4b98-a1d5-152c813e12d2      3472  zepto_2026_07_04
123  554896ba-1bc3-493a-84c2-8a0ce07c2611      1298  zepto_2026_07_04
124  55b244f4-1068-4dfc-be57-0aee061bc311      3184  zepto_2026_07_04
125  56b34f56-7705-43b0-8fee-64125becba91      3636  zepto_2026_07_04
126  56d50978-df14-48ba-aec8-79644b36fd6a      1217  zepto_2026_07_04
127  57a0c2ae-1cf1-4c4a-99eb-eb2e19864075      2006  zepto_2026_07_04
128  581b1461-3a0b-4698-adb6-93a51207b2e1      3231  zepto_2026_07_04
129  58c5b67d-32d8-494a-8451-a720173b6b8e      3235  zepto_2026_07_04
130  59099ea0-3411-4169-9c90-206cb03ef12a      1263  zepto_2026_07_04
131  5bc98314-fe7f-490b-a41c-cb478ab34dd9      3507  zepto_2026_07_04
132  5c720bb8-ef8e-45c7-a249-be01de180a15      3669  zepto_2026_07_04
133  5c78735a-a78d-4d43-8cb1-9ba75215f8a7      1344  zepto_2026_07_04
134  5c849951-0ba3-4878-9b29-eb2d3ef252eb      3659  zepto_2026_07_04
135  5c85fffa-7130-43f2-9b34-0decc06beddc      3590  zepto_2026_07_04
136  5ca7734d-e625-4328-8588-a4a102966b36      3407  zepto_2026_07_04
137  5cc22671-70e0-4077-8f1c-5502c2c5522b      3245  zepto_2026_07_04
138  5d205066-36a5-4929-982a-7571c60f876b      3697  zepto_2026_07_04
139  5d427762-35fa-45f0-92b2-560b135fcba3      2602  zepto_2026_07_04
140  5d83d37a-c7fa-4891-b9dd-72c9d308f862      3522  zepto_2026_07_04
141  5d94bdb2-32fe-42f1-bc68-732d1d7ccb11       746  zepto_2026_07_04
142  5eb1e899-1cb8-4374-a4de-69cf86cc36cc      3346  zepto_2026_07_04
143  5ec071fd-78df-41f6-b3ae-7298d9f96a3d      3014  zepto_2026_07_04
144  5f267ad5-446b-4a8b-86f0-df174ad545dd      1977  zepto_2026_07_04
145  5f97e876-bbea-4c00-8df2-2005db7db8dc      3194  zepto_2026_07_04
146  60252717-a8c5-4891-9b23-3db778b14477      3052  zepto_2026_07_04
147  6252e437-b1f6-4ea7-9062-d90fba216c6f      1367  zepto_2026_07_04
148  627273fe-a446-443c-b412-1f09a9131a72      3588  zepto_2026_07_04
149  6355d6a1-48e0-48fb-a1fd-9cba4fb43086      1316  zepto_2026_07_04
150  63e5a81f-f326-48df-8250-1f28417a8ebc      3736  zepto_2026_07_04
151  64391366-c8d4-4b3d-961e-a632a6458d06      3630  zepto_2026_07_04
152  64ad2a25-3ff0-4a5a-b168-6b1593e38467      3719  zepto_2026_07_04
153  658cf319-0b10-4dbe-809e-ea5c913974cb      1470  zepto_2026_07_04
154  67053fe0-7be5-4caf-97d4-d7b0d96f36a7      2875  zepto_2026_07_04
155  67aa2c02-3b10-4736-b493-aad9f07d28e0      2903  zepto_2026_07_04
156  681003a8-bce8-4481-980d-8253746471e6      1533  zepto_2026_07_04
157  684a75ae-c944-480c-a64f-76a1a9cfa393      2956  zepto_2026_07_04
158  68737136-459b-40b1-82bd-64557d1d50f1      3440  zepto_2026_07_04
159  6893b298-d63b-4c4f-b155-2e4a0ca502d5      3325  zepto_2026_07_04
160  68c16fa4-b598-4f88-a656-a573186596c7      3170  zepto_2026_07_04
161  695b2cc3-3e79-4e8e-99dc-85ddfb90d256      3240  zepto_2026_07_04
162  6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a      1520  zepto_2026_07_04
163  6c71a1ae-262e-443c-879a-3efbdc6dd8f0      1508  zepto_2026_07_04
164  6ceb23b1-672d-4fd7-a89c-66163925a764      3185  zepto_2026_07_04
165  6cf381cd-d178-4bd1-8018-14218a4c0c0d      1457  zepto_2026_07_04
166  6d1f09eb-28f1-48b4-86c8-bcfa246c70fa      3781  zepto_2026_07_04
167  6e2378a8-458e-4aff-b783-80685cf86a43      2998  zepto_2026_07_04
168  6e46b50c-08d0-49c8-a89a-4d29ce4ed370      3673  zepto_2026_07_04
169  6e4a3fce-7d2e-4cf2-8dad-3ef5e9922bfb      2908  zepto_2026_07_04
170  6e8bac7d-b774-43ae-9fba-3a2c9ce4637a      3759  zepto_2026_07_04
171  700d1509-0a10-4ca8-87b9-f8c3e612fb5c      3298  zepto_2026_07_04
172  703ffbf1-6ea7-4223-815c-82f39176f6e8       256  zepto_2026_07_04
173  72655f9e-d9be-4b01-b2ac-62e61d2efd47      3326  zepto_2026_07_04
174  72a5dc2f-b97c-406d-b3e4-090e99736baf      3748  zepto_2026_07_04
175  7333c09a-d46f-4c45-845d-360e2ed38c8e      2678  zepto_2026_07_04
176  73b0c599-728d-4642-a0e3-1e5b68836327      1374  zepto_2026_07_04
177  74039f14-48e6-4a32-b70f-7ddda4c42900      3519  zepto_2026_07_04
178  74dfeece-0ec5-4b41-a83b-576add66078e      3260  zepto_2026_07_04
179  751c003c-bbe4-453d-ae3d-404380528149      2974  zepto_2026_07_04
180  75c44b6e-b7eb-4590-85db-6d5e51907bbf      3631  zepto_2026_07_04
181  7644b7fa-98d0-4bdd-a093-965dac5a807b      3446  zepto_2026_07_04
182  769200e9-30cc-47a2-81d4-58904ed953cc      3350  zepto_2026_07_04
183  76cae5a0-b75d-456b-9aab-df0b0b7559c2      1494  zepto_2026_07_04
184  7732ead5-8482-4815-9559-7f4cb2a72f3e      1365  zepto_2026_07_04
185  774a725c-2c4b-4dc2-94d1-72b737f7e1f6      1415  zepto_2026_07_04
186  777e8f7a-733e-49cc-8632-619c6723f077      2787  zepto_2026_07_04
187  778b5c2b-0468-4f1e-8fa0-241cc91608a2      1253  zepto_2026_07_04
188  77e44380-aa2a-4eeb-b923-24c653aa6732      3379  zepto_2026_07_04
189  796c71f3-568e-4d6d-8767-87285ad4f23a        29  zepto_2026_07_04
190  7a6201d1-93ae-4a45-bdb1-fbf73c1255a8      3694  zepto_2026_07_04
191  7aad3d3f-1dcc-4bad-baeb-d0640bf7ab86      1125  zepto_2026_07_04
192  7d1a958f-c3c0-498d-ac4f-1482550f08d4      3720  zepto_2026_07_04
193  7de4838b-ae7c-44d0-bf24-fb2040666654      3188  zepto_2026_07_04
194  7e698981-3429-454f-8dae-16347b53eeed      3784  zepto_2026_07_04
195  803931bb-511e-48bc-8611-4b9910682bb4      1270  zepto_2026_07_04
196  809ea1fc-cf81-4257-b2b5-7d53a911cae0      3619  zepto_2026_07_04
197  81822dd8-20a3-4da0-b460-671c9d1f6d27      3326  zepto_2026_07_04
198  81d2371c-4e12-4122-9799-f8c21807947d      1316  zepto_2026_07_04
199  82dffafa-bf7f-4752-a0b2-561dc1349c4a      3167  zepto_2026_07_04
200  8303b80f-8aea-4d15-9c54-ef1b3c12b6e5      3359  zepto_2026_07_04
201  83e33858-a13f-4c67-a016-07de0cce8043      3340  zepto_2026_07_04
202  843e630a-7896-462d-b7cf-712140483ed3      1433  zepto_2026_07_04
203  856f5f52-8b1c-4089-b242-6c5dd371777e      3196  zepto_2026_07_04
204  863ee650-1df1-418c-a988-2a64f2c555e3      3538  zepto_2026_07_04
205  88c4cd44-4d68-40af-af18-9fd8c8db3f39      2745  zepto_2026_07_04
206  89f3ad21-ce3d-41d6-a3f5-54563135c339      1241  zepto_2026_07_04
207  8a278c72-1366-4926-b81e-ecc6e64df2a7      1060  zepto_2026_07_04
208  8a71c5dd-fc7e-42e0-b56d-7d3b7df30187       784  zepto_2026_07_04
209  8a93c269-b281-4e2d-98b8-cce217827cd0      3162  zepto_2026_07_04
210  8b0413dd-9188-4002-951a-660ab5a35e7a       711  zepto_2026_07_04
211  8bbd3120-1502-4ab1-a042-10b6191176df      3717  zepto_2026_07_04
212  8c4a9155-85ec-409f-a9d8-84b193ec06ad      1342  zepto_2026_07_04
213  8c84e7ae-6e94-48f2-b4c8-af6c199aef1b      3486  zepto_2026_07_04
214  8dcc9bd0-fb05-42e9-96c7-ef15a999c522      1282  zepto_2026_07_04
215  8dde3f32-eae6-42e2-a9cc-ada2f0a9d22f      1463  zepto_2026_07_04
216  8ec659c9-2faa-4eba-ba2e-158ae485ebb4       793  zepto_2026_07_04
217  905a8ac5-fea2-4e5c-bf26-13d0bdac9478      2885  zepto_2026_07_04
218  9062036c-d6b8-4291-ae86-775d46774b56      3823  zepto_2026_07_04
219  913cea7d-879a-46d4-a31d-375e6272a237      2887  zepto_2026_07_04
220  913e4d9c-179c-43fc-b130-b0c9c39d3800      3782  zepto_2026_07_04
221  931f1ec1-e287-4412-9b52-df3f8ab9c95c       683  zepto_2026_07_04
222  93e0e2c3-23a6-471f-9025-8dd79ef87d60      1388  zepto_2026_07_04
223  946909f7-f694-4d3f-adf5-7ed81dfe612a      2202  zepto_2026_07_04
224  94a98275-e83a-4a25-ba73-690cbfaa1d55      1369  zepto_2026_07_04
225  94f50df3-fb2e-4c36-ad6f-8a00bfd1c6af      1506  zepto_2026_07_04
226  9550ef6d-d1b6-4eb1-b379-580404d9c1d3      3157  zepto_2026_07_04
227  95bc5024-3ef7-49b5-80a9-9c9df49638dc      3748  zepto_2026_07_04
228  973a6df0-7634-4291-be0d-cd48a816516b      3373  zepto_2026_07_04
229  97aa163f-d50f-4f8b-b76e-0bc21cc1c0c2      2691  zepto_2026_07_04
230  9b6c805a-0324-4d78-96c0-0e9c3dec81ff      3185  zepto_2026_07_04
231  9bb503dd-63be-4b26-b2ba-8fe51192d2bd      1584  zepto_2026_07_04
232  9bfb7127-8a86-4de2-968a-e7cd9d1b8d51      3178  zepto_2026_07_04
233  9d0727d9-8296-4b1f-adc1-80e720f049f5      3721  zepto_2026_07_04
234  9e330266-5ce4-4408-af82-5614f2b3b001      3957  zepto_2026_07_04
235  9e82a26c-9e78-4ea5-93a7-b0b077538621      3668  zepto_2026_07_04
236  9ea894e0-db78-45f7-beb1-10b6a52c3fb8      1076  zepto_2026_07_04
237  9eebbbc9-3fb9-45c1-ab71-312606cf9852      3160  zepto_2026_07_04
238  9f128d50-def8-471b-bc47-b041d95b885a      3209  zepto_2026_07_04
239  9f31c2fd-b593-4cb4-85a5-49a47163aa9a      2584  zepto_2026_07_04
240  9fb087cf-076d-40a0-b974-8d26eaa69f44      3193  zepto_2026_07_04
241  9fb7a7ca-e61c-4904-b339-749b6b45bf09      3717  zepto_2026_07_04
242  a0cc192c-a4e7-4671-aacd-ce6891b53bba      3744  zepto_2026_07_04
243  a16e98dd-a208-4aa2-9627-69eef07e8d69      3184  zepto_2026_07_04
244  a1e3515e-8dbb-4e71-b521-0b6ae27126be      2894  zepto_2026_07_04
245  a20f91f9-3e2c-48fd-a720-a6bf6685a6fe      3109  zepto_2026_07_04
246  a414c96e-6808-45f5-bdaf-1182485ac38c      3216  zepto_2026_07_04
247  a559802e-0aed-4cc4-9e51-8f49be9d968e      1512  zepto_2026_07_04
248  a58369d0-5902-4113-b0b7-58f4daae321e      3057  zepto_2026_07_04
249  a5d48a70-31d9-4c5f-b61f-daae4ab4e3b3      3310  zepto_2026_07_04
250  a7860f3d-39d4-4275-811d-904d4c2438f4      1325  zepto_2026_07_04
251  a7c548c8-f8e5-41c6-9462-1b4d7e8de41e      1445  zepto_2026_07_04
252  a935152c-9baa-46c1-b2ac-37701a227a19      3414  zepto_2026_07_04
253  a95989f3-34a1-4288-b318-a01c946b6919       123  zepto_2026_07_04
254  aa443b4b-bf3b-499c-a846-bf5196d444ae      3060  zepto_2026_07_04
255  aa4c6307-c5ae-46c8-8c4d-9750b2bf193f      3167  zepto_2026_07_04
256  ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5      3430  zepto_2026_07_04
257  abd85a95-f3f3-42fd-aeb0-71b9127335f5      1413  zepto_2026_07_04
258  abed156e-9d65-4438-86b9-5c5c4696cbb6      3433  zepto_2026_07_04
259  ac3f4c36-1bc5-4305-b093-f3100f7877ed      4012  zepto_2026_07_04
260  accc8ada-86f9-48fe-9d7a-098000985bee      3463  zepto_2026_07_04
261  ad87f09e-6b7e-40d4-99e7-2776aaf587a1      3507  zepto_2026_07_04
262  adec0623-e83c-46cc-9eef-d33b4486d054      3365  zepto_2026_07_04
263  ae984dc5-d33f-49cd-914c-d95d51f9e0ca      3343  zepto_2026_07_04
264  b0a2db37-733d-46d1-808b-7af068fc7f8a      1227  zepto_2026_07_04
265  b0f7b4fe-835a-4ca6-907c-20be2be7cc50      3121  zepto_2026_07_04
266  b26ca2be-f12b-4645-a83a-adf09ecfd28b       388  zepto_2026_07_04
267  b2daed2f-9d3a-495a-a005-a0b0bc04a445      3162  zepto_2026_07_04
268  b32bcacd-f047-47c1-a3b8-c1ccacf364a8      3656  zepto_2026_07_04
269  b32d0635-2a28-4694-99fd-b2220c4ada24      3113  zepto_2026_07_04
270  b463b5a9-6661-4ee9-b58b-03b285ac536e      3846  zepto_2026_07_04
271  b4d53703-4b49-4a38-85ca-7e321d1d5222      2805  zepto_2026_07_04
272  b4dc8d65-ed2e-4142-81b6-373982b13500      3070  zepto_2026_07_04
273  b6ac55e9-9d60-4ea1-86b8-fe554ea1490c      1642  zepto_2026_07_04
274  b7c3c400-9275-4d75-afa3-62e0a6abfaac      3348  zepto_2026_07_04
275  b812518e-9cc3-45e3-8fef-a1dd3311194c      1428  zepto_2026_07_04
276  b8d61fbc-eb4a-4836-b785-e3b63aa3fa62      2861  zepto_2026_07_04
277  b8f93707-6d8d-4c31-8b58-627f09ba83cf      1456  zepto_2026_07_04
278  b916220e-7ace-4784-bdbf-a359f4411fa3      3209  zepto_2026_07_04
279  b9438b1f-1c27-4708-855d-f1b31b36186d      3096  zepto_2026_07_04
280  b9641f44-b385-4cbd-816e-6dceeff911b0      3371  zepto_2026_07_04
281  baa090fc-be13-4b34-87c5-2aea256fd4c4      3102  zepto_2026_07_04
282  badfd8b4-f39a-41ec-8f0a-4f86184f0953      1198  zepto_2026_07_04
283  bb713aac-cd12-4b4d-9026-704e3deaaac3      3336  zepto_2026_07_04

In [13]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [15]:
for name, df in dfs.items():

    print("\n",name)

    print(
        df["city"]
        .value_counts()
    )

 zepto_2026_07_04
city
Bangalore                    143769
Hyderabad                    130638
Mumbai                        97070
Chennai                       64877
Noida                         58013
Gurgaon                       57178
Delhi                         56647
Kolkata                       48950
Jaipur                        34092
Pune                          32363
Ghaziabad                     28080
Lucknow                       24681
Ahmedabad                     22038
Coimbatore                    18122
Kochi                         11872
Nashik                        11502
Chandigarh                    10977
Ludhiana                      10884
Faridabad                     10686
Vijayawada                    10551
Madurai                        7605
Dehradun                       7455
Kanpur                         7188
Nagpur                         7163
Prayagraj                      7157
Indore                         7120
Surat                          7116
Panipat                        6974
Mysuru                         6967
Navi Mumbai                    5219
S.A.S Nagar                    4512
Sonipat                        4091
Belagavi                       4012
Davanagere                     3997
Haridwar                       3957
Warangal                       3926
Udaipur                        3785
Vadodara                       3784
Varanasi                       3784
Hubballi                       3782
Puducherry                     3736
Meerut                         3721
Rajkot                         3719
Ambala                         3694
Gorakhpur                      3675
Bareilly                       3636
Valsad                         3463
Chhatrapati Sambhajinagar      3462
Rewari                         3443
Panchkula                      3209
Amritsar                       3096
Phagwara                       2956
Kalyan-Dombivli                2879
Kalamassery                     182
Name: count, dtype: int64

 zepto_2026_07_07
city
Bangalore          188844
Mumbai             154911
Hyderabad          134696
Chennai             81320
Pune                74172
Kolkata             71856
Ahmedabad           28239
Dehradun            18543
Faridabad           18503
Indore              17864
Coimbatore          15108
Meerut              14357
Jalandhar           13387
Nashik              11818
Nagpur              11178
Jaipur              10622
Chandigarh          10434
Prayagraj            9054
Greater Noida        7862
Ambala               7721
Palakkad             7583
Rajkot               7531
S.A.S Nagar          7530
Kochi                7501
Surat                7353
Vadodara             7337
Ludhiana             7326
Vijayawada           7145
Kanpur               7133
Kharar               7090
Panchkula            6553
Navi Mumbai          4433
Sonipat              4083
Mysuru               4001
Haridwar             3940
Hubballi             3908
Guntur               3881
Davanagere           3857
Puducherry           3748
Kota                 3732
Madurai              3718
Patiala              3718
Panipat              3705
Amritsar             3548
Gorakhpur            3528
Dera Bassi           3462
Kalyan-Dombivli      2893
Bhiwandi             2778
Name: count, dtype: int64

 zepto_2026_07_08
city
Bangalore                    201792
Mumbai                       144070
Hyderabad                    126604
Chennai                       98108
Pune                          50959
Kolkata                       32559
Kanpur                        22707
Kochi                         19311
Ahmedabad                     18061
Nagpur                        17714
Jaipur                        16634
Mysuru                        15327
Faridabad                     15105
Surat                         14776
Indore                        14554
Nashik                        11320
Vadodara                      11297
S.A.S Nagar                   11220
Vijayawada                    10963
Coimbatore                    10549
Warangal                       7703
Agra                           7640
Udaipur                        7593
Mohali                         7559
Madurai                        7434
Amritsar                       7306
Bareilly                       7256
Vasai Virar                    6614
Ludhiana                       6549
Secunderabad                   4464
Kurukshetra                    4040
Tumakuru                       3992
Navi Mumbai                    3970
Karimnagar                     3872
Palakkad                       3824
Prayagraj                      3805
Patiala                        3765
Kota                           3732
Bhiwadi                        3709
Chhatrapati Sambhajinagar      3703
Gorakhpur                      3675
Panchkula                      3657
Haridwar                       3563
Bidhan Nagar                   3507
Nandivaram Guduvancheri        3478
Chandigarh                     3460
Valsad                         3460
Rewari                         3449
Meerut                         3439
Ambarnath                      3215
Behta Hajipur                  3112
Thrippunithura                 3100
Barasat                        2773
Sankhol                        2702
Anand                          2521
Vrindavan                      2385
Mathura                        2360
Name: count, dtype: int64

 zepto_2026_07_09
city
Bangalore                    190604
Hyderabad                    155005
Mumbai                       131639
Pune                          84923
Chennai                       84666
Kolkata                       53118
Ahmedabad                     25497
Surat                         25241
Faridabad                     23319
Jaipur                        18103
Ludhiana                      14758
Mysuru                        14739
Jalandhar                     11570
Dehradun                      11459
Varanasi                      11027
Mohali                         7998
Vellore                        7869
Belagavi                       7837
Hubballi                       7605
Kochi                          7493
Thane                          7487
Karimnagar                     7398
Chhatrapati Sambhajinagar      7238
Prayagraj                      7164
Kanpur                         7129
Panipat                        6979
Agra                           6968
Kalyan                         4205
Davanagere                     3996
Puducherry                     3992
Patiala                        3973
Udaipur                        3877
Nagpur                         3855
Gorakhpur                      3804
Saharanpur                     3790
Karnal                         3777
Coimbatore                     3760
Vadodra                        3757
Nashik                         3755
Vijayawada                     3751
Guntur                         3745
Kurukshetra                    3724
Mehsana                        3690
Hosur                          3683
Gandhinagar                    3660
Bareilly                       3649
S.A.S Nagar                    3609
Hisar                          3501
Indore                         3462
Kota                           3338
Chandigarh                     3246
Navsari                        3171
Amritsar                       3109
Phagwara                       3011
Ulhasnagar                     2877
Talegaon Dabhade               2875
Name: count, dtype: int64

 zepto_2026_07_10
city
Delhi        259829
Noida        146268
Gurgaon      103648
Ghaziabad     85742
Lucknow       64759
Jaipur        51159
Name: count, dtype: int64

 zepto_2026_07_14
city
Delhi        342705
Gurgaon      166003
Noida        143352
Lucknow       99485
Ghaziabad     85770
Jaipur        43762
Name: count, dtype: int64

 zepto_2026_07_15
city
Bangalore        126721
Hyderabad         69118
Mumbai            66661
Chennai           57143
Pune              50162
Kolkata           25884
Surat             14649
Indore            14129
Mysuru            11240
Nagpur            10935
Ahmedabad         10607
Coimbatore         7460
Nashik             7448
Kochi              7431
Prayagraj          6199
Greater Noida      4271
Sonipat            4051
Haridwar           3908
Karnal             3746
Udaipur            3732
Vijayawada         3707
Hubballi           3705
Patiala            3687
Bhiwadi            3645
Panipat            3635
Bareilly           3573
Madurai            3555
S.A.S Nagar        3455
Dehradun           3358
Jalandhar          3273
Faridabad          3267
Kota               3262
Agra               3195
Barasat            2940
Name: count, dtype: int64

 zepto_2026_07_16
city
Bangalore          99045
Hyderabad          75245
Mumbai             67305
Chennai            45380
Kolkata            29102
Pune               28990
Jaipur             18250
Faridabad          15550
Surat              14436
Nagpur             10896
Ahmedabad          10799
Kanpur             10796
Prayagraj          10394
Nashik              7463
Mysuru              7278
Ludhiana            6790
Vasai Virar         6573
Amritsar            6393
Greater Noida       4549
Behta Hajipur       4529
S.A.S Nagar         4435
Secunderabad        4401
Dehradun            4086
Hubballi            3908
Udaipur             3750
Karimnagar          3697
Hosur               3676
Kharar              3498
Chandigarh          3467
Jalandhar           3292
Navsari             3161
Coimbatore          3152
Meerut              3054
Kalyan-Dombivli     2892
Name: count, dtype: int64

 zepto_2026_07_20
city
Bangalore                  128717
Chennai                     66834
Mumbai                      62212
Hyderabad                   56113
Pune                        26405
Faridabad                   15796
Kolkata                     14435
Ahmedabad                   13905
Jaipur                      11640
S.A.S Nagar                 11519
Varanasi                    10982
Karimnagar                   7550
Coimbatore                   7400
Dehradun                     7343
Jalandhar                    7045
Surat                        6969
Chandigarh                   6908
Thane                        4409
Karnal                       4096
Navi Mumbai                  3981
Puducherry                   3978
Meerut                       3967
Patiala                      3952
Guntur                       3890
Vellore                      3873
Kalyan                       3757
Warangal                     3757
Palakkad                     3757
Agra                         3676
Gandhinagar                  3666
Mehsana                      3656
Panchkula                    3656
Nagpur                       3646
Vijayawada                   3583
Vadodara                     3546
HAPUR                        3440
Nandivaram Guduvancheri      3436
Kanpur                       3367
Phagwara                     3051
Mathura                      3044
Bhiwandi                     2828
Secunderabad                 2322
Name: count, dtype: int64

 zepto_2026_07_21
city
Mumbai                       99787
Bangalore                    83692
Hyderabad                    62279
Pune                         33993
Chennai                      26077
Kolkata                      21216
Ahmedabad                    18239
Jaipur                       14676
Coimbatore                   10819
Surat                         7681
Faridabad                     7626
Kochi                         7526
Vijayawada                    7488
Rajkot                        7468
Dehradun                      7422
Ludhiana                      7157
Chandigarh                    6909
Panchkula                     6569
Kalamassery                   4406
Thane                         4118
Kurukshetra                   4018
Tumakuru                      3988
Kanpur                        3951
Vellore                       3936
Amritsar                      3897
Agra                          3831
Udaipur                       3812
Davanagere                    3789
Prayagraj                     3780
Gorakhpur                     3763
Guntur                        3746
Vadodra                       3730
Kota                          3683
Ambala                        3669
Chhatrapati Sambhajinagar     3665
Indore                        3638
Mohali                        3618
Kharar                        3607
Bareilly                      3597
Madurai                       3584
Haridwar                      3555
Jalandhar                     3555
Vrindavan                     3109
Thrippunithura                3095
Ghaziabad                     3017
Sankhol                       2753
Name: count, dtype: int64

 zepto_2026_07_22
city
Delhi      342191
Gurgaon    101348
Name: count, dtype: int64

 zepto_2026_07_23
city
Delhi    165326
Name: count, dtype: int64

In [16]:
for name, df in dfs.items():

    print("\n",name)

    print(
        df["department"]
        .value_counts()
    )

 zepto_2026_07_04
department
Beauty & Cosmetics      170644
Personal Care           156382
Baby Care               141434
Dairy & Breakfast       114853
Organic & Premium       112800
Cold Drinks & Juices     92494
Bakery & Biscuits        79453
Sweet Tooth              77042
Munchies                 50866
Atta, Rice & Dal         41487
Name: count, dtype: int64

 zepto_2026_07_07
department
Beauty & Cosmetics      170012
Personal Care           156673
Baby Care               136158
Dairy & Breakfast       116735
Organic & Premium       116567
Cold Drinks & Juices     93711
Bakery & Biscuits        80102
Sweet Tooth              79767
Munchies                 51940
Atta, Rice & Dal         41839
Name: count, dtype: int64

 zepto_2026_07_08
department
Beauty & Cosmetics      168568
Personal Care           153398
Baby Care               136134
Organic & Premium       113805
Dairy & Breakfast       113343
Cold Drinks & Juices     91875
Bakery & Biscuits        78933
Sweet Tooth              77751
Munchies                 50454
Atta, Rice & Dal         41755
Name: count, dtype: int64

 zepto_2026_07_09
department
Beauty & Cosmetics      170479
Personal Care           157615
Baby Care               136091
Dairy & Breakfast       117024
Organic & Premium       116955
Cold Drinks & Juices     94292
Sweet Tooth              81463
Bakery & Biscuits        80761
Munchies                 52283
Atta, Rice & Dal         42512
Name: count, dtype: int64

 zepto_2026_07_10
department
Beauty & Cosmetics      107223
Personal Care           101501
Dairy & Breakfast        88392
Baby Care                82058
Organic & Premium        80101
Cold Drinks & Juices     69056
Sweet Tooth              57993
Bakery & Biscuits        57743
Munchies                 37520
Atta, Rice & Dal         29818
Name: count, dtype: int64

 zepto_2026_07_14
department
Beauty & Cosmetics      127994
Personal Care           118692
Dairy & Breakfast       113777
Organic & Premium       101711
Baby Care                94469
Cold Drinks & Juices     87413
Sweet Tooth              75498
Bakery & Biscuits        74460
Munchies                 48649
Atta, Rice & Dal         38414
Name: count, dtype: int64

 zepto_2026_07_15
department
Beauty & Cosmetics      91710
Personal Care           80190
Baby Care               76430
Organic & Premium       61213
Dairy & Breakfast       61166
Cold Drinks & Juices    49080
Bakery & Biscuits       42372
Sweet Tooth             42210
Munchies                27134
Atta, Rice & Dal        22247
Name: count, dtype: int64

 zepto_2026_07_16
department
Beauty & Cosmetics      88421
Personal Care           76834
Baby Care               72880
Organic & Premium       58495
Dairy & Breakfast       58330
Cold Drinks & Juices    46911
Bakery & Biscuits       40598
Sweet Tooth             40284
Munchies                26129
Atta, Rice & Dal        21350
Name: count, dtype: int64

 zepto_2026_07_20
department
Beauty & Cosmetics      92518
Personal Care           80355
Baby Care               76146
Organic & Premium       60992
Dairy & Breakfast       60579
Cold Drinks & Juices    49041
Bakery & Biscuits       42255
Sweet Tooth             41120
Munchies                27121
Atta, Rice & Dal        21980
Name: count, dtype: int64

 zepto_2026_07_21
department
Beauty & Cosmetics      91210
Personal Care           77140
Baby Care               72717
Organic & Premium       59773
Dairy & Breakfast       59649
Cold Drinks & Juices    48151
Bakery & Biscuits       41508
Sweet Tooth             40910
Munchies                26709
Atta, Rice & Dal        21767
Name: count, dtype: int64

 zepto_2026_07_22
department
Beauty & Cosmetics      63024
Personal Care           60681
Dairy & Breakfast       57928
Organic & Premium       52099
Baby Care               46774
Cold Drinks & Juices    45125
Bakery & Biscuits       37341
Sweet Tooth             36357
Munchies                24528
Atta, Rice & Dal        19682
Name: count, dtype: int64

 zepto_2026_07_23
department
Beauty & Cosmetics      25600
Personal Care           23169
Baby Care               21181
Dairy & Breakfast       20084
Organic & Premium       18444
Cold Drinks & Juices    16345
Bakery & Biscuits       14035
Sweet Tooth             10648
Munchies                 8513
Atta, Rice & Dal         7307
Name: count, dtype: int64

In [17]:
for name, df in dfs.items():

    print("\n",name)

    print(
        df["category"]
        .value_counts()
    )

 zepto_2026_07_04
category
Skincare                     98629
Dairy, Bread & Eggs          70444
Baby Care                    68881
Toys & Sports                64053
Atta, Rice, Oil & Dals       63267
Bath & Body                  63010
Cold Drinks & Juices         62576
Ice Creams & More            61396
Munchies                     58750
Biscuits                     54813
Hair Care                    44387
Sweet Cravings               43199
Packaged Food                42500
Makeup & Beauty              41954
Breakfast & Sauces           41780
Feminine Hygiene             38551
Masala, Dry Fruits & More    33320
Tea, Coffee & More           33064
Fragrances & Grooming        26556
Pharma & Wellness             9294
Frozen Food                   6494
Zepto Cafe                    4979
Electronics & Appliances      4677
Home Needs                     490
Stationery & Books             238
Unlisted1                       84
Protein & Nutrition             65
Paan Corner                      4
Name: count, dtype: int64

 zepto_2026_07_07
category
Skincare                     97790
Dairy, Bread & Eggs          70862
Baby Care                    67427
Atta, Rice, Oil & Dals       64193
Cold Drinks & Juices         63759
Ice Creams & More            63088
Bath & Body                  62957
Toys & Sports                60396
Munchies                     60320
Biscuits                     55300
Hair Care                    44573
Sweet Cravings               44550
Breakfast & Sauces           42566
Packaged Food                42524
Makeup & Beauty              41729
Feminine Hygiene             39138
Masala, Dry Fruits & More    34328
Tea, Coffee & More           33689
Fragrances & Grooming        26521
Pharma & Wellness             9510
Frozen Food                   6857
Zepto Cafe                    6045
Electronics & Appliances      4560
Home Needs                     419
Stationery & Books             230
Unlisted1                      110
Protein & Nutrition             63
Name: count, dtype: int64

 zepto_2026_07_08
category
Skincare                     96967
Dairy, Bread & Eggs          68461
Baby Care                    67491
Atta, Rice, Oil & Dals       63717
Cold Drinks & Juices         62847
Bath & Body                  61667
Ice Creams & More            61471
Toys & Sports                60429
Munchies                     58518
Biscuits                     54460
Hair Care                    44145
Sweet Cravings               44118
Packaged Food                41691
Breakfast & Sauces           41592
Makeup & Beauty              41197
Feminine Hygiene             38189
Masala, Dry Fruits & More    33442
Tea, Coffee & More           32970
Fragrances & Grooming        26126
Pharma & Wellness             9147
Frozen Food                   6415
Zepto Cafe                    5428
Electronics & Appliances      4685
Home Needs                     429
Stationery & Books             235
Unlisted1                      110
Protein & Nutrition             69
Name: count, dtype: int64

 zepto_2026_07_09
category
Skincare                     97874
Dairy, Bread & Eggs          71154
Baby Care                    67427
Atta, Rice, Oil & Dals       64941
Cold Drinks & Juices         64149
Ice Creams & More            64149
Bath & Body                  63374
Munchies                     60721
Toys & Sports                60484
Biscuits                     55888
Sweet Cravings               45402
Hair Care                    44536
Breakfast & Sauces           42746
Packaged Food                42584
Makeup & Beauty              41603
Feminine Hygiene             39596
Masala, Dry Fruits & More    34491
Tea, Coffee & More           33748
Fragrances & Grooming        26827
Pharma & Wellness             9584
Frozen Food                   6765
Zepto Cafe                    5903
Electronics & Appliances      4748
Home Needs                     402
Stationery & Books             215
Unlisted1                      103
Protein & Nutrition             61
Name: count, dtype: int64

 zepto_2026_07_10
category
Skincare                     63317
Dairy, Bread & Eggs          57518
Ice Creams & More            45826
Atta, Rice, Oil & Dals       45651
Cold Drinks & Juices         44911
Bath & Body                  43419
Munchies                     43022
Baby Care                    42983
Biscuits                     39040
Toys & Sports                35486
Sweet Cravings               32012
Breakfast & Sauces           30908
Packaged Food                29793
Hair Care                    29184
Feminine Hygiene             26707
Makeup & Beauty              24811
Masala, Dry Fruits & More    24538
Tea, Coffee & More           23356
Fragrances & Grooming        17494
Frozen Food                   5016
Zepto Cafe                    3096
Electronics & Appliances      2147
Pharma & Wellness             1074
Home Needs                      76
Stationery & Books              15
Jewellery                        5
Name: count, dtype: int64

 zepto_2026_07_14
category
Dairy, Bread & Eggs          74038
Skincare                     73059
Ice Creams & More            58956
Atta, Rice, Oil & Dals       58287
Cold Drinks & Juices         57063
Munchies                     55759
Bath & Body                  52292
Biscuits                     50126
Baby Care                    49166
Sweet Cravings               41617
Toys & Sports                40738
Breakfast & Sauces           40088
Packaged Food                37947
Hair Care                    35929
Feminine Hygiene             32376
Masala, Dry Fruits & More    31129
Tea, Coffee & More           29970
Makeup & Beauty              28949
Fragrances & Grooming        21276
Frozen Food                   6229
Zepto Cafe                    3377
Electronics & Appliances      2100
Pharma & Wellness              601
Jewellery                        5
Name: count, dtype: int64

 zepto_2026_07_15
category
Skincare                     53610
Baby Care                    37625
Dairy, Bread & Eggs          37004
Toys & Sports                34757
Bath & Body                  34131
Atta, Rice, Oil & Dals       34113
Cold Drinks & Juices         33530
Ice Creams & More            32738
Munchies                     31461
Biscuits                     29245
Hair Care                    24429
Sweet Cravings               23869
Packaged Food                22614
Breakfast & Sauces           22533
Makeup & Beauty              22217
Feminine Hygiene             20744
Masala, Dry Fruits & More    18012
Tea, Coffee & More           17611
Fragrances & Grooming        13725
Frozen Food                   3528
Zepto Cafe                    3065
Electronics & Appliances      2810
Pharma & Wellness              381
Name: count, dtype: int64

 zepto_2026_07_16
category
Skincare                     51360
Baby Care                    35977
Dairy, Bread & Eggs          35409
Toys & Sports                32842
Atta, Rice, Oil & Dals       32581
Bath & Body                  32340
Cold Drinks & Juices         31682
Ice Creams & More            30973
Munchies                     30193
Biscuits                     27960
Hair Care                    23420
Sweet Cravings               23265
Packaged Food                21762
Breakfast & Sauces           21634
Makeup & Beauty              21531
Feminine Hygiene             20128
Masala, Dry Fruits & More    17208
Tea, Coffee & More           16964
Fragrances & Grooming        13433
Frozen Food                   3530
Zepto Cafe                    2987
Electronics & Appliances      2685
Pharma & Wellness              368
Name: count, dtype: int64

 zepto_2026_07_20
category
Skincare                     54065
Baby Care                    37285
Dairy, Bread & Eggs          36552
Toys & Sports                34819
Bath & Body                  34004
Atta, Rice, Oil & Dals       33837
Cold Drinks & Juices         33724
Ice Creams & More            31694
Munchies                     31370
Biscuits                     29271
Hair Care                    24535
Sweet Cravings               23867
Makeup & Beauty              22479
Breakfast & Sauces           22357
Packaged Food                22228
Feminine Hygiene             21110
Masala, Dry Fruits & More    17843
Tea, Coffee & More           17614
Fragrances & Grooming        13712
Frozen Food                   3691
Electronics & Appliances      2964
Zepto Cafe                    2700
Pharma & Wellness              377
Stationery & Books               9
Name: count, dtype: int64

 zepto_2026_07_21
category
Skincare                     52420
Baby Care                    36019
Dairy, Bread & Eggs          35740
Atta, Rice, Oil & Dals       33137
Cold Drinks & Juices         32808
Toys & Sports                32723
Bath & Body                  32663
Ice Creams & More            31374
Munchies                     30772
Biscuits                     28772
Hair Care                    24103
Sweet Cravings               23394
Makeup & Beauty              22427
Breakfast & Sauces           22230
Packaged Food                21929
Feminine Hygiene             20557
Masala, Dry Fruits & More    17680
Tea, Coffee & More           17460
Fragrances & Grooming        13533
Frozen Food                   3708
Zepto Cafe                    2890
Electronics & Appliances      2761
Pharma & Wellness              424
Stationery & Books              10
Name: count, dtype: int64

 zepto_2026_07_22
category
Skincare                     37568
Dairy, Bread & Eggs          37068
Atta, Rice, Oil & Dals       30254
Cold Drinks & Juices         29766
Ice Creams & More            28477
Munchies                     27904
Bath & Body                  26838
Biscuits                     25151
Baby Care                    24454
Sweet Cravings               21453
Breakfast & Sauces           20210
Toys & Sports                20179
Packaged Food                18836
Hair Care                    17050
Masala, Dry Fruits & More    16066
Feminine Hygiene             15973
Tea, Coffee & More           14959
Makeup & Beauty              13698
Fragrances & Grooming        10986
Frozen Food                   3623
Zepto Cafe                    1454
Electronics & Appliances      1228
Pharma & Wellness              318
Stationery & Books              25
Jewellery                        1
Name: count, dtype: int64

 zepto_2026_07_23
category
Skincare                     15778
Dairy, Bread & Eggs          12884
Baby Care                    11304
Atta, Rice, Oil & Dals       11206
Cold Drinks & Juices         10652
Bath & Body                   9838
Munchies                      9652
Biscuits                      9507
Toys & Sports                 8977
Ice Creams & More             8469
Sweet Cravings                7087
Breakfast & Sauces            6995
Packaged Food                 6990
Hair Care                     6661
Feminine Hygiene              5748
Makeup & Beauty               5740
Masala, Dry Fruits & More     5628
Tea, Coffee & More            5320
Fragrances & Grooming         4124
Frozen Food                   1334
Zepto Cafe                     684
Electronics & Appliances       588
Pharma & Wellness              146
Stationery & Books              14
Name: count, dtype: int64

In [18]:
for name, df in dfs.items():

    print("\n",name)

    print(
        df["sub_category"]
        .value_counts()
    )

 zepto_2026_07_04
sub_category
Face Wash & Scrubs            25144
Face Creams & Gels            14707
Chips & Crisps                14530
Toothbrush & More             14319
Rice & More                   13593
Body Lotion & Moisturizer     13463
Chocolates                    11968
Perfumes                      10918
Tubs                          10709
Sticks                        10413
Baby Bath                      9921
Premium Chocolates             9501
Dry Fruits & Nuts Munchies     9356
Namkeens                       9221
Gifting                        9106
Cones                          8994
Cups                           8779
Sun Care                       8757
Cookies                        8715
Energy Bars                    8699
Baking Mixes & Ingredients     8632
Cold Coffee & Iced Tea         8622
Milk Drinks                    8606
Besan, Sooji & Maida           8566
Dry Fruits & Nuts              8550
Honey & Spreads                8532
Breakfast Cereals              8505
Cheese                         8491
Sanitary Pads                  8480
Popcorn                        8472
Handwash & Sanitizers          8470
Tea                            8463
Peanut Butter                  8440
Cakes, Sandwiches & More       8429
Soaps                          8416
Nachos                         8401
Muesli & Oats                  8392
Dals & Pulses                  8382
Atta                           8371
Deos & Roll Ons                8345
Toothpaste                     8334
Oil                            8315
Soft Drinks                    8311
Dates & Seeds                  8300
Papads, Pickles & Chutney      8295
Baby Diapering                 8293
Noodles & Vermicelli           8284
Ketchup & Sauces               8278
Face Care                      8278
Salt, Sugar & Jaggery          8270
Shampoo                        8266
Fruit Juices & Drinks          8253
Pastries & Cakes               8244
Creamfills                     8239
Hair Color                     8162
Whole Spices & Seasonings      8152
Breads & Buns                  8140
Soda & Mixers                  8135
Candies, Gums & Mints          8125
Energy Drink                   8014
Millets & Other Flours         8011
Infant Food                    8011
Ghee                           8003
Crackers                       7984
Coffee                         7973
Rusk & Khari                   7972
Green & Herbal Tea             7967
Milk                           7964
Period Panties                 7904
Eye Makeup                     7892
Mouthwash                      7871
Eye & Lip Care                 7854
Conditioner & Masks            7733
Shower Gels                    7729
Talcum Powder                  7705
Kulfi                          7648
Hair Removal For Women         7641
Baby Oral Care                 7626
Face Makeup                    7593
Instant Drink Mixes            7591
Nails                          7565
Yogurt & Shrikhand             7544
Glucose & Marie                7520
Beauty Accessories             7520
Batters & Mixes                7442
Ready To Cook                  7421
Digestives                     7367
Soft Toys                      7269
Serums & Essence               7264
Hair Oil                       7257
Hair Serum & Polish            7237
Paneer & Cream                 7177
Baby Wipes                     7167
Sports & Fitness               7144
Baby Skin & Hair Care          7117
Vegan Drinks                   7074
Wafers                         6990
Butter                         6847
Eggs                           6782
Educational Toys & Sports      6625
Water                          6530
Men's Grooming                 6515
Sausages, Salami & Ham         6372
Baby Health                    6302
Lips Makeup                    6208
Card & Board Games             6196
Hair Styling                   6171
Electronic Toys & Vehicle      6114
Ice Cubes & Ice Pops           5974
Baby Hygiene                   5521
Baby Feeding                   5516
Indian Mithai                  5321
Milk Based Drinks              5123
Bath Accessories               4936
Curd & Probiotic Drink         4847
Grooming                       4833
Activities & Outdoor Toys      4705
Toners & Mists                 4702
Doll & Play Set                4612
Body Care                      4548
Toddler                        4175
Baby & Mom Gifting             4152
Hand & Feet Care               3998
Blocks & Puzzles               3959
Action Figures                 3836
Panty Liners                   3753
Tampons                        3674
Art & Craft                    3625
Intimate Care                  3241
Musical Instruments            3148
Musical Accessories            2883
Mom Care                       2800
Snacks                         2151
Toilet Hygiene                 2094
Infant Clothing                2049
Baby & Toddler Food            1824
Baby Gear                      1508
Period Pain Relief             1432
Baby Safety                    1203
Cold Beverages                 1033
Tea & Coffee                    756
Ready To Eat                    450
Sandwiches                      399
Ayurveda                        336
Personal Safety                 332
Rehydration & Electrolytes      313
Bakery                          286
Hair Tools & Accessories        160
Sides                           130
Powders & Pastes                125
Veg Snacks                      122
Italian                         102
Vitamin Supplements              82
Healthy                          60
Asian                            59
Indian Breads                    25
Toothpaste & Mouthwash           23
Dessert Mixes                    22
Hydration Drinks                 15
Sets                              4
Desserts                          3
Name: count, dtype: int64

 zepto_2026_07_07
sub_category
Face Wash & Scrubs            25041
Chips & Crisps                14916
Face Creams & Gels            14783
Toothbrush & More             14047
Rice & More                   13488
Body Lotion & Moisturizer     13307
Chocolates                    12544
Tubs                          11186
Perfumes                      10815
Sticks                        10586
Baby Bath                      9966
Premium Chocolates             9964
Dry Fruits & Nuts Munchies     9703
Namkeens                       9485
Cups                           9333
Cones                          9317
Sun Care                       8948
Cookies                        8922
Energy Bars                    8893
Cakes, Sandwiches & More       8758
Cold Coffee & Iced Tea         8747
Dry Fruits & Nuts              8728
Milk Drinks                    8720
Handwash & Sanitizers          8718
Sanitary Pads                  8716
Cheese                         8708
Baking Mixes & Ingredients     8700
Toothpaste                     8700
Tea                            8683
Soaps                          8681
Honey & Spreads                8669
Besan, Sooji & Maida           8663
Popcorn                        8658
Breakfast Cereals              8657
Dates & Seeds                  8624
Atta                           8589
Peanut Butter                  8587
Nachos                         8586
Fruit Juices & Drinks          8584
Oil                            8567
Muesli & Oats                  8554
Baby Diapering                 8535
Noodles & Vermicelli           8512
Deos & Roll Ons                8511
Whole Spices & Seasonings      8493
Ketchup & Sauces               8452
Papads, Pickles & Chutney      8444
Salt, Sugar & Jaggery          8434
Face Care                      8421
Gifting                        8420
Dals & Pulses                  8420
Creamfills                     8354
Shampoo                        8310
Ghee                           8283
Soft Drinks                    8262
Pastries & Cakes               8261
Breads & Buns                  8256
Candies, Gums & Mints          8223
Hair Color                     8216
Soda & Mixers                  8200
Coffee                         8185
Milk                           8173
Eye Makeup                     8169
Millets & Other Flours         8165
Rusk & Khari                   8141
Period Panties                 8106
Energy Drink                   8044
Green & Herbal Tea             8035
Crackers                       8022
Conditioner & Masks            7863
Talcum Powder                  7832
Kulfi                          7830
Shower Gels                    7813
Mouthwash                      7799
Yogurt & Shrikhand             7783
Hair Removal For Women         7781
Eye & Lip Care                 7778
Instant Drink Mixes            7771
Infant Food                    7733
Baby Oral Care                 7675
Face Makeup                    7627
Glucose & Marie                7570
Nails                          7501
Batters & Mixes                7452
Beauty Accessories             7408
Digestives                     7357
Serums & Essence               7320
Vegan Drinks                   7285
Hair Serum & Polish            7273
Ready To Cook                  7262
Baby Wipes                     7224
Soft Toys                      7207
Hair Oil                       7192
Sports & Fitness               7142
Paneer & Cream                 7123
Baby Skin & Hair Care          7093
Butter                         6956
Wafers                         6898
Water                          6790
Eggs                           6777
Sausages, Salami & Ham         6717
Men's Grooming                 6507
Educational Toys & Sports      6499
Baby Health                    6297
Lips Makeup                    6161
Electronic Toys & Vehicle      6064
Hair Styling                   6062
Card & Board Games             6001
Ice Cubes & Ice Pops           5641
Indian Mithai                  5507
Baby Feeding                   5387
Baby Hygiene                   5137
Milk Based Drinks              4904
Curd & Probiotic Drink         4745
Grooming                       4733
Bath Accessories               4720
Toners & Mists                 4388
Activities & Outdoor Toys      4326
Doll & Play Set                4247
Body Care                      4229
Toddler                        3797
Baby & Mom Gifting             3758
Panty Liners                   3753
Hand & Feet Care               3674
Blocks & Puzzles               3655
Tampons                        3643
Action Figures                 3500
Intimate Care                  3162
Art & Craft                    2983
Musical Instruments            2728
Snacks                         2637
Musical Accessories            2477
Mom Care                       2471
Toilet Hygiene                 2175
Baby & Toddler Food            1835
Infant Clothing                1810
Period Pain Relief             1437
Cold Beverages                 1326
Baby Gear                      1225
Baby Safety                    1103
Tea & Coffee                    803
Sandwiches                      501
Ready To Eat                    437
Bakery                          354
Personal Safety                 353
Ayurveda                        332
Rehydration & Electrolytes      326
Hair Tools & Accessories        177
Sides                           148
Veg Snacks                      140
Italian                         125
Powders & Pastes                119
Healthy                          78
Asian                            68
Vitamin Supplements              56
Hydration Drinks                 24
Dessert Mixes                    15
Tampons & Menstrual Cups         12
Indian Breads                     7
Desserts                          5
Name: count, dtype: int64

 zepto_2026_07_08
sub_category
Face Wash & Scrubs            24498
Face Creams & Gels            14714
Chips & Crisps                14450
Rice & More                   13798
Toothbrush & More             13699
Body Lotion & Moisturizer     13099
Chocolates                    12381
Tubs                          10783
Perfumes                      10583
Sticks                        10229
Baby Bath                      9874
Premium Chocolates             9714
Dry Fruits & Nuts Munchies     9430
Namkeens                       9224
Cones                          9052
Cups                           8988
Sun Care                       8924
Gifting                        8791
Cookies                        8733
Energy Bars                    8662
Baking Mixes & Ingredients     8595
Milk Drinks                    8594
Cold Coffee & Iced Tea         8590
Besan, Sooji & Maida           8586
Honey & Spreads                8498
Dry Fruits & Nuts              8488
Sanitary Pads                  8479
Cakes, Sandwiches & More       8472
Atta                           8466
Cheese                         8455
Peanut Butter                  8450
Muesli & Oats                  8440
Fruit Juices & Drinks          8434
Tea                            8429
Soaps                          8428
Baby Diapering                 8427
Breakfast Cereals              8424
Popcorn                        8418
Dates & Seeds                  8399
Handwash & Sanitizers          8377
Oil                            8369
Toothpaste                     8350
Dals & Pulses                  8327
Face Care                      8304
Deos & Roll Ons                8287
Nachos                         8283
Papads, Pickles & Chutney      8266
Whole Spices & Seasonings      8256
Noodles & Vermicelli           8227
Soft Drinks                    8227
Salt, Sugar & Jaggery          8224
Pastries & Cakes               8220
Creamfills                     8193
Shampoo                        8186
Candies, Gums & Mints          8147
Soda & Mixers                  8132
Ketchup & Sauces               8102
Hair Color                     8089
Coffee                         8082
Ghee                           8078
Millets & Other Flours         8076
Breads & Buns                  8041
Milk                           8011
Eye Makeup                     7992
Crackers                       7955
Energy Drink                   7910
Rusk & Khari                   7887
Period Panties                 7858
Green & Herbal Tea             7824
Conditioner & Masks            7747
Eye & Lip Care                 7744
Shower Gels                    7697
Mouthwash                      7662
Instant Drink Mixes            7641
Kulfi                          7638
Talcum Powder                  7631
Hair Removal For Women         7628
Infant Food                    7626
Glucose & Marie                7554
Baby Oral Care                 7523
Yogurt & Shrikhand             7440
Face Makeup                    7426
Batters & Mixes                7425
Serums & Essence               7399
Digestives                     7326
Nails                          7319
Beauty Accessories             7310
Hair Serum & Polish            7260
Baby Wipes                     7248
Ready To Cook                  7184
Soft Toys                      7157
Hair Oil                       7144
Baby Skin & Hair Care          7132
Vegan Drinks                   7063
Sports & Fitness               7033
Paneer & Cream                 6959
Water                          6791
Wafers                         6774
Butter                         6584
Men's Grooming                 6547
Eggs                           6502
Educational Toys & Sports      6343
Baby Health                    6276
Sausages, Salami & Ham         6274
Hair Styling                   6090
Lips Makeup                    6084
Card & Board Games             6082
Electronic Toys & Vehicle      6068
Ice Cubes & Ice Pops           5859
Indian Mithai                  5606
Baby Feeding                   5383
Baby Hygiene                   5250
Grooming                       4857
Bath Accessories               4660
Curd & Probiotic Drink         4558
Milk Based Drinks              4489
Toners & Mists                 4346
Body Care                      4322
Activities & Outdoor Toys      4256
Doll & Play Set                4190
Toddler                        3842
Baby & Mom Gifting             3808
Blocks & Puzzles               3729
Hand & Feet Care               3720
Tampons                        3687
Action Figures                 3621
Panty Liners                   3555
Intimate Care                  3042
Art & Craft                    2993
Musical Instruments            2817
Mom Care                       2567
Musical Accessories            2533
Snacks                         2493
Toilet Hygiene                 2183
Infant Clothing                1875
Baby & Toddler Food            1756
Period Pain Relief             1401
Baby Gear                      1258
Baby Safety                    1142
Cold Beverages                 1000
Tea & Coffee                    734
Sandwiches                      471
Ready To Eat                    450
Personal Safety                 356
Ayurveda                        336
Bakery                          336
Rehydration & Electrolytes      309
Hair Tools & Accessories        166
Powders & Pastes                143
Sides                           143
Veg Snacks                      141
Italian                         121
Healthy                          65
Asian                            61
Vitamin Supplements              48
Hydration Drinks                 13
Dessert Mixes                    10
Desserts                          4
Indian Breads                     2
Name: count, dtype: int64

 zepto_2026_07_09
sub_category
Face Wash & Scrubs            24967
Chips & Crisps                15086
Face Creams & Gels            14724
Toothbrush & More             13991
Rice & More                   13809
Body Lotion & Moisturizer     13312
Chocolates                    12823
Tubs                          11213
Perfumes                      10912
Sticks                        10751
Premium Chocolates            10101
Baby Bath                     10037
Dry Fruits & Nuts Munchies     9762
Namkeens                       9549
Cones                          9504
Cups                           9483
Sun Care                       9050
Cookies                        8980
Energy Bars                    8931
Cakes, Sandwiches & More       8859
Handwash & Sanitizers          8807
Sanitary Pads                  8798
Cold Coffee & Iced Tea         8796
Toothpaste                     8792
Besan, Sooji & Maida           8791
Milk Drinks                    8790
Dry Fruits & Nuts              8780
Baking Mixes & Ingredients     8757
Cheese                         8752
Soaps                          8744
Tea                            8733
Honey & Spreads                8711
Dates & Seeds                  8704
Breakfast Cereals              8697
Popcorn                        8695
Atta                           8688
Fruit Juices & Drinks          8648
Peanut Butter                  8639
Nachos                         8634
Baby Diapering                 8633
Muesli & Oats                  8616
Deos & Roll Ons                8597
Oil                            8576
Dals & Pulses                  8518
Gifting                        8514
Whole Spices & Seasonings      8488
Salt, Sugar & Jaggery          8463
Noodles & Vermicelli           8461
Papads, Pickles & Chutney      8453
Face Care                      8445
Ketchup & Sauces               8430
Creamfills                     8407
Shampoo                        8346
Milk                           8303
Ghee                           8296
Breads & Buns                  8296
Soda & Mixers                  8262
Millets & Other Flours         8244
Pastries & Cakes               8228
Soft Drinks                    8222
Candies, Gums & Mints          8201
Hair Color                     8198
Coffee                         8172
Energy Drink                   8170
Rusk & Khari                   8154
Eye Makeup                     8154
Period Panties                 8144
Crackers                       8132
Green & Herbal Tea             7999

In [19]:
summary = []

for name, df in dfs.items():
    summary.append({
        "Date": name.replace("zepto_", ""),
        "Rows": len(df),
        "Cities": df["city"].nunique(),
        "Stores": df["store_id"].nunique(),
        "Store Locations": df["store_name_location"].nunique(),
        "Departments": df["department"].nunique(),
        "Categories": df["category"].nunique(),
        "Sub Categories": df["sub_category"].nunique(),
        "Brands": df["brand_name"].nunique(),
        "Unique Products (unique_id)": df["unique_id"].nunique(),
        "Unique URLs": df["product_url"].nunique()
    })

summary_df = pd.DataFrame(summary)

summary_df

,Date,Rows,Cities,Stores,Store Locations,Departments,Categories,Sub Categories,Brands,Unique Products (unique_id),Unique URLs
0,2026_07_04,1037455,54,381,292,10,28,161,1766,17349,17351
1,2026_07_07,1043504,48,375,295,10,27,160,1687,16351,16351
2,2026_07_08,1026016,57,357,287,10,27,159,1714,17374,17374
3,2026_07_09,1049475,56,369,291,10,27,159,1697,16566,16566
4,2026_07_10,711405,6,253,259,10,26,158,1226,8855,8855
5,2026_07_14,881077,6,310,292,10,24,159,1222,8824,8825
6,2026_07_15,553752,34,206,147,10,23,159,1622,14936,14940
7,2026_07_16,530232,34,198,146,10,23,159,1624,14804,14804
8,2026_07_20,552107,42,196,146,10,24,159,1626,15827,15827
9,2026_07_21,539534,46,194,147,10,24,160,1680,16636,16636
10,2026_07_22,443539,2,159,148,10,25,158,1099,7229,7231
11,2026_07_23,165326,1,63,60,10,24,150,939,5508,5508