### Data loading

In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [3]:
df = pd.read_csv(r"/home/user/Documents/zepto_2026_07_08.csv",low_memory=False)
df.head()

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-07-08 00:06:07,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,fbd26605-0200-4b3e-834b-bded506a1c31,234d874b-8d10-459f-b645-d3cb2fed0e6f,Baby Care,Packaged Food,Baby & Toddler Food,NaN,Happa,Happa Apple | Banana Puree,NaN,100 g,NaN,1 pc (100 g),NaN,99.0,99.0,No,No,99.0,NaN,No offer,99.0,0,4,https://www.zepto.com/pn/happa-apple-banana-puree/pvid/fbd26605-0200-4b3e-834b-bded506a1c31,NaN
1,2026-07-08 00:06:07,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,90f8967b-e6f6-40d4-a0e0-ea25eddc9f9e,5fe0046b-8ad2-4030-9dba-d4d5a6d3d358,Baby Care,Packaged Food,Baby & Toddler Food,NaN,Happa,Happa Apple | Mango | Multigrain Puree,NaN,100 g,NaN,1 pc (100 g),NaN,99.0,92.0,No,Yes,92.0,NaN,₹7 OFF,92.0,7,6,https://www.zepto.com/pn/happa-apple-mango-multigrain-puree/pvid/90f8967b-e6f6-40d4-a0e0-ea25eddc9f9e,NaN
2,2026-07-08 00:06:08,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,af27062e-f619-4749-9a25-d1196f93b01a,75ecd229-d2fa-4de5-b411-83cfcf444bee,Baby Care,Packaged Food,Baby & Toddler Food,NaN,Happa,Happa Super Puffs Strawberry | Banana,NaN,40 g,NaN,1 pc (40 g),NaN,179.0,165.0,No,Yes,165.0,NaN,₹14 OFF,165.0,7,1,https://www.zepto.com/pn/happa-super-puffs-strawberry-banana/pvid/af27062e-f619-4749-9a25-d1196f93b01a,NaN
3,2026-07-08 00:06:08,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,b72e7ea9-b336-4e2a-b30a-c4ea018ce3d6,b75fc4b5-1d9f-4ece-a81e-fdc7114e43ea,Baby Care,Packaged Food,Baby & Toddler Food,NaN,Nestle Nutrition,Nestle Ceregrow No Refined Sugar Multigrain Cereal,NaN,300 g,NaN,1 pack (300 g),NaN,299.0,299.0,No,No,299.0,NaN,No offer,299.0,0,4,https://www.zepto.com/pn/nestle-ceregrow-no-refined-sugar-multigrain-cereal/pvid/b72e7ea9-b336-4e2a-b30a-c4ea018ce3d6,NaN
4,2026-07-08 00:06:08,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,f0d07a8e-8089-4722-a605-7c8ba2bae85a,b37453ad-cc86-45bf-ba7a-2573228879ec,Baby Care,Packaged Food,Baby & Toddler Food,NaN,Nestle Nutrition,Nestle Nangrow Nutritious Milk drink for growing children | 2-6 Years,NaN,800 g,NaN,1 pack (800 g),NaN,1110.0,1054.0,No,Yes,1054.0,NaN,₹56 OFF,1054.0,5,3,https://www.zepto.com/pn/nestle-nangrow-nutritious-milk-drink-for-growing-children-2-6-years/pvid/f0d07a8e-8089-4722-a605-7c8ba2bae85a,NaN

### Data analysis

In [4]:
df.shape

(1026016, 31)

In [7]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1026016 entries, 0 to 1026015
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1026016 non-null  object
 1   platform_name            1026016 non-null  object
 2   store_id                 1026016 non-null  object
 3   store_name_location      1026016 non-null  object
 4   city                     1026016 non-null  object
 5   pin_code                 1026016 non-null  int64
 6   unique_id                1026016 non-null  object
 7   product_id_upc_ean       1026016 non-null  object
 8   department               1026016 non-null  object
 9   category                 1026016 non-null  object
 10  sub_category             1026016 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1026016 non-null  object
 13  product_name             1026016 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         839625 non-null   object
 16  package_type             0 non-null        float64
 17  net_quantity             1026016 non-null  object
 18  variants                 27856 non-null    object
 19  item_mrp                 1026016 non-null  float64
 20  item_selling_price       1026016 non-null  float64
 21  out_of_stock_flag        1026016 non-null  object
 22  discount_flag            1026016 non-null  object
 23  product_price            1026016 non-null  float64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1026016 non-null  object
 26  promo_offer_price        1026016 non-null  float64
 27  discount_in_percent      1026016 non-null  int64
 28  stock_count              1026016 non-null  int64
 29  product_url              1026016 non-null  object
 30  product_image_urls       0 non-null        float64
dtypes: float64(9), int64(3), object(19)
memory usage: 242.7+ MB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.nunique()

crawl_date_and_time        17859
platform_name                  1
store_id                     357
store_name_location          287
city                          57
pin_code                     248
unique_id                  17374
product_id_upc_ean         16857
department                    10
category                      27
sub_category                 159
product_type                   0
brand_name                  1714
product_name               15478
product_description            0
product_grammage            1092
package_type                   0
net_quantity                2145
variants                     349
item_mrp                    1203
item_selling_price          2212
out_of_stock_flag              2
discount_flag                  2
product_price               2212
unit_price                     0
promo_offer_description     1547
promo_offer_price           2212
discount_in_percent           93
stock_count                   58
product_url                17374
product_image_urls             0
dtype: int64

In [10]:
df.isnull().sum()

crawl_date_and_time              0
platform_name                    0
store_id                         0
store_name_location              0
city                             0
pin_code                         0
unique_id                        0
product_id_upc_ean               0
department                       0
category                         0
sub_category                     0
product_type               1026016
brand_name                       0
product_name                     0
product_description        1026016
product_grammage            186391
package_type               1026016
net_quantity                     0
variants                    998160
item_mrp                         0
item_selling_price               0
out_of_stock_flag                0
discount_flag                    0
product_price                    0
unit_price                 1026016
promo_offer_description          0
promo_offer_price                0
discount_in_percent              0
stock_count                      0
product_url                      0
product_image_urls         1026016
dtype: int64

In [11]:
df.city.unique()

array(['Mumbai', 'Hyderabad', 'Kochi', 'Chennai', 'Pune', 'Bangalore',
       'Mysuru', 'Patiala', 'Prayagraj', 'Ludhiana', 'Kanpur', 'Warangal',
       'Panchkula', 'Kolkata', 'Meerut', 'Indore', 'Jaipur',
       'Chhatrapati Sambhajinagar', 'Ahmedabad', 'Anand', 'Vijayawada',
       'Agra', 'Coimbatore', 'Surat', 'Barasat', 'Vrindavan', 'Rewari',
       'Vadodara', 'Vasai Virar', 'Mohali', 'S.A.S Nagar', 'Bhiwadi',
       'Behta Hajipur', 'Faridabad', 'Ambarnath', 'Mathura', 'Madurai',
       'Udaipur', 'Haridwar', 'Kota', 'Thrippunithura', 'Kurukshetra',
       'Karimnagar', 'Navi Mumbai', 'Secunderabad', 'Amritsar', 'Valsad',
       'Nashik', 'Nagpur', 'Palakkad', 'Chandigarh',
       'Nandivaram Guduvancheri', 'Tumakuru', 'Bareilly', 'Bidhan Nagar',
       'Sankhol', 'Gorakhpur'], dtype=object)

In [13]:
pin_check = (
    df.groupby("store_name_location")["pin_code"]
        .nunique()
        .sort_values(ascending=False)
)

pin_check[pin_check > 1]

Series([], Name: pin_code, dtype: int64)

In [15]:
check = (
    df.groupby("store_name_location")
    .agg(
        store_ids=("store_id", "nunique"),
        cities=("city", "nunique"),
        pincodes=("pin_code", "nunique")
    )
)

check[check["store_ids"] > 1]

,store_ids,cities,pincodes
store_name_location,,,
"1, Dattani Park Rd, Thakur, Dattani Park, Thakur Village, Kandivali East, Mumbai, Maharashtra, 400066, India",2,1,1
"126, MM Road, Pulikeshi Nagar, Bengaluru, Karnataka, 560005, India",2,1,1
"2, Mumbai Cantral Rd, Dadal Estate, Bane Compound, Tardeo, Mumbai, Maharashtra, 400034, India",2,1,1
"2-1-676, 1st Phase Allwyn Colony, Allwyn Colony, Kukatpally, Hyderabad, Telangana, 500072, India",2,1,1
"20, 5th Cross Rd, Jagruthi Colony, Bob Colony, JP Nagar 7th Phase, J. P. Nagar, Bengaluru, Karnataka, 560078, India",2,1,1
"39, 2nd Main Rd, Classic Orchards Layout, Kalena Agrahara, Bengaluru, Karnataka, 560076, India",2,1,1
"43, Rd Number, 26, Spring Mill Complex, Wadala, Mumbai, Maharashtra, 400031, India",2,1,1
"64-10, Kanakapura Rd, Umarbagh Layout, Banashankari Temple Ward, Bengaluru, Karnataka, 560078, India",2,1,1
"74/9, 3rd Main Rd, Jakkasandra, 1st Block Koramangala, Koramangala, Bengaluru, Karnataka, 560034, India",2,1,1
"9 Star Family Restaurant & Bakers, Bachupally, Hyderabad, Telangana, 500090, India",2,1,1
"Aakruthi Sunshine Apartment, Aakruthi Sunshine, Panathur Main Rd, Kaverappa Layout, Kadubeesanahalli, Bengaluru, Karnataka, 560103, India",2,1,1
"Aalekha, Bengaluru, BEML Layout 3rd Stage, RajaRajeshwari Nagar, Bengaluru, Karnataka, 560098, India",2,1,1
"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",2,1,1
"Adhithyaa EnterPrises, Samathapuri Colony, New Nagole Colony, Samathapuri, Kothapet, Hyderabad, Telangana, 500035, India",2,1,1
"Aeromarine Private Limited, 20, Jawahar Industrial Estate, Opposite To Mcdonald, Near J.K. Industries, Jawahar Co-Op Ind, Kamothe, Panvel, Navi Mumbai, Maharashtra, 410209, India",2,1,1
"Ajab Shahar, 146, Kasturba Nagar, Nirman Nagar, Brijlalpura, Jaipur, Rajasthan, 302019, India",2,1,1
"Akshaya Ashraya Apartment, 23, Flour Mill Rd, Raviprakash Nagar, Konena Agrahara, Murgesh Pallya, Bengaluru, Karnataka, 560017, India",2,1,1
"Albertsons International Private Limited, 104, Richmond Town Tower, 12, Richmond Rd, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka, 560025, India",2,1,1
"Andies Hotels And Restaurants Pvt Ltd, SCO 55 Golden Green Market, Sector 124, Sahibzada Ajit Singh Nagar, Punjab, 140301, India",2,1,1
"Anuj Industrial Park, Yadav Nagar, Dahisar East, Mumbai, Maharashtra, 400068, India",2,1,1
"Apoorvam (B Desai Group), B/h, Vandemataram Icon, Opposite Prathna Elegance, Near By Aaryan City, Gota, Ahmedabad, Gujarat, 382481, India",2,1,1
"Asha Turf, Press Bazar, Ulhasnagar, Maharashtra, 421002, India",2,1,1
"BESCOM, 11, Begur - Hulimavu Rd, Krishna Layout, Hulimavu, Bengaluru, Karnataka, 560076, India",2,1,1
"Bagara Biryani Cafe, R. Narayanapura, Whitefield, Gandhipura, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560066, India",2,1,1
"Bali Residency CHS Ltd, Marve Rd, Malad, Kharodi Village, Malad West, Mumbai, Maharashtra, 400067, India",2,1,1
"Belgium Metal Godown, Kausar Baugh Rd, Kausar Baugh, Kondhwa, Pune, Maharashtra, 411048, India",2,1,1
"Bharat Petroleum Monorail Station, Azad Nagar, Chembur, Mumbai, Maharashtra 400074",2,1,1
"BigBasket JP Nagar 5K Hub, Santrupthi Nagar, JP Nagar 7th Phase, Arekere, Bengaluru, Karnataka, 560078, India",2,1,1
"C.B. Chajed & Company, Old Prabhadevi Rd, Dadar West, Century Bazaar, Prabhadevi, Mumbai, Maharashtra, 400025, India",2,1,1
"Can Heritage - Canara Bank Quarters, Lal Bahadur Shastri Marg, Chandan Nagar, Vikhroli West, Mumbai, Maharashtra, 400079, India",2,1,1
"Comfort Stay, Lohegaon, Pune, Maharashtra, 411047, India",2,1,1
"Devdarshan, Mogul LN, New Dinkar Co Operative Housing Society, Mahim, Mumbai, Maharashtra, 400016, India",2,1,1
"Dlpluxury PG For Ladies, 10th 'A' Mian Rd, 3rd Cross, Near Metro Station Indira Nagar, Stage 1, IndiraNagar, Bengaluru, Karnataka, 560038, India",2,1,1
"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",2,1,1
"Empire Restaurant, 8, 1, Hennur Main Rd, Kothanur, Bengaluru, Karnataka, 560077, India",2,1,1
"GFC Gowdru Biriyani, 20, Teachers Colony, Chikkabidarakallu, Bengaluru, Karnataka, 560073, India",2,1,1
"GM Infinite E City Phase 1 B Block, Block-F, GM Infinite, Thirupalya Main Rd, Thirupalya, Bommasandra, Karnataka, 560099, India",2,1,1
"Gachiboli APHB Colony MiG 91, APHB Colony, JV Colony, Chhota Anjaiah Nagar, Gachibowli, Hyderabad, Telangana, 500032, India",2,1,1
"Ghanshyam Super Market, Brig Syed Rd, SAIL Colony, Bowenpally, Secunderabad, Telangana, 500009, India",2,1,1
"Glam Salon Makeup And Nail Academy, 442, 7th Main, Mallathalli Lake Road, Bangalore 56, Mallathahalli Lake Rd, Bengaluru, Karnataka 560056",2,1,1
"Golden Tobacco Limited, Tobacco House, S.V. Road, Vile Parle (West), Navpada, Vile Parle West, Mumbai, Maharashtra, 400049, India",2,1,1
"Gopalan Gardenia, Chikka Thogu, Konappana Agrahara, Electronic City, Bengaluru, Karnataka, 560100, India",3,1,1
"Govind Villa, Kishore Tupe House, 18.511329, 73.411036, Chandan Nagar, Malwadi, Hadapsar, Pune, Maharashtra",2,1,1
"Gulf Bakers, 2-3-578/1, 2, & 3, SriNivas Heights, Minister Rd, Beside KIMS Hospital, Krishna Nagar Colony, Ramgopalpet, Secunderabad, Hyderabad, Telangana, 500003, India",2,1,1
"Haji Ebrahim Restaurant, National Highway 544, Pathadipalam, Koonamthai Pathadipalam Residence Association Block A, Pathadipalam, Edappally, Kochi, Kerala, 682033, India",2,1,1
"Horizontal UniSex Skin And Hair Studio, No#45 Beerappa Layout, K.S. Halli Road, Opp. Shoba Lake Garden, Virgonagar Industrial Estate, Medahalli, Bengaluru, Karnataka, 560049, India",2,1,1
"Hotel Silver Inn, Mandir Marg, Gopalpura Mode, Siddharth Nagar, Sector 9, Durgapura, Jaipur, Rajasthan 302017, India",2,1,1
"Hyundai Charging Station, The Pavailion, 177/3, Bannerghatta Rd, Dollars Colony, Phase 4, J. P. Nagar, Bengaluru, Karnataka, 560078, India",2,1,1
"IndusInd Bank, Block Bangalore, 208, 80 Feet Rd, HBR Layout 2nd Block, 1st Stage, HBR Layout, Bengaluru, Karnataka, 560043, India",2,1,1
"Instamart Ravet, Dr, Dy Patil Rd, Ravet, Pune, Pimpri-Chinchwad, Maharashtra, 412101, India",2,1,1
"Jeeva Stores, Shop No.3, 243, SH 49, Rajendra Garden, Bismillah Nagar, Narayana Nagar, Vettuvankeni, Chennai, Tamil Nadu, 600115, India",2,1,1
"Juhu Gaon Marg, Juhu Nagar, Juhu Village, Sector 11, Vashi, Navi Mumbai, Maharashtra, 400703, India",2,1,1
"Jupiter Computers, 45a/1, Central Rd, Bidhanpally, Jadavpur, Kolkata, West Bengal, 700032, India",2,1,1
"Kabra Paradise, D.N.Nagar, Andheri West, Mumbai, Maharashtra, 400058, India",2,1,1
"Kamini Krafts, 20, Khetani Industrial Estate, 106/7, Bazar Ward, Sonapur LN, Near Ashok Leyland, Kurla West, Kurla, Mumbai, Maharashtra, 400070, India",2,1,1
"Kanelones Bakers, Deepthi Sree Nagar Rd, Deepthi Sri Nagar Colony, Madinaguda, Sri Durga Colony, Miyapur, Telangana, 500050, India",2,1,1
"Kia Car Showroom - Shaw Kia, Bandra East, Bharti Compound, 167, V.N Marg, Near Audi West Workshop, Kolivery Village, MMRDA Area, Kalina, Santacruz East, Opposite Ferrari Showrooom, Block G, Bandra East, Mumbai, Maharashtra 400098",2,1,1
"Kp'S Restaurant, 411036, Matruchhaya Building, Poonawalla Road, Sasane Colony, Keshav Nagar, Mundhwa, Pune, Maharashtra",2,1,1
"Krisala Rizzz, Nora Society, Sector R17b, Life Republic Township, Tathawade, Pimpri-Chinchwad, Maharashtra 411033, India",3,1,1
"Kurlon EnterPrises Ltd, 689, Vallathol Junction, Thrikkakara, Kollamkudimugal, Mundampalam, Ernakulam, Kakkanad, Kerala, 682037, India",2,1,1
"Lake View County Approach Road, Lake View County Approach Rd, AECS C Block, Begur, Bengaluru, Karnataka, 560114, India",2,1,1
"Lal Chand Girdhari Lal, Mill Store, Ambala Chandigarh Barwala Chowk, Bhagat Singh Nagar, Dera Bassi, Punjab, 140507, India",2,1,1
"Le Luxe Apartment, Le Luxe Horta Homes, Gopanapalli Thanda, Nalagandla, Telangana, 500019, India",2,1,1
"Lenskart.Com At L P Savani Road, Surat, Shop No 6B, Shivalik Western, Subhash Chandra Bose Marg, TGB, Adajan Gam, Adajan, Surat, Gujarat, 395009, India",2,1,1
"Limra Steel Furniture, Mahboob Colony, Syed Ali Guda, Hyderabad, Telangana, 500028, India",2,1,1
"Lodha Golf Course, Casa Bella, Casa Bella Gold, Casa Bella, Casa Bella Gold, Nilje Gaon, Maharashtra, 421204, India",2,1,1
"MG Motor India - Service Center, S No 136/137 Majiwada, Near Universal Petrol Pump, Subhash Nagar, Thane West, Thane, Maharashtra, 400610, India",2,1,1
"MGL Turbhe Store, 7, Railway Yard, Sector 19F, Vashi, Navi Mumbai, Maharashtra, 400703, India",2,1,1
"Machaxi Ahalya Sports Centre (Swimming, Badminton, Football, Cricket), Near Manyata Tech Park Gate 4 & 5, Rachenahalli Main Road, Mesthri Palya, Rachenahalli, Thanisandra, Bengaluru, Karnataka, 560045, India",2,1,1
"Madishetty Srikanth, Srinagar Colony, Bolarum, Secunderabad, Telangana, 500010, India",2,1,1
"Magnate Icon, New Ranip, Ahmedabad, Gujarat, 382470, India",2,1,1
"Marathon Monte Carlo, Opposite P&t Colony, Near Samriddhi Banquet Hall, Off LBS Rd, Madan Mohan Malviya Road, Asha Nagar, Mulund West, Mumbai, Maharashtra, 400080, India",2,1,1
"Milkman Street, Milkman St, Langford Town, Shanti Nagar, Bengaluru, Karnataka, 560025, India",2,1,1
"Mumtaz Function Palace, Ramkoti, King Koti, Hyderguda, Telangana, 500001, India",2,1,1
"Nano Hospitals, Uttarahalli, No. 47 12/1A Uttarahalli Main Rd Near Bharat Petrol Bunk Simhadri Layout Uttarahalli Hobli Bengaluru Karnataka 560061",2,1,1
"National Mime Institute, 7 Block, CK Block, Sector II, Bidhannagar, Kolkata, West Bengal, 700091, India",2,1,1
"National Public School Kengeri Junior Wing, 9, 4th Cross Rd, 1st Block, Sir M Vishveswaraya Layout, Nagdevanahalli, Bengaluru, Ramasandra, Karnataka, 560056, India",2,1,1
"New Ganesh Nagar, Nandivali Gaon, Kalyan, Maharashtra, 421306, India",2,1,1
"Nikki Nagar, Khadakpada, Kalyan, Maharashtra, 421301, India",2,1,1
"Nine 2 Twelve Khana Ghar Jaisa, Marathahalli Village, Marathahalli, Bengaluru, Karnataka, 560037, India",3,1,1
"Ovum Hospitals, Outer Ring Road Katriguppe Bangalore South Bengaluru Urban Karnataka 560085 India",2,1,1
"Patel Cargo Packers, 865, Ghodbunder Rd, Patlipada, Thane West, Thane, Maharashtra, 400607, India",2,1,1
"Pavithra Toolings, Jayachamarajendra Industrial Estate, Kumaraswamy Layout, Bengaluru, Karnataka, 560111, India",2,1,1
"Physiotattva Bannerghatta Road, 05 & 10, 2nd Floor, Syndicate Bank Colony, OmKar Nagar, Hulimavu, Bengaluru, Karnataka, 560076, India",2,1,1
"Pimple Nilakh Bus Depot, Panchasheel Nagar, Pimple Nilakh, Pimpri-Chinchwad, Maharashtra 411027, India",3,1,1
"Prime Gardens, Moti Nagar Phase III, Kalyan Nagar, Moti Nagar, Hyderabad, Telangana, 500018, India",2,1,1
"Prospero, Building, D P Farm, Road, Tulaja Bhawani Nagar, Kharadi, Pune, Maharashtra, 411014, India",2,1,1
"RR Living Grand Hotel, Mahalneknapur, Manikonda, Hyderabad, Telangana 500089, India",2,1,1
"Ramanuja Credit Co Op Soc Limited, No 22, Seshadri Rd, Lakshmanpuri, Gandhi Nagar, Bengaluru, Karnataka, 560009, India",2,1,1
"Reliance Smart SuperStore, No 6/7, Ground Floor, RamChandra LN, Malad, Moti Udyog Nagar, Kanchpada, Malad West, Mumbai, Maharashtra 400064, India",2,1,1
"Rising Stars Music & Arts Academy, Apartments, Above Ghanshyam Super Market, 5th Floor, Flat No: 508, Opp:, Janapriya Utopia Rd, Hyderguda, Gumma Konda Colony, Hyderabad, Telangana, 500048, India",2,1,1
"Royale Sapphire Suites, 513, Whitefield Rd, Maheswari Nagar, Puttappa Layout, Mahadevapura, Bengaluru, Karnataka, 560048, India",2,1,1
"Royalmart SuperMarket RR Nagar, No.2460/266/3, Halagevaderahalli, Halagevaderahalli Village Kengeri, Hobli, Remco Bhel Layout, Kenchenhalli, RajaRajeshwari Nagar, Bengaluru, Karnataka, 560098, India",2,1,1
"SK.Khan Car Service Point, Agrahara Layout, Yelahanka Taluku, Bengaluru Urban, Karnataka, 560064, India",2,1,1
"SLV Tea Store, Electronics City Phase 1, Electronic City, Bengaluru, Karnataka, 560100, India",2,1,1
"SM Grand Mart, 43, Silver County Rd, Lakedew Residency- Phase 2, Haralur, Karnataka, 560068, India",2,1,1
"Saggi Solutions, House No. 76, M.G Layout, Mullur Rd, Bengaluru, Karnataka, 560035, India",2,1,1
"Sai Ram Men's Hostel, 7, Kennedy St, West Tambaram, Tambaram, Chennai, Tamil Nadu 600045, India",2,1,1
"Samriddhi-Early Learning Center, 302 N Hanumantha Reddy BLG, Opp Vinayaka Layout, Doddathogur, Electronics City Phase 1, Electronic City, Bengaluru, Karnataka, 560100, India",2,1,1
"Sangme Digital Production, Sri Venkateshvar Lauout Abbigere Shettihalli Ward Number 12, Kereguddadahalli, Chikkabanavara, Bengaluru, Karnataka, 560090, India",2,1,1
"Saqi (Bar & Kitchen), First Floor 10/A, Raj Kutir Apartment, Railway Station, 3rd Street, Near Unicontinental Hotel, Khar, Ram Krishna Nagar, Khar West, Mumbai, Maharashtra, 400052, India",2,1,1
"Saroj Whitesands Apartment, 4, Gear School Rd, Adarsh Palm Retreat, Doddakannelli, Bengaluru, Karnataka, 560103, India",2,1,1
"Satyas Sunrise, Road No. 16, Ayyappa Society, Mega Hills, Madhapur, Hyderabad, Telangana, 500081, India",2,1,1
"Selvi Sweets And Bakery, East Coast Road, No:53, 23, Avvai Nagar Rd, Vasudeva Nagar Extension, Thiruvanmiyur, Chennai, Tamil Nadu, 600041, India",2,1,1
"Shree Sai EnterPrises, Dombala, Panvel, Navi Mumbai, Maharashtra, 410206, India",2,1,1
"Shree TVS Service Centre, Podu Main Rd, Bettadasanapura, Bengaluru, Karnataka, 560100, India",2,1,1
"Sohini IT Tech Park, Financial District, Nanakaramguda, Telangana, 500032, India",2,1,1
"Southindia Properties SIP Ikon, Kelambakkam, Chennai, Kelambakkam, Chennai, 603103, India",2,1,1
"Sri Lakshmi Narasimha Nilayam, 42, 1st Main Rd, Balaji Layout, Green Woods Layout, Varanasi, Bengaluru, Karnataka, 560049, India",2,1,1
"Sri Mathaji Papad, No1 A 1st Cross Street, Indira Nagar East 1st St, Selaiyur, Chennai, Tamil Nadu, 600126, India",2,1,1
"Sri Padmavathi School, Sai Ram Enclave, Naredra Nagar Rd, Ameenpur Village, Ameenpur, Miyapur, Telangana, 502032, India",2,1,1
"Sri Srinivasa Creations, 17th Main Road, 9th Cross, 19th Main Rd, Riehs Layout, JC Nagar, Kurubarahalli, Basaweshwara Nagar, Bengaluru, Karnataka, 560086, India",2,1,1
"Sripathi Solutions, Devi Padmasree Convention Backside, Balaji Hills Rd, Nagaarjun Colony, Mallikarjuna Nagar, Boduppal, Hyderabad, Telangana, 500092, India",2,1,1
"Standard Electricals Co, Shop No 4, Bhavani Complex, Opposite To Alpine Super Market, NTR Nagar, Mallapur, Secunderabad, Telangana, 500076, India",2,1,1
"Studio Chhavi, Bellandur, Studio Chhavi, B-1202, Mantri Espana, Near Sakra World Hospital, Kariyammana Agrahara, Bellandur, Bengaluru, Karnataka, 560103, India",2,1,1
"Subham Internationals, 172, 4th Main Rd, KKR Garden, Madhavaram, Chennai, Tamil Nadu, 600060, India",2,1,1
"Sudarshan Industries, 59, 1st Main Road, Petechannappa Indl Area, 1st Cross Rd, Govindaraja Nagar Ward, Pete Channappa Industrial Estate, Kamakshipalya, Bengaluru, Karnataka, 560079, India",2,1,1
"Sus Pashan Bridge, Sus Pashan BRG, Mohan Nagar Co-Op Society, Pune, Maharashtra, 411021, India",2,1,1
"TVS Matrix Service Centre, Gala No.B-4, Behind Maruti Showroom, Hatkesh Udhog Nagar, Mira Road East, Mira Bhayandar, Maharashtra, 401104, India",2,1,1
"The Centrum, Ugat Canal Rd, Opp. D Mart, Jahangirabad, Dahin Nagar, Surat, Gujarat, 395005, India",2,1,1
"The TV Shop, 22/118, Bazaar Rd, Periyapet, Saidapet, Chennai, Tamil Nadu, 600015, India",2,1,1
"Trimbak Kotakar Marg, Deshmukh Wadi, Shiv Colony, Sector 1, Airoli, Navi Mumbai, Maharashtra, 400708, India",2,1,1
"Urban Hospitals, Block-1, 1-123/329, Beside D-Mart, Bachupally, Nizampet, Hyderabad, Telangana 500090, India",2,1,1
"Vinayak Nagar Main Road, Vinayak Nagar Main Rd, Old Safilguda, A. S. Rao Nagar, Secunderabad, Telangana, 500056, India",2,1,1
"Vishal Mega Mart, Kanshiram Nagar, Vaderahalli, Opposite Karnataka Bank, Vidyaranyapura, Bengaluru, Karnataka 560097",2,1,1
"Wing A, VDB Celadon, Surabhi Layout, Nehru Nagar, Bengaluru, Karnataka, 560064, India",2,1,1
"YD Homes, Gopala Reddy Layout, YD Homes, 2nd Main Rd, Gopal Reddy Layout, Annaiah Reddy Layout, Dodda Banaswadi, Bengaluru, Karnataka, 560043, India",2,1,1
"Zentech System And Solution, Noapara, Sukanta Pally, Baguiati, Kolkata, West Bengal, 700157, India",2,1,1
"Zepto Mohamed, No.5, Vaigai Nagar, Urapakkam, Chennai, Tamil Nadu, 603210, India",2,1,1
"Zepto Pammal New, Nagalkeni, Chromepet, Chennai, Tamil Nadu 600075, India",2,1,1
"Zepto Parent Shad, 656, 6th Cross Rd, 5th Phase, HAL 2nd Stage, Kodihalli, Bengaluru, Karnataka, 560008, India",2,1,1

In [17]:
product_id_check = (
    df.groupby("unique_id")["product_id_upc_ean"]
    .nunique()
)

product_id_check[product_id_check > 1]

Series([], Name: product_id_upc_ean, dtype: int64)

In [19]:
missing_grammage = df[df["product_grammage"].isna()]

print("Rows with missing product_grammage:", len(missing_grammage))
missing_grammage.head()

Rows with missing product_grammage: 186391

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
20,2026-07-08 00:06:08,zepto,f860ca85-ea81-46eb-9448-1de0226aa0fe,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,e4db8353-f2cf-4a78-aefe-e92d26ee5081,fccf5721-68e5-40ee-b978-a5fbf74696ff,Baby Care,Packaged Food,Infant Food,NaN,Nestle Nutrition,"Nestle Lactogen Pro 2 Follow-Up Formula Baby Powder, Probiotic L. reuteri | 6-12 Months",NaN,NaN,NaN,1.2 kg,NaN,1260.0,1260.0,No,No,1260.0,NaN,No offer,1260.0,0,1,https://www.zepto.com/pn/nestle-lactogen-pro-2-follow-up-formula-baby-powder-probiotic-l-reuteri-6-12-months/pvid/e4db8353-f2cf-4a78-aefe-e92d26ee5081,NaN
21,2026-07-08 00:06:08,zepto,f860ca85-ea81-46eb-9448-1de0226aa0fe,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,12a38d25-34c4-4433-bdae-26bca9b20e65,7f06994d-51cf-4056-91dc-99de7f9544aa,Baby Care,Packaged Food,Infant Food,NaN,Nestle Nutrition,Nestle NAN PRO Stage 1 Infant Formula | 0 - 6 M,NaN,NaN,NaN,1.2 kg,NaN,2170.0,2170.0,No,No,2170.0,NaN,No offer,2170.0,0,1,https://www.zepto.com/pn/nestle-nan-pro-stage-1-infant-formula-0-6-m/pvid/12a38d25-34c4-4433-bdae-26bca9b20e65,NaN
41,2026-07-08 00:06:08,zepto,f860ca85-ea81-46eb-9448-1de0226aa0fe,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,73f81346-fc52-4bbb-8d88-d6dc847179d6,3d4bbf1c-3261-409b-a4c6-65b607427ad5,Baby Care,Packaged Food,Infant Food,NaN,Nestle Nutrition,Nestle NAN PRO Stage 2 Follow-up Powder | 6 - 12 M,NaN,NaN,NaN,1.2 kg,NaN,2170.0,2170.0,Yes,No,2170.0,NaN,No offer,2170.0,0,0,https://www.zepto.com/pn/nestle-nan-pro-stage-2-follow-up-powder-6-12-m/pvid/73f81346-fc52-4bbb-8d88-d6dc847179d6,NaN
44,2026-07-08 00:06:08,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,7886b5f6-5057-46a1-a12c-42bf99662844,821cd989-9562-46a2-ad3f-f4cb4ad1d341,Baby Care,Baby Care,Infant Clothing,NaN,Super Bottoms,Superbottoms Supersoft Baby Brief | 2-3y | Stretchy & Breathable - Pack of 3 | Assorted,NaN,NaN,NaN,1 pc,NaN,599.0,439.0,No,Yes,439.0,NaN,₹160 OFF,439.0,26,1,https://www.zepto.com/pn/superbottoms-supersoft-baby-brief-2-3y-stretchy-breathable-pack-of-3-assorted/pvid/7886b5f6-5057-46a1-a12c-42bf99662844,NaN
45,2026-07-08 00:06:08,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Eduriser Learning Solutions - Elearning | Business Simulations | Instructor-LED-Training, A Wing, Unit No.001, Ground Floor, Raheja Plaza, Lal Bahadur Shastri Marg, Nityanand Nagar, Ghatkopar West, Mumbai, Maharashtra, 400086, India",Mumbai,400086,6c6025c7-3cad-4152-861b-af3f215eda30,6f56f14a-6f26-497a-8ed1-bce9beb19c9a,Baby Care,Baby Care,Infant Clothing,NaN,Super Bottoms,Superbottoms Supersoft Baby Bloomer | 2-3y | Stretchy & Breathable - Pack of 3 | Assorted,NaN,NaN,NaN,1 pc,NaN,599.0,439.0,No,Yes,439.0,NaN,₹160 OFF,439.0,26,1,https://www.zepto.com/pn/superbottoms-supersoft-baby-bloomer-2-3y-stretchy-breathable-pack-of-3-assorted/pvid/6c6025c7-3cad-4152-861b-af3f215eda30,NaN

In [20]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Agra,314,977,621,1383,696,718,382,833,1107,609
Ahmedabad,799,2461,1290,3102,1531,2079,942,1763,2756,1338
Ambarnath,141,245,260,495,322,454,187,391,445,275
Amritsar,319,933,583,1286,602,732,382,805,1105,559
Anand,157,139,290,165,316,261,192,393,311,297
Bangalore,8277,28239,15063,30540,17729,22573,9798,23010,31175,15388
Barasat,105,288,227,451,237,342,175,344,383,221
Bareilly,317,960,599,1319,619,630,383,820,1045,564
Behta Hajipur,147,229,266,422,311,446,190,391,442,268
Bhiwadi,160,400,319,650,351,451,192,420,495,271
Bidhan Nagar,132,410,267,562,361,407,191,426,484,267
Chandigarh,156,404,275,617,290,392,183,408,475,260
Chennai,3882,13179,7500,15601,8505,10998,4856,10502,15636,7449
Chhatrapati Sambhajinagar,160,471,283,653,346,373,191,417,519,290
Coimbatore,468,1316,765,1873,909,1118,575,1223,1472,830
Faridabad,609,1620,1246,2567,1456,1742,761,1680,2238,1186
Gorakhpur,160,455,319,668,340,305,192,404,526,306
Haridwar,157,436,306,630,344,279,189,412,531,279
Hyderabad,4940,18184,9343,21123,11143,14487,5730,13572,19097,8985
Indore,634,1892,1118,2580,1277,1428,765,1611,2078,1171
Jaipur,631,2798,1235,2843,1424,1780,752,1531,2412,1228
Kanpur,956,3060,1845,4063,1897,2153,1149,2449,3240,1895
Karimnagar,160,519,314,695,354,368,191,423,571,277
Kochi,788,2475,1527,3210,1675,2121,956,2229,2830,1500
Kolkata,1147,4457,2601,5531,2982,3686,1717,3639,4587,2212
Kota,160,464,304,671,345,401,192,402,486,307
Kurukshetra,160,590,320,706,359,388,190,425,630,272
Ludhiana,312,755,537,1156,550,669,380,795,908,487
Madurai,317,950,573,1354,638,744,380,821,1115,542
Mathura,156,98,254,207,303,200,190,397,286,269
Meerut,158,387,286,584,316,351,190,413,499,255
Mohali,309,1183,581,1321,626,828,313,816,1014,568
Mumbai,5538,17318,10906,23321,14121,17159,6889,16521,21421,10876
Mysuru,636,2007,1207,2691,1361,1642,764,1679,2117,1223
Nagpur,791,2049,1355,3163,1654,1801,960,2085,2493,1363
Nandivaram Guduvancheri,145,407,281,526,332,419,185,386,510,287
Nashik,480,1333,930,2017,1017,1147,564,1214,1693,925
Navi Mumbai,145,635,266,671,296,440,165,406,662,284
Palakkad,160,527,276,700,322,340,192,415,595,297
Panchkula,160,427,319,639,341,426,192,397,482,274
Patiala,159,528,296,685,295,386,192,410,563,251
Prayagraj,160,524,311,694,337,292,191,413,591,292
Pune,2034,7892,3966,8542,3990,5447,2279,5128,8039,3642
Rewari,160,413,292,656,331,347,160,415,487,188
S.A.S Nagar,460,1523,884,1798,998,1287,481,1248,1604,937
Sankhol,153,250,256,500,223,306,187,386,308,133
Secunderabad,160,763,318,741,383,438,192,462,720,287
Surat,627,1926,1166,2460,1279,1505,766,1581,2187,1279
Thrippunithura,153,345,235,505,272,337,190,394,439,230
Tumakuru,160,548,318,671,381,447,192,420,550,305
Udaipur,320,960,604,1389,639,796,381,800,1077,627
Vadodara,479,1401,921,2003,1096,1192,575,1209,1496,925
Valsad,160,371,296,619,364,345,191,383,456,275
Vasai Virar,277,535,544,1032,673,900,363,818,921,551
Vijayawada,480,1373,820,1955,1012,1100,574,1241,1606,802
Vrindavan,156,98,254,213,302,217,189,397,295,264
Warangal,314,1007,595,1349,702,723,384,832,1188,609

In [21]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

category,"Atta, Rice, Oil & Dals",Baby Care,Bath & Body,Biscuits,Breakfast & Sauces,Cold Drinks & Juices,"Dairy, Bread & Eggs",Electronics & Appliances,Feminine Hygiene,Fragrances & Grooming,Frozen Food,Hair Care,Home Needs,Ice Creams & More,Makeup & Beauty,"Masala, Dry Fruits & More",Munchies,Packaged Food,Pharma & Wellness,Protein & Nutrition,Skincare,Stationery & Books,Sweet Cravings,"Tea, Coffee & More",Toys & Sports,Unlisted1,Zepto Cafe
city,,,,,,,,,,,,,,,,,,,,,,,,,,,
Agra,466,517,474,446,315,497,334,46,284,206,59,374,2,463,356,257,436,321,72,4,688,0,353,255,411,0,4
Ahmedabad,1157,1169,1100,967,788,1043,1231,82,734,508,146,843,7,1068,744,487,1085,659,178,0,1694,1,564,617,1130,0,59
Ambarnath,217,140,183,171,153,224,294,2,115,79,30,109,0,218,121,124,217,131,34,0,293,0,157,113,88,1,1
Amritsar,452,477,459,396,318,452,352,34,291,181,55,363,3,385,306,261,438,317,73,2,694,0,352,251,390,0,4
Anand,224,139,144,197,149,241,110,0,113,0,0,64,0,218,0,132,214,126,2,0,166,0,154,128,0,0,0
Bangalore,12795,13284,12365,10225,8113,12226,14048,981,7766,4647,1225,8115,123,12154,6985,6427,11449,8609,1755,0,19355,120,8880,6257,12697,50,1141
Barasat,157,127,157,145,136,170,186,2,91,64,28,132,0,175,136,118,204,133,35,0,219,0,120,107,129,0,2
Bareilly,457,478,445,410,316,462,317,42,281,197,0,372,0,435,326,258,433,317,68,2,656,0,297,255,428,0,4
Behta Hajipur,224,136,187,171,152,209,288,0,107,75,30,120,0,205,81,125,216,123,32,1,256,0,168,108,96,0,2
Bhiwadi,234,186,219,223,159,226,288,9,137,94,30,183,0,241,161,130,220,161,32,0,318,0,148,128,180,0,2
Bidhan Nagar,194,200,191,171,159,233,239,4,127,87,31,153,0,214,159,127,219,157,35,1,295,0,149,127,178,0,57
Chandigarh,224,195,204,180,158,216,206,4,142,90,28,157,0,175,154,127,214,163,32,0,310,0,171,127,181,0,2
Chennai,6149,6615,6448,5088,3681,5954,6977,548,3386,2301,337,4209,46,5756,3460,3098,5719,3300,893,26,9903,36,4560,2897,6125,0,596
Chhatrapati Sambhajinagar,233,211,225,214,158,246,152,22,133,108,31,188,0,231,161,131,221,161,35,0,307,0,178,128,226,0,3
Coimbatore,687,674,629,547,465,675,520,22,403,301,89,516,0,567,445,382,666,481,102,0,931,0,503,376,561,0,7
Faridabad,924,735,949,862,511,954,1236,34,614,431,108,712,0,950,669,520,869,611,136,4,1246,0,696,500,820,0,14
Gorakhpur,230,245,211,223,157,232,168,14,142,95,1,188,0,228,172,129,217,162,34,0,337,0,176,128,184,0,2
Haridwar,229,237,221,210,125,243,159,13,142,96,0,167,0,244,160,128,216,147,35,1,334,0,149,126,179,0,2
Hyderabad,7698,8872,7504,6371,4995,7264,9482,599,4794,3263,780,5330,75,7725,5342,3761,6767,4914,1096,0,12302,30,4760,3923,8267,0,690
Indore,912,907,830,786,636,926,648,37,545,372,117,734,1,875,601,515,869,641,136,4,1365,0,682,511,892,0,12
Jaipur,851,1362,984,861,625,914,1131,66,634,486,110,744,7,977,755,507,870,660,140,0,1427,0,687,506,1317,4,9
Kanpur,1375,1545,1295,1269,960,1385,1214,114,874,568,6,1062,2,1366,1061,770,1335,970,204,0,2129,0,1050,766,1373,0,14
Karimnagar,236,231,237,219,159,250,180,19,152,115,31,182,0,243,173,129,219,163,34,2,350,0,149,128,269,0,2
Kochi,1195,1296,1095,1065,786,1236,1187,102,750,525,150,843,5,1130,883,632,1096,804,179,0,1684,4,887,625,1020,0,132
Kolkata,1718,2076,1833,1739,1431,2012,2170,135,1139,827,274,1455,6,1863,1463,1144,1966,1430,317,9,2996,4,1192,1141,2049,0,170
Kota,227,222,196,225,158,233,210,5,140,90,26,190,0,247,172,128,218,163,33,1,329,0,175,128,214,0,2
Kurukshetra,237,287,243,224,158,255,234,31,168,109,0,189,1,241,191,128,219,176,35,1,372,0,147,128,264,0,2
Ludhiana,447,408,394,350,305,421,318,11,248,171,49,332,0,331,255,253,438,313,63,0,588,0,325,237,288,0,4
Madurai,466,498,490,411,314,487,355,42,281,207,54,371,0,416,331,258,437,319,66,0,681,0,282,251,413,0,4
Mathura,226,99,134,179,158,225,23,4,113,29,0,64,0,182,47,133,212,123,2,0,114,0,163,128,0,0,2
Meerut,230,198,216,193,159,224,165,9,140,88,30,167,0,218,140,126,216,157,36,0,288,0,147,127,163,0,2
Mohali,446,577,422,399,308,462,464,15,277,174,54,352,3,392,305,244,375,301,66,0,729,0,344,249,541,0,60
Mumbai,8904,9356,8138,7609,5677,8959,11393,729,4946,4011,1033,5604,90,8759,5880,4602,7997,5649,1273,0,14113,36,6241,4515,6823,36,1697
Mysuru,938,903,938,833,636,933,911,80,545,414,121,715,0,966,702,519,872,643,140,0,1299,0,720,508,977,4,10
Nagpur,1165,955,1084,985,788,1163,791,68,674,496,113,846,0,1200,800,648,1100,783,165,5,1518,0,749,635,966,5,12
Nandivaram Guduvancheri,232,224,220,189,129,232,268,0,115,81,13,146,0,219,98,111,220,106,33,1,340,0,177,104,174,0,46
Nashik,699,687,685,648,462,721,570,41,460,307,90,536,0,738,524,384,654,462,105,0,1059,0,540,375,563,0,10
Navi Mumbai,237,317,241,179,151,213,277,31,140,117,30,170,5,209,157,112,183,159,36,0,440,2,172,117,273,1,1
Palakkad,236,247,248,199,158,242,138,31,143,117,29,177,1,208,187,131,220,154,35,1,358,0,176,128,258,0,2
Panchkula,229,209,205,223,158,259,242,3,138,98,28,189,0,193,146,130,211,162,33,0,315,0,174,128,182,0,2
Patiala,227,269,223,201,160,226,198,24,151,102,27,182,0,190,178,128,220,165,33,0,354,0,147,127,231,0,2
Prayagraj,231,280,212,223,158,233,145,31,156,90,1,190,2,209,168,128,219,161,36,0,391,0,177,128,232,0,4
Pune,3158,3808,3254,2746,1884,2661,3432,273,1877,1241,369,2270,38,2690,2017,1543,2618,2015,423,0,5116,0,1892,1496,3752,0,386
Rewari,235,208,208,222,160,223,164,10,140,96,10,186,0,161,175,128,188,162,33,0,303,0,138,128,171,0,0
S.A.S Nagar,673,781,658,612,459,744,744,38,425,266,81,498,3,668,401,366,574,458,98,0,1023,0,514,371,645,0,120
Sankhol,221,114,133,159,144,172,169,2,87,84,0,159,0,83,102,130,212,157,32,2,219,0,108,108,103,2,0
Secunderabad,255,360,274,223,160,251,308,31,171,112,0,188,5,252,192,128,221,169,36,0,455,2,151,129,368,0,23
Surat,900,1018,911,799,635,961,760,63,586,455,118,542,3,966,587,506,860,635,138,0,1371,0,674,500,775,0,13
Thrippunithura,222,191,190,166,155,207,132,3,129,75,30,138,0,146,145,123,219,145,35,0,229,0,170,119,129,0,2
Tumakuru,234,244,239,223,158,254,280,30,141,106,31,159,0,242,192,130,220,163,35,0,329,0,182,128,270,0,2
Udaipur,457,508,448,444,316,480,402,25,288,211,54,372,0,449,338,259,431,322,66,0,716,0,348,255,400,0,4
Vadodara,686,727,640,638,480,752,664,9,428,277,90,559,1,723,514,391,650,479,102,0,966,0,527,384,604,0,6
Valsad,233,179,194,218,160,251,147,7,135,89,31,172,0,245,154,128,216,133,34,0,294,0,150,128,160,0,2
Vasai Virar,440,307,373,372,292,447,591,16,229,182,57,231,0,453,265,245,426,260,64,0,588,0,293,221,196,2,64
Vijayawada,699,681,666,596,470,740,470,50,421,268,88,514,0,702,548,390,651,489,102,0,971,0,440,378,619,3,7
Vrindavan,225,99,135,179,160,224,37,4,113,32,0,64,0,178,51,133,212,123,2,0,121,0,163,128,0,0,2
Warangal,464,476,466,437,317,502,342,38,288,215,62,358,0,489,361,260,434,324,68,2,723,0,330,256,485,2,4

In [22]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals, Packaged Food]"
1,Baby Care,"[Baby Care, Dairy, Bread & Eggs, Home Needs, Packaged Food, Pharma & Wellness, Skincare, Stationery & Books, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Bath & Body, Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare, Unlisted1]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Biscuits, Breakfast & Sauces, Cold Drinks & Juices, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food, Protein & Nutrition, Sweet Cravings, Unlisted1]"
6,Munchies,"[Biscuits, Masala, Dry Fruits & More, Munchies, Packaged Food, Unlisted1]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Home Needs, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Home Needs, Makeup & Beauty, Pharma & Wellness, Skincare, Unlisted1]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Frozen Food, Ice Creams & More, Munchies, Packaged Food, Sweet Cravings]"

In [23]:
same_product = (
    df.groupby(["product_name","product_id_upc_ean", "product_grammage", "net_quantity"])
    .agg(
        url_count=( "product_url", "nunique"),
       product_urls=( "product_url", lambda x: list(x.unique()))
    )
    .reset_index()
)

same_product = same_product[same_product["url_count"] > 1]

same_product

,product_name,product_id_upc_ean,product_grammage,net_quantity,url_count,product_urls
1670,Britannia Brown Bread,ebaccf7b-ff5c-48fc-a86a-e30899be6544,400 g,1 pack (400 g),2,"[https://www.zepto.com/pn/britannia-brown-bread/pvid/9df86bf5-25f9-46e2-bc1d-4d2742ca2f2e, https://www.zepto.com/pn/britannia-brown-bread/pvid/521dda39-83a6-4391-9eb4-c8744684f6d7]"
1713,Britannia Milk Slice White Bread,f07b5c07-077a-475a-9c84-1dcae05f5fce,400 g,1 pack (400 g),2,"[https://www.zepto.com/pn/britannia-milk-slice-white-bread/pvid/6b647b7a-59fa-49fa-83d2-36bb790eb425, https://www.zepto.com/pn/britannia-milk-slice-white-bread/pvid/fd98be99-5687-45fe-9fcc-a60ca95746d1]"
4815,Haldiram's Bhujia | Spicy & Crunchy Snack,f3bbc93f-9be2-44dd-a198-4d088f2b19cd,200 g,1 pack (200 g),2,"[https://www.zepto.com/pn/haldirams-bhujia-spicy-crunchy-snack/pvid/3cbfea0c-f23f-4101-aa8f-a724cb5f3814, https://www.zepto.com/pn/haldirams-bhujia-spicy-crunchy-snack/pvid/ad3859e2-5d02-4c9e-b9c7-e0cdded4b22a]"
6603,Listerine Cool Mint Taste Mouthwash,74a6d411-5549-44ed-9501-2ee8967a85fa,250 ml,1 pc (250 ml),2,"[https://www.zepto.com/pn/listerine-cool-mint-taste-mouthwash/pvid/79231951-9ad9-401e-8e2b-225826d6522e, https://www.zepto.com/pn/listerine-cool-mint-taste-mouthwash/pvid/a00b4795-0715-4ef1-9531-962690673a8e]"
7313,Mentos Pure Fresh Sugarfree Spearmint Chewing Gum Pocket Bottle,fdc06649-7767-4f32-87e7-e261690b429e,58.5 g or 54.6 g,1 pack (58.5 g or 54.6 g),2,"[https://www.zepto.com/pn/mentos-pure-fresh-sugarfree-spearmint-chewing-gum-pocket-bottle/pvid/5d9a7b47-7196-4c8f-ab95-4c72f68dd29f, https://www.zepto.com/pn/mentos-pure-fresh-sugarfree-spearmint-chewing-gum-pocket-bottle/pvid/1101cea4-a512-4e3d-9a9a-b95ba78d0438]"

In [24]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag              No    Yes   Total  Out_of_stock_%
city
Bidhan Nagar                 1749   1758    3507           50.13
Behta Hajipur                1784   1328    3112           42.67
Mumbai                      95962  48108  144070           33.39
Karimnagar                   2752   1120    3872           28.93
Ambarnath                    2303    912    3215           28.37
Nashik                       8186   3134   11320           27.69
Vasai Virar                  4875   1739    6614           26.29
Navi Mumbai                  2962   1008    3970           25.39
Chennai                     73345  24763   98108           25.24
Jaipur                      12552   4082   16634           24.54
Kolkata                     24754   7805   32559           23.97
Mohali                       5773   1786    7559           23.63
Valsad                       2646    814    3460           23.53
Chandigarh                   2660    800    3460           23.12
S.A.S Nagar                  8632   2588   11220           23.07
Warangal                     5970   1733    7703           22.50
Vijayawada                   8564   2399   10963           21.88
Pune                        39941  11018   50959           21.62
Kochi                       15222   4089   19311           21.17
Panchkula                    2893    764    3657           20.89
Faridabad                   12004   3101   15105           20.53
Nandivaram Guduvancheri      2770    708    3478           20.36
Madurai                      5934   1500    7434           20.18
Udaipur                      6088   1505    7593           19.82
Hyderabad                  102712  23892  126604           18.87
Haridwar                     2932    631    3563           17.71
Indore                      12022   2532   14554           17.40
Kota                         3092    640    3732           17.15
Ahmedabad                   14976   3085   18061           17.08
Bangalore                  167622  34170  201792           16.93
Chhatrapati Sambhajinagar    3086    617    3703           16.66
Meerut                       2868    571    3439           16.60
Surat                       12324   2452   14776           16.59
Prayagraj                    3177    628    3805           16.50
Vadodara                     9485   1812   11297           16.04
Kanpur                      19073   3634   22707           16.00
Coimbatore                   8904   1645   10549           15.59
Agra                         6494   1146    7640           15.00
Amritsar                     6257   1049    7306           14.36
Ludhiana                     5618    931    6549           14.22
Nagpur                      15266   2448   17714           13.82
Palakkad                     3296    528    3824           13.81
Secunderabad                 3851    613    4464           13.73
Patiala                      3249    516    3765           13.71
Mysuru                      13225   2102   15327           13.71
Gorakhpur                    3190    485    3675           13.20
Bareilly                     6326    930    7256           12.82
Rewari                       3010    439    3449           12.73
Kurukshetra                  3571    469    4040           11.61
Bhiwadi                      3324    385    3709           10.38
Tumakuru                     3671    321    3992            8.04
Anand                        2362    159    2521            6.31
Thrippunithura               2912    188    3100            6.06
Vrindavan                    2252    133    2385            5.58
Barasat                      2650    123    2773            4.44
Sankhol                      2600    102    2702            3.77
Mathura                      2311     49    2360            2.08

In [25]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag         No    Yes   Total  Out_of_stock_%
department
Bakery & Biscuits      58909  20024   78933           25.37
Dairy & Breakfast      85605  27738  113343           24.47
Personal Care         116201  37197  153398           24.25
Baby Care             105140  30994  136134           22.77
Organic & Premium      90197  23608  113805           20.74
Beauty & Cosmetics    135374  33194  168568           19.69
Cold Drinks & Juices   74385  17490   91875           19.04
Atta, Rice & Dal       33815   7940   41755           19.02
Munchies               42593   7861   50454           15.58
Sweet Tooth            65810  11941   77751           15.36

In [26]:
cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No    Yes  Total  Out_of_stock_%
category
Zepto Cafe                   639   4789   5428           88.23
Unlisted1                     15     95    110           86.36
Home Needs                   243    186    429           43.36
Electronics & Appliances    2930   1755   4685           37.46
Dairy, Bread & Eggs        46103  22358  68461           32.66
Stationery & Books           165     70    235           29.79
Fragrances & Grooming      19418   6708  26126           25.68
Feminine Hygiene           28831   9358  38189           24.50
Baby Care                  51014  16477  67491           24.41
Biscuits                   41759  12701  54460           23.32
Makeup & Beauty            31946   9251  41197           22.46
Toys & Sports              46887  13542  60429           22.41
Sweet Cravings             34354   9764  44118           22.13
Bath & Body                48591  13076  61667           21.20
Skincare                   76997  19970  96967           20.59
Hair Care                  35499   8646  44145           19.59
Atta, Rice, Oil & Dals     51312  12405  63717           19.47
Protein & Nutrition           56     13     69           18.84
Frozen Food                 5234   1181   6415           18.41
Packaged Food              34233   7458  41691           17.89
Breakfast & Sauces         34428   7164  41592           17.22
Masala, Dry Fruits & More  27809   5633  33442           16.84
Munchies                   48668   9850  58518           16.83
Pharma & Wellness           7615   1532   9147           16.75
Cold Drinks & Juices       52376  10471  62847           16.66
Tea, Coffee & More         27771   5199  32970           15.77
Ice Creams & More          53136   8335  61471           13.56

In [27]:
same_store_diff = (
    df.groupby(["store_id", "store_name_location", "city", "unique_id"])
    .agg(
        product_name=("product_name", "first"),
        price_count=("item_selling_price", "nunique"),
        discount_count=("discount_in_percent", "nunique"),
        mrp_count=("item_mrp", "nunique")
    )
    .reset_index()
)

same_store_diff = same_store_diff[
    (same_store_diff["price_count"] > 1) |
    (same_store_diff["discount_count"] > 1) |
    (same_store_diff["mrp_count"] > 1)
]

same_store_diff

Empty DataFrame
Columns: [store_id, store_name_location, city, unique_id, product_name, price_count, discount_count, mrp_count]
Index: []

In [28]:
import re

# Normalize brand names
df["brand_norm"] = (
    df["brand_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
brand_issue = (
    df.groupby("brand_norm")
    .agg(
        variant_count=("brand_name", "nunique"),
        brand_variants=("brand_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

brand_issue = brand_issue[brand_issue["variant_count"] > 1]

brand_issue

,brand_norm,variant_count,brand_variants
211,bombayshavingcompany,2,"[Bombay Shaving Company, Bombay shaving Company]"
212,bonn,2,"[Bonn, bonn]"
216,borges,2,"[BORGES, Borges]"
304,cocacolaus,2,"[Coca-Cola US, Coca-cola US]"
386,delichic,2,"[Deli Chic, Delichic]"
786,kharifoods,2,"[KHARI FOODS, Khari Foods]"
1068,noto,2,"[NOTO, Noto]"
1146,paperboat,2,"[PAPER BOAT, Paper Boat]"
1159,patanjali,2,"[PATANJALI, Patanjali]"
1193,plixtheplantfix,2,"[Plix -The Plant Fix, Plix The Plant Fix]"
1405,star,2,"[STAR, Star]"
1439,sunscoop,2,"[SunScoop, Sunscoop]"
1617,vijay,2,"[VIJAY, Vijay]"

In [29]:
productid_name_issue = (
    df.groupby("product_id_upc_ean")
    .agg(
        product_name_count=("product_name", "nunique"),
        product_names=("product_name", lambda x: sorted(x.unique()))
    )
    .reset_index()
)

productid_name_issue = productid_name_issue[
    productid_name_issue["product_name_count"] > 1
]

productid_name_issue

Empty DataFrame
Columns: [product_id_upc_ean, product_name_count, product_names]
Index: []

In [4]:
df.product_grammage.unique()

array(['100 g', '40 g', '300 g', ..., '15 x 2 g', '235 ml',
       '500 ml or 625 ml'], shape=(1093,), dtype=object)

In [5]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
286,Mumbai,f6080683-4654-4500-ba97-74aafe1e2019,17,2791,2808,99.39
142,Hyderabad,02a58e65-a110-4856-b787-16ba7ef238ec,16,22,38,57.89
256,Mumbai,71ca681c-6ee4-467d-9d0a-8d761ce8400f,1521,1661,3182,52.20
277,Mumbai,d50a3a1a-4ab0-4a0e-b87d-e032776daff9,1640,1731,3371,51.35
94,Bidhan Nagar,553c9cfa-5a00-4b98-a1d5-152c813e12d2,1734,1748,3482,50.20
268,Mumbai,9afa54f1-78a4-4ce7-a632-be8e99531cb0,1630,1601,3231,49.55
282,Mumbai,e92b6e46-2f9f-46b5-99ab-56d2db0a90a6,1823,1773,3596,49.30
131,Chennai,fb0d381c-e38f-4bcc-a5f8-872e3e033e62,1889,1743,3632,47.99
244,Mumbai,2ed65df1-196d-4877-93dd-cc1ae94fe3c7,1742,1471,3213,45.78
260,Mumbai,7fda3ccf-78cb-4aa8-a910-b1046fd0baf0,1980,1661,3641,45.62
275,Mumbai,cc72f206-e146-43c5-a01b-56ddc8d11464,1894,1457,3351,43.48
92,Behta Hajipur,49d9df40-6b3b-4f3e-ad7d-bda18f57d419,1784,1328,3112,42.67
215,Kolkata,5d94bdb2-32fe-42f1-bc68-732d1d7ccb11,372,262,634,41.32
95,Bidhan Nagar,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,15,10,25,40.00
276,Mumbai,d390ee2b-1c8f-4236-9c8b-b60173fd330a,2006,1330,3336,39.87
251,Mumbai,4a54d5f5-0bd9-4b8f-b08a-120d8e7926d7,1979,1277,3256,39.22
235,Mumbai,0dee4754-034b-43ec-bcab-2664340690dd,1994,1278,3272,39.06
220,Kolkata,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,2134,1349,3483,38.73
114,Chennai,6db09732-73a0-424c-b528-1778ad7ba7e5,2092,1304,3396,38.40
287,Mumbai,f860ca85-ea81-46eb-9448-1de0226aa0fe,1808,1099,2907,37.81
129,Chennai,ee6f8d8a-94dc-47c7-a4c5-7ea1efe3031b,1932,1161,3093,37.54
284,Mumbai,ebabbe83-2299-49ca-bbd8-edfd8dd03d60,2298,1323,3621,36.54
258,Mumbai,74aa405e-238e-4103-abb3-096bd7e6f553,2022,1134,3156,35.93
267,Mumbai,973a6df0-7634-4291-be0d-cd48a816516b,2158,1202,3360,35.77
289,Mumbai,fe7c8d05-02c0-4358-a794-1d5f862d74e8,2144,1165,3309,35.21
36,Bangalore,4b085c97-667a-4149-ade7-d61c8a7fa42f,2017,1089,3106,35.06
101,Chennai,198b7ff3-353f-4735-bf3f-75b180544478,2362,1264,3626,34.86
181,Hyderabad,de95e00b-0ebf-4f65-8f27-df66fd91dc13,626,331,957,34.59
119,Chennai,aae1e2ef-3de3-4662-ab2d-b5734264b384,2301,1200,3501,34.28
243,Mumbai,2e7ec440-fd1b-441e-90ee-9c8611648bb6,2149,1114,3263,34.14
259,Mumbai,769200e9-30cc-47a2-81d4-58904ed953cc,2204,1136,3340,34.01
98,Chennai,0f8103ff-a85c-40ac-8658-ffecaa4fb853,2378,1220,3598,33.91
352,Vasai Virar,0b45bb12-e3bd-415b-b298-ee97db10a222,2470,1241,3711,33.44
264,Mumbai,8988d40f-12d3-42d5-9a8e-243712f8e37f,2193,1074,3267,32.87
118,Chennai,aa16c37d-46a9-4e32-84b3-0e2401bd196f,2445,1193,3638,32.79
257,Mumbai,72655f9e-d9be-4b01-b2ac-62e61d2efd47,2251,1094,3345,32.71
255,Mumbai,684a75ae-c944-480c-a64f-76a1a9cfa393,2006,972,2978,32.64
290,Mumbai,fec59a85-00e2-4551-a354-869500f18e23,2186,1054,3240,32.53
123,Chennai,cbb87b63-9d7e-44bc-a5e5-38972f48f45e,1996,954,2950,32.34
195,Jaipur,2036c1f6-0885-407c-a607-6a237897ae33,2600,1206,3806,31.69
247,Mumbai,37b900f0-25c0-448b-825a-74d62c8ceb41,2251,1039,3290,31.58
222,Kolkata,d4965e43-bb99-400e-9107-7371e08cf06a,2355,1086,3441,31.56
128,Chennai,eae819e6-830f-4bc1-95ef-514cab9dbdbd,2455,1126,3581,31.44
318,Pune,60252717-a8c5-4891-9b23-3db778b14477,2212,1013,3225,31.41
252,Mumbai,5223893f-f150-4fb3-9f8b-2e86a7c15af1,888,398,1286,30.95
110,Chennai,56b257df-32c7-482f-9963-01ec865624c3,2507,1123,3630,30.94
239,Mumbai,2175898f-b70e-46d9-8def-aba7f0745662,896,395,1291,30.60
112,Chennai,64b8c907-1b43-4f03-a739-fa20d2ac339f,2520,1061,3581,29.63
237,Mumbai,178dbe40-5ad9-4ddf-99ec-18192cb71db7,2245,932,3177,29.34
241,Mumbai,238a227d-697c-4fa9-a4f5-4fd064760098,2307,956,3263,29.30
355,Vijayawada,471b6b1b-6289-47bf-ac72-a61684f86181,2625,1084,3709,29.23
50,Bangalore,75946a5e-942e-4db1-9e7c-5fe2eb85088b,2183,899,3082,29.17
254,Mumbai,57d17930-01e0-4657-a792-57a1b7edf762,2638,1075,3713,28.95
206,Karimnagar,fa4d495a-c01f-4132-9be3-89c4cf72dd7b,2752,1120,3872,28.93
285,Mumbai,ec68621c-2e28-40d5-8fe7-fa38ba0e3692,2147,866,3013,28.74
303,Nashik,da931d01-2519-4d80-89ae-9d74dbb71918,2678,1076,3754,28.66
156,Hyderabad,6671859b-cb7c-4dc7-bba6-d6554b27b7b2,2685,1068,3753,28.46
124,Chennai,cd810e0e-6373-4ae8-b18d-c040393a4191,2596,1032,3628,28.45
242,Mumbai,291264cf-55b8-4ae3-93b2-cb23fd795054,2345,930,3275,28.40
8,Ambarnath,b54c01f1-4f46-47d6-a3e7-bd040d3e8548,2303,912,3215,28.37
77,Bangalore,cf384ecd-5e1f-47e9-9194-8e9dc940e8c3,2624,1039,3663,28.36
301,Nashik,4be1c14d-98a6-42a7-aea9-488538abd03c,2716,1067,3783,28.21
288,Mumbai,fdc84bec-ec86-4b5d-b18b-84daca52c609,2675,1047,3722,28.13
270,Mumbai,b099eada-6069-4faf-91fb-8faa600884c3,2618,1023,3641,28.10
262,Mumbai,84e7185d-375b-4386-ad42-ae55139e9e0f,2535,980,3515,27.88
263,Mumbai,88c4cd44-4d68-40af-af18-9fd8c8db3f39,2010,777,2787,27.88
37,Bangalore,4f54ea62-0269-4b93-87cd-ef7ed796c6b1,2332,891,3223,27.65
246,Mumbai,3583fadc-1d44-42ff-b09d-68d09b0aec89,2633,1005,3638,27.63
162,Hyderabad,7ed513e4-0a4c-453d-9446-7ab609bafdbf,2361,898,3259,27.55
120,Chennai,b4d53703-4b49-4a38-85ca-7e321d1d5222,2036,773,2809,27.52
188,Hyderabad,f275b3c5-5538-46b4-940f-82d9358dba84,2718,1019,3737,27.27
304,Navi Mumbai,9f31c2fd-b593-4cb4-85a5-49a47163aa9a,1891,708,2599,27.24
245,Mumbai,30cbdf99-c43b-4a4f-8754-7399625ce08c,2649,972,3621,26.84
143,Hyderabad,13ffc117-24d6-4854-a53e-a51d7330973e,2466,899,3365,26.72
218,Kolkata,a414c96e-6808-45f5-bdaf-1182485ac38c,2376,859,3235,26.55
232,Mohali,1fe58380-341b-4509-b712-a66f5aea2e86,2650,955,3605,26.49
253,Mumbai,52278321-e20a-4a88-b24c-613fafa720e0,2446,880,3326,26.46
334,S.A.S Nagar,a0e51d17-0a52-4222-a1ff-777b700e5b30,2376,855,3231,26.46
223,Kolkata,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,467,168,635,26.46
107,Chennai,49e487f6-07bf-48f9-b379-203f76c11964,2572,920,3492,26.35
325,Pune,a6aaf608-0a95-47fd-a981-a52d1a5e5e2a,2496,891,3387,26.31
265,Mumbai,8a278c72-1366-4926-b81e-ecc6e64df2a7,802,285,1087,26.22
302,Nashik,bc299560-8f6b-43ba-b146-879f3594ea7e,2792,991,3783,26.20
213,Kolkata,17532e16-28d2-4271-bbac-c48b9b3f8dd1,2712,959,3671,26.12
315,Pune,4b7f2491-a77d-4e8d-9317-08f5a29fc821,2678,946,3624,26.10
152,Hyderabad,477d50e9-2c13-435c-8db4-dd0077b4ab2e,914,322,1236,26.05
102,Chennai,1e32417a-1c1c-4f1c-972e-9852a27904d0,2298,801,3099,25.85
319,Pune,68e86539-d883-4fc2-b735-0ab599643721,2704,939,3643,25.78
194,Jaipur,188961a6-213a-4ab6-9d5d-2aaa495042aa,3005,1023,4028,25.40
250,Mumbai,44cc43cf-500a-44a1-967f-36164e30d124,2476,836,3312,25.24
208,Kochi,1dfb0f79-3c66-45e8-8b24-9d79ab1b2477,2816,935,3751,24.93
61,Bangalore,97bf23f5-dc0c-4783-ba7d-9d6da842066b,2756,915,3671,24.93
81,Bangalore,e0e12ce6-3431-4ed8-a74b-b0de26426220,2769,919,3688,24.92
314,Pune,4b7a4e49-97dc-4bab-a168-52fcc8711105,2326,769,3095,24.85
209,Kochi,6d1f09eb-28f1-48b4-86c8-bcfa246c70fa,2847,941,3788,24.84
144,Hyderabad,26ec9b6b-b566-4f36-b5dd-eb6fb92a0caf,2545,839,3384,24.79
359,Warangal,561f9537-1e81-4654-a9e0-6144a15caa90,2841,935,3776,24.76
316,Pune,4ba4eee4-2869-4f08-8ba8-ccf06a2b4e3c,805,264,1069,24.70
18,Bangalore,0f2d3f82-cf97-45e8-bd80-759fe5dfbf6c,2789,909,3698,24.58
105,Chennai,3c87aea3-d63e-4765-bf86-2fd7a8c1ebff,2648,860,3508,24.52
150,Hyderabad,43b12c97-dc99-431a-9ba3-e3cde9c716bb,2812,894,3706,24.12
310,Pune,252ed3f4-d99b-4793-951e-ae673cb9ebbf,2403,760,3163,24.03
320,Pune,7644b7fa-98d0-4bdd-a093-965dac5a807b,2711,856,3567,24.00
233,Mohali,46582e95-02a7-4eb6-b80a-526a5e73c6ae,2235,704,2939,23.95
273,Mumbai,badfd8b4-f39a-41ec-8f0a-4f86184f0953,1079,338,1417,23.85
73,Bangalore,b1403534-cd6b-49d0-a7cd-ce20e6497768,2444,765,3209,23.84
54,Bangalore,7a00b962-e558-4d95-9d23-98060c62152b,2363,739,3102,23.82
332,S.A.S Nagar,2bf9f3ff-7b68-4ac5-a814-1059b71840cf,2664,825,3489,23.65
351,Valsad,accc8ada-86f9-48fe-9d7a-098000985bee,2646,814,3460,23.53
42,Bangalore,5c85fffa-7130-43f2-9b34-0decc06beddc,2777,852,3629,23.48
16,Bangalore,071461ac-2354-4e5e-b5f5-04ef935f591c,2908,892,3800,23.47
228,Madurai,2abca56f-4918-4aa7-b110-34068bd40d7e,2977,911,3888,23.43
187,Hyderabad,ed887f36-42af-4fcb-92b8-e626ff12058b,2819,854,3673,23.25
96,Chandigarh,2c224926-8b10-4295-9710-004f8e7b3880,2660,800,3460,23.12
335,S.A.S Nagar,f625ba3c-a01b-4fb4-992e-18498a745538,2690,804,3494,23.01
133,Coimbatore,4942530d-03e3-44f5-ba28-30c05c238e24,2905,858,3763,22.80
266,Mumbai,95d6c1a2-b071-4cf3-a322-30b5754d7cb6,838,247,1085,22.76
136,Faridabad,33879b19-7a4e-41bd-86d5-66402c04dd03,3006,885,3891,22.74
211,Kochi,8a71c5dd-fc7e-42e0-b56d-7d3b7df30187,613,179,792,22.60
197,Jaipur,4db672ad-efd4-44f3-bd91-300233162d1c,2890,841,3731,22.54
104,Chennai,37e0300a-af5d-494a-a88e-de79f61c4dde,2553,732,3285,22.28
137,Faridabad,3d277bf6-7a5f-498a-a956-56fd8ab9ef82,2968,850,3818,22.26
32,Bangalore,3bf7d17f-4fa3-481d-b14d-66ca5c4f14da,1112,315,1427,22.07
149,Hyderabad,33a1d02e-1bb7-44cc-8d38-9697bcc23dba,922,261,1183,22.06
186,Hyderabad,e9c206f4-5e36-40ea-9d34-071b0c016be3,2953,834,3787,22.02
175,Hyderabad,bb713aac-cd12-4b4d-9026-704e3deaaac3,2634,741,3375,21.96
69,Bangalore,a7860f3d-39d4-4275-811d-904d4c2438f4,1171,329,1500,21.93
305,Navi Mumbai,de3fdf29-3177-4fb9-99f7-43b940f38175,1071,300,1371,21.88
63,Bangalore,996c6a91-1fd7-46cc-9ccc-f0960c219aaf,2887,806,3693,21.83
99,Chennai,0fbf57e9-75ca-499b-94d5-479f33b564ea,3062,853,3915,21.79
196,Jaipur,32989280-a610-4395-aca5-5ba4823af4bd,2989,833,3822,21.79
219,Kolkata,a935152c-9baa-46c1-b2ac-37701a227a19,2684,734,3418,21.47
217,Kolkata,9cc80a80-f39d-4da4-9ce6-14fad42e470e,2904,784,3688,21.26
328,Pune,d5350a6a-f6d4-454f-9c53-205dfefec328,2527,682,3209,21.25
34,Bangalore,416b9549-1413-435d-b08b-1d150131f6cd,2494,667,3161,21.10
317,Pune,53aeab86-e3e6-4183-bc51-da47cf967c24,2555,682,3237,21.07
24,Bangalore,20b71590-dbe0-4666-b941-017436eae4d4,1095,291,1386,21.00
329,Pune,e2305bd9-95df-47f0-8b81-54b606b1497e,1034,274,1308,20.95
185,Hyderabad,e531dd78-694e-4025-afdb-76adec0f6d48,888,235,1123,20.93
148,Hyderabad,314533d4-8bd7-4985-8ca5-9b737431149b,2936,777,3713,20.93
307,Panchkula,0bbd1898-6621-47bd-b806-7e5b822f0fc7,2893,764,3657,20.89
173,Hyderabad,adec0623-e83c-46cc-9eef-d33b4486d054,2691,709,3400,20.85
346,Udaipur,8dd0f61c-7734-4af8-b5e2-bf198cf6fe56,3013,791,3804,20.79
86,Bangalore,f5ee88f8-c372-4160-ac4e-bb22d8b0158e,2342,611,2953,20.69
168,Hyderabad,95bc5024-3ef7-49b5-80a9-9c9df49638dc,2977,775,3752,20.66
46,Bangalore,6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a,1247,322,1569,20.52
212,Kochi,8edffc62-2cea-4cbc-8af6-8ac14201f45d,3017,777,3794,20.48
300,Nandivaram Guduvancheri,3994880c-5e18-4de9-9f68-847c18108e27,2770,708,3478,20.36
358,Warangal,48ff71eb-60ab-412e-937c-cdef9b1d3a33,3129,798,3927,20.32
97,Chennai,083a3e0d-4b0c-4353-927f-02c4614e6f47,2481,628,3109,20.20
354,Vijayawada,308d5afe-f44d-443b-ab47-5f6e43f3fcbd,2968,749,3717,20.15
67,Bangalore,a1cbdf77-8824-4c12-85b4-3b114318497d,2388,597,2985,20.00
238,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,1064,266,1330,20.00
155,Hyderabad,5ca7734d-e625-4328-8588-a4a102966b36,2743,674,3417,19.72
7,Ahmedabad,e8906fc6-3925-4713-bca4-3388408415d9,3003,734,3737,19.64
160,Hyderabad,7a85bcbe-fbfc-4ad8-be93-9da42c05a380,2931,711,3642,19.52
116,Chennai,9a0ea877-80f5-441f-b63a-6f2c8eef3832,2593,626,3219,19.45
192,Indore,a02cc832-e25e-4851-b7bd-3330a61c2158,2931,704,3635,19.37
167,Hyderabad,8dcc9bd0-fb05-42e9-96c7-ef15a999c522,880,210,1090,19.27
210,Kochi,74eedd8a-1705-46c3-8dd3-bbfcc0289ec3,2914,690,3604,19.15
44,Bangalore,658cf319-0b10-4dbe-809e-ea5c913974cb,1256,297,1553,19.12
55,Bangalore,7de4838b-ae7c-44d0-bf24-fb2040666654,2636,622,3258,19.09
154,Hyderabad,56d50978-df14-48ba-aec8-79644b36fd6a,983,232,1215,19.09
41,Bangalore,5ac90c68-3608-41c5-b3e3-dc59ff0f0a91,2565,598,3163,18.91
108,Chennai,4f1a8aec-600b-429b-81e8-c9ecebf9b5da,2407,561,2968,18.90
111,Chennai,59099ea0-3411-4169-9c90-206cb03ef12a,996,232,1228,18.89
313,Pune,3a15115a-c99e-4421-bfcc-5b97a2716da5,2645,615,3260,18.87
347,Udaipur,ddd350df-f43c-408e-9d70-03fbf4417600,3075,714,3789,18.84
269,Mumbai,a9588bc2-3d75-410c-88c3-ec029bf4593a,1011,234,1245,18.80
236,Mumbai,0e8c4509-c9cd-4235-9da5-18fbede8ce72,903,209,1112,18.79
138,Faridabad,425e3ad2-0f08-4dbb-b90b-c892dc41be83,2869,663,3532,18.77
33,Bangalore,3fdf2ec3-0ac0-4e8d-a7f0-e184ef12fbe6,2624,605,3229,18.74
122,Chennai,c8f9f22d-b083-4eb1-894d-47b4daeeb2b5,2585,596,3181,18.74
153,Hyderabad,4c93e224-40da-4c86-a5ff-c9c2cfee1168,956,220,1176,18.71
342,Surat,d2020a3b-0420-4886-8c55-3128f6a3f592,2824,649,3473,18.69
226,Ludhiana,2a607d6c-27cf-4475-a804-e99a363919c4,2861,653,3514,18.58
214,Kolkata,56b34f56-7705-43b0-8fee-64125becba91,2964,673,3637,18.50
158,Hyderabad,6fdc556b-2daf-480a-b272-b48c18e4460c,2987,673,3660,18.39
179,Hyderabad,d71ff3ac-0dbd-43de-bf48-6a1b0ba17c12,985,222,1207,18.39
35,Bangalore,49879539-9538-42ca-b59e-952cdd73b506,1194,268,1462,18.33
146,Hyderabad,2a3b1c03-c42a-484e-bdd9-bc853efd6fca,3020,677,3697,18.31
139,Faridabad,77d27ceb-e171-4aa5-bd86-58c0e8bf7512,3161,703,3864,18.19
198,Jaipur,8b0413dd-9188-4002-951a-660ab5a35e7a,356,79,435,18.16
163,Hyderabad,8275a3ee-3b08-4201-9be3-6e12aed69ea9,2638,584,3222,18.13
283,Mumbai,eb92685d-4aad-4424-b38f-f876e41640a8,1025,226,1251,18.07
29,Bangalore,312fd0bd-4163-4768-8e94-ea1dc57783dd,2337,515,2852,18.06
177,Hyderabad,ce354a55-f185-4de0-ba8b-50d62ea483d1,3016,663,3679,18.02
200,Kanpur,1a96b304-c2cb-4a59-88cc-8e3496e1b525,3078,676,3754,18.01
191,Indore,6fee31f5-1ec7-43e1-9d2f-1bc462d5fee9,3059,669,3728,17.95
134,Coimbatore,64391366-c8d4-4b3d-961e-a632a6458d06,2986,652,3638,17.92
5,Ahmedabad,a1b25791-8117-4059-bb44-cb57a42bd7be,2887,628,3515,17.87
141,Haridwar,b9bb6846-a7b6-423a-8c44-5b35c3ba8745,2932,631,3563,17.71
341,Surat,a08faf0a-3921-4ebd-a076-a551e2a9c91d,3001,645,3646,17.69
280,Mumbai,e278914b-34ce-4bd8-a961-1a4456c620cc,968,206,1174,17.55
174,Hyderabad,aed3e474-bd2f-4577-bd79-b74b53ce9e4e,2744,580,3324,17.45
240,Mumbai,21db1e24-d6a7-484a-b5aa-b43e1aafb8fc,929,196,1125,17.42
190,Indore,61d4ef22-b293-4f2b-a1ef-faa0f49c4322,3049,640,3689,17.35
278,Mumbai,dd0aebf0-fb91-4644-bf64-5ac156a4b57f,1012,212,1224,17.32
66,Bangalore,9fb087cf-076d-40a0-b974-8d26eaa69f44,2649,553,3202,17.27
353,Vasai Virar,8185771a-0624-44cc-8370-b1299e6649a5,2405,498,2903,17.15
224,Kota,bf18569a-7111-4e13-b389-edf020a1218d,3092,640,3732,17.15
204,Kanpur,abed156e-9d65-4438-86b9-5c5c4696cbb6,2872,593,3465,17.11
6,Ahmedabad,e677968e-5901-4ff2-8613-ebd72359a67c,481,99,580,17.07
350,Vadodara,3c0de1fa-d7b5-4cef-b867-cad33562463c,3138,645,3783,17.05
26,Bangalore,2614cabb-fff2-4ef6-aa5b-e94c2b875880,1344,276,1620,17.04
85,Bangalore,eeea2403-3a6e-49b7-874b-3d8743ef3cd8,2716,556,3272,16.99
9,Amritsar,848af961-1a54-410e-b220-59a42507d39a,3275,669,3944,16.96
39,Bangalore,542cf806-1216-4d13-b888-c3da22c20db0,1279,261,1540,16.95
327,Pune,c00b42da-968d-46af-b09d-8313ed62be85,2747,556,3303,16.83
324,Pune,931f1ec1-e287-4412-9b52-df3f8ab9c95c,1061,213,1274,16.72
132,Chhatrapati Sambhajinagar,3d1b28be-1e25-471f-a4d9-f2151a7d1bfc,3086,617,3703,16.66
79,Bangalore,dbf340e3-54d9-4842-98da-e11d23d7e3ac,2681,535,3216,16.64
248,Mumbai,3b18ee5e-9d22-44cd-acff-646042e546bf,954,190,1144,16.61
229,Madurai,b91aec1b-7f2b-45a0-b047-bf7750d4d193,2957,589,3546,16.61
68,Bangalore,a559802e-0aed-4cc4-9e51-8f49be9d968e,1260,251,1511,16.61
231,Meerut,a44922a3-06b3-4840-959b-f3f0623c983e,2868,571,3439,16.60
309,Prayagraj,a704a05d-0f16-42da-a511-627c9f613d33,3177,628,3805,16.50
2,Ahmedabad,35225fcb-30cc-4ab8-939b-a0a5e0887285,2725,534,3259,16.39
38,Bangalore,5400933d-3c5d-4015-a767-daed27781a0d,2662,522,3184,16.39
322,Pune,8beb19a0-01c1-4e12-841d-7d7e440a296f,2695,527,3222,16.36
183,Hyderabad,e096acfe-3139-4927-b2c8-f36e3587fcf8,965,187,1152,16.23
349,Vadodara,1bbb2d45-ee2a-40b6-9f0b-c451b7960651,3131,602,3733,16.13
45,Bangalore,6abd3309-1e45-4411-943a-81f5c32fef41,1041,200,1241,16.12
189,Hyderabad,fc88e94a-f4b7-4eab-8ce0-fdecf2e29d5f,981,188,1169,16.08
296,Nagpur,2a87c5ee-1495-4e8f-a259-f1246ab1f2d2,2935,560,3495,16.02
356,Vijayawada,e22f0f25-8f33-43b9-af30-c0bbf8d53126,2971,566,3537,16.00
27,Bangalore,29b4c8b1-587b-497c-b4d9-bd2177fefb34,2642,502,3144,15.97
78,Bangalore,d4205b92-165a-4ad5-89c1-f857521a047f,1137,216,1353,15.96
182,Hyderabad,e052e083-dbfe-4156-a86e-e2fd848f8c3e,964,183,1147,15.95
203,Kanpur,8b5992ad-b397-4fdb-be52-0d780c7cc501,3342,634,3976,15.95
165,Hyderabad,8c84e7ae-6e94-48f2-b4c8-af6c199aef1b,2948,557,3505,15.89
51,Bangalore,774a725c-2c4b-4dc2-94d1-72b737f7e1f6,1210,228,1438,15.86
4,Ahmedabad,5c720bb8-ef8e-45c7-a249-be01de180a15,2909,547,3456,15.83
207,Kochi,1c6c1528-3f93-42f0-8640-66ba46e9dace,3015,567,3582,15.83
281,Mumbai,e5319547-8bba-4fee-862c-7d9ab6dc97c8,974,183,1157,15.82
145,Hyderabad,29f978f1-5bc3-4358-a811-4b817ebebfcb,2755,517,3272,15.80
330,Pune,f931724a-0140-4c06-b832-027e03fc320a,1014,190,1204,15.78
321,Pune,7a75116f-d14e-49b3-bfde-a6c2a4d180a7,1062,199,1261,15.78
58,Bangalore,874241a8-e4fc-439e-a816-ee65aceba124,1725,322,2047,15.73
13,Bangalore,0059ff6a-7eb0-477a-a7f5-69256f2c444b,1196,223,1419,15.72
340,Surat,8ea7989c-7d2a-4093-9713-a17b6c3d9bc8,3035,566,3601,15.72
205,Kanpur,d8ced7ed-2331-40d8-9f41-5154bb1ced89,3162,588,3750,15.68
337,Secunderabad,02a58e65-a110-4856-b787-16ba7ef238ec,1000,185,1185,15.61
311,Pune,281082b4-7a69-4373-a3c3-385b02d134b1,1119,206,1325,15.55
164,Hyderabad,83e33858-a13f-4c67-a016-07de0cce8043,2820,519,3339,15.54
216,Kolkata,917a6609-db18-4f35-ba88-3e681d1ebfa4,2834,521,3355,15.53
3,Ahmedabad,46b54f69-c5ff-4595-934d-3d98fbf33ec0,2971,543,3514,15.45
291,Mysuru,14dd523d-d177-479e-ad17-8d1185f3e185,3379,616,3995,15.42
202,Kanpur,6272824c-8e49-42e1-a31d-19f76894bf74,3196,580,3776,15.36
159,Hyderabad,778b5c2b-0468-4f1e-8fa0-241cc91608a2,972,176,1148,15.33
59,Bangalore,917d20a7-58e4-4574-95dd-dfe3513dd1b2,2651,479,3130,15.30
30,Bangalore,320121c9-8af7-4921-9eea-5c456b7a900d,2758,495,3253,15.22
23,Bangalore,1d852498-590f-4ffa-babf-aae026e3584d,2732,490,3222,15.21
57,Bangalore,843e630a-7896-462d-b7cf-712140483ed3,1200,215,1415,15.19
0,Agra,482b8c90-9e75-4390-9884-64f00a4ce22c,3170,566,3736,15.15
166,Hyderabad,8d94ae95-db29-44f7-b705-d533f7c66176,1030,181,1211,14.95
348,Vadodara,1a376afe-b235-48a4-9153-b33342739fd9,3216,565,3781,14.94
100,Chennai,166f8ba8-c333-4c60-9d12-faeab29ac22c,1129,198,1327,14.92
1,Agra,805ea004-3262-4094-9df6-0b87ad6d1476,3324,580,3904,14.86
74,Bangalore,b4dc8d65-ed2e-4142-81b6-373982b13500,2619,457,3076,14.86
83,Bangalore,ea49abf1-77df-4575-8022-fbcf9e25b3b4,2580,450,3030,14.85
71,Bangalore,abd85a95-f3f3-42fd-aeb0-71b9127335f5,1171,204,1375,14.84
176,Hyderabad,c7cea2d4-d5c9-476b-aa5e-8c72bad4148d,2768,482,3250,14.83
193,Indore,be1ccc2b-a9dd-4372-82da-e831188bcb55,2983,519,3502,14.82
323,Pune,8c4a9155-85ec-409f-a9d8-84b193ec06ad,1157,201,1358,14.80
47,Bangalore,6ceb23b1-672d-4fd7-a89c-66163925a764,2732,473,3205,14.76
343,Surat,ebc8fa1c-02ba-4a0a-a544-0854ce8beead,2970,508,3478,14.61
178,Hyderabad,cf454a02-0633-4d96-8d45-9c90076d3b04,2821,481,3302,14.57
184,Hyderabad,e4cb21ce-7d08-43cf-af28-bf84bac6e094,2616,446,3062,14.57
19,Bangalore,0f5f31f2-f764-498a-9cc5-606cf82f4f2e,2749,468,3217,14.55
339,Surat,2918790f-421a-493e-84a3-e9a2d8f0b60d,494,84,578,14.53
76,Bangalore,ccc9dc9b-9c6f-421e-bedc-f2e7463a75e9,2808,471,3279,14.36
65,Bangalore,9eebbbc9-3fb9-45c1-ab71-312606cf9852,2725,457,3182,14.36
60,Bangalore,93e0e2c3-23a6-471f-9025-8dd79ef87d60,1250,209,1459,14.32
292,Mysuru,31903708-6be4-4223-9730-aa1b43564b75,3338,556,3894,14.28
22,Bangalore,1c9e155e-83a8-457a-a687-01eabb1e7a36,1188,197,1385,14.22
157,Hyderabad,6893b298-d63b-4c4f-b155-2e4a0ca502d5,2877,477,3354,14.22
298,Nagpur,ea7bcce0-6cbf-4a46-a731-3cc66449e073,3137,519,3656,14.20
170,Hyderabad,9ea894e0-db78-45f7-beb1-10b6a52c3fb8,994,164,1158,14.16
70,Bangalore,a7c548c8-f8e5-41c6-9462-1b4d7e8de41e,1159,191,1350,14.15
88,Bangalore,ff1fc8e6-9f22-4c75-b7cf-15a5bd19be91,2702,445,3147,14.14
117,Chennai,a1e3515e-8dbb-4e71-b521-0b6ae27126be,2474,407,2881,14.13
201,Kanpur,54c72546-0ffd-4491-b075-faadc90e4cb0,3423,563,3986,14.12
297,Nagpur,8851f149-0658-4c0f-9995-1fcf9ca5404b,3169,518,3687,14.05
126,Chennai,dfb0d9eb-9cf0-4629-aa03-ba2cf9626042,2610,423,3033,13.95
293,Mysuru,411fefdc-6597-4e1e-ad2c-1cd7cdeadb5a,3059,492,3551,13.86
306,Palakkad,f79f191f-80eb-430f-b855-448625ab2243,3296,528,3824,13.81

In [6]:
out_of_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "Yes",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (Out of Stock):", len(out_of_stock_urls))
out_of_stock_urls.head()

Products to verify (Out of Stock): 217987

,unique_id,product_name,city,store_id,product_url
41,73f81346-fc52-4bbb-8d88-d6dc847179d6,Nestle NAN PRO Stage 2 Follow-up Powder | 6 - 12 M,Mumbai,f860ca85-ea81-46eb-9448-1de0226aa0fe,https://www.zepto.com/pn/nestle-nan-pro-stage-2-follow-up-powder-6-12-m/pvid/73f81346-fc52-4bbb-8d88-d6dc847179d6
42,d78863a0-8340-46e4-b63d-fd35e4c5238a,Aptamil Gold Stage 1 Tin,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/aptamil-gold-stage-1-tin/pvid/d78863a0-8340-46e4-b63d-fd35e4c5238a
46,337dd121-1fa8-462f-9a56-f130e7619601,Nestle NAN PRO Stage 4 Follow-up Formula | 18 - 24 M,Mumbai,f860ca85-ea81-46eb-9448-1de0226aa0fe,https://www.zepto.com/pn/nestle-nan-pro-stage-4-follow-up-formula-18-24-m/pvid/337dd121-1fa8-462f-9a56-f130e7619601
53,42cda441-5b94-4eb5-97d8-f4c3811a59d4,SuperBottoms Langot Trial Kit with 5 Best Selling Langot for New Born | 0 - 6 Months | Up to 5kg,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/superbottoms-langot-trial-kit-with-5-best-selling-langot-for-new-born-0-6-months-up-to-5kg/pvid/42cda441-5b94-4eb5-97d8-f4c3811a59d4
54,54d4e977-f88d-4092-a931-6c8757fc0523,Superbottoms Supersoft Girls Boyshort | 4-6y| Stretchy & Breathable - Pack of 3 | Assorted,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/superbottoms-supersoft-girls-boyshort-4-6y-stretchy-breathable-pack-of-3-assorted/pvid/54d4e977-f88d-4092-a931-6c8757fc0523

In [7]:
in_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "No",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (In Stock):", len(in_stock_urls))
in_stock_urls.head()

Products to verify (In Stock): 808029

,unique_id,product_name,city,store_id,product_url
0,fbd26605-0200-4b3e-834b-bded506a1c31,Happa Apple | Banana Puree,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/happa-apple-banana-puree/pvid/fbd26605-0200-4b3e-834b-bded506a1c31
1,90f8967b-e6f6-40d4-a0e0-ea25eddc9f9e,Happa Apple | Mango | Multigrain Puree,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/happa-apple-mango-multigrain-puree/pvid/90f8967b-e6f6-40d4-a0e0-ea25eddc9f9e
2,af27062e-f619-4749-9a25-d1196f93b01a,Happa Super Puffs Strawberry | Banana,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/happa-super-puffs-strawberry-banana/pvid/af27062e-f619-4749-9a25-d1196f93b01a
3,b72e7ea9-b336-4e2a-b30a-c4ea018ce3d6,Nestle Ceregrow No Refined Sugar Multigrain Cereal,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/nestle-ceregrow-no-refined-sugar-multigrain-cereal/pvid/b72e7ea9-b336-4e2a-b30a-c4ea018ce3d6
4,f0d07a8e-8089-4722-a605-7c8ba2bae85a,Nestle Nangrow Nutritious Milk drink for growing children | 2-6 Years,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,https://www.zepto.com/pn/nestle-nangrow-nutritious-milk-drink-for-growing-children-2-6-years/pvid/f0d07a8e-8089-4722-a605-7c8ba2bae85a