In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
df= pd.read_csv(r'/home/user/Documents/zepto_2026_07_22.csv',  low_memory=False)

In [3]:
summary = (
    df[df["city"] == "Delhi"]
      .groupby(["category", "sub_category"])
      .size()
      .reset_index(name="product_count")
      .sort_values("product_count", ascending=True)
)

summary

                      category                sub_category  product_count
88                   Jewellery                        Sets              1
153                 Zepto Cafe                     Italian              1
149                 Zepto Cafe                       Asian              1
97   Masala, Dry Fruits & More            Powders & Pastes              2
155                 Zepto Cafe                       Sides              2
150                 Zepto Cafe                      Bakery              3
154                 Zepto Cafe                  Sandwiches              4
126         Stationery & Books              Crafts & Hobby             16
152                 Zepto Cafe                     Healthy             48
156                 Zepto Cafe                      Snacks             49
113          Pharma & Wellness                    Ayurveda             58
54         Dairy, Bread & Eggs               Indian Breads             61
79                   Hair Care    Hair Tools & Accessories             62
115          Pharma & Wellness         Vitamin Supplements             77
73                 Frozen Food                  Veg Snacks             97
65            Feminine Hygiene             Personal Safety            101
114          Pharma & Wellness  Rehydration & Electrolytes            102
112              Packaged Food                Ready To Eat            244
11                   Baby Care                   Baby Gear            261
15                   Baby Care                 Baby Safety            263
18                   Baby Care             Infant Clothing            324
157                 Zepto Cafe                Tea & Coffee            415
63            Feminine Hygiene          Period Pain Relief            428
144              Toys & Sports         Musical Accessories            481
145              Toys & Sports         Musical Instruments            522
68            Feminine Hygiene              Toilet Hygiene            529
106              Packaged Food         Baby & Toddler Food            632
136              Toys & Sports              Action Figures            635
19                   Baby Care                    Mom Care            715
148              Toys & Sports                     Toddler            801
59    Electronics & Appliances                    Grooming            817
151                 Zepto Cafe              Cold Beverages            879
143              Toys & Sports   Electronic Toys & Vehicle            890
138              Toys & Sports                 Art & Craft            921
116                   Skincare                   Body Care            922
92             Makeup & Beauty                     Gifting            962
7                    Baby Care          Baby & Mom Gifting            970
122                   Skincare            Hand & Feet Care            971
141              Toys & Sports             Doll & Play Set           1002
137              Toys & Sports   Activities & Outdoor Toys           1046
21                 Bath & Body                     Gifting           1048
139              Toys & Sports            Blocks & Puzzles           1094
10                   Baby Care                Baby Feeding           1106
20                 Bath & Body            Bath Accessories           1179
61            Feminine Hygiene               Intimate Care           1217
62            Feminine Hygiene                Panty Liners           1235
67            Feminine Hygiene                     Tampons           1272
12                   Baby Care                 Baby Health           1292
125                   Skincare              Toners & Mists           1292
108              Packaged Food                 Infant Food           1335
91             Makeup & Beauty                 Face Makeup           1340
146              Toys & Sports                   Soft Toys           1363
124                   Skincare                    Sun Care           1375
94             Makeup & Beauty                       Nails           1411
140              Toys & Sports          Card & Board Games           1457
13                   Baby Care                Baby Hygiene           1511
78                   Hair Care                Hair Styling           1666
90             Makeup & Beauty                  Eye Makeup           1712
17                   Baby Care                  Baby Wipes           1743
76                   Hair Care                    Hair Oil           1796
70       Fragrances & Grooming              Men's Grooming           1820
147              Toys & Sports            Sports & Fitness           1824
77                   Hair Care         Hair Serum & Polish           1957
52         Dairy, Bread & Eggs      Curd & Probiotic Drink           2000
93             Makeup & Beauty                 Lips Makeup           2021
56         Dairy, Bread & Eggs           Milk Based Drinks           2058
74                   Hair Care         Conditioner & Masks           2065
118                   Skincare              Eye & Lip Care           2096
23                 Bath & Body                 Shower Gels           2110
16                   Baby Care       Baby Skin & Hair Care           2174
60            Feminine Hygiene      Hair Removal For Women           2230
142              Toys & Sports   Educational Toys & Sports           2284
83           Ice Creams & More                        Cups           2312
123                   Skincare            Serums & Essence           2324
48         Dairy, Bread & Eggs             Batters & Mixes           2325
34                    Biscuits                      Wafers           2350
47        Cold Drinks & Juices                       Water           2454
14                   Baby Care              Baby Oral Care           2475
111              Packaged Food               Ready To Cook           2535
22                 Bath & Body                   Mouthwash           2550
31                    Biscuits                  Digestives           2554
80                   Hair Care                     Shampoo           2555
64            Feminine Hygiene              Period Panties           2562
132         Tea, Coffee & More                      Coffee           2577
46        Cold Drinks & Juices                Vegan Drinks           2579
75                   Hair Care                  Hair Color           2683
8                    Baby Care                   Baby Bath           2692
33                    Biscuits                Rusk & Khari           2701
40        Cold Drinks & Juices                Energy Drink           2721
4       Atta, Rice, Oil & Dals      Millets & Other Flours           2728
84           Ice Creams & More        Ice Cubes & Ice Pops           2742
85           Ice Creams & More                       Kulfi           2752
129             Sweet Cravings               Indian Mithai           2761
42        Cold Drinks & Juices         Instant Drink Mixes           2787
25                 Bath & Body               Talcum Powder           2789
3       Atta, Rice, Oil & Dals                        Ghee           2824
32                    Biscuits             Glucose & Marie           2842
69       Fragrances & Grooming             Deos & Roll Ons           2863
134         Tea, Coffee & More          Green & Herbal Tea           2876
29                    Biscuits                    Crackers           2946
30                    Biscuits                  Creamfills           2948
72                 Frozen Food      Sausages, Salami & Ham           2974
38          Breakfast & Sauces               Muesli & Oats           2975
95   Masala, Dry Fruits & More               Dates & Seeds           2990
119                   Skincare                   Face Care           3002
41        Cold Drinks & Juices       Fruit Juices & Drinks           3030
27                 Bath & Body                  Toothpaste           3032
133         Tea, Coffee & More      Cold Coffee & Iced Tea           3068
35          Breakfast & Sauces           Breakfast Cereals           3069
109              Packaged Food        Noodles & Vermicelli           3076
9                    Baby Care              Baby Diapering           3079
53         Dairy, Bread & Eggs                        Eggs           3080
135         Tea, Coffee & More                         Tea           3089
0       Atta, Rice, Oil & Dals                        Atta           3097
81           Ice Creams & More    Cakes, Sandwiches & More           3103
50         Dairy, Bread & Eggs                      Butter           3103
66            Feminine Hygiene               Sanitary Pads           3106
51         Dairy, Bread & Eggs                      Cheese           3118
45        Cold Drinks & Juices                 Soft Drinks           3130
57         Dairy, Bread & Eggs              Paneer & Cream           3146
127             Sweet Cravings       Candies, Gums & Mints           3151
89             Makeup & Beauty          Beauty Accessories           3167
44        Cold Drinks & Juices               Soda & Mixers           3169
1       Atta, Rice, Oil & Dals        Besan, Sooji & Maida           3173
5       Atta, Rice, Oil & Dals                         Oil           3190
130             Sweet Cravings            Pastries & Cakes           3192
39          Breakfast & Sauces               Peanut Butter           3198
58         Dairy, Bread & Eggs          Yogurt & Shrikhand           3210
55         Dairy, Bread & Eggs                        Milk           3214
98   Masala, Dry Fruits & More       Salt, Sugar & Jaggery           3217
99   Masala, Dry Fruits & More   Whole Spices & Seasonings           3221
105                   Munchies                     Popcorn           3222
43        Cold Drinks & Juices                 Milk Drinks           3223
2       Atta, Rice, Oil & Dals               Dals & Pulses           3235
49         Dairy, Bread & Eggs               Breads & Buns           3236
110              Packaged Food   Papads, Pickles & Chutney           3244
24                 Bath & Body                       Soaps           3248
103                   Munchies                      Nachos           3248
36          Breakfast & Sauces             Honey & Spreads           3257
107              Packaged Food  Baking Mixes & Ingredients           3260
37          Breakfast & Sauces            Ketchup & Sauces           3261
96   Masala, Dry Fruits & More           Dry Fruits & Nuts           3263
28                    Biscuits                     Cookies           3292
102                   Munchies                 Energy Bars           3313
131             Sweet Cravings          Premium Chocolates           3411
82           Ice Creams & More                       Cones           3442
104                   Munchies                    Namkeens           3460
101                   Munchies  Dry Fruits & Nuts Munchies           3481
71       Fragrances & Grooming                    Perfumes           3668
86           Ice Creams & More                      Sticks           3849
87           Ice Creams & More                        Tubs           3853
120                   Skincare          Face Creams & Gels           4057
117                   Skincare   Body Lotion & Moisturizer           4253
128             Sweet Cravings                  Chocolates           4345
26                 Bath & Body           Toothbrush & More           4505
100                   Munchies              Chips & Crisps           5207
6       Atta, Rice, Oil & Dals                 Rice & More           5514
121                   Skincare          Face Wash & Scrubs           8270

In [9]:
df.head()

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-07-22 09:40:29,zepto,1c3ca061-43e6-4119-85c3-76e51106a606,"1, Dwarka Goyla Dairy Rd, Near Goyla More, Deenpur, Surya Vihar, Najafgarh, New Delhi, Delhi, 110043, India",Delhi,110043,08aa72b7-cac2-4cbb-84d9-525c812f19fa,920e3ebd-5c66-4e51-9795-d48baf63ff1c,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Atta,NaN,Aashirvaad,Aashirvaad Shudh Chakki Atta | Pure Atta 0% Maida,NaN,10 kg,NaN,1 pack (10 kg),NaN,489.0,449.0,No,Yes,449.0,NaN,₹40 OFF,449.0,8,2,https://www.zepto.com/pn/aashirvaad-shudh-chakki-atta-pure-atta-0-maida/pvid/08aa72b7-cac2-4cbb-84d9-525c812f19fa,NaN
1,2026-07-22 09:40:29,zepto,1c3ca061-43e6-4119-85c3-76e51106a606,"1, Dwarka Goyla Dairy Rd, Near Goyla More, Deenpur, Surya Vihar, Najafgarh, New Delhi, Delhi, 110043, India",Delhi,110043,02f06d00-5bfc-4574-9fe3-d96d443da0f8,041ba1d7-0309-4533-8acd-33c18dfa2bd6,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Atta,NaN,Daily Good,Whole Wheat Chakki Atta,NaN,10 kg,NaN,1 pack (10 kg),NaN,560.0,381.0,No,Yes,381.0,NaN,₹179 OFF,381.0,31,6,https://www.zepto.com/pn/whole-wheat-chakki-atta/pvid/02f06d00-5bfc-4574-9fe3-d96d443da0f8,NaN
2,2026-07-22 09:40:29,zepto,1c3ca061-43e6-4119-85c3-76e51106a606,"1, Dwarka Goyla Dairy Rd, Near Goyla More, Deenpur, Surya Vihar, Najafgarh, New Delhi, Delhi, 110043, India",Delhi,110043,e885d51e-6d37-47dd-9b02-42812c8f755e,920e3ebd-5c66-4e51-9795-d48baf63ff1c,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Atta,NaN,Aashirvaad,Aashirvaad Shudh Chakki Atta | Pure Atta 0% Maida,NaN,5 kg,NaN,1 pack (5 kg),NaN,262.0,238.0,No,Yes,238.0,NaN,₹24 OFF,238.0,9,2,https://www.zepto.com/pn/aashirvaad-shudh-chakki-atta-pure-atta-0-maida/pvid/e885d51e-6d37-47dd-9b02-42812c8f755e,NaN
3,2026-07-22 09:40:29,zepto,1c3ca061-43e6-4119-85c3-76e51106a606,"1, Dwarka Goyla Dairy Rd, Near Goyla More, Deenpur, Surya Vihar, Najafgarh, New Delhi, Delhi, 110043, India",Delhi,110043,1f2ac706-4277-40fa-928b-18980ec09289,cf8a682e-43c4-49f3-81d0-3588c4baaf47,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Atta,NaN,Pansari,"Pansari Chakki Fresh Atta | 100% Atta, 0% Maida",NaN,10 kg,NaN,1 pack (10 kg),NaN,492.0,397.0,No,Yes,397.0,NaN,₹95 OFF,397.0,19,4,https://www.zepto.com/pn/pansari-chakki-fresh-atta-100-atta-0-maida/pvid/1f2ac706-4277-40fa-928b-18980ec09289,NaN
4,2026-07-22 09:40:29,zepto,1c3ca061-43e6-4119-85c3-76e51106a606,"1, Dwarka Goyla Dairy Rd, Near Goyla More, Deenpur, Surya Vihar, Najafgarh, New Delhi, Delhi, 110043, India",Delhi,110043,ada057ef-353d-4fa5-a187-a34e5daf0864,20c928c1-3a78-4d00-9177-dc90f72223d2,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Atta,NaN,Pillsbury,Pillsbury Chakki Fresh Atta,NaN,10 kg,NaN,1 pack (10 kg),NaN,495.0,399.0,No,Yes,399.0,NaN,₹96 OFF,399.0,19,2,https://www.zepto.com/pn/pillsbury-chakki-fresh-atta/pvid/ada057ef-353d-4fa5-a187-a34e5daf0864,NaN

In [3]:
df.shape

(443539, 31)

In [4]:
df.isnull().sum()

crawl_date_and_time             0
platform_name                   0
store_id                        0
store_name_location             0
city                            0
pin_code                        0
unique_id                       0
product_id_upc_ean              0
department                      0
category                        0
sub_category                    0
product_type               443539
brand_name                      0
product_name                    0
product_description        443539
product_grammage            67591
package_type               443539
net_quantity                    1
variants                   435208
item_mrp                        0
item_selling_price              0
out_of_stock_flag               0
discount_flag                   0
product_price                   0
unit_price                 443539
promo_offer_description         0
promo_offer_price               0
discount_in_percent             0
stock_count                     0
product_url                     0
product_image_urls         443539
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.nunique()

crawl_date_and_time        13180
platform_name                  1
store_id                     159
store_name_location          148
city                           2
pin_code                      79
unique_id                   7229
product_id_upc_ean          7066
department                    10
category                      25
sub_category                 158
product_type                   0
brand_name                  1099
product_name                6734
product_description            0
product_grammage             659
package_type                   0
net_quantity                1128
variants                     142
item_mrp                     879
item_selling_price          1609
out_of_stock_flag              2
discount_flag                  2
product_price               1609
unit_price                     0
promo_offer_description     1074
promo_offer_price           1609
discount_in_percent           91
stock_count                   51
product_url                 7231
product_image_urls             0
dtype: int64

In [7]:
df.city.value_counts()

city
Delhi      342191
Gurgaon    101348
Name: count, dtype: int64

In [8]:
df[df['net_quantity'].isna()]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
388211,2026-07-22 13:43:17,zepto,b6ac55e9-9d60-4ea1-86b8-fe554ea1490c,"528/1, Shitala Mata Mandir Marg, Sheetla Colony Phase 2, Sheetala Colony, Gurugram, Haryana, 122017, India",Gurgaon,122017,f44d5eaf-082b-4424-be02-e0dd71beaf64,e80c7713-f499-4f36-bad3-70745079d84a,Organic & Premium,Packaged Food,Ready To Cook,NaN,Heinz,Heinz Beaked Beans,NaN,NaN,NaN,NaN,NaN,199.0,178.0,No,Yes,178.0,NaN,₹21 OFF,178.0,10,2,https://www.zepto.com/pn/heinz-beaked-beans/pvid/f44d5eaf-082b-4424-be02-e0dd71beaf64,NaN

In [10]:
import pandas as pd

# Missing product_grammage
grammage_missing = (
    df["product_grammage"].isna() |
    (df["product_grammage"].astype(str).str.strip() == "")
)

# net_quantity contains text inside parentheses
netqty_with_brackets = (
    df["net_quantity"]
      .fillna("")
      .str.contains(r"\(.+\)", regex=True)
)

issues = df[grammage_missing & netqty_with_brackets]

print("Rows found:", len(issues))

issues[[
    "unique_id",
    "product_name",
    "net_quantity",
    "product_grammage"
]]

Rows found: 0

Empty DataFrame
Columns: [unique_id, product_name, net_quantity, product_grammage]
Index: []

In [13]:
import pandas as pd

# Missing product_grammage
grammage_missing = (
    df["product_grammage"].isna() |
    (df["product_grammage"].astype(str).str.strip() == "")
)

# net_quantity contains a measurement inside parentheses
pattern = r"\(\s*[\d.,]+\s*(g|kg|mg|ml|l)\s*(?:or\s*[\d.,]+\s*(g|kg|mg|ml|l))?(?:\s*\+\s*[\d.,]+\s*(g|kg|mg|ml|l))*\s*\)"

mask = df["net_quantity"].fillna("").str.contains(
    pattern,
    case=False,
    regex=True,
    na=False
)

issues = df[grammage_missing & mask]

print("Rows found:", len(issues))

issues[[
    "unique_id",
    "product_name",
    "net_quantity",
    "product_grammage"
]]

/tmp/ipykernel_18107/5463894.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df["net_quantity"].fillna("").str.contains(

Rows found: 0

Empty DataFrame
Columns: [unique_id, product_name, net_quantity, product_grammage]
Index: []

In [17]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Delhi,15457,34228,29217,48036,35101,44988,19289,41038,46631,28206
Gurgaon,4225,12546,8124,14988,10024,12940,5239,11061,14050,8151

In [18]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

category,"Atta, Rice, Oil & Dals",Baby Care,Bath & Body,Biscuits,Breakfast & Sauces,Cold Drinks & Juices,"Dairy, Bread & Eggs",Electronics & Appliances,Feminine Hygiene,Fragrances & Grooming,Frozen Food,Hair Care,Ice Creams & More,Jewellery,Makeup & Beauty,"Masala, Dry Fruits & More",Munchies,Packaged Food,Pharma & Wellness,Skincare,Stationery & Books,Sweet Cravings,"Tea, Coffee & More",Toys & Sports,Zepto Cafe
city,,,,,,,,,,,,,,,,,,,,,,,,,
Gurgaon,6493,5849,6377,5518,4450,6673,8517,411,3293,2635,552,4266,6424,0,3085,3373,5973,4510,81,9006,9,4593,3349,5859,52

In [19]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals]"
1,Baby Care,"[Baby Care, Packaged Food, Pharma & Wellness, Stationery & Books, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Breakfast & Sauces, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food]"
6,Munchies,"[Masala, Dry Fruits & More, Munchies, Packaged Food]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Skincare]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Fragrances & Grooming, Frozen Food, Ice Creams & More, Jewellery, Munchies, Packaged Food, Sweet Cravings]"

In [20]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag      No    Yes   Total  Out_of_stock_%
city
Delhi              276779  65412  342191           19.12
Gurgaon             83977  17371  101348           17.14

In [21]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag        No    Yes  Total  Out_of_stock_%
department
Baby Care             35544  11230  46774           24.01
Personal Care         47408  13273  60681           21.87
Beauty & Cosmetics    50339  12685  63024           20.13
Cold Drinks & Juices  36391   8734  45125           19.36
Dairy & Breakfast     47170  10758  57928           18.57
Bakery & Biscuits     30646   6695  37341           17.93
Sweet Tooth           29853   6504  36357           17.89
Organic & Premium     44709   7390  52099           14.18
Atta, Rice & Dal      16967   2715  19682           13.79
Munchies              21729   2799  24528           11.41

In [22]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No   Yes  Total  Out_of_stock_%
category
Zepto Cafe                   664   790   1454           54.33
Pharma & Wellness            206   112    318           35.22
Electronics & Appliances     817   411   1228           33.47
Makeup & Beauty             9998  3700  13698           27.01
Fragrances & Grooming       8049  2937  10986           26.73
Baby Care                  17947  6507  24454           26.61
Dairy, Bread & Eggs        29020  8048  37068           21.71
Feminine Hygiene           12590  3383  15973           21.18
Skincare                   30048  7520  37568           20.02
Toys & Sports              16155  4024  20179           19.94
Biscuits                   20450  4701  25151           18.69
Cold Drinks & Juices       24236  5530  29766           18.58
Bath & Body                21994  4844  26838           18.05
Sweet Cravings             17730  3723  21453           17.35
Ice Creams & More          23557  4920  28477           17.28
Hair Care                  14176  2874  17050           16.86
Packaged Food              15774  3062  18836           16.26
Atta, Rice, Oil & Dals     25508  4746  30254           15.69
Munchies                   23636  4268  27904           15.30
Tea, Coffee & More         12976  1983  14959           13.26
Masala, Dry Fruits & More  14037  2029  16066           12.63
Breakfast & Sauces         17924  2286  20210           11.31
Frozen Food                 3239   384   3623           10.60
Stationery & Books            24     1     25            4.00
Jewellery                      1     0      1            0.00

In [23]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
143,Gurgaon,9fd9b34c-0ffe-4180-adde-ba6fd267fb50,0,1,1,100.00
114,Delhi,f2818431-48b5-4b57-9ec5-02e8eef7bc92,926,702,1628,43.12
16,Delhi,261b9c45-eb5b-4398-be1c-909ccde6f629,1922,1376,3298,41.72
139,Gurgaon,90f2f25e-b21f-4999-957f-a96a81f01dfb,2170,1485,3655,40.63
40,Delhi,4b54927e-5c54-4564-8c9f-1e518e6488e3,2160,1408,3568,39.46
109,Delhi,ead42923-cfd0-4a7d-bb71-b879631773f1,1879,1181,3060,38.59
39,Delhi,49d9df40-6b3b-4f3e-ad7d-bda18f57d419,1882,1179,3061,38.52
23,Delhi,31a8b99d-0d1a-4f32-a367-e6cf62bb8603,2002,1213,3215,37.73
65,Delhi,7e7b4df8-a5a1-4acb-9aa4-b5ecf86a6f2b,2137,1263,3400,37.15
64,Delhi,7e586f3d-8e30-4859-8851-4476b8a965f4,2240,1322,3562,37.11
47,Delhi,57fbfbc2-6ec0-4465-aff3-81e771faf303,2139,1222,3361,36.36
155,Gurgaon,e09e8bac-2aad-4634-9d2c-d19833956f3a,2059,1131,3190,35.45
2,Delhi,05c5bd1a-d9b2-4ea3-848c-d8ae96b1d04a,2412,1239,3651,33.94
8,Delhi,1585f304-7c1d-404d-b925-84bd48e90433,2031,1022,3053,33.48
0,Delhi,01e98a7e-46d7-48f1-bbcd-8e864116e992,2094,960,3054,31.43
24,Delhi,321b0b48-7137-4832-ab17-f131421bdb78,2232,994,3226,30.81
82,Delhi,a5ff49ab-36f4-4aa6-b66e-de385f5d147b,1083,456,1539,29.63
12,Delhi,1edbc6f5-f8dd-4dd0-9555-a8a5d90dd2d7,2135,891,3026,29.44
86,Delhi,ac3b884c-75d1-48a6-b477-0a0782cf19b4,2581,1016,3597,28.25
99,Delhi,c978abd4-1b79-40d2-ab47-ec19b7c29d41,1265,494,1759,28.08
93,Delhi,c46cc946-f7eb-4f5b-aaff-cf6fdcba6618,2234,857,3091,27.73
98,Delhi,c951a741-faf1-4189-be8c-e441b6985190,2246,848,3094,27.41
89,Delhi,b8aed0f4-59e0-4387-825d-406800150b71,2430,912,3342,27.29
95,Delhi,c70d824a-414c-4204-8ae3-d3f6bac461b4,2057,763,2820,27.06
54,Delhi,6118ee4c-ee70-4b20-b071-f8e5e39fb7be,2346,856,3202,26.73
137,Gurgaon,82dffafa-bf7f-4752-a0b2-561dc1349c4a,2353,842,3195,26.35
25,Delhi,32ac84e0-0a29-4c1f-865a-c33780173389,2278,803,3081,26.06
50,Delhi,5d8ec059-9f5f-4867-8520-b232a1ebde3d,2219,764,2983,25.61
60,Delhi,73952e1c-38a1-40a3-b71f-a4150849ee52,2191,750,2941,25.50
121,Gurgaon,0a493c16-c8cc-4f45-a02c-51e7b1328f53,2670,909,3579,25.40
57,Delhi,681003a8-bce8-4481-980d-8253746471e6,1270,432,1702,25.38
76,Delhi,93cd2e82-b141-41bc-91c5-2805396da43d,2621,888,3509,25.31
112,Delhi,f02ef084-eab2-4651-8168-a4814b97ca06,2326,771,3097,24.90
46,Delhi,57a0c2ae-1cf1-4c4a-99eb-eb2e19864075,1627,533,2160,24.68
80,Delhi,9bb503dd-63be-4b26-b2ba-8fe51192d2bd,1311,428,1739,24.61
92,Delhi,c2c05ffc-0eb1-4164-86cc-49cb1271d92a,2162,690,2852,24.19
61,Delhi,73b0c599-728d-4642-a0e3-1e5b68836327,2323,725,3048,23.79
102,Delhi,da285a58-89f2-448e-b5d7-dddce15e9bba,2336,719,3055,23.54
132,Gurgaon,58d6551e-edf2-48df-828c-7deb5a25033f,2807,852,3659,23.29
34,Delhi,41b702ce-4302-4b24-8997-c9bd507d5ea7,2773,834,3607,23.12
158,Gurgaon,fd647cf6-e1e8-417e-b2ce-e3f9cb4fbb4f,2307,691,2998,23.05
66,Delhi,7ed44401-afcd-41bb-9122-fcfaa918a101,2162,641,2803,22.87
106,Delhi,dc8d6b1b-1d01-46bd-809c-606fca125ab1,2437,695,3132,22.19
111,Delhi,efaa6e99-a68b-4c31-a50a-1bc5712533d7,1252,342,1594,21.46
30,Delhi,3a8029df-cae5-4c17-88ea-814f8366b814,2473,675,3148,21.44
74,Delhi,8fe0a1ee-0ea0-4a84-ba34-80b0d266ad31,2391,651,3042,21.40
77,Delhi,94f50df3-fb2e-4c36-ad6f-8a00bfd1c6af,1291,348,1639,21.23
21,Delhi,2fa35ecf-4334-4ec6-b6de-5bae11a3dbf7,2763,736,3499,21.03
115,Delhi,f2e8316d-0937-4104-bae3-a24d608bb09c,2381,617,2998,20.58
20,Delhi,2baf335a-045a-4401-8761-a53b44b5cdcd,2219,564,2783,20.27
81,Delhi,a122a7fb-b822-45b5-adb5-c92ed4661980,2296,577,2873,20.08
67,Delhi,803ae812-e031-4287-9513-8137dac95f3d,2218,555,2773,20.01
29,Delhi,34af034f-74b8-4fa1-a931-3c25375f374f,4,1,5,20.00
73,Delhi,8dde3f32-eae6-42e2-a9cc-ada2f0a9d22f,1309,325,1634,19.89
138,Gurgaon,9062036c-d6b8-4291-ae86-775d46774b56,3048,741,3789,19.56
90,Delhi,b8d61fbc-eb4a-4836-b785-e3b63aa3fa62,2259,545,2804,19.44
157,Gurgaon,f4626c02-1bd4-4396-9a7c-e111d2fc0170,1307,312,1619,19.27
107,Delhi,e0a0c84c-0819-482e-8b95-55d4b32592d8,1276,303,1579,19.19
125,Gurgaon,1c31b7f9-1213-49ea-8346-4879856906a4,2566,609,3175,19.18
15,Delhi,2522b064-b9af-4967-9c41-2bfffe8786d3,2404,561,2965,18.92
32,Delhi,3d03e7a7-4ded-458a-9349-2978cd333ef0,2855,664,3519,18.87
44,Delhi,55bbe2f9-33f4-4ce0-a864-9730284b2a7c,2596,593,3189,18.60
126,Gurgaon,1d31c12c-1669-4ed5-bf1e-251da70753b8,1240,276,1516,18.21
151,Gurgaon,d890c3ec-bdf4-4253-b3b4-60742f691584,1296,282,1578,17.87
119,Delhi,f88dd0bb-dc4a-400c-badc-d8fc18aeaeb7,1323,283,1606,17.62
84,Delhi,aa443b4b-bf3b-499c-a846-bf5196d444ae,2202,466,2668,17.47
33,Delhi,3f23fe21-69e5-4b46-9e90-809b609a3131,1303,273,1576,17.32
70,Delhi,84f9975d-cc19-4d21-aa76-43e3aab9779a,2476,513,2989,17.16
118,Delhi,f70fa1be-1eea-45a4-a692-219b12d85b24,2577,517,3094,16.71
55,Delhi,656bef79-0f91-45cd-9f93-8fedf1a932ce,2755,552,3307,16.69
108,Delhi,e1befcff-e3d0-4fce-929c-50b9b6ae296f,25,5,30,16.67
96,Delhi,c73b0824-ac1e-43eb-98e4-ed5b849a651b,2957,590,3547,16.63
7,Delhi,10655b62-1ead-42a2-a02c-d7a749951d48,2580,510,3090,16.50
116,Delhi,f36075d2-40c9-4e63-a9d0-4fe36b2ca31f,2620,508,3128,16.24
146,Gurgaon,baa090fc-be13-4b34-87c5-2aea256fd4c4,2566,495,3061,16.17
104,Delhi,dad7f2ba-1d52-4c30-8c5a-c7fa01f705a1,2579,497,3076,16.16
56,Delhi,65b4f18b-34d3-43f7-a3ce-361471b15345,2615,503,3118,16.13
136,Gurgaon,760bb995-e9d4-4372-8a03-6d34c08cec8d,2639,505,3144,16.06
105,Delhi,db68a1c5-3c18-49d4-bd83-87b4f580fd45,2667,507,3174,15.97
120,Gurgaon,02d2c306-7699-434b-947e-88c99afc54f9,2003,379,2382,15.91
128,Gurgaon,225cd095-2106-490a-81c8-de5faa97ac65,2611,491,3102,15.83
153,Gurgaon,de5f724c-2832-47fb-b811-d0cdcc00157d,2516,473,2989,15.82
130,Gurgaon,48a75423-507c-4e6d-8eaa-603c77f48b05,2624,486,3110,15.63
148,Gurgaon,cb64eb92-03c1-452a-b98d-2582d7818f74,2488,460,2948,15.60
4,Delhi,082229f8-d7ec-4b29-8220-db1d7776d7e9,2775,509,3284,15.50
59,Delhi,70bbc5c2-af73-43f1-a5ee-e76a9ca9019f,2660,487,3147,15.48
117,Delhi,f429e749-364b-480a-a86d-b3bd2c0d6620,2347,428,2775,15.42
51,Delhi,5dbd7e40-75db-452c-bd76-7dac3d7c0c0b,2636,479,3115,15.38
145,Gurgaon,b6ac55e9-9d60-4ea1-86b8-fe554ea1490c,1373,249,1622,15.35
142,Gurgaon,9bfb7127-8a86-4de2-968a-e7cd9d1b8d51,2614,473,3087,15.32
36,Delhi,4332c938-8582-4628-95d9-2844086daf78,2517,441,2958,14.91
19,Delhi,2b2c7579-3735-4ddc-8f77-2ba7f4c1a307,2365,414,2779,14.90
124,Gurgaon,19196ae9-a62a-4eee-a6c3-b6243c9b3f01,2651,458,3109,14.73
141,Gurgaon,9a51d2b1-9708-4648-a294-0f5a5909cf5a,2725,468,3193,14.66
149,Gurgaon,d38c9d04-5703-4156-8431-c27aebbf3dc1,1406,240,1646,14.58
88,Delhi,b5c0eebd-0709-4d34-9530-d4540f4db62f,2949,501,3450,14.52
41,Delhi,4ba5f414-34e0-442c-938e-ef76fc9804bf,2711,458,3169,14.45
17,Delhi,266fb1d0-6495-4f65-9bcd-f03b54724799,2730,456,3186,14.31
6,Delhi,0c865653-8eac-4a33-900c-d2ed7f3c0477,2702,451,3153,14.30
14,Delhi,23e18cbf-7e46-49ec-a559-d5a6cdb09d3b,2581,430,3011,14.28
45,Delhi,56c431da-a864-4121-be49-15e003139701,2690,447,3137,14.25
35,Delhi,42d58798-26cc-429a-aea6-92dbbecae776,2654,440,3094,14.22
38,Delhi,444a442d-982b-437d-a8eb-9ca9385eaed5,2739,453,3192,14.19
78,Delhi,9550ef6d-d1b6-4eb1-b379-580404d9c1d3,2689,443,3132,14.14
122,Gurgaon,0cdd4ac3-fbeb-4bfd-8960-ebf2192d29b4,1276,210,1486,14.13
71,Delhi,852818aa-dfa5-4943-b2b5-1cd51c26bdd5,2780,457,3237,14.12
26,Delhi,3325a4aa-354c-4c9a-9230-178cbb4286f6,2873,468,3341,14.01
18,Delhi,2a655482-29d6-48fd-bb6c-6051fb5900ee,1359,221,1580,13.99
72,Delhi,8a63a860-9ec1-4fcc-b37a-523a34647742,2798,450,3248,13.85
94,Delhi,c620a3ce-ee2e-493f-a83d-5555531fd861,2768,439,3207,13.69
52,Delhi,5ebdb9c0-59e0-436c-9e67-5594e00a45af,2633,417,3050,13.67
127,Gurgaon,1f606e33-cc6a-46ae-95d7-21bb5a401d7a,1350,210,1560,13.46
140,Gurgaon,96348a97-316b-4e61-963d-05f9827366de,52,8,60,13.33
113,Delhi,f090d50a-60ed-4b98-9493-3f0d9751a3f3,2753,412,3165,13.02
13,Delhi,207df3d7-87f9-4b65-b6be-8e7114d22512,1270,190,1460,13.01
11,Delhi,1c3ca061-43e6-4119-85c3-76e51106a606,2637,394,3031,13.00
1,Delhi,0553cf88-c712-4469-88b0-bec9e41ef03c,2368,352,2720,12.94
101,Delhi,d9b656fe-41ad-4645-9fad-af3bf1cf7d8f,2729,404,3133,12.89
69,Delhi,834e1acb-7f03-424e-9b2b-3bebefbdde9a,2529,371,2900,12.79
27,Delhi,33622370-e10f-4996-aaf2-84076a8f66c2,2496,363,2859,12.70
43,Delhi,4f0e57e8-9610-41b9-acb0-efe2cd7eb7d9,2699,383,3082,12.43
147,Gurgaon,bcfaff62-217e-4fab-b8cd-a89d81ccfc4a,2561,363,2924,12.41
134,Gurgaon,6c3a340a-8c23-4518-95ff-4e7aebe0ff6a,2657,374,3031,12.34
28,Delhi,34420157-825b-4822-acc8-9f20ae822fe3,2748,386,3134,12.32
79,Delhi,96a968d7-aca7-4b78-9302-ef72fbb1cc57,2683,375,3058,12.26
129,Gurgaon,2809502a-1c2c-4305-9b1d-f00d75bf65c3,2777,387,3164,12.23
91,Delhi,bc4b39b0-c1c4-4b68-aef5-076a323e8cf4,2674,372,3046,12.21
5,Delhi,08d249a3-3f40-428b-8ec5-cd9beb33ed41,2629,364,2993,12.16
58,Delhi,6e87b960-71e6-414e-b6f7-55d08e324811,2545,342,2887,11.85
68,Delhi,81d2371c-4e12-4122-9799-f8c21807947d,1101,145,1246,11.64
9,Delhi,17a221cb-335d-4a8c-a04a-694435f615c3,2605,341,2946,11.58
152,Gurgaon,dbce85ee-e3de-44b6-994d-72bc38c63389,2815,364,3179,11.45
133,Gurgaon,6596a71b-54df-4556-9119-7de895a9c300,2767,352,3119,11.29
131,Gurgaon,4db16931-a992-4b6a-805d-be5d594941ba,2702,344,3046,11.29
31,Delhi,3a9d3627-e56b-4584-ab9f-ed78e1903ed4,2602,330,2932,11.26
123,Gurgaon,1879c01a-f20c-4987-9ce4-0f47f75ad4f9,2832,359,3191,11.25
49,Delhi,5cad640b-fe79-43bb-aac2-849733defb55,2729,338,3067,11.02
100,Delhi,d13c1520-9614-4788-940b-b94ebdfa434f,2616,324,2940,11.02
22,Delhi,3072e208-7b9a-4821-a000-e121ba8a43fa,2850,352,3202,10.99
150,Gurgaon,d8507dc4-e2dc-4b97-96f6-c7d285da48bf,2783,340,3123,10.89
110,Delhi,ebc222f1-119b-457b-a137-3a4cfa10c571,2731,333,3064,10.87
53,Delhi,5ee3f39d-3d7b-44b2-bbeb-b17e8457dc4e,2875,346,3221,10.74
144,Gurgaon,a05f78f8-00f3-4105-b850-f8bf851e5996,2490,299,2789,10.72
3,Delhi,05d5e1df-5159-4484-8322-87e02e4655c3,2591,308,2899,10.62
48,Delhi,5c5665dc-dc3a-4a6e-9829-acecadfe49d5,2932,348,3280,10.61
97,Delhi,c8e077b9-6eec-4317-8254-6fd9eca59bed,2608,306,2914,10.50
42,Delhi,4de81c28-7ac9-4ad6-80e4-b812ed475261,2612,283,2895,9.78
37,Delhi,433bb54d-7e04-4f91-ac03-bee784a3102c,2639,271,2910,9.31
10,Delhi,194a2150-fe10-4b2a-b495-badf3eb25273,1435,143,1578,9.06
103,Delhi,da5125c1-14c6-4407-b8a3-7e2749ecbc51,2696,268,2964,9.04
83,Delhi,a7a8db9f-5860-4635-9e4b-8b3aba6526e4,2654,262,2916,8.98
154,Gurgaon,e03f540b-f6e2-4749-93fc-5c777cb31628,1348,131,1479,8.86
135,Gurgaon,73af75a4-63d5-4a42-9d43-900e02bc7266,2562,238,2800,8.50
87,Delhi,ad2daf79-44db-459d-9a45-d7807b5b37a2,2941,259,3200,8.09
156,Gurgaon,e7baa74b-172d-4b9d-9a62-a797d0cd9b3a,966,84,1050,8.00
85,Delhi,ab0ae767-8b37-467b-9774-5c04a83c6ef6,2620,227,2847,7.97
63,Delhi,7841c1f4-64bf-4c81-824f-c5369ead251d,2694,218,2912,7.49
62,Delhi,7583cabb-d210-453f-87e1-cf28634b6a85,2741,206,2947,6.99
75,Delhi,91e425f8-a2d5-49e5-9f7d-a31972d22b0b,2656,179,2835,6.31

In [3]:
store_id = "9fd9b34c-0ffe-4180-adde-ba6fd267fb50"

df[df["store_id"] == store_id]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
407892,2026-07-22 13:54:57,zepto,9fd9b34c-0ffe-4180-adde-ba6fd267fb50,"Omi Tuition Classes/coaching Centre(otc), Near Sangam Sweet Shop, Near Chauma, Chauma Village, Sector 1, Mahzid, Gurugram, Haryana, 122017, India",Gurgaon,122017,e7beef17-2cdb-427a-859c-68fca8c4187c,3f420b5b-21ed-4344-ba73-9417d3ad5d7a,Baby Care,Toys & Sports,Soft Toys,NaN,Fablue,Fablue Penguin Plush & Soft Toy For Boys Girls And Kids | Black & White - 17 cm,NaN,NaN,NaN,1 pc,NaN,499.0,497.0,Yes,No,497.0,NaN,₹2 OFF,497.0,0,0,https://www.zepto.com/pn/fablue-penguin-plush-soft-toy-for-boys-girls-and-kids-black-white-17-cm/pvid/e7beef17-2cdb-427a-859c-68fca8c4187c,NaN

In [4]:
import pandas as pd

# Ensure stock_count is numeric
df["stock_count"] = pd.to_numeric(df["stock_count"], errors="coerce")

# Normalize out_of_stock_flag
flag = df["out_of_stock_flag"].astype(str).str.strip().str.lower()

# 1. out_of_stock_flag = Yes, but stock_count > 0
yes_stock_gt0 = df[
    (flag == "yes") &
    (df["stock_count"] > 0)
]

print(f"Rows with out_of_stock_flag='Yes' but stock_count > 0: {len(yes_stock_gt0)}")
print(yes_stock_gt0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

# 2. out_of_stock_flag = No, but stock_count = 0
no_stock_0 = df[
    (flag == "no") &
    (df["stock_count"] == 0)
]

print(f"\nRows with out_of_stock_flag='No' but stock_count = 0: {len(no_stock_0)}")
print(no_stock_0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

Rows with out_of_stock_flag='Yes' but stock_count > 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

Rows with out_of_stock_flag='No' but stock_count = 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

In [5]:
import pandas as pd

# Convert price columns to numeric
price_cols = [
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]

for col in price_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Normalize discount flag
flag = df["discount_flag"].astype(str).str.strip().str.lower()

# 1. Selling Price > MRP
selling_gt_mrp = df[df["item_selling_price"] > df["item_mrp"]]

print(f"1. Selling Price > MRP : {len(selling_gt_mrp)} rows")
print(selling_gt_mrp[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price"
]])

# 2. Discount Flag = Yes but MRP == Selling Price
discount_no_difference = df[
    (flag == "yes") &
    (df["item_mrp"] == df["item_selling_price"])
]

print(f"\n2. Discount Flag = Yes but MRP == Selling Price : {len(discount_no_difference)} rows")
print(discount_no_difference[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_flag"
]])

# 3. Discount % > 100
discount_gt_100 = df[df["discount_in_percent"] > 100]

print(f"\n3. Discount % > 100 : {len(discount_gt_100)} rows")
print(discount_gt_100[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]])

1. Selling Price > MRP : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price]
Index: []

2. Discount Flag = Yes but MRP == Selling Price : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_flag]
Index: []

3. Discount % > 100 : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_in_percent]
Index: []

In [6]:
import re

# Normalize brand names
df["brand_norm"] = (
    df["brand_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
brand_issue = (
    df.groupby("brand_norm")
    .agg(
        variant_count=("brand_name", "nunique"),
        brand_variants=("brand_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

brand_issue = brand_issue[brand_issue["variant_count"] > 1]

brand_issue

          brand_norm  variant_count                             brand_variants
47             aplus              2                            [A+Plus, Aplus]
143             bonn              2                               [Bonn, bonn]
209       cocacolaus              2               [Coca-Cola US, Coca-cola US]
265         delichic              2                      [Deli Chic, Delichic]
510       kharifoods              2                 [KHARI FOODS, Khari Foods]
704             noto              2                               [NOTO, Noto]
767        patanjali              2                     [PATANJALI, Patanjali]
793  plixtheplantfix              2  [Plix -The Plant Fix, Plix The Plant Fix]

In [9]:
df[df["brand_norm"] == "aplus"][
    [
        "brand_name",
        "product_name",
        "unique_id",
        "product_id_upc_ean",
        "product_url"
    ]
].sort_values(["product_name", "brand_name"])

,brand_name,product_name,unique_id,product_id_upc_ean,product_url
81062,A+Plus,A+PLUS Kabuli Chana Big,78180479-3b97-493a-9e34-05d1924b5743,57d94087-5da9-482b-8866-95e24fdbc640,https://www.zepto.com/pn/aplus-kabuli-chana-big/pvid/78180479-3b97-493a-9e34-05d1924b5743
81065,A+Plus,A+PLUS Kabuli Chana Medium,2fa76236-1adc-451b-9c26-b6f00b88cba9,8f1642f3-c542-4966-9617-7ac4179106dd,https://www.zepto.com/pn/aplus-kabuli-chana-medium/pvid/2fa76236-1adc-451b-9c26-b6f00b88cba9
81061,A+Plus,A+PLUS Moong Dal | Chilka,413a8369-5433-425a-b845-2a3c2f0a1e3c,8d7e318f-3704-4085-afb2-4c279ef8983f,https://www.zepto.com/pn/aplus-moong-dal-chilka/pvid/413a8369-5433-425a-b845-2a3c2f0a1e3c
81064,A+Plus,A+PLUS Moong Sabut,c816452b-4063-470b-8c47-7cbd729a418d,9de583fd-7670-4d8e-98f4-586be285104b,https://www.zepto.com/pn/aplus-moong-sabut/pvid/c816452b-4063-470b-8c47-7cbd729a418d
81072,A+Plus,A+PLUS Rajmah Chitra,215989f7-c909-4d84-a262-debb0082d6e2,464fc58c-1467-43d3-a91a-75984341fc43,https://www.zepto.com/pn/aplus-rajmah-chitra/pvid/215989f7-c909-4d84-a262-debb0082d6e2
81074,A+Plus,A+PLUS Rajmah Red,03f68c3b-edb5-4807-a9bf-78ce5f166e5e,0e5130c5-caa8-44ea-8a63-5aeea7398b84,https://www.zepto.com/pn/aplus-rajmah-red/pvid/03f68c3b-edb5-4807-a9bf-78ce5f166e5e
81055,Aplus,A+PLUS Tur Dal,73738e7b-cb4f-4613-b4ec-2ab6cc61e234,e494c824-1685-42b7-9482-dae51f64ee4d,https://www.zepto.com/pn/aplus-tur-dal/pvid/73738e7b-cb4f-4613-b4ec-2ab6cc61e234
81068,A+Plus,A+PLUS Urad Sabut,1db2af85-177a-4984-9924-3e308c32ec2b,137f4c7b-2f23-441e-8583-27bd8baeeda7,https://www.zepto.com/pn/aplus-urad-sabut/pvid/1db2af85-177a-4984-9924-3e308c32ec2b

In [11]:
url_name_issues = (
    df.groupby("product_id_upc_ean")
      .agg(
          product_count=("product_name", "nunique"),
          product_names=("product_name", lambda x: sorted(set(x)))
      )
      .reset_index()
)

url_name_issues = url_name_issues[url_name_issues["product_count"] > 1]

print("URLs with different product names:", len(url_name_issues))
url_name_issues.head()

URLs with different product names: 1

,product_id_upc_ean,product_count,product_names
6971,fcd3ccb2-4d6f-49b9-a5ad-c584e474213c,2,"[Orbit Spearmint Sugar Free Chewing Gum Tube, Orbit Spearmint Sugarfree Chewing Gum Pot]"

In [5]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls'],
      dtype='object')

In [13]:
result = (
    df.groupby("product_url")
      .agg(
          product_count=("product_name", "nunique"),
          product_names=("product_name", lambda x: sorted(set(x))),
          unique_ids=("unique_id", lambda x: sorted(set(x))),
          product_ids=("product_id_upc_ean", lambda x: sorted(set(x)))
      )
      .reset_index()
)

# Keep only URLs mapped to multiple product names
result = result[result["product_count"] > 1]

print(f"Found {len(result)} URLs with different product names.")
result

Found 0 URLs with different product names.

Empty DataFrame
Columns: [product_url, product_count, product_names, unique_ids, product_ids]
Index: []

In [14]:
top10_longest = (
    df.drop_duplicates(subset="product_name")
      .assign(name_length=lambda x: x["product_name"].fillna("").str.len())
      .sort_values("name_length", ascending=False)
      [["unique_id", "name_length", "product_name", "product_url"]]
      .head(10)
)

print(top10_longest)

                                   unique_id  name_length  \
93314   7e1c699f-d191-4be4-9314-3506b1a75b97          389
376457  2bdf7ef7-4796-4969-ba37-5fca1e01b31c          259
93311   edd24376-4a56-4c30-bc25-17740efa5f75          206
128053  58caf284-73d7-4a9e-ab54-eb51f6b197f5          204
92684   7cfc3765-fcc7-41e0-8a86-f39bd0c19271          186
19783   05099171-d97f-4169-99d8-2f6fc01a0c22          170
894     4907f3af-c281-4005-aff6-a9aa3b2d76d9          169
890     f7b9124f-022b-4896-a7a6-8c546d89a996          169
17780   4b45a46c-7559-4707-bc8a-a013171cfed1          158
9781    f6271978-512b-4f18-9786-db39a78754ac          154

                                                                                                                                                                                                                                                                                                                                                                                                 product_name  \
93314   Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo
376457                                                                                                                                    Sirona Heavy Flow Tampons | Organic Cotton Core | Ultra-High Absorbency And Leak-Proof Protection (20pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) & Sirona Sanitary Pads And Diapers Disposal Bag (15pc) Combo
93311                                                                                                                                                                                          Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) Combo
128053                                                                                                                                                                                           Sirona Heavy Flow Tampons | Organic Cotton Core | Ultra-High Absorbency And Leak-Proof Protection (20pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) Combo
92684                                                                                                                                                                                                              Hyphen 7% Ceramides-Nmf Face Toner Essence | 5% Glass Skin Blend With Rice Water (100ml) & Hyphen 18% Brightening + 20% Collagen Double Serum | 5% Niacinamide For Dark Spots (50ml) Combo
19783                                                                                                                                                                                                                              Plum Green Tea Pore Cleansing Face Wash Fights Pimples & Removes Excess Oil Enriched With Green Tea & Glycolic Acid Best Suits Oily Acne-Prone Combination Skin 100% Vegan
894                                                                                                                                                                                                                                 Colgate Batman Toothbrush For Kids, Battery Powered Electric Toothbrush, Age 3+, Kids Toothbrush With Extra Soft Bristles And Slim Handle, Includes Replaceable Batteries
890                                                                                                                                                                                                                                 Colgate Barbie Toothbrush For Kids, Battery Powered Electric Toothbrush, Age 3+, Kids Toothbrush With Extra Soft Bristles And Slim Handle, Includes Replaceable Batteries
17780                                                                                                                                                                                                                                          Spinz BB Brightening & Beauty Face Talc for Instant Brightness that Lasts 2X Longer Covers Dark Spots and Blemishes Gives Soft and Smooth Skin (Natural Beige)
9781                                                                                                                                                                                                                                               Fast&Up Reload Berry Instant Energy Drink 5 Essential Electrolytes(20pc) & Fast&Up Reload Orange Instant Energy Drink 5 Essential Electrolytes(20pc) Combo

                                                                                                                                                                                                                                                                                                                                                                                                                        product_url
93314   https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97
376457                                                                                                        https://www.zepto.com/pn/sirona-heavy-flow-tampons-organic-cotton-core-ultra-high-absorbency-and-leak-proof-protection-20pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-sirona-sanitary-pads-and-diapers-disposal-bag-15pc-combo/pvid/2bdf7ef7-4796-4969-ba37-5fca1e01b31c
93311                                                                                                                                                                       https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-combo/pvid/edd24376-4a56-4c30-bc25-17740efa5f75
128053                                                                                                                                                           https://www.zepto.com/pn/sirona-heavy-flow-tampons-organic-cotton-core-ultra-high-absorbency-and-leak-proof-protection-20pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-combo/pvid/58caf284-73d7-4a9e-ab54-eb51f6b197f5
92684                                                                                                                                                                                  https://www.zepto.com/pn/hyphen-7-ceramides-nmf-face-toner-essence-5-glass-skin-blend-with-rice-water-100ml-hyphen-18-brightening-20-collagen-double-serum-5-niacinamide-for-dark-spots-50ml-combo/pvid/7cfc3765-fcc7-41e0-8a86-f39bd0c19271
19783                                                                                                                                                                                      https://www.zepto.com/pn/plum-green-tea-pore-cleansing-face-wash-fights-pimples-removes-excess-oil-enriched-with-green-tea-glycolic-acid-best-suits-oily-acne-prone-combination-skin-100-vegan/pvid/05099171-d97f-4169-99d8-2f6fc01a0c22
894                                                                                                                                                                                         https://www.zepto.com/pn/colgate-batman-toothbrush-for-kids-battery-powered-electric-toothbrush-age-3-kids-toothbrush-with-extra-soft-bristles-and-slim-handle-includes-replaceable-batteries/pvid/4907f3af-c281-4005-aff6-a9aa3b2d76d9
890                                                                                                                                                                                         https://www.zepto.com/pn/colgate-barbie-toothbrush-for-kids-battery-powered-electric-toothbrush-age-3-kids-toothbrush-with-extra-soft-bristles-and-slim-handle-includes-replaceable-batteries/pvid/f7b9124f-022b-4896-a7a6-8c546d89a996
17780                                                                                                                                                                                                 https://www.zepto.com/pn/spinz-bb-brightening-beauty-face-talc-for-instant-brightness-that-lasts-2x-longer-covers-dark-spots-and-blemishes-gives-soft-and-smooth-skin-natural-beige/pvid/4b45a46c-7559-4707-bc8a-a013171cfed1
9781                                                                                                                                                                                                          https://www.zepto.com/pn/fastup-reload-berry-instant-energy-drink-5-essential-electrolytes20pc-fastup-reload-orange-instant-energy-drink-5-essential-electrolytes20pc-combo/pvid/f6271978-512b-4f18-9786-db39a78754ac

In [17]:
# 1. Group by identity columns to isolate the exact same physical product
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        # Count how many different spelling/name variations exist for this product
        name_variant_count=("product_name", "nunique"),
        # Create an alphabetised list of those unique name variations
        name_variants=("product_name", lambda x: sorted(set(x))),
        # Optional: capture variations in brand name for the same product
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
    )
    .reset_index()
)

# 2. Filter for rows where the same product has more than 1 name variation
name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

# 3. View the final flagged discrepancies
print(name_issues_by_id)

                                 unique_id product_grammage     net_quantity  \
1758  51e330d7-1483-4cd3-80d0-ff29eba1b153           59.4 g  1 pack (59.4 g)
2114  61b8e3c5-b1b7-4b71-bb21-3a4f1c2ec1a8           19.8 g  1 pack (19.8 g)

      name_variant_count  \
1758                   2
2114                   2

                                                                                 name_variants  \
1758  [Orbit Spearmint Sugar Free Chewing Gum Tube, Orbit Spearmint Sugarfree Chewing Gum Pot]
2114  [Orbit Spearmint Sugar Free Chewing Gum Tube, Orbit Spearmint Sugarfree Chewing Gum Pot]

     brand_variants
1758        [Orbit]
2114        [Orbit]

In [18]:
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        name_variant_count=("product_name", "nunique"),
        name_variants=("product_name", lambda x: sorted(set(x))),
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
        url_count=("product_url", "nunique"),
        product_urls=("product_url", lambda x: sorted(set(x.dropna())))
    )
    .reset_index()
)

name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

name_issues_by_id

,unique_id,product_grammage,net_quantity,name_variant_count,name_variants,brand_variants,url_count,product_urls
1758,51e330d7-1483-4cd3-80d0-ff29eba1b153,59.4 g,1 pack (59.4 g),2,"[Orbit Spearmint Sugar Free Chewing Gum Tube, Orbit Spearmint Sugarfree Chewing Gum Pot]",[Orbit],2,"[https://www.zepto.com/pn/orbit-spearmint-sugar-free-chewing-gum-tube/pvid/51e330d7-1483-4cd3-80d0-ff29eba1b153, https://www.zepto.com/pn/orbit-spearmint-sugarfree-chewing-gum-pot/pvid/51e330d7-1483-4cd3-80d0-ff29eba1b153]"
2114,61b8e3c5-b1b7-4b71-bb21-3a4f1c2ec1a8,19.8 g,1 pack (19.8 g),2,"[Orbit Spearmint Sugar Free Chewing Gum Tube, Orbit Spearmint Sugarfree Chewing Gum Pot]",[Orbit],2,"[https://www.zepto.com/pn/orbit-spearmint-sugar-free-chewing-gum-tube/pvid/61b8e3c5-b1b7-4b71-bb21-3a4f1c2ec1a8, https://www.zepto.com/pn/orbit-spearmint-sugarfree-chewing-gum-pot/pvid/61b8e3c5-b1b7-4b71-bb21-3a4f1c2ec1a8]"