In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
import pandas as pd

# Read the Excel file
df = pd.read_excel(r"/home/user/Downloads/dubailand_uae_2026_07_30_05.xlsx")

# View the first 5 rows
print(df.head())

   Office Number                             Name English  \
0           1007  SEVEN CENTURY REAL ESTATE BROKERS L.L.C
1          23173                ON PLAN REAL ESTATE L.L.C
2           2004          HARBOR REAL ESTATE BROKER L.L.C
3            469       W CAPITAL REAL ESTATE BROKER L.L.C
4          16933         DRIVEN PROPERTIES L.L.C (BRANCH)

                              Name Arabic               Website  \
0     القرن السابع للوساطة العقارية ذ.م.م  www.sevencentury.com
1               اون بلان للعقارات ش.ذ.م.م             onplan.ae
2         هاربور للوساطة العقارية ش.ذ.م.م   www.harbordubai.com
3  دبليو كابيتال للوساطه العقاريه ش.ذ.م.م                   NaN
4            درفن للعقارات ش.ذ.م.م  (فرع)                   NaN

      Phone Number                      Email
0    971-4-4520077   naghmeh@sevencentury.com
1              NaN           q-l2@hotmail.com
2  971-971-3251616    mohanad@harbordubai.com
3    971|501151118  walid.alzarooni@gmail.com
4    971-4-4297040    pro@drivenproperties.ae

In [ ]:
# import pandas as pd
# import json

# df = pd.read_json(
#     r"/home/user/Downloads/haraj_kse_2026_07.json",
#     lines=True
# )

# # Convert list/dict columns into strings
# df = df.apply(
#     # lambda col: col.map(
#         lambda x: json.dumps(x, sort_keys=True)
#         if isinstance(x, (list, dict))
#         else x
#     )
# )

In [ ]:
# req_cols = """id, url, broker_display_name, broker, category, category_url, title, property_type, sub_category_1, sub_category_2, description, location, depth, price, currency, price_per, bedrooms, bathrooms, furnished, rera_permit_number, dtcm_licence, scraped_ts, amenities, details, agent_name, reference_number, number_of_photos, user_id, published_at, phone_number, date, iteration_number, latitude, longitude"""

# req_cols = [c.strip() for c in req_cols.split(",") if c.strip()]

# missing = [c for c in req_cols if c not in df.columns]
# extra = [c for c in df.columns if c not in req_cols]

# print("Requirement columns:", len(req_cols))
# print("File columns:", len(df.columns))
# print("Missing:", missing)
# print("Extra:", extra)
# print("Order matches:", req_cols == list(df.columns))

Requirement columns: 34
File columns: 34
Missing: []
Extra: []
Order matches: True

In [3]:
df.columns

Index(['Office Number', 'Name English', 'Name Arabic', 'Website',
       'Phone Number', 'Email'],
      dtype='object')

In [4]:
import re

url_pattern = re.compile(
    r'^(https?://)'
    r'([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}'
    r'(/[^\s]*)?$'
)

invalid_url = df[
    ~df["Website"].fillna("").astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_url)}")
display(invalid_url[[ "Website"]])

Invalid URLs: 10002

                                      Website
0                        www.sevencentury.com
1                                   onplan.ae
2                         www.harbordubai.com
3                                         NaN
4                                         NaN
5                              Mohammad Rafie
6                                         NaN
7                         www.a1properties.ae
8                               Mahoud Khalil
9                                         NaN
10                         www.alansarire.com
11                                        NaN
12                                        NaN
13                            theurbannest.ae
14                                        NaN
15                           Alireza Alekasir
16                      www.coldwellbanker.ae
17                  www.alzajelrealestate.com
18                   www.classicproperties.ae
19      KIRAN KUMAR ASHOK KUMAR UTTAMCHANDANI
20                                        NaN
21                             www.alruwad.ae
22                       www.ottomans-uae.com
23                                        NaN
24                      www.yasproperties.com
25                            www.azuruae.com
26                                        NaN
27                   www.valco-properties.com
28                                        NaN
29                                        NaN
30                      www.famproperties.com
31                                        NaN
32                            www.raywhite.ae
33                     www.ajwaproperties.com
34                        www.livedubai.co.uk
35                           www.capriuae.com
36                        www.mountaingate.ae
37                                        NaN
38                                        NaN
39                        www.newhomesuae.com
40                           www.resdubai.com
41                              Manzoor Ahmed
42                       www.phrealestate.ae/
43                             www.appello.ae
44                      www.goldengateway.net
45                     caspian-properties.com
46                                        NaN
48                                        NaN
49                                        NaN
50                                        NaN
51                                        NaN
52                       MICHELLE SONG BAILEY
53                              www.stones.ae
55                    www.super7realestate.ae
57                                        NaN
58                                        NaN
59                                 www.rba.ae
60                      www.khalifabakhit.com
61                           www.superdxb.com
62                        ATIQ ISMAIL KAPADIA
63                                        NaN
64                                 www.gwp.ae
65                      www.fourpointsreb.com
66                          www.tcrbroker.com
67                                        NaN
68                                        NaN
69                                        NaN
70                                        NaN
71                                        NaN
73                                        NaN
74                                        NaN
75                                        NaN
76                                        NaN
77                                        NaN
78                                      Simon
79                                        NaN
80                                        NaN
81                                        NaN
82                                        NaN
83                                        NaN
84                   www.keyoneproperties.com
85                       www.bluechiphome.com
86                                        NaN
87                                        NaN
88                                www.cbre.ae
90                  www.househuntersdubai.com
91                                alhuraiz.ae
92                      www.westgatedubai.com
93                         www.valoremdxb.com
94                           www.loyaluae.com
95                                        NaN
96                          www.rootsland.com
97                               www.mkuae.ae
98                                        NaN
99                                        NaN
100                          www.shoaibre.com
101                                       NaN
102                      www.betterlivings.ae
103                          www.uniconre.com
104                                       NaN
105                                       NaN
106                            www.igguae.com
108                    www.candourproperty.ae
109                      www.w2realestate.com
110                 www.elysianrealestate.com
111                               www.tjre.ae
112                                       NaN
113                                       NaN
114                                       NaN
115               www.sevenlinerealestate.com
116                                       NaN
117                                       NaN
118                                       NaN
119                                       NaN
120                                       NaN
121                                       NaN
122                        www.countryhome.ae
123                     www.sapphiredubai.com
124                             www.ddreb.com
125                                       NaN
126                                       NaN
127                                       NaN
128                               www.arta.ae
129                                       NaN
130                                       NaN
131                                       NaN
132                                       NaN
133                      www.uberhomesuae.com
134                           www.omniyat.com
135                         www.dcbrokers.net
136                                       NaN
137                         www.blocksdxb.com
138                                       NaN
139                                       NaN
140                     www.house2homeuae.com
141                                       NaN
142                                       NaN
143                       www.bestdealsre.com
144                       propertyboutique.ae
145                                       NaN
146                www.penthouseproperties.ae
147                                       NaN
149                      www.abodeproperty.ae
150                                       NaN
151                  www.virtusrealestate.org
152                    www.metropoledubai.com
153                                       NaN
154                     www.royalparkhome.com
155                                       NaN
156                           www.rsdubai.com
157                    www.vogueproperties.ae
158                                       NaN
159                                       NaN
160                                       NaN
161                                       NaN
162                                       NaN
163                                       NaN
164                                       NaN
165                                       NaN
166                                0503002225
167                      vostokrealestate.com
169                         www.edgerealty.ae
170                                       NaN
171                             www.rk-re.com
172                 www.platinumheightsre.com
173                                       NaN
174                                       NaN
175                                       NaN
176                                       NaN
178                      www.taqproperties.ae
179                                       NaN
180                                       NaN
181                                       NaN
182                www.imperialhomesdubai.com
183                                       NaN
184                                       NaN
185                                       NaN
186                                       NaN
187                                       NaN
188                                       NaN
189                                       NaN
191                    www.novelproperties.ae
192                                       NaN
194                                       NaN
195                                       NaN
196                        www.propertypro.ae
198                                       NaN
199                                       NaN
200                                       NaN
201                         www.lcredubai.com
202                  www.atomicproperties.org
203                                       NaN
204                     www.newport-homes.com
205                      www.alhilalhomes.com
206                                       NaN
207                          www.yourplace.ae
209               www.touchwoodrealestate.com
210                                       NaN
211                                       NaN
212                                       NaN
213                                       NaN
214                 SHEIROSE NURMMAD OSSEMANE
215                            realreturns.ae
216                         www.primelinks.ae
217                    MAHESH SADHURAM DUDEJA
218                                       NaN
219                           www.landmark.ae
220                            www.alraea.com
221                          www.firstgpp.com
222                                       NaN
223                          www.predubai.com
224                            www.imexre.com
225                           www.hawkland.ae
227                                       NaN
228                       www.mobhholding.com
229                                       NaN
230                                www.cre.ae
231                                       NaN
232                           www.zabadani.ae
233                                       NaN
234                                       NaN
235                  www.meedarrealestate.com
236                                       NaN
238                                       NaN
239                         www.evernestre.ae
240                                       NaN
241                       www.homespartner.ae
242                                       NaN
243                                       NaN
244                                       NaN
245                                       NaN
246                                       NaN
247                                       NaN
248                     www.landeurglobal.com
249                                       NaN
251                                       NaN
253                  www.knightsbridgeprop.ae
254                                       NaN
255                                       NaN
256                 www.alnafisproperties.com
257                                       NaN
258                                       NaN
260                                       NaN
261                                       NaN
262                               www.299.com
263                                       NaN
264                                       NaN
265                                       NaN
266                                       NaN
267                                       NaN
268                                       NaN
269                            www.manresa.ae
270                        www.investinae.com
272                                       NaN
273                                       NaN
274                                       NaN
275                        www.cparamount.com
276                                       NaN
277                                       NaN
278                www.globalpropertygroup.co
279                      www.sevencentury.com
280                                       NaN
281                                       NaN
282                                       NaN
283                                       NaN
285                                       NaN
286                         www.brownstone.ae
287                          www.landhouse.ae
288                                       NaN
289                                       NaN
290                                       NaN
291                                       NaN
292                                       NaN
293                                       NaN
294                             www.verare.ae
295                                       NaN
296                                       NaN
297                                       NaN
298                                       NaN
299                                       NaN
300                                       NaN
301                                       NaN
302                                       NaN
303                                       NaN
304                                       NaN
306                                       NaN
307             www.simplyhomesrealestate.com
308                                       NaN
309                                       NaN
310                                       NaN
311                                       NaN
312                                       NaN
313                           www.houseit.com
314                   www.nvestrealestate.com
315                      www.creativehomes.ae
316                        www.john-taylor.ae
317                                       NaN
318                                       NaN
319                      www.idealshelters.ae
320                                       NaN
321                                       NaN
322                                       NaN
323                                       NaN
324                                       NaN
325                                       NaN
326                            www.bhomes.com
327                             www.ushre.com
328                                       NaN
329                                       NaN
330                                       NaN
331                                       NaN
332                       www.beyondbricks.ae
333                                       NaN
334                                       NaN
335                                       NaN
336                                       NaN
337                                       NaN
338                                       NaN
339                                       NaN
340                                       NaN
341                                       NaN
342             www.bullandbearproperties.com
343                                       NaN
344                                       NaN
345                                       NaN
347                                       NaN
348                                       NaN
349                                       NaN
350                                       NaN
351                                       NaN
352                                       NaN
353                                       NaN
354                                       NaN
355                                       NaN
356                                       NaN
357                                       NaN
358                                       NaN
359                        www.move-homes.com
360                                       NaN
361                                       NaN
362                                       NaN
363                                       NaN
364                                       NaN
365                                       NaN
366                                       NaN
367                                       NaN
368                                       NaN
369                                       NaN
370                                       NaN
371                                       NaN
372                                       NaN
373                                       NaN
374                                       NaN
375                                       NaN
376                                       NaN
377                                       NaN
378                                       NaN
379                                       NaN
380                                       NaN
381                                       NaN
382                                       NaN
383                                       NaN
384                                       NaN
385                                       NaN
387                                       NaN
388                                       NaN
389                                       NaN
390                                       NaN
391                                       NaN
392                                       NaN
393                                       NaN
394                              www.korek.ae
395                                       NaN
396                                       NaN
397                                       NaN
398                                       NaN
399                                       NaN
400                                       NaN
401                                       NaN
402                                       NaN
403                                       NaN
404                                       NaN
405                                       NaN
406                                       NaN
407                                       NaN
408                                       NaN
409                                       NaN
410                                       NaN
411                                       NaN
412                                       NaN
413                                       NaN
414                                       NaN
415                                       NaN
416                            www.pico37.com
417                                       NaN
418                                       NaN
419                                       NaN
420                                       NaN
421                                       NaN
422                                       NaN
423                                       NaN
424                                       NaN
425                                       NaN
426                                       NaN
427                                       NaN
429                                       NaN
430                              www.layan.ae
431                                       NaN
432                                       NaN
433                                       NaN
434                                       NaN
435                                       NaN
436                                       NaN
437                                       NaN
438                                       NaN
439                                       NaN
440                                       NaN
441                                       NaN
442                www.benchmarkproperties.ae
443                                       NaN
444                                       NaN
445                                       NaN
446                                       NaN
447                                       NaN
448                                       NaN
449                                       NaN
450                                       NaN
451                                       NaN
452                                       NaN
453                                       NaN
454                                       NaN
455                                       NaN
456                                       NaN

In [5]:
df.shape

(10191, 6)

In [8]:
import re

# URL validation regex
url_pattern = re.compile(
    r"^(https?://)?([A-Za-z0-9-]+\.)+[A-Za-z]{2,}(/.*)?$",
    re.IGNORECASE
)

# Remove nulls and empty strings
website = df["Website"].dropna().astype(str).str.strip()
website = website[website != ""]

# Find invalid websites
invalid = df.loc[website.index][~website.str.match(url_pattern)]

# Add Excel row numbers
invalid = invalid.copy()
invalid["row_number"] = invalid.index + 2

print("Invalid website values:", len(invalid))
print(invalid[["row_number", "Website"]])

Invalid website values: 54
      row_number                                 Website
5              7                          Mohammad Rafie
8             10                           Mahoud Khalil
15            17                        Alireza Alekasir
19            21   KIRAN KUMAR ASHOK KUMAR UTTAMCHANDANI
41            43                           Manzoor Ahmed
52            54                    MICHELLE SONG BAILEY
62            64                     ATIQ ISMAIL KAPADIA
78            80                                   Simon
166          168                              0503002225
214          216               SHEIROSE NURMMAD OSSEMANE
217          219                  MAHESH SADHURAM DUDEJA
467          469                    zahidgee92@gmail.com
732          734     Mohammed Abdul Aziz Mohammed Janahi
736          738                        NEXT REAL ESTATE
741          743             MODERN REAL ESTATE (L.L.C.)
1103        1105  omar mohamed abdalla yousif al rayaysi
1126        1128                          Louise Heatley
1139        1141               RULA JERIES HANNA MADANAT
1640        1642          Muhammad Arshad Muhammad ullah
1641        1643                           Hana AL Zamel
1654        1656                  Julian Philipp Straube
1720        1722                      SHAIMA JAMAL HAJJI
2381        2383                aymankastalani@yahoo.com
2388        2390                            kamal Samimi
2411        2413              mohamed.alamin@outlook.com
2428        2430                          Rakesh M Bohra
2431        2433                       LEENA ALBUQUERQUE
2876        2878                      Akram Ahmad Shafiq
2883        2885                           mohamed regab
2885        2887          Mohamad Abdulla Sulaiman Sedki
2909        2911            ahmed mohd mahmood al dallal
2913        2915                                     دبي
2917        2919           ADIL ABDULLA MOHAMED FALAKNAZ
2922        2924             NATIONWIDE REALTORS (L.L.C)
2932        2934                khalifa sultan bin harib
2938        2940                             SAMEER ADAM
3436        3438                          00971506254167
4196        4198                         khaja saifuddin
4207        4209                             Abdul Nazer
4213        4215                     alwarddxb@gmail.com
4218        4220                                     دبي
4220        4222         MAHMOUD MOHAMED IBRAHIM MOHAMED
4233        4235              Riadh Ahmed Mohammed Abbas
4236        4238               ramy@dubaienterprises.org
4239        4241                              0506453117
4256        4258           Mr. Rajan Radhakrishen Israni
4259        4261            SALEM JAMAL HUSSEIN ABBOUSHI
4261        4263                      hrajk007@yahoo.com
5303        5305                zahirgulam2010@gmail.com
5438        5440                                       0
8736        8738                    huma.maria@gmail.vom
9252        9254              bilal adnan zaki saffarini
9363        9365           AL RAYAN  REAL ESTATE (L.L.C)
9401        9403       Obaid Saeed Manana Ghedair Ejtabi

In [12]:
pattern = r"^[A-Za-z0-9\s.,'&()/\-]+$"

invalid_name_en = df[
    df["Name English"].notna() &
    ~df["Name English"].astype(str).str.fullmatch(pattern)
]

print("Invalid Name English:", len(invalid_name_en))
print(invalid_name_en[["Name English"]])

Invalid Name English: 0
Empty DataFrame
Columns: [Name English]
Index: []

In [13]:
phone_pattern = r"^[+]?[0-9()\-\s]+$"

invalid_phone = df[
    df["Phone Number"].notna() &
    ~df["Phone Number"].astype(str).str.fullmatch(phone_pattern)
]

print("Invalid Phone Numbers:", len(invalid_phone))
print(invalid_phone[["Phone Number"]])

Invalid Phone Numbers: 108
         Phone Number
3       971|501151118
64      971|504264267
116     971|504694448
152      971|44225079
184     971|528550000
186     971|543131168
207      971|43682168
250     971|558559751
251      971|46969499
278     971|042545070
291     971|509154354
340     971|585306318
365     971|529109324
441     971|559361112
521     971|526699625
542     971|506285858
572     971|555501477
625     971|562212721
631     971|529948887
682     971|509533066
693      971|42396655
917     971|503442133
945     971|527513222
1020    971|567512389
1065    971|528588118
1184    971|522437443
1192    971|586492729
1235    971|556698774
1298     971|44546695
1353    971|504815644
1383    971|506909809
1483    971|529568060
1652     971|42699113
1655     971|44385044
1679    971|508244492
1803    971|561883983
1866    971|043210201
2036    971|521940000
2080    971|501652929
2175    971|567200137
2189     971|42253778
2207    971|549957499
2337    971|551045220
2377    971|559986405
2418     971|44474830
2477    971|566981111
2482    971|506529580
2521    971|503271026
2524    971|558792902
2525    971|559948415
2531    971|528276668
2643    971|503076799
2756    971|561117544
2894     971|42660026
2901    971|563909966
2934    971|506458993
2936    971|506446091
3127    971|501088066
3140    971|557687676
3297    971|506009916
3362     971|43372165
3424    971|555774076
3500     971|42011441
3535    971|564171773
3577    971|589318302
3644    971|505054135
3646    971|566769999
3769    971|553476430
4006    971|585798448
4104   971|0550000800
4193    971|501601800
4194    971|508882629
4410    971|585779087
4488    971|585524299
4780    971|564543300
4893    971|502313737
5206   971|0558737207
5255    971|502449444
5303      971|4426375
5474     971|44217422
5599   '971-4-2944970
5604     971|44472444
5608    971|559022151
5662    971|544996449
6116    971|582752606
6210    971|585328625
6542    971|589199454
6551    971|559532583
7096    971|589989290
7155    971|585755419
7465    971|581290088
7624    971|551256730
7766    971|525275822
7982    971|557062277
8035    971|502152124
8195   971|0506668962
8430    971|523366419
8647    971|555227532
8833            971|0
8892    971|547792882
8938   971|0551122341
9023    971|543888834
9068    971|554407767
9150    971|527837376
9443    971|528174550
9678   971|0501760361
9714    971|551599100
10043  971|0567650550

In [14]:
import re

phone_pattern = r"^971\|(0?[1-9]\d{7,9})$"

invalid_phone = df[
    df["Phone Number"].notna() &
    ~df["Phone Number"].astype(str).str.fullmatch(phone_pattern)
]

print(invalid_phone[["Phone Number"]])

            Phone Number
0          971-4-4520077
2        971-971-3251616
4          971-4-4297040
5          971-4-3298844
6            97142438000
7          971-4-3515583
8         971-04-3990990
9          971-4-4522202
10             044473277
11         971-4-3026000
12           97144227900
13         971-4-2212442
14         971-4-3236222
15             043499767
16         971-4-4391200
17         971-4-2957771
18         971-4-2500177
19         971-4-3532000
20             043663334
21         971-4-3430111
22           97145616900
23             043518800
24         971-4-3552266
25         971-4-5516626
26            0585299999
27           97143799919
29         971-4-2661167
30        971-04-3691774
32         971-4-3631999
33         971-4-4472730
34           97144323920
35           97144207170
36         971-4-4524466
37         971-4-5539020
38         971-4-2977302
39         971-4-4473501
40         971-4-3295959
41             044328398
42         971-4-3476853
43         971-4-4430399
44         971-4-4218687
45             042877466
46         971-4-4488555
47         971-4-3432393
48        971-04-3957207
50         971-4-4491087
51             043387464
52         971-4-5588149
53             043998833
54         971-4-5539144
55             044474313
57         971-4-4356173
58         971-4-4434450
59         971-4-3990611
60             043746151
61         971-4-4572248
62         971-4-4527744
63         971-4-5779321
65             042555511
66             044574202
67         971-4-3414699
68         971-4-3614040
69         971-4-4227589
70         971-4-3418044
71             044306933
72         971-4-3663377
73             045520272
74         971-4-3792244
75           97144471990
76        971-04-4340730
77        971-04-4277224
79             043519995
80         971-4-2251251
81         971-4-3396222
82             045639596
83         971-4-3994909
84           97142089111
85         971-4-3951212
86         971-4-3687876
87           97143039222
88           97144377200
90             044522007
91             043525460
92             043927677
93         971-4-3378040
95         971-4-2639922
96         971-4-3298333
97        971-04-2432525
98             044037777
99        971-04-3992447
100       971-04-8787053
101            042452100
102        971-4-4472352
103            043674702
104        971-4-2821191
105        971-4-3551666
106        971-4-4572257
107          97144475461
108        971-4-5576608
109       971-04-4281454
110        971-4-3234545
111        971-4-4223372
112        971-4-5736900
115       971-04-2769442
117            044215555
118       971-04-2424149
121       971-04-5665191
122            042414845
123            044471778
124        971-4-5727684
125        971-4-3573806
128            044419311
129        971-4-3258819
130        971-4-4425685
132          97143990090
133            042760444
134        971-4-5115000
135        971-4-2833746
136        971-4-5898687
137        971-4-3469333
138        971-4-4558888
139        971-4-5515680
140        971-4-2980201
141          97144434303
142        971-4-2562577
143           0557057733
144        971-4-4425434
145        971-4-4512000
146        971-4-3695091
147        971-4-4550884
148        971-4-3792211
149            044487664
150        971-4-4304270
156        971-4-2771009
157        971-4-3757444
159       +971-506544554
160        971-4-5896605
161       971-04-2853949
165          97142727234
166            044541313
167        971-4-2417773
168        971-4-4540990
169        971-4-3881856
170       971-04-8790730
171          97144239010
172            043630088
173          97145648496
174        971-4-4290621
175       971-04-5723616
177        971-4-5635900
179       971-04-3304686
181            045799888
182        971-4-4274076
183       971-04-2739838
185        971-4-4252780
188        971-4-4343241
190            042729973
193        971-4-8999523
196            043607775
197        971-4-4542117
198        971-4-5844921
199        971-4-3885855
200            045587121
201        971-4-4414387
202            044342678
203        971-4-4250600
204        971-4-5586510
205        971-4-5506344
206        971-4-3304432
208          97146052400
209        971-4-4548751
210        971-4-3575509
211        971-4-3619988
212       971-55-8911362
214        971-4-4471702
215        971-4-3850550
216        971-4-2771143
217        971-4-3594666
218        971-4-3929770
219        971-4-2405050
220        971-4-2681833
221        971-4-4534133
223        971-4-3996747
224        971-4-3951911
225        971-4-3607944
226        971-4-4537777
227        971-4-3356666
228        971-4-2821191
229        971-4-4408018
231            043884888
232        971-4-3887828
233        971-4-4430268
234        971-4-5139922
235           0505507997
236            043684497
237       971-04-5897440
242            040000000
247            045140422
248            043241932
249        971-4-2364444
253       971-04-2275700
256        9715094444007
258            043447977
259            042957606
262        971-4-3399222
264        971-4-5846450
267            045656216
268         971558888169
269        971-4-2409292
271        971-4-8746767
272          97143519995
277        971-4-5674912
281       971-04-7181371
283        971-4-5598021
285       971-04-2423612
288       971-04-5126848
292       971-04-5517101
293           0585523942
296       971-04-5475151
297        971-4-5539027
298           0559719590
299       971-04-3991834
300            042355274
301       971-04-2401777
306       971-04-5489895
307       971-04-8851898
309       971-04-5542518
313       971-04-4096715
314       971-04-2426556
315       971-04-2387671
316            044516543
318        971-4-2721516
319        971-4-3272300
321            044426200
323        971-4-3691700
324            045472756
326          97144081000
327        971-4-5512598
331           0568316391
332            044237799
333           0503439003
337        971-4-5686927
342        971-4-3695593
345       971-04-5837940
349       971-04-5516626
354        971-4-5477942
359           0585811084
361        971-4-3691700
366             04331111
372            045294398
383        971-4-3256209
387           0455807374
394        971-4-3638880
395            048878825
399               309074
401        971-4-3211700
403           0567907966
404            043111111
405            043425507
407           0506578281
409           0505806618
411            042567646
414        971-4-5851737
416        971-4-4469808
417           0542438753
426            044521010
429           0505057379
430        971-4-4343607
432           0568272868
433        971-2-4442774
442       971-04-5704777
445            048735835
450            045896555
454            043691717
455           0521100555
459          97145547961
460        971-4-2309000
467              4212262
469           0505056462
471          97145782048
472       971-55-8313570
498               000000
501       971-04-2344482
504            043929715
507        971-4-3691700
509            044431780
510           0563498252
513       971-04-2649938
516            045914116
517           0000000000
518           0564883038
520            503381158
525            800593737
526          0-4-4468300
539                   01
540        971-4-3713333
545       971-04-2959965
556                   04
559        971-4-5809254
564        971-4-3210800
568            043421179
570        971-4-3691700
574        971-4-3389761
575            045693994
579        971-4-4231104
580            045524606
582        971-4-3472217
591       971-04-8345777
595            045151515
601       971-04-3342639
604       971-04-4291258
605            043541646
611           0529744650
615           0551133552
618           0522382829
619       971-58-5899724
622           0502848264
634       971-04-3374717
642        971-4-5055646
653       971-52-8242600
654       971-04-5726321
657        971-4-5915688
661            043510077
663       971-04-8189045
665            040000000
669            044514369
670            045700542
672          97148719200
674            042405000
676           0562199292
677       971-04-4413235
679           0558188780
683        971-4-5298671
684             04331111
688           0507657277
701              0000000
710            042836681
716        971-4-3790904
717        971-4-6444519
718        971-4-3885866
719        971-4-5754740
720        971-4-2216222
721           0551459955
722        971-4-3639342
723        971-4-3382560
724        971-4-2222269
725        971-4-4508298
726        971-4-2627400
727        971-4-4516161
728            043708922
729        971-4-3998873
730          97145519484
731       971-04-4541266
732        971-4-3375553
733        971-4-2225586
734        971-4-3691700
735            044511638
736        971-4-2341575
737        971-4-3242224
738        971-4-2289661
739        971-4-3688036
740        971-4-4294444
741          97143987337
742       971-04-3586805
743        971-4-3881115
744        971-4-3520555
745        971-4-4477834
746          97144200899
748            043977746
749            044548668
750            044296028
751            043713377
752        971-4-2821414
753          97144232006
754            042500200
755         971044324415
756       971-50-2995785
758        971-4-3883101
759          0-4-3794794
764        971-4-3436361
765             42030292
766            043685697
768        971-4-5596330
771        971-4-5656320
772            042644900
773        971-4-5891054
774        971-4-3230200
775       971-04-5705358
776        971-4-4431030
777       971-04-2971111
779            043388188
782                   04
783       971-04-8786222
785        971-4-3488680
786        971-4-4539614
790        971-4-5124023
791             44579900
794            502860596
795       971-04-5294840
796          97143713308
804       971-04-2959965
805            043555808
811        971-4-3518133
821            971800302
826        971-4-2776400
829       971-04-5643863
849           0555753166
857       971-04-4578752
860       971-04-4582121
866           0585451818
870           0543283673
871        971-4-4322209
881            043812000
884        971-4-4560701
885       971-04-2294130
889            045911722
897            042800133
902           0555014552
905        971-4-5647064
906          97145187555
908       971-04-5759685
909        971-4-5776153
919        971-4-5821333
920       971-04-8359989
924           0507551080
929           0543030379
933        971-4-4533687
935           0555925517
937        971-4-3555922
947            042400016
948        971-4-4323465
949           0509565777
956           0412345678
957        971-4-2422882
958       971-04-8763935
960        971-4-3275066
963       971-04-3323319
969           9714000000
970       971-04-3881525
977            043264499
980           0545533388
981           0567590887
984            044484314
987            044297040
988        971-4-2598112
1001       971-4-2240374
1002       971-4-3314202
1006          0551026826
1008           044272217
1015           042587990
1017      971-04-2840243
1018      971-04-4081900
1025       971-4-4566135
1026      971-55-2466888
1028          0562818000
1029          0400000000
1035       971-4-2504444
1037       971-4-2322567
1045         97145293458
1046      971-04-4211543
1047      971-04-3481300
1054           043965199
1061       971-4-5579469
1062           048357114
1063          0502250532
1071           045707455
1073       971-4-4030618
1078      971-50-8728712
1086          0501805656
1087       971-4-5833365
1093            04369717
1095      971-04-5803444
1096       971-4-5896951
1098       971-4-5858723
1099           044327307
1101       971-4-2959841
1102       971-4-3388745
1103       971-4-2684432
1104       971-4-3434999
1105       971-4-3792565
1106        971043586969
1107      971-04-3273377
1108         97143321090
1109           048850705
1110       971-4-4518844
1111       971-4-3364447
1112       971-4-4542383
1113       971-4-3794669
1114       971-4-4472272
1115      971-04-5757336
1116       971-4-4327560
1117       971-4-3388471
1118       971-4-3799507
1119       971-4-2249094
1120       971-4-4534917
1121      971-04-4226104
1122       971-4-5534695
1123       971-4-3455711
1124       971-4-5462744
1125       971-4-3884666
1126       971-4-3994937
1127       971-4-3799986
1128       971-4-3387300
1129       971-4-3467011
1130       971-4-4572104
1131       971-4-4385232
1133       971-4-4477109
1134       971-4-4474188
1135       971-4-2438479
1136         97143205200
1137       971-4-2959965
1138       971-4-4392273
1139       971-4-4433585
1140           045667894
1141       971-4-3574142
1142           045847442
1143      971-04-4572365
1144       971-4-2364467
1145         97143069999
1146       971-4-3957550
1147       971-4-8886811
1148       971-4-4516767
1149       971-4-2280249
1150       971-4-2692008
1151            04232810
1152        971507495882
1153                  04
1154       971-4-2432977
1155       971-4-4579418
1156       971-4-2959536
1157       971-4-2525787
1158         97145579973
1159       971-4-3333211
1165           045657811
1169          0555566612
1170           042432670
1172      971-04-5506337
1173       971-4-2299297
1175      971-04-3796104
1179          0504207073
1180       971-4-3987997
1181           045830857
1186      971-04-3686408
1188      971-04-3491399
1189       971-4-3442266
1190      971-04-4030716
1191           043996487
1193          0501021555
1195         0-4-3132551
1196      971-04-4208583
1198       971-4-4220747
1203       971-4-2765579
1212           041376566
1219      971-50-7042014
1221            04474666
1222      971-04-5541710
1232       971-4-4549917
1250       971-4-4312304
1253       971-4-3790003
1255          0551046679
1257                   0
1261      971-58-5538699
1262      971-04-2848888
1264          0566819205
1271      971-56-6266391
1282       971-4-3312555
1284          0508058266
1286        971523441963
1293       0097143691700
1294       971-4-4545465
1296           045583354
1303            04222222
1304           042414845
1314       971-4-4563346
1318      971-04-3413322
1321      971-04-3159936
1323           045587955
1325                   0
1326       971-4-2899368
1330       971-4-1594545
1332       971-4-3365880
1334           048189001
1337          0552167782
1339       971-4-2668467
1341      971-04-5875382
1344          0585255290
1345       971-4-3218908
1347      971-04-3469998
1351           045674939
1352          0554073535
1365       971-4-4286130
1370          0582763546
1371           042288508
1372      971-04-2738887
1393       971-4-3810200
1397       971-4-3663200
1401          0528868555
1407       971-4-3251251
1412       971-4-4218412
1414      971-52-7899350
1419           042508196
1423      971-04-5516250
1424           043866723
1429      971-04-5512872
1435          0557761458
1441           065572210
1447            04253323
1450           044542366
1455       971-4-3516035
1459       971-4-3520253
1461       971-4-5519556
1465           044206611
1467          0557179560
1469       971-4-3025800
1470       971-4-1131725
1471       971-4-5831920
1475      971-50-1083541
1478           043378691
1482       971-4-5466194
1489        971585101598
1490       971-4-3250035
1491      971-04-4107255
1492      971-58-5729977
1495          0558830830
1499           044563650
1504           045896778
1505          0422251111
1508           045705615
1513      971-04-3400153
1519       971-4-2593576
1521      971-04-5516497
1543       9714045584803
1545           042799100
1550          0502151077
1553      971-04-3554408
1559       971-4-2417191
1564      971-04-3308499
1565       971-4-3695383
1568           045753328
1569        971044474466
1570       971-4-4542588
1573       971-4-4542828
1575       971-4-3307713
1579          0585546090
1580      971-04-5770623
1583           044474665
1584          0554102160
1587           041234567
1588           044214337
1590          0509067566
1595       971-4-2219221
1601        971505719944
1603       971-4-2543643
1610      971-50-4668762
1614       971-2-6100085
1623           043609409
1628       971-4-4370431
1629      971-04-3210200
1630       971-4-3325355
1631       971-4-4405043
1632       971-4-3966666
1633           044308902
1634       971-4-2400800
1635       971-4-4298000
1636       971-4-5469777
1637         97145187555
1638       971-4-3657700
1639       971-4-2270100
1640       971-4-3246017
1641      971-04-4549700
1642       971-4-3979061
1643         97143367000
1644       971-4-2666595
1645       971-4-2543770
1646       971-4-3235977
1647       971-4-4527788
1648       971-4-3297360
1649       971-4-3995101
1650       971-4-5220000
1651       971-4-3320181
1653           044474797
1654       971-4-3746938
1657       971-4-4599902
1658       971-4-3588070
1659      971-04-4327866
1660       971-4-3994944
1661           042493600
1662       971-4-3298121
1663       971-4-3353434
1664       971-4-2944412
1666       971-4-8831090
1667           044356390
1670      971-04-7700309
1674           045844591
1677      971-04-5543227
1678      971-04-5809243
1680      971-04-3685282
1685       971-4-8824588
1688           044228598
1690       971-4-2222669
1691       971-4-4547765
1692      971-04-2418886
1694       971-4-5850975
1695                 045
1696       971-4-4210430
1699      971-04-5783581
1701       971-4-3441604
1702       971-4-4317733
1703           042544683
1704           045762666
1707      971-04-8762333
1712        971045892777
1713        971045657678
1714       971-4-5830001
1715           043580000
1717       971-4-4216770
1719       971-4-3980990
1720         97144221996
1722           045693020
1726       971-4-3940495
1728           043965199
1730          0506769398
1741       971-4-5998700
1744          0585335430
1749          0504951218
1753        971042221414
1757          0506656405
1758           044475469
1768       971-4-5130243
1771           025594877
1773          0589317788
1775         97144508262
1778         97144264720
1783           585308810
1786          0542378096
1797       971-4-5545232
1800           043961552
1806           042145786
1807           043463955
1813       971-4-4558555
1814          0504502460
1821      971-04-8866722
1831        971555163733
1836           045805339
1846           045548613
1857          0521100555
1861       971-4-2688180
1867          0528080200
1875           045578771
1917          0585252575
1923         97144470096
1929          0522222262
1936      971-04-3437177
1944      971-04-2877444
1947          0542212352
1948       971-4-4911111
1960       971-4-4385248
1966       971-4-3804400
1974          0557429007
1978      971-04-5539292
1984          0504313517
1986       971-4-8840841
1987          0566240604
1990           043510077
2005          0503223197
2007       971-4-5197666
2016      971-04-5277877
2019       971-4-2734777
2022          0523705872
2025      971-04-5686577
2028           047649645
2029          0565213504
2030      971-04-4514737
2034        050555835040
2035           042416999
2042       971-4-2688750
2043           043920086
2044       971-4-2959750
2048         97148811199
2055           044223500
2058       971-4-4294444
2062      971-04-5681173
2066       971-4-5519527
2069           044495525
2071           045729444
2083      971-50-8025555
2089       971-4-5787698
2094       971-4-2945228
2117       971-4-5574063
2120           042673003
2122            04229056
2123           041234567
2142          0561543190
2143          0553268890
2150           043353806
2166          0588919860
2173       971-4-5702887
2174           042625161
2176      971-04-2765026

In [6]:
df.isnull().sum()

Office Number       0
Name English        0
Name Arabic         0
Website          9424
Phone Number     7880
Email              25
dtype: int64

In [15]:
import pandas as pd

df1 = df.replace(r'^\s*$', pd.NA, regex=True)

empty_columns = df1.columns[df1.isna().all()]

print("Completely empty columns:")
print(list(empty_columns))

Completely empty columns:
['sub_category_2', 'depth', 'price', 'currency', 'price_per', 'bedrooms', 'bathrooms', 'furnished', 'rera_permit_number', 'dtcm_licence', 'amenities', 'details', 'agent_name', 'reference_number', 'phone_number', 'latitude', 'longitude']

In [19]:
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

invalid_email = df[
    df["Email"].notna() &
    ~df["Email"].astype(str).str.fullmatch(email_pattern)
]

print("Invalid Emails:", len(invalid_email))
print(invalid_email[["Email"]])

Invalid Emails: 0
Empty DataFrame
Columns: [Email]
Index: []

In [3]:
df.iteration_number.value_counts()

iteration_number
202608    1141
Name: count, dtype: int64

In [12]:
df.id.duplicated().sum()

np.int64(0)

In [11]:
df[df.url.duplicated() >= 1]

,id,url,broker_display_name,broker,category,category_url,title,property_type,sub_category_1,sub_category_2,description,location,depth,price,currency,price_per,bedrooms,bathrooms,furnished,rera_permit_number,dtcm_licence,scraped_ts,amenities,details,agent_name,reference_number,number_of_photos,user_id,published_at,phone_number,date,iteration_number,latitude,longitude
19972,11183753030,https://haraj.com.sa/11183754057/شقة_مفروشه_فاخرة_للايجار_في_أبها,x0x507,X0X507,rent,/tags/%D8%B4%D9%82%D9%82%20%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1,احتاج شقة في حي النخيل نظيفه وايجارها معقول وكبيره,Apartments,Residential,,احتاج شقة في حي النخيل نظيفه وايجارها معقول وكبيره,أبها,,,,,,,,,,2026-07-27,,,,,1,x0x507,2026-07-04,,2026-07-27,202608,,

In [10]:
df.url.duplicated().sum()

np.int64(1)

In [7]:
df.broker_licenses.value_counts()

broker_licenses
[{"end_date": "08/11/2026", "license_number": "36806", "license_type": "Trade License"}]            1
[{"end_date": "31/03/2027", "license_number": "5606", "license_type": "Trade License"}]             1
[{"end_date": "19/02/2027", "license_number": "64891", "license_type": "Trade License"}]            1
[{"end_date": "02/09/2026", "license_number": "7921", "license_type": "Trade License"}]             1
[{"end_date": "03/02/2027", "license_number": "70776", "license_type": "Trade License"}]            1
[{"end_date": "01/09/2026", "license_number": "38571", "license_type": "Trade License"}]            1
[{"end_date": "28/01/2027", "license_number": "116496", "license_type": "Trade License"}]           1
[{"end_date": "15/02/2027", "license_number": "2800", "license_type": "Trade License"}]             1
[{"end_date": "12/04/2027", "license_number": "130893", "license_type": "Professional License"}]    1
[{"end_date": "07/07/2027", "license_number": "119036", "license_type": "Professional License"}]    1
[{"end_date": "19/05/2027", "license_number": "107950", "license_type": "Professional License"}]    1
[{"end_date": "30/01/2027", "license_number": "103261", "license_type": "Professional License"}]    1
[{"end_date": "05/02/2027", "license_number": "99931", "license_type": "Professional License"}]     1
[{"end_date": "29/04/2027", "license_number": "95834", "license_type": "Professional License"}]     1
[{"end_date": "10/11/2026", "license_number": "94447", "license_type": "Trade License"}]            1
[{"end_date": "20/09/2026", "license_number": "66467", "license_type": "Professional License"}]     1
[{"end_date": "25/10/2026", "license_number": "61805", "license_type": "Trade License"}]            1
[{"end_date": "25/11/2026", "license_number": "61935", "license_type": "Trade License"}]            1
[{"end_date": "02/08/2026", "license_number": "58365", "license_type": "Professional License"}]     1
[{"end_date": "07/01/2027", "license_number": "55246", "license_type": "Professional License"}]     1
[{"end_date": "24/04/2027", "license_number": "54535", "license_type": "Trade License"}]            1
[{"end_date": "10/10/2026", "license_number": "2534", "license_type": "Trade License"}]             1
[{"end_date": "13/07/2027", "license_number": "47977", "license_type": "Trade License"}]            1
[{"end_date": "27/07/2026", "license_number": "46456", "license_type": "Trade License"}]            1
[{"end_date": "20/02/2027", "license_number": "46191", "license_type": "Trade License"}]            1
[{"end_date": "26/03/2027", "license_number": "45657", "license_type": "Trade License"}]            1
[{"end_date": "13/01/2027", "license_number": "45806", "license_type": "Trade License"}]            1
[{"end_date": "08/05/2027", "license_number": "43728", "license_type": "Trade License"}]            1
[{"end_date": "23/04/2027", "license_number": "43202", "license_type": "Trade License"}]            1
[{"end_date": "29/01/2027", "license_number": "42567", "license_type": "Trade License"}]            1
[{"end_date": "13/02/2027", "license_number": "42453", "license_type": "Trade License"}]            1
[{"end_date": "21/05/2027", "license_number": "40680", "license_type": "Trade License"}]            1
[{"end_date": "09/08/2026", "license_number": "39714", "license_type": "Trade License"}]            1
[{"end_date": "22/03/2027", "license_number": "39657", "license_type": "Trade License"}]            1
[{"end_date": "23/12/2026", "license_number": "39771", "license_type": "Trade License"}]            1
[{"end_date": "11/02/2027", "license_number": "39459", "license_type": "Trade License"}]            1
[{"end_date": "20/03/2027", "license_number": "39364", "license_type": "Trade License"}]            1
[{"end_date": "10/02/2027", "license_number": "22140", "license_type": "Trade License"}]            1
[{"end_date": "14/05/2027", "license_number": "22099", "license_type": "Trade License"}]            1
[{"end_date": "14/08/2027", "license_number": "21985", "license_type": "Trade License"}]            1
[{"end_date": "03/01/2027", "license_number": "21398", "license_type": "Professional License"}]     1
[{"end_date": "26/02/2027", "license_number": "21382", "license_type": "Trade License"}]            1
[{"end_date": "27/07/2026", "license_number": "20737", "license_type": "Trade License"}]            1
[{"end_date": "07/03/2027", "license_number": "16096", "license_type": "Professional License"}]     1
[{"end_date": "04/01/2027", "license_number": "10239", "license_type": "Trade License"}]            1
[{"end_date": "05/11/2026", "license_number": "8907", "license_type": "Trade License"}]             1
[{"end_date": "09/01/2027", "license_number": "8556", "license_type": "Professional License"}]      1
[{"end_date": "25/09/2026", "license_number": "7250", "license_type": "Trade License"}]             1
[{"end_date": "16/10/2026", "license_number": "8372", "license_type": "Trade License"}]             1
[{"end_date": "22/08/2026", "license_number": "7187", "license_type": "Trade License"}]             1
[{"end_date": "25/11/2026", "license_number": "5018", "license_type": "Trade License"}]             1
[{"end_date": "05/03/2027", "license_number": "4382", "license_type": "Trade License"}]             1
[{"end_date": "01/05/2027", "license_number": "3677", "license_type": "Trade License"}]             1
[{"end_date": "02/03/2027", "license_number": "27926", "license_type": "Trade License"}]            1
[{"end_date": "29/08/2026", "license_number": "27443", "license_type": "Trade License"}]            1
[{"end_date": "09/05/2027", "license_number": "25927", "license_type": "Professional License"}]     1
[{"end_date": "20/09/2026", "license_number": "25694", "license_type": "Trade License"}]            1
[{"end_date": "11/02/2027", "license_number": "24814", "license_type": "Trade License"}]            1
[{"end_date": "01/07/2027", "license_number": "24717", "license_type": "Trade License"}]            1
[{"end_date": "21/04/2027", "license_number": "24707", "license_type": "Trade License"}]            1
[{"end_date": "13/09/2026", "license_number": "24232", "license_type": "Trade License"}]            1
[{"end_date": "06/01/2027", "license_number": "24197", "license_type": "Trade License"}]            1
[{"end_date": "19/03/2027", "license_number": "23256", "license_type": "Trade License"}]            1
[{"end_date": "10/12/2026", "license_number": "22824", "license_type": "Trade License"}]            1
[{"end_date": "14/08/2026", "license_number": "22557", "license_type": "Trade License"}]            1
[{"end_date": "16/08/2026", "license_number": "49887", "license_type": "Trade License"}]            1
[{"end_date": "13/02/2027", "license_number": "22399", "license_type": "Trade License"}]            1
[{"end_date": "03/04/2027", "license_number": "22354", "license_type": "Trade License"}]            1
[{"end_date": "06/02/2027", "license_number": "49441", "license_type": "Trade License"}]            1
[{"end_date": "20/08/2026", "license_number": "61511", "license_type": "Trade License"}]            1
[{"end_date": "29/08/2026", "license_number": "60843", "license_type": "Trade License"}]            1
[{"end_date": "02/05/2027", "license_number": "35793", "license_type": "Trade License"}]            1
[{"end_date": "29/05/2027", "license_number": "60130", "license_type": "Trade License"}]            1
[{"end_date": "21/02/2027", "license_number": "58881", "license_type": "Trade License"}]            1
[{"end_date": "22/11/2026", "license_number": "35536", "license_type": "Trade License"}]            1
[{"end_date": "28/09/2026", "license_number": "58775", "license_type": "Professional License"}]     1
[{"end_date": "22/02/2027", "license_number": "34938", "license_type": "Trade License"}]            1
[{"end_date": "06/07/2026", "license_number": "57584", "license_type": "Trade License"}]            1
[{"end_date": "26/07/2027", "license_number": "33237", "license_type": "Trade License"}]            1
[{"end_date": "22/08/2026", "license_number": "33547", "license_type": "Trade License"}]            1
[{"end_date": "11/08/2027", "license_number": "53040", "license_type": "Trade License"}]            1
[{"end_date": "15/08/2026", "license_number": "28594", "license_type": "Trade License"}]            1
[{"end_date": "02/07/2027", "license_number": "52122", "license_type": "Trade License"}]            1
[{"end_date": "09/04/2027", "license_number": "28444", "license_type": "Trade License"}]            1
[{"end_date": "05/06/2027", "license_number": "28504", "license_type": "Trade License"}]            1
[{"end_date": "25/08/2026", "license_number": "66254", "license_type": "Trade License"}]            1
[{"end_date": "12/01/2027", "license_number": "38530", "license_type": "Trade License"}]            1
[{"end_date": "26/04/2027", "license_number": "65439", "license_type": "Trade License"}]            1
[{"end_date": "05/11/2026", "license_number": "38145", "license_type": "Trade License"}]            1
[{"end_date": "06/08/2026", "license_number": "37992", "license_type": "Trade License"}]            1
[{"end_date": "18/04/2027", "license_number": "65334", "license_type": "Trade License"}]            1
[{"end_date": "31/03/2027", "license_number": "65280", "license_type": "Professional License"}]     1
[{"end_date": "22/04/2027", "license_number": "65259", "license_type": "Trade License"}]            1
[{"end_date": "06/04/2027", "license_number": "64646", "license_type": "Trade License"}]            1
[{"end_date": "04/12/2026", "license_number": "64536", "license_type": "Trade License"}]            1
[{"end_date": "02/12/2026", "license_number": "64341", "license_type": "Trade License"}]            1
[{"end_date": "02/12/2026", "license_number": "64347", "license_type": "Trade License"}]            1
[{"end_date": "11/10/2026", "license_number": "64274", "license_type": "Trade License"}]            1
[{"end_date": "19/03/2027", "license_number": "36892", "license_type": "Trade License"}]            1
[{"end_date": "14/11/2026", "license_number": "62265", "license_type": "Trade License"}]            1
[{"end_date": "01/10/2026", "license_number": "61575", "license_type": "Trade License"}]            1
[{"end_date": "31/01/2027", "license_number": "69451", "license_type": "Trade License"}]            1
[{"end_date": "26/08/2026", "license_number": "69267", "license_type": "Trade License"}]            1
[{"end_date": "21/03/2027", "license_number": "41899", "license_type": "Trade License"}]            1
[{"end_date": "17/01/2027", "license_number": "41111", "license_type": "Trade License"}]            1
[{"end_date": "19/04/2027", "license_number": "67935", "license_type": "Trade License"}]            1
[{"end_date": "10/03/2027", "license_number": "67751", "license_type": "Professional License"}]     1
[{"end_date": "19/01/2027", "license_number": "40645", "license_type": "Trade License"}]            1
[{"end_date": "16/03/2027", "license_number": "67674", "license_type": "Trade License"}]            1
[{"end_date": "17/02/2027", "license_number": "67655", "license_type": "Trade License"}]            1
[{"end_date": "06/03/2027", "license_number": "67637", "license_type": "Trade License"}]            1
[{"end_date": "02/05/2027", "license_number": "39952", "license_type": "Trade License"}]            1
[{"end_date": "26/04/2027", "license_number": "39913", "license_type": "Trade License"}]            1
[{"end_date": "02/03/2027", "license_number": "66688", "license_type": "Trade License"}]            1
[{"end_date": "06/02/2027", "license_number": "39138", "license_type": "Trade License"}]            1
[{"end_date": "19/09/2026", "license_number": "38830", "license_type": "Trade License"}]            1
[{"end_date": "13/09/2026", "license_number": "66370", "license_type": "Trade License"}]            1
[{"end_date": "13/11/2026", "license_number": "89768", "license_type": "Professional License"}]     1
[{"end_date": "02/10/2026", "license_number": "79080", "license_type": "Trade License"}]            1
[{"end_date": "04/08/2026", "license_number": "78513", "license_type": "Trade License"}]            1
[{"end_date": "09/08/2026", "license_number": "78430", "license_type": "Trade License"}]            1
[{"end_date": "08/08/2026", "license_number": "78413", "license_type": "Trade License"}]            1
[{"end_date": "02/08/2026", "license_number": "78338", "license_type": "Trade License"}]            1
[{"end_date": "27/07/2027", "license_number": "78283", "license_type": "Trade License"}]            1
[{"end_date": "19/07/2026", "license_number": "78169", "license_type": "Trade License"}]            1
[{"end_date": "30/01/2027", "license_number": "75982", "license_type": "Trade License"}]            1
[{"end_date": "02/11/2026", "license_number": "73528", "license_type": "Trade License"}]            1
[{"end_date": "17/07/2027", "license_number": "71514", "license_type": "Trade License"}]            1
[{"end_date": "07/03/2027", "license_number": "70823", "license_type": "Trade License"}]            1
[{"end_date": "12/01/2027", "license_number": "70433", "license_type": "Trade License"}]            1
[{"end_date": "02/02/2027", "license_number": "70388", "license_type": "Trade License"}]            1
[{"end_date": "16/11/2026", "license_number": "69974", "license_type": "Trade License"}]            1
[{"end_date": "03/10/2026", "license_number": "69601", "license_type": "Trade License"}]            1
[{"end_date": "07/08/2026", "license_number": "104491", "license_type": "Trade License"}]           1
[{"end_date": "24/07/2027", "license_number": "43490", "license_type": "Trade License"}]            1
[{"end_date": "22/04/2027", "license_number": "95712", "license_type": "Trade License"}]            1
[{"end_date": "30/05/2027", "license_number": "43246", "license_type": "Trade License"}]            1
[{"end_date": "22/02/2027", "license_number": "95017", "license_type": "Trade License"}]            1
[{"end_date": "31/01/2027", "license_number": "94739", "license_type": "Trade License"}]            1
[{"end_date": "26/07/2027", "license_number": "92716", "license_type": "Trade License"}]            1
[{"end_date": "19/07/2026", "license_number": "92612", "license_type": "Trade License"}]            1
[{"end_date": "16/07/2027", "license_number": "92609", "license_type": "Professional License"}]     1
[{"end_date": "24/04/2027", "license_number": "91671", "license_type": "Trade License"}]            1
[{"end_date": "22/02/2027", "license_number": "90781", "license_type": "Trade License"}]            1
[{"end_date": "01/03/2027", "license_number": "90866", "license_type": "Trade License"}]            1
[{"end_date": "07/01/2027", "license_number": "90165", "license_type": "Trade License"}]            1
[{"end_date": "01/01/2027", "license_number": "90038", "license_type": "Trade License"}]            1
[{"end_date": "21/12/2026", "license_number": "89966", "license_type": "Trade License"}]            1
[{"end_date": "15/11/2026", "license_number": "89789", "license_type": "Trade License"}]            1
[{"end_date": "11/01/2027", "license_number": "44004", "license_type": "Trade License"}]            1
[{"end_date": "19/06/2027", "license_number": "139222", "license_type": "Trade License"}]           1
[{"end_date": "21/01/2027", "license_number": "137024", "license_type": "Trade License"}]           1
[{"end_date": "18/01/2027", "license_number": "136869", "license_type": "Trade License"}]           1
[{"end_date": "27/08/2026", "license_number": "133769", "license_type": "Trade License"}]           1
[{"end_date": "26/05/2027", "license_number": "131924", "license_type": "Trade License"}]           1
[{"end_date": "05/03/2027", "license_number": "117089", "license_type": "Trade License"}]           1
[{"end_date": "11/11/2026", "license_number": "115296", "license_type": "Trade License"}]           1
[{"end_date": "04/06/2027", "license_number": "43746", "license_type": "Trade License"}]            1
[{}]                                                                                                1
[{"end_date": "23/09/2026", "license_number": "114489", "license_type": "Trade License"}]           1
[{"end_date": "11/11/2026", "license_number": "109860", "license_type": "Trade License"}]           1
[{"end_date": "28/09/2026", "license_number": "109363", "license_type": "Trade License"}]           1
[{"end_date": "22/04/2027", "license_number": "107647", "license_type": "Trade License"}]           1
[{"end_date": "11/08/2026", "license_number": "43552", "license_type": "Trade License"}]            1
[{"end_date": "28/01/2027", "license_number": "106504", "license_type": "Trade License"}]           1
[{"end_date": "20/10/2026", "license_number": "52371", "license_type": "Trade License"}]            1
[{"end_date": "10/02/2027", "license_number": "52025", "license_type": "Trade License"}]            1
[{"end_date": "22/10/2026", "license_number": "51826", "license_type": "Trade License"}]            1
[{"end_date": "15/05/2027", "license_number": "51721", "license_type": "Trade License"}]            1
[{"end_date": "12/07/2027", "license_number": "51233", "license_type": "Trade License"}]            1
[{"end_date": "14/02/2027", "license_number": "51155", "license_type": "Trade License"}]            1
[{"end_date": "03/07/2027", "license_number": "51148", "license_type": "Trade License"}]            1
[{"end_date": "22/07/2027", "license_number": "50258", "license_type": "Trade License"}]            1
[{"end_date": "06/04/2027", "license_number": "50244", "license_type": "Trade License"}]            1
[{"end_date": "07/08/2026", "license_number": "49381", "license_type": "Trade License"}]            1
[{"end_date": "13/11/2026", "license_number": "48945", "license_type": "Trade License"}]            1
[{"end_date": "27/05/2027", "license_number": "47164", "license_type": "Trade License"}]            1
[{"end_date": "26/07/2027", "license_number": "46601", "license_type": "Trade License"}]            1
[{"end_date": "23/03/2027", "license_number": "45468", "license_type": "Trade License"}]            1
[{"end_date": "17/09/2026", "license_number": "44854", "license_type": "Trade License"}]            1
[{"end_date": "11/07/2027", "license_number": "44124", "license_type": "Trade License"}]            1
[{"end_date": "04/08/2026", "license_number": "60950", "license_type": "Trade License"}]            1
[{"end_date": "18/07/2027", "license_number": "60784", "license_type": "Trade License"}]            1
[{"end_date": "11/09/2026", "license_number": "58635", "license_type": "Trade License"}]            1
[{"end_date": "20/05/2027", "license_number": "57699", "license_type": "Trade License"}]            1
[{"end_date": "10/02/2027", "license_number": "57969", "license_type": "Trade License"}]            1
[{"end_date": "03/03/2027", "license_number": "56868", "license_type": "Trade License"}]            1
[{"end_date": "24/01/2027", "license_number": "56835", "license_type": "Trade License"}]            1
[{"end_date": "17/08/2026", "license_number": "54659", "license_type": "Trade License"}]            1
[{"end_date": "14/10/2026", "license_number": "55651", "license_type": "Trade License"}]            1
[{"end_date": "10/04/2027", "license_number": "54075", "license_type": "Professional License"}]     1
[{"end_date": "09/11/2026", "license_number": "53456", "license_type": "Trade License"}]            1
[{"end_date": "10/11/2026", "license_number": "53400", "license_type": "Trade License"}]            1
[{"end_date": "07/11/2026", "license_number": "53388", "license_type": "Trade License"}]            1
[{"end_date": "25/10/2026", "license_number": "53256", "license_type": "Trade License"}]            1

In [9]:
df[df.broker_licenses == "[{}]""]

SyntaxError: unterminated string literal (detected at line 1) (190675803.py, line 1)

In [10]:
df[df["broker_licenses"].astype(str) == "[{}]"]

,unique_id,url,name,license_number,license_expiry_date,broker_type,mobile_number,email_address,the_unified_number_of_the_establishment,broker_licenses,street,city,region,district,building_number,additional_number,scraped_ts,date,iteration_number
155,c157d8a0-3bfb-4779-a68c-39c9c60f16b6,https://eservices.ajmanded.ae/en/TradeLicense/License/c157d8a0-3bfb-4779-a68c-39c9c60f16b6,YOUR CHOICE REALESTATE INVES L.L.C,114813,13/10/2026,,,,,[{}],,,Aamra,,ألعامرة 1,5,2026-07-29,2026-07-29,202608

In [11]:
df.name.value_counts()

name
.BIN MALEK REAL ESTATE/ (S.P.S - L.L.C)                                                                                        1
ALBAIT ALFARID REALSTATE                                                                                                       1
AL MOTAKAMLA REALSTATE                                                                                                         1
AL FAISAL REALESTATE SERVICES                                                                                                  1
ALMUNA  REALSTATE-L.L.C                                                                                                        1
ROYAL PALAC REAL ESTATE (S.P.S - L.L.C)                                                                                        1
AL HAYAT REALESTATE L.L.C                                                                                                      1
YOUSEF BIN NASSER & SONS REAL ESTATE (S.P.S - L.L.C)                                                                           1
ARYAF HOTEL APARTMENTS (S.P.S - L.L.C)                                                                                         1
NEW ROYAL PALACE HOTEL APARTMENTS                                                                                              1
ONYX HOTEL APARTMENTS L.L.C                                                                                                    1
THE PARADISE INN HOTEL APARTMENTS-L.L.C - Branch 01                                                                            1
AMR ACACIA HOTEL APARTMENTS L.L.C                                                                                              1
REEF HOTEL APARTMENTS - L.L.C                                                                                                  1
EWAN TOWER HOTEL APARTMENTS                                                                                                    1
HALA INN HOTEL APARTMENTS-L.LC                                                                                                 1
THE PARADISE INN HOTEL APARTMENTS-L.L.C                                                                                        1
ALSMOU HOTEL APARTMENTS/ L.L.C                                                                                                 1
ARABIAN HOTEL APARTMENTS                                                                                                       1
EWAN HOTEL APARTMENTS                                                                                                          1
SARA HOTEL APARTMENTS                                                                                                          1
ALI MOHAMED YOUSUF REAL ESTATE (S.P.S - L.L.C)                                                                                 1
.AL AMEED REALESTATE                                                                                                           1
AL FAREED REALESTATE INVESTMENT CENTRE                                                                                         1
AL SARMINI REALESTATE EST /L.L.C                                                                                               1
ABU ALHOUSH REALESTATE                                                                                                         1
(MOOSANI REALESTATE (L.L.C                                                                                                     1
BIN ZAYED REALESTATE INVESTMENT                                                                                                1
.DIYAR AJMAN REALESTATE INVESTMENT L.L.C                                                                                       1
PIONEERS REALESTATE (L.L.C)                                                                                                    1
.AL MARWAH REALESTATE L.L.C                                                                                                    1
AL JAWAL REALESTATE                                                                                                            1
.HINYAMI REALESTATE                                                                                                            1
AL SHOZAWI REALESTATE L.L.C (SOLE PROPRIETORSHIP)                                                                              1
DREAM HOME REALESTATE INVESTMET EST                                                                                            1
ABU SAIF REALESTATE EST                                                                                                        1
AL HESSIN REALESTATE                                                                                                           1
AL SAEEDI REAL ESTATE. CO /L.L.C                                                                                               1
AL DHIAFA REAL ESTATE SELLING BUYING AND RENTIN - L.L.C                                                                        1
.(AL NAHHAM REAL ESTATE (L.L.C                                                                                                 1
AL ZAJEL REAL ESTATE CO - L.L.C                                                                                                1
(.AL AHLIA REAL ESTATE CO(L.L.C                                                                                                1
.UNITED REAL ESTATE EST                                                                                                        1
AL WAHDA REAL ESTATE OFFICE                                                                                                    1
KHALFAN ALKAABI REAL ESTATE.EST .                                                                                              1
AL OLA REAL ESTATE OFFICE L.L.C (SOLE PROPRIETORSHIP)                                                                          1
AL HAIF REAL ESTATE OFFICE                                                                                                     1
AL NAKHEELAT REAL ESTATE OFFICE                                                                                                1
.AL BURJ REAL ESTATE TRADING EST                                                                                               1
GREENS REAL ESTATE L.L.C                                                                                                       1
.ABU AHMAD REAL ESTATE OFFICE                                                                                                  1
AL SHAAB REAL ESTATE OFFICE                                                                                                    1
EASTERN GATE TO DETECTION REAL ESTATE                                                                                          1
AL MAJED REAL ESTATE                                                                                                           1
.CENTRAL INTERNATIONAL REAL ESTATE EST                                                                                         1
AL HADAF REAL ESTATE CENTER                                                                                                    1
ABU HUMAID REAL ESTATE OFFICE                                                                                                  1
.AL SAD AL AALI REAL ESTATE EST                                                                                                1
BIN SALMEEN REAL ESTATE                                                                                                        1
CONTRACT REAL ESTATE                                                                                                           1
ALDURAH REAL ESTATE L.L.C                                                                                                      1
.AL OBAIDLY REAL ESTATE                                                                                                        1
.AL DIWAN REAL ESTATE INVESTMENT/L.L.C                                                                                         1
EXPRESS REAL ESTATE L.L.C                                                                                                      1
AL TQADUM REAL ESTATE                                                                                                          1
LAND MARK REALESTATE/L.L.C                                                                                                     1
ALBONIAN REAL ESTATE                                                                                                           1
AL RAMLA REAL ESTATE                                                                                                           1
AL AWAEL REALESTATE IVESTEMENT /L.LC                                                                                           1
AL RABYA REALESTATE- L.L.C                                                                                                     1
REAL HOME REALESTATE /L.L.C                                                                                                    1
MAKKAH REAL ESTATE (S.P.S - L.L.C)                                                                                             1
SAMA DUBAI REALESTATE/L.L.C                                                                                                    1
CLASSIC LAND REALESTATE                                                                                                        1
EAGLE REAL ESTATE/L.L.C                                                                                                        1
AL ASIMA REALESTATE INVESTMENT                                                                                                 1
.AL NASHMY REAL ESTATE L.L.C                                                                                                   1
AL JOZOOR REALESTATE /L.L.C                                                                                                    1
.AL SAHEL REAL ESTATE                                                                                                          1
.AL MUSTAQBEL REAL ESTATE                                                                                                      1
ETHMAR REALESTATE                                                                                                              1
.BIN HASSAN REAL ESTATE EST                                                                                                    1
FALCON REALESTATE                                                                                                              1
HAMAD AL GHANEM REAL ESTATE                                                                                                    1
NOOR AL HAYAT REAL ESTATE L.L.C                                                                                                1
.AL WAFI REALESTATE                                                                                                            1
NATIONAL CENTRE FOR REAL ESTATE INVESTMENT -L.L.C                                                                              1
AL MIRAJ REALESTATE/L.L.C                                                                                                      1
.AL BARAHA REAL ESTATE                                                                                                         1
OASIS REAL ESTATE INVESTMENT-L.L.C                                                                                             1
QASER AL RAWDHA REALESTATE L.L.C (SOLE PROPRIETORSHIP)                                                                         1
AL  OSOOL REALESTATE/L.L.C                                                                                                     1
MOHAMED HASAN OSMAN REALESTATE /L.L.C                                                                                          1
AL REHAN REALESTATE /L.L.C                                                                                                     1
MAGIC HOMES REALESTATE /L.L.C                                                                                                  1
HOME LAND REALESTATE - L.L.C                                                                                                   1
.AL MUTAMAIZ REALESTATE/L.L.C                                                                                                  1
SABR AL AWSI REALESTATE/L.L.C                                                                                                  1
CROWN REAL ESTATE/L.L.C                                                                                                        1
AL SHAMSI REALESTATE                                                                                                           1
AL HAYASHI REALESTATE                                                                                                          1
AL BURAQ REALESTATE                                                                                                            1
LOYAL REALESTATE  L.L.C                                                                                                        1
.(AL AIN OASIS REAL ESTATE(L.L.C                                                                                               1
.ALHEWADI REAL ESTATE/L.L.C                                                                                                    1
ALSHAALI REALESTATE                                                                                                            1
 AL QUDRAT REALESTATE - L.L.C                                                                                                  1
QUALITY HOUSE REAL ESTATE                                                                                                      1
ENMA REALESTATE /L.L.C                                                                                                         1
ALASRIYAH REALESTATE INVES L.L.C                                                                                               1
SILVER GATE REALESTATE/L.L.C                                                                                                   1
ALSHAHD REAL ESTATE                                                                                                            1
SADAF REAL ESTATE L.L.C                                                                                                        1
PARAMOUNT REALESTATE                                                                                                           1
AL KHAIMAH REAL ESTATE  -SOLE PROPRIETORSHIP L.L.C                                                                             1
MAX REAL ESTATE L.L.C                                                                                                          1
AL MOZA REALESTATE L.L.C                                                                                                       1
BWABET AL OMRAN REALESTATE L.L.C                                                                                               1
ALMOSTATHMR REALESTATE CENTER                                                                                                  1
AL KHOR REALESTATE - L.L.C                                                                                                     1
PLAZA REALESTATE - L.L.C                                                                                                       1
ALNAFOORA REALESTATE                                                                                                           1
AL BWADI REALESTATE - L.L.C                                                                                                    1
AL MAZROERY REALESTATE/L.L.C                                                                                                   1
JEWEL REALESTATE L.L.C                                                                                                         1
AL SAHM REALESTATE - L.L.C                                                                                                     1
AL SAEED REALESTATE - L.L.C                                                                                                    1
AL QOSOR REALESTATE / L.L.C                                                                                                    1
BASEL REALESTATE -L.L.C                                                                                                        1
STANDERD HOMES REALESTATE/L.L.C                                                                                                1
AL NAMOZAJIA REALESTATE                                                                                                        1
AL SENYAR REALESTATE/L.L.C                                                                                                     1
(RUFI REALESTATE (L.L.C                                                                                                        1
BU HASSAN REALESTATE INVES                                                                                                     1
.SARAA REAL ESTATE L.L.C (SOLE PROPRIETORSHIP)                                                                                 1
BIN ALOUH REALESTATE                                                                                                           1
(STYLE HOME REAL ESTATE INVEST (L.L.C                                                                                          1
AL ZAHRA REALESTATE - L.L.C                                                                                                    1
HUNOOF REALESTATE                                                                                                              1
HASSAN REALESTATE - L.L.C                                                                                                      1
ALMANARA REALESTATE INVESTMENT                                                                                                 1
SHAMMALAH  REALESTATE - L.L.C                                                                                                  1
AL HARIB REALESTATE (S.P.S - L.L.C)                                                                                            1
AL HARAMAIN REALESTATE L.L.C                                                                                                   1
TNMIA REALESTATE L.L.C                                                                                                         1
IMADE SUBEH REALESTATE -L.L.C                                                                                                  1
ARD AL TASAMH REALESTATE                                                                                                       1
MOYNUL ISLAM REALESTATE-L.L.C                                                                                                  1
ABU HAFSAH REALESTATE                                                                                                          1
DAR AL EMARAT REAL ESTATE INVESTMENT/L.L.C                                                                                     1
AL KAITOOB REALESTATE                                                                                                          1
THAMARA REALESTATE (S.P.S - L.L.C)                                                                                             1
TAYAB REALESTATE                                                                                                               1
BIN FAHID  REALESTATE (S.P.S - L.L.C)                                                                                          1
NEST REALESTATE (S.P.S - L.L.C)                                                                                                1

In [18]:
import pandas as pd

text_cols = df.select_dtypes(include="object").columns

# Regex for whitespace issues
pattern = r"(^ )|( $)|( {2,})|(\t)|(\n)|(\r)|(\u00A0)"

for col in text_cols:
    mask = (
        df[col]
        .fillna("")
        .astype(str)
        .str.contains(pattern, regex=True)
    )

    if mask.any():
        print(f"\n=== {col}: {mask.sum()} rows ===")

        cols = ["website" col]
        cols = [c for c in cols if c in df.columns]

        print(
            df.loc[mask, cols]
              .reset_index(names="row_no")
        )

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2854391279.py, line 19)

In [13]:
df.isna().sum()

id                     0
url                    0
broker_display_name    0
broker                 0
category               0
category_url           0
title                  0
property_type          0
sub_category_1         0
sub_category_2         0
description            0
location               0
depth                  0
price                  0
currency               0
price_per              0
bedrooms               0
bathrooms              0
furnished              0
rera_permit_number     0
dtcm_licence           0
scraped_ts             0
amenities              0
details                0
agent_name             0
reference_number       0
number_of_photos       0
user_id                0
published_at           0
phone_number           0
date                   0
iteration_number       0
latitude               0
longitude              0
dtype: int64

In [14]:
(df == "").sum()

id                         0
url                        0
broker_display_name        0
broker                     0
category                   0
category_url               0
title                      0
property_type              0
sub_category_1             1
sub_category_2         32356
description               20
location                   0
depth                  32356
price                  32356
currency               32356
price_per              32356
bedrooms               32356
bathrooms              32356
furnished              32356
rera_permit_number     32356
dtcm_licence           32356
scraped_ts                 0
amenities              32356
details                32356
agent_name             32356
reference_number       32356
number_of_photos        6223
user_id                    0
published_at               0
phone_number           32356
date                       0
iteration_number           0
latitude               32356
longitude              32356
dtype: int64

In [18]:
df[df.license_expiry_date == ""]

,unique_id,url,name,license_number,license_expiry_date,broker_type,mobile_number,email_address,the_unified_number_of_the_establishment,broker_licenses,street,city,region,district,building_number,additional_number,scraped_ts,date,iteration_number
111,ac2635f3-cf27-4793-82c7-595f0334c793,https://eservices.ajmanded.ae/en/TradeLicense/License/ac2635f3-cf27-4793-82c7-595f0334c793,AL QUDRAT REALESTATE - L.L.C,67751,,,,,,"[{""end_date"": ""10/03/2027"", ""license_number"": ""67751"", ""license_type"": ""Professional License""}]",,,Rashideya 1,,Horizon tower,610,2026-07-29,2026-07-29,202608

In [19]:
import pandas as pd
import re

# Column to check
col = "name"   # change to your column name

# Expected keywords
keywords = [
    "Real estate",
    "Realestate",
    "Realstate",
    "Real estates",
    "Realty",
    "Properties",
    "Property",
    "Property management",
    "Realtors",
    "Business Center",
    "Holiday Homes",
    "Hotel Apartments"
]

# Normalize text
series = df[col].fillna("").astype(str)

print("===== Expected Keywords =====")

matched_rows = pd.Series(False, index=df.index)

for kw in keywords:
    mask = series.str.contains(re.escape(kw), case=False, regex=True)
    matched_rows |= mask
    print(f"{kw:<25}: {mask.sum()}")

print("\n===== Rows with Other Values =====")

others = (
    df.loc[~matched_rows, [col]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print(f"Unique other values: {len(others)}")
print(others)

===== Expected Keywords =====
Real estate              : 783
Realestate               : 110
Realstate                : 8
Real estates             : 0
Realty                   : 3
Properties               : 191
Property                 : 18
Property management      : 7
Realtors                 : 0
Business Center          : 16
Holiday Homes            : 0
Hotel Apartments         : 15

===== Rows with Other Values =====
Unique other values: 1
                               name
0  العرب للعقارات ذ.م.م - Branch 01

In [20]:
import pandas as pd
import re

col = "name"

expected = {
    "REAL ESTATE",
    "REALESTATE",
    "REALSTATE",
    "REAL ESTATES",
    "REALTY",
    "PROPERTIES",
    "PROPERTY",
    "PROPERTY MANAGEMENT",
    "REALTORS",
    "BUSINESS CENTER",
    "HOLIDAY HOMES",
    "HOTEL APARTMENTS"
}

# Extract suffix after company name
suffix = (
    df[col]
    .fillna("")
    .str.upper()
    .str.extract(r'([A-Z ]+)$')[0]
    .str.strip()
)

print("===== Expected Types =====")
print(suffix.value_counts()[suffix.value_counts().index.isin(expected)])

print("\n===== Unexpected Types =====")
unexpected = suffix[~suffix.isin(expected)].value_counts()
print(unexpected)

===== Expected Types =====
0
REAL ESTATE    2
Name: count, dtype: int64

===== Unexpected Types =====
0
C                                                             675
LC                                                              3
BR                                                              3
WHITE SPACE REAL ESTATE                                         1
AQAR LINE  REAL ESTATE                                          1
FOUR SEASONS REAL ESTATE                                        1
HATTA REAL ESTATE                                               1
ALMAIMANI  REAL ESTATE                                          1
TILAL ALEASIMA REAL ESTATE DEVELOPMENTS                         1
ALEBTIKAR REAL ESTATE                                           1
QIMMA ALIBDAA  REAL ESTATE                                      1
APEX REAL ESTATE                                                1
AL FURSA AL ZAHABIA REAL ESTATE                                 1
AHMED ALSAADI REAL ESTATE                                       1
YOUSUF AL FALASI REAL ESTATE                                    1
PREMIERE  REAL ESTATE                                           1
GRAND TOWN REAL ESTATE                                          1
GULFA REAL ESTATE                                               1
EMARATEK REAL ESTATE                                            1
AQEED REAL ESTATE                                               1
M D REAL ESTATE                                                 1
ABRAJ ALRAWDA REAL ESTATE                                       1
THE EDGE REAL ESTATE                                            1
SWIFT REAL ESTATE                                               1
THE VIEW REAL ESTATE                                            1
ALAMAARIA REAL ESTATE                                           1
SHALLAL MADINA REAL ESTATE                                      1
RASHED AL SHAMSI REAL ESTATE                                    1
NXT GEN REAL ESTATE PURCHASE AND SALE BROKERAGE                 1
O N REAL ESTATE                                                 1
FINE HOUSE REAL ESTATE                                          1
LEGACY REAL ESTATE INVESTMENT                                   1
NOVARA REAL ESTATE                                              1
STEP ONE BUYING AND SELLING REAL ESTATE                         1
LIO REAL ESTATE                                                 1
TOP LINE REAL ESTATE LEASE AND MANAGEMENT SERVICES              1
M B K  REAL ESTATE                                              1
LIBERTY LAND REAL ESTATE                                        1
GOLDEN AVENUE REAL ESTATE                                       1
AL KHUBARA AL MUTAMAYIZON REAL ESTATE                           1
ABDULLA ALSHARQI REAL ESTATE                                    1
SLSLAT ROQE REAL ESTATE                                         1
ORA CITY REAL ESTATE                                            1
ALQIMA ALDHAHABIA REAL ESTATE                                   1
SHORUQ BALADI REAL ESTATE                                       1
S H REAL ESTATE                                                 1
AL QANNAS REAL ESTATE                                           1
ABDULLA ALMURSHIDI REAL ESTATE                                  1
GATE REAL ESTATE                                                1
AL SHORAFA REAL ESTATE EST                                      1
AL SAIF REAL ESTATE ESTABLISHMENT                               1
ALWADI REAL ESTATE                                              1
ROYAL GEMS REAL ESTATE BROKERAGE                                1
HOME BUILDERS REAL ESTATE INVESTMENT                            1
ELMAAM REAL ESTATE                                              1
BU HAMDAN REAL ESTATE                                           1
ALFORSAN REAL ESTATE                                            1
AL DARB AL AKHDAR REAL ESTATE                                   1
AL BOOM REAL ESTATE                                             1
MOHAMMED ALKAABI REAL ESTATE                                    1
RASIKH REAL ESTATE                                              1
LIWA  REAL ESTATE                                               1
TAMM REAL ESTATE                                                1
AL GHROUB REAL ESTATE                                           1
S H Q REAL ESTATE                                               1
ALMASKAN REAL ESTATE                                            1
ALSOMU REAL ESTATE                                              1
SHARK REAL ESTATE                                               1
L C                                                             1
SABAH AL ARAB REAL ESTATE L L C                                 1
COM   REAL ESTATE                                               1
B K REAL ESTATE                                                 1
AL RIYAMI REAL ESTATE                                           1
AL MUSTAQIR REAL ESTATE LEASE AND MANAGEMENT SERVICES           1
ASIA REAL ESTATE                                                1
QASR SAM REAL ESTATE                                            1
TURKINEST REAL ESTATE INVESTMENT                                1
BAB AL FALAH REAL ESTATE LEASE AND MANAGEMENT SERVICES          1
ALMASAR ALHADITH  REAL ESTATE                                   1
SLAITAR REAL ESTATE INVESTMENT                                  1
ALETIHAD REAL ESTATE                                            1
AL MASHRIQ REAL ESTATE                                          1
AL HAMADI REAL ESTATE                                           1
MANAGEMENT REAL ESTATE                                          1
NEW ROYAL PALACE HOTEL APARTMENTS                               1
EWAN TOWER HOTEL APARTMENTS                                     1
ARABIAN HOTEL APARTMENTS                                        1
EWAN HOTEL APARTMENTS                                           1
AL HUR REAL ESTATE                                              1
AL JABAL BUSINESS CENTER                                        1
CITY STARS PROPERTIES                                           1
FIVE STAR PROPERTIES                                            1
ALEURUBA PROPERTIES                                             1
EXCELLENCY PROPERTIES                                           1
KEYSTONE PROPERTIES                                             1
NOVA PROPERTIES                                                 1
IMPERIAL HOMES PROPERTIES                                       1
PRIDE PROPERTIES                                                1
SARA HOTEL APARTMENTS                                           1
UNITED REAL ESTATE EST                                          1
AL WAHDA REAL ESTATE OFFICE                                     1
AL HAIF REAL ESTATE OFFICE                                      1
AL NAKHEELAT REAL ESTATE OFFICE                                 1
AL BURJ REAL ESTATE TRADING EST                                 1
ABU AHMAD REAL ESTATE OFFICE                                    1
AL SHAAB REAL ESTATE OFFICE                                     1
EASTERN GATE TO DETECTION REAL ESTATE                           1
AL AMEED REALESTATE                                             1
AL AJYAL REALESTATE                                             1
ABU ALHOUSH REALESTATE                                          1
BIN ZAYED REALESTATE INVESTMENT                                 1
AL JAWAL REALESTATE                                             1
HINYAMI REALESTATE                                              1
LULU BUSINESS CENTER                                            1
STANDARD BUSINESS CENTER                                        1
AL NJOOM REALESTATE                                             1
ABRAJ REAL ESTATE CO                                            1
AL WASEET REAL ESTATE EST                                       1
AL FAREED REALESTATE INVESTMENT CENTRE                          1
NEXORA  REAL ESTATE                                             1
AZAAYA   REAL ESTATE                                            1
PEARLS REAL ESTATE                                              1
AJZAL REAL ESTATE                                               1
PRIME TOWN REAL ESTATE                                          1
YOURGATE  REAL ESTATE                                           1
GLOBAL HOMES REAL ESTATE                                        1
FORBES REAL ESTATE                                              1
ZED PROPERTIES                                                  1
LINK IN REAL ESTATE                                             1
ONE REAL ESTATE                                                 1
THANI  ALGHAIS REAL ESTATE                                      1
R B A M REAL ESTATE                                             1
CONTACT REAL ESTATE                                             1
WEJHA REAL ESTATE                                               1
MIDLAND REAL ESTATE                                             1
AL NAKHEAL  REAL ESTATE                                         1
AL QARYA REAL ESTATE                                            1
M B G REAL ESTATE                                               1
DARKOM PROPERTIES                                               1
GOLDEN PROPERTIES                                               1
ALSHARQ PROPERTIES                                              1
JANA PROPERTIES                                                 1
BAYT AL TATWIR PROPERTIES                                       1
AEDAD PROPERTIES                                                1
SO LIVING PROPERTIES                                            1
ALNAJAH  PROPERTIES                                             1
ALRABEA PROPERTIES                                              1
T S AMANAH  REAL ESTATE                                         1
RUYAT MITHAQ PROPERTIES                                         1
BUNYAN BE PROPERTIES                                            1
ALRACKY PROPERTIES                                              1
AL WASBA PROPERTIES                                             1
EDRAK PROPERTIES                                                1
SKY LINE PROPERTIES                                             1
MARSA PROPERTIES                                                1
AL HASBAH PROPERTIES                                            1
AL SAS PROPERTIES                                               1
OCEAN CLOUD PROPERTIES                                          1
ARD AL TASAMH REALESTATE                                        1
ABU HAFSAH REALESTATE                                           1
ALMOSTATHMR REALESTATE CENTER                                   1
ALNAFOORA REALESTATE                                            1
AL NAMOZAJIA REALESTATE                                         1
AL BURAQ REALESTATE                                             1
ALSHAALI REALESTATE                                             1
QUALITY HOUSE REAL ESTATE                                       1
QARAR REAL ESTATE                                               1
PARAMOUNT REALESTATE                                            1
AL WAFI REALESTATE                                              1
AL BARAHA REAL ESTATE                                           1
AL SHAMSI REALESTATE                                            1
AL HAYASHI REALESTATE                                           1
CLASSIC LAND REALESTATE                                         1
AL ASIMA REALESTATE INVESTMENT                                  1
AL SAHEL REAL ESTATE                                            1
AL MUSTAQBEL REAL ESTATE                                        1
ALSHAHD REAL ESTATE                                             1
MESAHAT REAL ESTATE                                             1
EST                                                             1
TALEB REAL ESTATE                                               1
AL BAHIA REAL ESTATE                                            1
DANI REAL ESTATE                                                1
BIN HARIB REAL ESTATE                                           1
AL REMAL REAL ESTATE                                            1
AL HADIDI REAL ESTATE INVESTMENT                                1
AL SARRAJ REAL ESTATE INVEST                                    1
ALMANARA REALESTATE INVESTMENT                                  1
TAYAB REALESTATE                                                1
AL RUKN REALESTATE                                              1
GHAZAL ALMADINH REAL ESTATE                                     1
AL MUSTASHAR REALESTATE INVES                                   1
AL TURATH AL OMRANY REALESTATE INVES                            1
ALMUHANDIS REALESTATE                                           1
BU HASSAN REALESTATE INVES                                      1
BIN ALOUH REALESTATE                                            1
HUNOOF REALESTATE                                               1
AL KAITOOB REALESTATE                                           1
DYMONT PROPERTIES                                               1
TARF PROPERTIES                                                 1
DREAM HOUSE PROPERTIES                                          1
TIGER HOME PROPERTIES                                           1
NEXT DOOR PROPERTIES                                            1
HOME POINT PROPERTIES                                           1
HISTORY PROPERTIES                                              1
HAMDAN PROPERTIES LLC                                           1
ETHMAR REALESTATE                                               1
ABU SAIF REALESTATE EST                                         1
AL HESSIN REALESTATE                                            1
AL MANSOOR REALESTATE                                           1
AL EMMAR  REALESTATE                                            1
JAMAL REALESTATE INVESTMENTS EST                                1
BIN GHUDAIR REALESTATE INVESTMENT                               1
AL FAISAL REALESTATE SERVICES                                   1
AL MOTAKAMLA REALSTATE                                          1
ALBAIT ALFARID REALSTATE                                        1
DREAM HOME REALESTATE INVESTMET EST                             1
BIN HASSAN REAL ESTATE EST                                      1
FALCON REALESTATE                                               1
HAMAD AL GHANEM REAL ESTATE                                     1
AL MAJED REAL ESTATE                                            1
CENTRAL INTERNATIONAL REAL ESTATE EST                           1
AL HADAF REAL ESTATE CENTER                                     1
ABU HUMAID REAL ESTATE OFFICE                                   1
AL SAD AL AALI REAL ESTATE EST                                  1
BIN SALMEEN REAL ESTATE                                         1
EID SAEED   PROPERTIES                                          1
AL OBAIDLY REAL ESTATE                                          1
AL TQADUM REAL ESTATE                                           1
ALBONIAN REAL ESTATE                                            1
AL RAMLA REAL ESTATE                                            1
CONCORD BUSINESS CENTER                                         1
AL ARQOUB BUSINESS CENTER                                       1
ADNAN AL MADANI PROPERTY MANGEMENT                              1
AJMAN BR                                                        1
MUSHERIF PROPERTIES                                             1
CONTRACT REAL ESTATE                                            1
AL KHALIJIYA REAL ESTATE                                        1
ALNUKHBA ALMALAKYA REAL ESTATE                                  1
MEMARI DISTRICT REAL ESTATE                                     1
NASSER REAL ESTATE                                              1
ANWAR ALMADINA REAL ESTATE                                      1
SUN SET REAL ESTATE                                             1
BURJ DUBAI REAL ESTATE                                          1
SULTAN RASHID REAL ESTATE                                       1
AL JAWAREH REAL ESTATE                                          1
ALGHAITH REAL ESTATE                                            1
ELAF REAL ESTATE                                                1
ALAMERAH REAL ESTATE                                            1
AL JAZEM REAL ESTATE                                            1
EAQARATI REAL ESTATE                                            1
BIN HATEM REAL ESTATE                                           1
ABYAT REAL ESTATE                                               1
HIGH VISION REAL ESTATE                                         1
AGNAS REAL ESTATE                                               1
AL NUKHBA REAL ESTATE                                           1
ALI BIN ZAAL REAL ESTATE INVESTMENT                             1
AL NAWRAS REAL ESTATE                                           1
AL BARQ REAL ESTATE                                             1
ALKHUBARA REAL ESTATE                                           1
BLUE SKY REAL ESTATE                                            1
AL NADER REAL ESTATE                                            1
DLALH  REAL ESTATE                                              1
ALHASEM  REAL ESTATE                                            1
THANI ALHAMMADI REAL ESTATE                                     1
AL THIQA REAL ESTATE                                            1
S Q REAL ESTATE                                                 1
BIN SULAIMAN REAL ESTATE                                        1
TATWEER REAL ESTATE                                             1
LAFFI REAL ESTATE                                               1
AL RAQAIB REAL ESTATE                                           1
SALIL REAL ESTATE                                               1
ALMAGLES REAL ESTATE                                            1
HASSAN NASIR ALMIDFA REAL ESTATE                                1
ALSEDIQ REAL ESTATE                                             1
DAR ALSHMOOK REAL ESTATE                                        1
AL EALIH REAL ESTATE                                            1
ALRUWYA REAL ESTATE                                             1
DEYAR REAL ESTATE                                               1
MUBADRA REAL ESTATE                                             1
MEDRAR REAL ESTATE                                              1
BAYT ALMUSTAQBAL REAL ESTATE LEASE AND MANAGEMENT SERVICES      1
AQAR CITY REAL ESTATE                                           1
DAR UL ESKAN REAL ESTATE                                        1
QETAA REAL ESTATE                                               1
DAR AL ZAIN REAL ESTATE                                         1
AL SHAHBAH REAL ESTATE                                          1
ZAMZAM REAL ESTATE                                              1
AL TAFAWQ REAL ESTATE                                           1
AL SAROOJ REAL ESTATE                                           1
AL RAEESI REAL ESTATE SERVICES                                  1
AL MASIDY REAL ESTATE EST                                       1
HORIZON REAL ESTATE                                             1
JASIM BIN HAIDAR REAL ESTATE INVESTMENT                         1
THE TOP INTERNATIONAI REAL ESTATE                               1
SAVILLS REAL ESTATE PRICING SERVICES                            1
LUXURY REAL ESTATE                                              1
CITY REAL ESTATE                                                1
QASER AL SAADAH REAL ESTATE                                     1
HM REAL ESTATE                                                  1
AL TELAL REAL ESTATE                                            1
ALAZM REAL ESTATE                                               1

In [21]:
df[df.name == " العرب للعقارات ذ.م.م - Branch 01"]

Empty DataFrame
Columns: [unique_id, url, name, license_number, license_expiry_date, broker_type, mobile_number, email_address, the_unified_number_of_the_establishment, broker_licenses, street, city, region, district, building_number, additional_number, scraped_ts, date, iteration_number]
Index: []

In [22]:
df[df["name"] == "العرب للعقارات ذ.م.م - Branch 01"]

,unique_id,url,name,license_number,license_expiry_date,broker_type,mobile_number,email_address,the_unified_number_of_the_establishment,broker_licenses,street,city,region,district,building_number,additional_number,scraped_ts,date,iteration_number
877,98bf3b22-e4dc-4048-8827-78312394cf8b,https://eservices.ajmanded.ae/en/TradeLicense/License/98bf3b22-e4dc-4048-8827-78312394cf8b,العرب للعقارات ذ.م.م - Branch 01,139525,12/07/2027,,,,,"[{""end_date"": ""12/07/2027"", ""license_number"": ""139525"", ""license_type"": ""Trade License""}]",,,Jurf 3,,ABDULRAHMAN BUILDING,,2026-07-29,2026-07-29,202608

In [23]:
df.mobile_number.value_counts()

mobile_number
              1140
9098409509       1
Name: count, dtype: int64

In [25]:
mask = (
    df["building_number"].isna() |
    (df["building_number"].astype(str).str.strip() == "")
)

df.loc[mask, ["building_number", "url"]].reset_index(names="row_no")

,row_no,building_number,url
0,8,,https://eservices.ajmanded.ae/en/TradeLicense/License/c17119f1-d37a-4dc8-ba4a-5c9979762ce8
1,28,,https://eservices.ajmanded.ae/en/TradeLicense/License/5ad01373-fecf-4b88-af07-38deda88550d
2,102,,https://eservices.ajmanded.ae/en/TradeLicense/License/c768d1cf-3326-46c8-9ec4-989cfa5c22fb
3,122,,https://eservices.ajmanded.ae/en/TradeLicense/License/0d7b0b87-1489-46f8-8c7b-1441efa6d6a4
4,159,,https://eservices.ajmanded.ae/en/TradeLicense/License/626456e9-a796-462f-bb4c-948c6841231d
5,160,,https://eservices.ajmanded.ae/en/TradeLicense/License/d7dc0425-f38e-4e1d-9e22-50caa6ed8d02
6,191,,https://eservices.ajmanded.ae/en/TradeLicense/License/1e7c91c9-a767-4146-9dde-79f65af8ef16
7,198,,https://eservices.ajmanded.ae/en/TradeLicense/License/4188300e-6f70-479f-9d86-ae04404f7e5b
8,247,,https://eservices.ajmanded.ae/en/TradeLicense/License/48c59116-d636-4506-bf8d-a04eb08355a8
9,271,,https://eservices.ajmanded.ae/en/TradeLicense/License/e8feda51-9b8e-4c74-b2cb-772b82dea9e9
10,288,,https://eservices.ajmanded.ae/en/TradeLicense/License/1d3c8811-03de-46e3-a3e5-59e912e74d54
11,297,,https://eservices.ajmanded.ae/en/TradeLicense/License/7350a76c-6452-4ee3-8ed9-7334de5741f4
12,344,,https://eservices.ajmanded.ae/en/TradeLicense/License/32448d03-4214-42b2-bf69-80f49cdaebd3
13,349,,https://eservices.ajmanded.ae/en/TradeLicense/License/4625e1df-9afe-460c-9ed5-fd577faaa99f
14,359,,https://eservices.ajmanded.ae/en/TradeLicense/License/b6432e7b-38b2-4e86-b99c-cda74978e021
15,375,,https://eservices.ajmanded.ae/en/TradeLicense/License/0f592b14-c8ee-43fc-a969-ac26dc0f394b
16,404,,https://eservices.ajmanded.ae/en/TradeLicense/License/834ec004-44ed-4fc6-a9ad-93d4a3135887
17,424,,https://eservices.ajmanded.ae/en/TradeLicense/License/1a34109c-5f3d-4893-96ef-e5d326e30364
18,467,,https://eservices.ajmanded.ae/en/TradeLicense/License/9681f51f-f148-41db-823e-51504f606d23
19,479,,https://eservices.ajmanded.ae/en/TradeLicense/License/fbf6eff9-e2e2-4d7c-8965-6584ef5149de
20,532,,https://eservices.ajmanded.ae/en/TradeLicense/License/c2b2192e-2255-4b27-b8c7-c14538af1bf2
21,574,,https://eservices.ajmanded.ae/en/TradeLicense/License/4270a153-fd66-412b-9631-c9c037143d1b
22,581,,https://eservices.ajmanded.ae/en/TradeLicense/License/a10496de-259a-42d3-aa92-5b4b5f912954
23,586,,https://eservices.ajmanded.ae/en/TradeLicense/License/341a101e-316a-40f3-be06-cbbc7cf5dbf6
24,603,,https://eservices.ajmanded.ae/en/TradeLicense/License/10d1cc44-3e75-4c77-9cac-95eb0d2922fb
25,617,,https://eservices.ajmanded.ae/en/TradeLicense/License/d68fb6ab-74fc-4050-83a0-989fe3372a2b
26,627,,https://eservices.ajmanded.ae/en/TradeLicense/License/c871dad3-d7a6-4e44-afd8-d22c0b528538
27,646,,https://eservices.ajmanded.ae/en/TradeLicense/License/c0579f9e-f22c-4688-be74-80e72c1b6bce
28,690,,https://eservices.ajmanded.ae/en/TradeLicense/License/12164b80-ea8b-4d88-b26c-c7f4858cfcf0
29,697,,https://eservices.ajmanded.ae/en/TradeLicense/License/22a2504e-6405-49e3-8fa3-355e74bdd150
30,702,,https://eservices.ajmanded.ae/en/TradeLicense/License/ffea1406-f2be-4c5b-89b4-e268a19e7dba
31,703,,https://eservices.ajmanded.ae/en/TradeLicense/License/58f741d3-300b-4b17-8688-6cf5c84d76d0
32,706,,https://eservices.ajmanded.ae/en/TradeLicense/License/2efe8273-87be-465f-93b7-8b298e7793ea
33,711,,https://eservices.ajmanded.ae/en/TradeLicense/License/1e141a87-908c-40c1-bfb3-d712c208c2ff
34,713,,https://eservices.ajmanded.ae/en/TradeLicense/License/67b31991-1548-402b-a292-44bdc73a72b9
35,722,,https://eservices.ajmanded.ae/en/TradeLicense/License/ce96cb4f-114b-44c4-8e1e-abbf18614971
36,723,,https://eservices.ajmanded.ae/en/TradeLicense/License/8b8a4f3d-8e65-48d3-97e1-59a697960b20
37,725,,https://eservices.ajmanded.ae/en/TradeLicense/License/724ba191-eb78-425d-a046-b424325d0798
38,732,,https://eservices.ajmanded.ae/en/TradeLicense/License/3068e2de-1eca-4104-97e3-4709c2bcdc28
39,749,,https://eservices.ajmanded.ae/en/TradeLicense/License/d45461a7-40c1-4c5c-af0a-3ee0865811e7
40,750,,https://eservices.ajmanded.ae/en/TradeLicense/License/00e7d659-12c2-4c5a-ba68-81950c6b7b7b
41,752,,https://eservices.ajmanded.ae/en/TradeLicense/License/8ac09449-4c40-41bc-b127-0e2980e620b0
42,761,,https://eservices.ajmanded.ae/en/TradeLicense/License/07462605-be63-4f75-a2bb-7986c09d804e
43,764,,https://eservices.ajmanded.ae/en/TradeLicense/License/d94698ef-51e6-411a-bb3f-ab7f738ef5d0
44,774,,https://eservices.ajmanded.ae/en/TradeLicense/License/7924a027-0ac1-4d37-8a06-0c6190e721b1
45,778,,https://eservices.ajmanded.ae/en/TradeLicense/License/41fa9fb3-6df6-4b71-ab93-a5b36555b428
46,782,,https://eservices.ajmanded.ae/en/TradeLicense/License/3ad4d3df-e6d1-42ae-bb54-8f73faa5e046
47,787,,https://eservices.ajmanded.ae/en/TradeLicense/License/b96f793c-004d-4bec-a92a-2dca57e5ebc5
48,791,,https://eservices.ajmanded.ae/en/TradeLicense/License/92eaf1e2-0b87-4527-b1ae-de74d1e5baaf
49,798,,https://eservices.ajmanded.ae/en/TradeLicense/License/3a7b2083-b627-4df4-9482-ce93b3b85791
50,803,,https://eservices.ajmanded.ae/en/TradeLicense/License/f7aec187-f637-4f65-b934-bf7e4fcbe58c
51,804,,https://eservices.ajmanded.ae/en/TradeLicense/License/59428dab-a96e-4909-ab22-8d1cb3669d30
52,809,,https://eservices.ajmanded.ae/en/TradeLicense/License/a84ab68f-792e-4098-973e-9f5851d53464
53,815,,https://eservices.ajmanded.ae/en/TradeLicense/License/5b374691-d057-4919-bf38-e900e64de416
54,825,,https://eservices.ajmanded.ae/en/TradeLicense/License/6fa03c02-25fe-4365-9ccd-5f3fc7c1fee5
55,830,,https://eservices.ajmanded.ae/en/TradeLicense/License/ded5a5b7-c965-4b59-b319-973a7a746467
56,833,,https://eservices.ajmanded.ae/en/TradeLicense/License/1cac2b12-2365-43f1-9168-9216a64908d3
57,836,,https://eservices.ajmanded.ae/en/TradeLicense/License/5ba17a82-ba33-4243-993c-4763a77beb86
58,841,,https://eservices.ajmanded.ae/en/TradeLicense/License/49231e9a-1e8a-464b-ba64-e7316b45e77a
59,843,,https://eservices.ajmanded.ae/en/TradeLicense/License/59b6b2ce-7eea-445a-898f-03ae70be3b61
60,847,,https://eservices.ajmanded.ae/en/TradeLicense/License/d7fa6264-daf0-4374-a3c5-f8d5a882e924
61,849,,https://eservices.ajmanded.ae/en/TradeLicense/License/032efd90-3f3c-4f54-9d81-5f693c432bb5
62,851,,https://eservices.ajmanded.ae/en/TradeLicense/License/50d61e07-646e-4db5-9728-719281cba46f
63,853,,https://eservices.ajmanded.ae/en/TradeLicense/License/15e510af-cff2-4a65-b954-711eb19f7772
64,875,,https://eservices.ajmanded.ae/en/TradeLicense/License/ba0954b2-3526-48ab-a365-1ad4cc76e77e
65,876,,https://eservices.ajmanded.ae/en/TradeLicense/License/0542a49f-ebe7-4264-a39f-7e43efcacb5a
66,878,,https://eservices.ajmanded.ae/en/TradeLicense/License/84987697-77f2-4bb5-88d1-274a82e5430d
67,880,,https://eservices.ajmanded.ae/en/TradeLicense/License/1acc8440-686e-47b8-b5ba-0d1970f81b3b
68,881,,https://eservices.ajmanded.ae/en/TradeLicense/License/ae5541ed-705b-462c-9716-3c0505ccc1d1
69,882,,https://eservices.ajmanded.ae/en/TradeLicense/License/de9bd51b-a496-4617-9a29-4103001b0e30
70,918,,https://eservices.ajmanded.ae/en/TradeLicense/License/98f37e06-b2c9-4e68-8751-d56d277110c2
71,922,,https://eservices.ajmanded.ae/en/TradeLicense/License/9fa56912-f26c-40d1-bbaa-6076a2e5c39e
72,947,,https://eservices.ajmanded.ae/en/TradeLicense/License/ce166fe0-6737-4953-bf90-3306705b6efd
73,967,,https://eservices.ajmanded.ae/en/TradeLicense/License/3fd9795c-a040-45d6-808d-e9efb90f3ea4
74,968,,https://eservices.ajmanded.ae/en/TradeLicense/License/35fed668-ed2e-4a61-9ef3-08023e7f76bd
75,991,,https://eservices.ajmanded.ae/en/TradeLicense/License/d016f15c-d244-4c8b-85f2-610e4c2ae120
76,1004,,https://eservices.ajmanded.ae/en/TradeLicense/License/5d31a00a-8081-4de4-ad90-7017738a5cc2
77,1005,,https://eservices.ajmanded.ae/en/TradeLicense/License/6736b792-2fbf-4545-9a99-6263ac5c13b4
78,1007,,https://eservices.ajmanded.ae/en/TradeLicense/License/95cb3aa4-b9a2-4346-99a2-a83cafd6f978
79,1010,,https://eservices.ajmanded.ae/en/TradeLicense/License/2ed41562-7d20-4fc5-9ffb-b3503a871932
80,1016,,https://eservices.ajmanded.ae/en/TradeLicense/License/eb751321-b3e0-4101-a799-7ba090bf1935
81,1025,,https://eservices.ajmanded.ae/en/TradeLicense/License/be7440db-4083-4748-b469-f0b9ae238051
82,1026,,https://eservices.ajmanded.ae/en/TradeLicense/License/01da86d0-dc12-4d81-b3df-d402069c2825
83,1036,,https://eservices.ajmanded.ae/en/TradeLicense/License/970971ff-f6ae-47b4-be23-23a0ac24d974
84,1044,,https://eservices.ajmanded.ae/en/TradeLicense/License/af5dace6-d64b-4c48-a89e-38da934c8469
85,1049,,https://eservices.ajmanded.ae/en/TradeLicense/License/8e0dfca6-dfd6-4931-bb8d-14027c5919ff
86,1067,,https://eservices.ajmanded.ae/en/TradeLicense/License/5ca2d00f-5f0c-4291-8b3a-d387e771f4d2
87,1072,,https://eservices.ajmanded.ae/en/TradeLicense/License/36cae3d7-95af-4a8e-87bb-91f3cbb08c11
88,1073,,https://eservices.ajmanded.ae/en/TradeLicense/License/a051ebcf-509f-43e6-8356-cd15aa7f23fe
89,1100,,https://eservices.ajmanded.ae/en/TradeLicense/License/1c892e4a-70b3-43f5-8410-fcc8de5f32d0
90,1105,,https://eservices.ajmanded.ae/en/TradeLicense/License/72e51992-f123-4cbd-bd97-0b6740cb4e06
91,1106,,https://eservices.ajmanded.ae/en/TradeLicense/License/448ab311-bec0-4872-840d-921ee0ca2b66

In [30]:
import pandas as pd

# Parse expiry date
df["license_expiry_date"] = pd.to_datetime(
    df["license_expiry_date"],
    dayfirst=True,
    errors="coerce"
)

# Convert iteration_number (202608 -> 2026-08-01)
df["iteration_date"] = pd.to_datetime(
    df["iteration_number"].astype(str).str[:4] + "-" +
    df["iteration_number"].astype(str).str[4:6] + "-01"
)

# Two months before iteration date
df["cutoff_date"] = df["iteration_date"] - pd.DateOffset(months=2)

# Records that should have been excluded
mask = df["license_expiry_date"] < df["cutoff_date"]

result = df.loc[
    mask,
    [
        "unique_id",
        "url",
        "license_expiry_date",
        "iteration_number"
    ]
].reset_index(names="row_no")

print(f"Records that should have been excluded: {len(result)}")
print(result)

Records that should have been excluded: 1
   row_no                             unique_id  \
0     448  09102247-1054-4fc6-87d4-554e06a77ae0

                                                                                          url  \
0  https://eservices.ajmanded.ae/en/TradeLicense/License/09102247-1054-4fc6-87d4-554e06a77ae0

  license_expiry_date  iteration_number
0          2026-05-31            202608

In [29]:
print(df["iteration_number"].dtype)
print(df["iteration_number"].head())

int64
0    202608
1    202608
2    202608
3    202608
4    202608
Name: iteration_number, dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)